// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Create as $Create} from "@wailsio/runtime";

/**
 * Person represents a person
 */
export interface Person {
    "Title": Title;
    "Name": string;
}

/**
 * Title is a title
 */
export enum Title {
    Dr = "Dr",
    Miss = "Miss",

    /**
     * Mister is a title
     */
    Mister = "Mr",
    Mrs = "Mrs",
    Ms = "Ms",
};
