// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Create as $Create} from "@wailsio/runtime";

/**
 * A generic struct
 */
export interface Person<T> {
    "Name": T | null;
    "AliasedField": number;
}
