// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetFileInfo(path: string): $CancellablePromise<$models.FileInfo> {
    return $Call.ByName("main.Service.GetFileInfo", path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetMode(path: string): $CancellablePromise<number> {
    return $Call.ByName("main.Service.GetMode", path);
}

// Private type creation functions
const $$createType0 = $models.FileInfo.createFrom;
