// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Create as $Create} from "@wailsio/runtime";

/**
 * @typedef { {
 *     "Name": string,
 *     "Parent": Person | null,
 *     "Details": {"Age": number, "Address": {"Street": string}},
 * } } Person
 */
