package binding_test

// Define the Go types to be tested
type PromisesTest struct{}
type PromisesTestReturnStruct struct{}

// Methods returning different types to exercise promise handling
func (h *PromisesTest) NoReturn(_ string)              {}
func (h *PromisesTest) ErrorReturn(_ int) error        { return nil }
func (h *PromisesTest) SingleReturn(_ interface{}) int { return 0 }
func (h *PromisesTest) SingleReturnStruct(_ interface{}) PromisesTestReturnStruct {
	return PromisesTestReturnStruct{}
}
func (h *PromisesTest) SingleReturnStructPointer(_ interface{}) *PromisesTestReturnStruct {
	return &PromisesTestReturnStruct{}
}
func (h *PromisesTest) SingleReturnStructSlice(_ interface{}) []PromisesTestReturnStruct {
	return []PromisesTestReturnStruct{}
}
func (h *PromisesTest) SingleReturnStructPointerSlice(_ interface{}) []*PromisesTestReturnStruct {
	return []*PromisesTestReturnStruct{}
}
func (h *PromisesTest) SingleReturnWithError(_ int) (string, error) { return "", nil }
func (h *PromisesTest) TwoReturn(_ interface{}) (string, int)       { return "", 0 }

// Optional Get() method for consistency with other tests
func (h *PromisesTest) Get() PromisesTest { return *h }

// The test definition recognized by TestBindings_GenerateModels
var PromisesBindingTest = BindingTest{
	name: "PromisesBindingTest",
	structs: []interface{}{
		&PromisesTest{},
		&PromisesTestReturnStruct{},
	},
	exemptions:  nil,
	shouldError: false,
	want: `// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {binding_test} from '../models';

export function ErrorReturn(arg1:number):Promise<void>;

export function NoReturn(arg1:string):Promise<void>;

export function SingleReturn(arg1:any):Promise<number>;

export function SingleReturnStruct(arg1:any):Promise<binding_test.PromisesTestReturnStruct>;

export function SingleReturnStructPointer(arg1:any):Promise<binding_test.PromisesTestReturnStruct>;

export function SingleReturnStructPointerSlice(arg1:any):Promise<Array<binding_test.PromisesTestReturnStruct>>;

export function SingleReturnStructSlice(arg1:any):Promise<Array<binding_test.PromisesTestReturnStruct>>;

export function SingleReturnWithError(arg1:number):Promise<string>;

export function TwoReturn(arg1:any):Promise<string|number>;
`,
}
