// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call} from "/wails/runtime.js";

export function TestMethod(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2241101727) as any;
    return $resultPromise;
}
