// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


export class Address {
    street: string;
    state: string;
    country: string;

    constructor(source: Partial<Address> = {}) {
        const {street = "", state = "", country = ""} = source;
        this.street = street;
        this.state = state;
        this.country = country;
    }

    static createFrom(source: string | object = {}): Address {
        let parsedSource = typeof source === 'string' ? JSON.parse(source) : source;
        return new Address(parsedSource as Partial<Address>);
    }
}
