// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * @typedef {import('./models').Address} Address
 */

/**
 * Yay does this and that 
 * @function Yay
 * @returns {Promise<Address>}
 **/
export async function Yay() {
	return wails.CallByID(1592414782, ...Array.prototype.slice.call(arguments, 0));
}
