// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * @typedef {import('../services/models').Address} servicesAddress
 */

export const Person = class {
    /**
     * Creates a new Person instance.
     * @constructor
     * @param {Object} source - The source object to create the Person.
     * @param {string} source.Name
     * @param {servicesAddress} source.Address
     */
    constructor(source = {}) {
        const { name = "", address = null } = source;        
        this.name = name;
        this.address = address;
    }

    /**
     * Creates a new Person instance from a string or object.
     * @param {string|object} source - The source data to create a Person instance from.
     * @returns {Person} A new Person instance.
     */
    static createFrom(source) {
        let parsedSource = typeof source === 'string' ? JSON.parse(source) : source;
        return new Person(parsedSource);
    }
};

