// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function OtherHiddenMethod(): Promise<string> {
    let $resultPromise = $Call.ByID(1678140063);
    return $resultPromise as any;
}
