import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import type { SigningStatus, SigningDefaults } from '../types';
import { getSigningStatus, getSigning, saveSigning, getState, createNotarizationProfile, createGPGKey, createWindowsCert, exportGPGKey } from '../api';

const pageVariants = {
  initial: { opacity: 0 },
  animate: { opacity: 1 },
  exit: { opacity: 0 }
};

type Platform = 'darwin' | 'windows' | 'linux';
type HostOS = 'darwin' | 'windows' | 'linux';

// Wails code-signing guide. Section anchors are generated by Starlight from the
// guide's headings.
const SIGNING_DOCS = 'https://v3.wails.io/guides/build/signing';

// Host-aware install guidance for the tools needed to sign each target platform.
// `link` points at the relevant section of the Wails code-signing guide so users
// get setup instructions in context (not just the upstream tool homepage).
const TOOL_INFO: Record<string, {
  label: string;
  desc: string;
  link?: string;
  install: Partial<Record<HostOS, string>>;
}> = {
  gpg: {
    label: 'GnuPG (gpg)',
    desc: 'Signs Linux releases, packages and checksums.',
    link: `${SIGNING_DOCS}/#linux-package-signing`,
    install: {
      darwin: 'brew install gnupg',
      linux: 'sudo apt install gnupg   # or: sudo dnf install gnupg2',
      windows: 'winget install GnuPG.Gpg4win',
    },
  },
  rcodesign: {
    label: 'rcodesign (apple-codesign)',
    desc: 'Signs & notarizes macOS apps from Linux/Windows using a .p12 + App Store Connect API key.',
    link: `${SIGNING_DOCS}/#macos-code-signing`,
    install: {
      darwin: 'brew install rcodesign',
      linux: 'cargo install apple-codesign',
      windows: 'cargo install apple-codesign',
    },
  },
  osslsigncode: {
    label: 'osslsigncode',
    desc: 'Authenticode-signs Windows binaries from macOS/Linux.',
    link: `${SIGNING_DOCS}/#windows-code-signing`,
    install: {
      darwin: 'brew install osslsigncode',
      linux: 'sudo apt install osslsigncode',
    },
  },
  openssl: {
    label: 'OpenSSL',
    desc: 'Needed to generate a self-signed test certificate.',
    link: `${SIGNING_DOCS}/#windows-code-signing`,
    install: {
      darwin: 'brew install openssl',
      linux: 'sudo apt install openssl',
      windows: 'winget install ShiningLight.OpenSSL.Light',
    },
  },
  signtool: {
    label: 'signtool (Windows SDK)',
    desc: 'Native Authenticode signing tool, ships with the Windows SDK.',
    link: `${SIGNING_DOCS}/#windows-code-signing`,
    install: {
      windows: 'winget install Microsoft.WindowsSDK',
    },
  },
};

function CopyableCommand({ cmd }: { cmd: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <div className="flex items-center gap-2 mt-1.5">
      <code className="flex-1 text-xs bg-gray-100 dark:bg-gray-900 text-gray-700 dark:text-gray-300 px-2 py-1.5 rounded font-mono overflow-x-auto whitespace-pre">
        {cmd}
      </code>
      <button
        type="button"
        onClick={() => { navigator.clipboard.writeText(cmd); setCopied(true); setTimeout(() => setCopied(false), 1500); }}
        className="text-gray-500 hover:text-gray-700 dark:hover:text-gray-300 p-1.5 flex-shrink-0"
        title="Copy command"
        aria-label="Copy command"
      >
        {copied ? (
          <svg className="w-4 h-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
        ) : (
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg>
        )}
      </button>
    </div>
  );
}

// ToolStatus shows whether a required tool is installed and, when it isn't,
// the host-appropriate install command and a docs link.
function ToolStatus({ toolKey, available, host }: { toolKey: string; available: boolean; host: HostOS }) {
  const info = TOOL_INFO[toolKey];
  if (!info) return null;
  const cmd = info.install[host];
  return (
    <div className="p-3 rounded-lg bg-gray-100 dark:bg-gray-900/50 border border-gray-200 dark:border-gray-800">
      <div className="flex items-center gap-2">
        <span className={`w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 ${available ? 'bg-green-500/20' : 'bg-amber-500/20'}`}>
          {available ? (
            <svg className="w-3 h-3 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" /></svg>
          ) : (
            <svg className="w-3 h-3 text-amber-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M12 9v2m0 4h.01M5 19h14a2 2 0 001.7-3L13.7 4a2 2 0 00-3.4 0L3.3 16A2 2 0 005 19z" /></svg>
          )}
        </span>
        <span className="text-sm font-medium text-gray-900 dark:text-white">{info.label}</span>
        <span className={`text-xs ${available ? 'text-green-600 dark:text-green-400' : 'text-amber-600 dark:text-amber-400'}`}>
          {available ? 'Installed' : 'Not found'}
        </span>
        {info.link && (
          <a href={info.link} target="_blank" rel="noopener noreferrer" className="ml-auto text-xs text-blue-500 hover:underline">Docs ↗</a>
        )}
      </div>
      {!available && (
        <>
          <p className="text-xs text-gray-500 dark:text-gray-400 mt-1.5">{info.desc}</p>
          {cmd ? <CopyableCommand cmd={cmd} /> : (
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-1.5">See the docs link for installation on this platform.</p>
          )}
        </>
      )}
    </div>
  );
}

interface Props {
  onNext: () => void;
  onSkip: () => void;
  onBack?: () => void;
  canGoBack?: boolean;
}

export default function SigningStep({ onNext, onSkip, onBack, canGoBack }: Props) {
  const [status, setStatus] = useState<SigningStatus | null>(null);
  const [config, setConfig] = useState<SigningDefaults | null>(null);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [hostOS, setHostOS] = useState<HostOS>('linux');
  const [rechecking, setRechecking] = useState(false);
  const [authorName, setAuthorName] = useState('');
  const [authorEmail, setAuthorEmail] = useState('');
  const [selectedPlatform, setSelectedPlatform] = useState<Platform>('darwin');
  // 'status' | 'identity' | 'notarize'
  const [configStep, setConfigStep] = useState<'status' | 'identity' | 'notarize'>('status');
  const headingRef = useRef<HTMLHeadingElement>(null);

  // Extract Team ID from identity string like "Developer ID Application: Name (TEAMID)"
  const extractTeamID = (identity: string): string => {
    const match = identity.match(/\(([A-Z0-9]+)\)$/);
    return match ? match[1] : '';
  };

  useEffect(() => {
    headingRef.current?.focus();
    loadData();
  }, []);

  const loadData = async () => {
    setLoadError(null);
    try {
      const [s, c, state] = await Promise.all([getSigningStatus(), getSigning(), getState()]);
      setStatus(s);
      setConfig(c || { darwin: {}, windows: {}, linux: {} });
      if (state.system?.os) {
        setHostOS(state.system.os as HostOS);
      }
      if (state.system?.gitName) setAuthorName(state.system.gitName);
      if (state.system?.gitEmail) setAuthorEmail(state.system.gitEmail);
    } catch (e) {
      console.error('Failed to load signing data:', e);
      setLoadError('Failed to load signing configuration. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const enterConfigMode = () => {
    // Pre-populate config from detected identities if no saved config exists
    if (config && status && selectedPlatform === 'darwin') {
      if (!config.darwin?.identity && status.darwin.identities && status.darwin.identities.length > 0) {
        const identity = status.darwin.identities[0];
        setConfig({
          ...config,
          darwin: {
            ...config.darwin,
            identity,
            teamID: config.darwin?.teamID || extractTeamID(identity),
          }
        });
      }
    }
    setConfigStep('identity');
  };

  const handleSave = async (): Promise<boolean> => {
    if (!config) return false;
    setSaveError(null);
    try {
      await saveSigning(config);
      return true;
    } catch (e) {
      console.error('Failed to save signing config:', e);
      setSaveError('Failed to save configuration. Please try again.');
      return false;
    }
  };

  const renderConfigForm = () => {
    if (!config) return null;

    if (selectedPlatform === 'darwin') {
      const isOnMac = hostOS === 'darwin';
      
      return (
        <div className="space-y-4">
          {!isOnMac && (
            <div className="p-3 rounded-lg bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 text-sm">
              <p className="text-amber-800 dark:text-amber-200 font-medium mb-1">Signing macOS from {hostOS === 'linux' ? 'Linux' : 'Windows'}</p>
              <p className="text-amber-700 dark:text-amber-300 text-xs">
                Use <a href="https://github.com/indygreg/apple-platform-rs/tree/main/apple-codesign"
                   target="_blank" rel="noopener noreferrer"
                   className="underline hover:no-underline">rcodesign</a> with a .p12 certificate exported from a Mac
                (or via the Apple Developer portal).
              </p>
            </div>
          )}

          {!isOnMac && (
            <ToolStatus toolKey="rcodesign" available={status?.darwin.rcodesignAvailable ?? false} host={hostOS} />
          )}

          <div className="p-3 rounded-lg bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 text-xs text-blue-700 dark:text-blue-300">
            Apple signing certificates can't be generated locally — they're issued by Apple. Create a{' '}
            <a href="https://developer.apple.com/account/resources/certificates/list" target="_blank" rel="noopener noreferrer" className="underline hover:no-underline">Developer ID certificate</a>{' '}
            in your Apple Developer account{isOnMac ? ', then it appears in the list below.' : ', then export it as a .p12.'}
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              Signing Identity
            </label>
            {isOnMac && status?.darwin.identities && status.darwin.identities.length > 0 ? (
              <>
                {status.darwin.identities.length === 1 ? (
                  <div className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-gray-50 dark:bg-gray-800 text-gray-900 dark:text-white text-sm">
                    {status.darwin.identities[0]}
                  </div>
                ) : (
                  <select
                    value={config.darwin?.identity || ''}
                    onChange={(e) => {
                      const identity = e.target.value;
                      setConfig({
                        ...config,
                        darwin: {
                          ...config.darwin,
                          identity,
                          teamID: config.darwin?.teamID || extractTeamID(identity),
                        }
                      });
                    }}
                    className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
                  >
                    <option value="" disabled>Select a signing identity...</option>
                    {status.darwin.identities.map((id) => (
                      <option key={id} value={id}>{id}</option>
                    ))}
                  </select>
                )}
                <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                  {status.darwin.identities.length} {status.darwin.identities.length === 1 ? 'identity' : 'identities'} detected in keychain
                </p>
              </>
            ) : (
              <>
                <input
                  type="text"
                  value={config.darwin?.identity || ''}
                  onChange={(e) => {
                    const identity = e.target.value;
                    setConfig({
                      ...config,
                      darwin: {
                        ...config.darwin,
                        identity,
                        teamID: config.darwin?.teamID || extractTeamID(identity),
                      }
                    });
                  }}
                  placeholder="Developer ID Application: Your Name (TEAMID)"
                  className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
                />
                {isOnMac && (
                  <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                    Find with: <code className="bg-gray-100 dark:bg-gray-800 px-1 rounded">security find-identity -v -p codesigning</code>
                  </p>
                )}
              </>
            )}
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              Team ID
            </label>
            <input
              type="text"
              value={config.darwin?.teamID || ''}
              onChange={(e) => setConfig({
                ...config,
                darwin: { ...config.darwin, teamID: e.target.value }
              })}
              placeholder="ABCD1234EF"
              className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
            />
          </div>

          {!isOnMac && (
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                P12 Certificate Path
              </label>
              <input
                type="text"
                value={config.darwin?.p12Path || ''}
                onChange={(e) => setConfig({
                  ...config,
                  darwin: { ...config.darwin, p12Path: e.target.value }
                })}
                placeholder="/path/to/certificate.p12"
                className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
              />
              <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                Export from Keychain Access on a Mac, or generate via Apple Developer Portal
              </p>
            </div>
          )}

          {!isOnMac && (
            <>
              <div className="border-t border-gray-200 dark:border-gray-700 pt-4 mt-4">
                <p className="text-xs text-gray-500 dark:text-gray-400 mb-3 font-medium">
                  App Store Connect API (for notarization from {hostOS === 'linux' ? 'Linux' : 'Windows'})
                </p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  API Key ID
                </label>
                <input
                  type="text"
                  value={config.darwin?.apiKeyID || ''}
                  onChange={(e) => setConfig({
                    ...config,
                    darwin: { ...config.darwin, apiKeyID: e.target.value }
                  })}
                  placeholder="ABC123DEF4"
                  className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Issuer ID
                </label>
                <input
                  type="text"
                  value={config.darwin?.apiIssuerID || ''}
                  onChange={(e) => setConfig({
                    ...config,
                    darwin: { ...config.darwin, apiIssuerID: e.target.value }
                  })}
                  placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                  className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  API Key Path (.p8 file)
                </label>
                <input
                  type="text"
                  value={config.darwin?.apiKeyPath || ''}
                  onChange={(e) => setConfig({
                    ...config,
                    darwin: { ...config.darwin, apiKeyPath: e.target.value }
                  })}
                  placeholder="/path/to/AuthKey_ABC123DEF4.p8"
                  className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
                />
                <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                  Create at{' '}
                  <a href="https://appstoreconnect.apple.com/access/api" 
                     target="_blank" 
                     rel="noopener noreferrer"
                     className="text-blue-500 hover:underline">App Store Connect → Users and Access → Keys</a>
                </p>
              </div>
            </>
          )}
        </div>
      );
    }

    if (selectedPlatform === 'windows') {
      const winHost = hostOS === 'windows';
      return (
        <div className="space-y-4">
          {/* Tooling needed to actually run the signing on this host */}
          {winHost ? (
            <ToolStatus toolKey="signtool" available={status?.windows.hasSignTool ?? false} host={hostOS} />
          ) : (
            <ToolStatus toolKey="osslsigncode" available={status?.windows.osslsigncodeAvailable ?? false} host={hostOS} />
          )}

          {/* Generate a self-signed certificate (testing/internal only) */}
          {status?.windows.opensslAvailable ? (
            <WindowsCertSetup config={config} setConfig={setConfig} onCreated={loadData} />
          ) : (
            <ToolStatus toolKey="openssl" available={false} host={hostOS} />
          )}

          <div className="text-center text-xs text-gray-400 dark:text-gray-500 pt-1">— or use an existing certificate —</div>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              Certificate Path (PFX/P12)
            </label>
            <input
              type="text"
              value={config.windows?.certificatePath || ''}
              onChange={(e) => setConfig({
                ...config,
                windows: { ...config.windows, certificatePath: e.target.value }
              })}
              placeholder="/path/to/certificate.pfx"
              className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
            />
          </div>

          <div className="text-center text-xs text-gray-500 dark:text-gray-400">— or —</div>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              Certificate Thumbprint (Windows Store)
            </label>
            <input
              type="text"
              value={config.windows?.thumbprint || ''}
              onChange={(e) => setConfig({
                ...config,
                windows: { ...config.windows, thumbprint: e.target.value }
              })}
              placeholder="ABC123DEF456..."
              className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              Timestamp Server
            </label>
            <input
              type="text"
              value={config.windows?.timestampServer || 'http://timestamp.digicert.com'}
              onChange={(e) => setConfig({
                ...config,
                windows: { ...config.windows, timestampServer: e.target.value }
              })}
              className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
            />
          </div>
        </div>
      );
    }

    if (selectedPlatform === 'linux') {
      const gpgAvailable = status?.linux.gpgAvailable ?? false;
      const gpgKeys = status?.linux.gpgKeys ?? [];
      return (
        <div className="space-y-4">
          <ToolStatus toolKey="gpg" available={gpgAvailable} host={hostOS} />

          {gpgAvailable && (
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                GPG Signing Key
              </label>
              {gpgKeys.length > 0 ? (
                <>
                  <select
                    value={config.linux?.gpgKeyID || ''}
                    onChange={(e) => setConfig({
                      ...config,
                      // Clear the exported path when the key changes so it can't
                      // mismatch the id (and the export prompt can re-appear).
                      linux: { ...config.linux, gpgKeyID: e.target.value, gpgKeyPath: '' }
                    })}
                    className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
                  >
                    <option value="" disabled>Select a GPG key...</option>
                    {gpgKeys.map((k) => (
                      <option key={k.keyID} value={k.keyID}>{k.uid} — {k.keyID}</option>
                    ))}
                  </select>
                  <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                    {gpgKeys.length} secret {gpgKeys.length === 1 ? 'key' : 'keys'} detected. Need another?
                  </p>
                </>
              ) : (
                <p className="text-xs text-gray-500 dark:text-gray-400">
                  No GPG secret keys found on this machine. Create one below.
                </p>
              )}

              {/* A key configured by ID only (e.g. generated before export was
                  automatic) isn't usable by a build until exported to a file. */}
              {config.linux?.gpgKeyID && !config.linux?.gpgKeyPath
                && gpgKeys.some((k) => k.keyID === config.linux?.gpgKeyID) && (
                <GPGExportNotice keyID={config.linux.gpgKeyID} onExported={loadData} />
              )}

              <GPGKeySetup
                defaultName={authorName}
                defaultEmail={authorEmail}
                onCreated={loadData}
                startOpen={gpgKeys.length === 0}
              />
            </div>
          )}

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              GPG Key Path (optional)
            </label>
            <input
              type="text"
              value={config.linux?.gpgKeyPath || ''}
              onChange={(e) => setConfig({
                ...config,
                linux: { ...config.linux, gpgKeyPath: e.target.value }
              })}
              placeholder="~/.gnupg/private-key.asc"
              className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
            />
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
              Only needed to import a key from a file (e.g. in CI).
            </p>
          </div>
        </div>
      );
    }

    return null;
  };

  const renderPlatformStatus = () => {
    if (!status) return null;
    
    if (selectedPlatform === 'darwin') {
      const darwin = status.darwin;
      return (
        <div className="space-y-4">
          <StatusRow
            label="Code Signing Identity"
            configured={darwin.hasIdentity}
            value={darwin.hasIdentity ? (darwin.identity || 'Configured') : 'Not configured'}
          />
          <StatusRow
            label="Notarization"
            configured={darwin.hasNotarization}
            value={darwin.hasNotarization ? `Team ID: ${darwin.teamID || 'Configured'}` : 'Not configured'}
          />
          {darwin.identities && darwin.identities.length > 1 && (
            <div className="text-xs text-gray-500 dark:text-gray-400 p-3 rounded-lg bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800">
              <span className="font-medium">{darwin.identities.length} signing identities</span> found in keychain
            </div>
          )}
        </div>
      );
    }

    if (selectedPlatform === 'windows') {
      const windows = status.windows;
      return (
        <div className="space-y-4">
          <StatusRow
            label="Code Signing Certificate"
            configured={windows.hasCertificate}
            value={windows.hasCertificate ? `Type: ${windows.certificateType}` : 'Not configured'}
          />
          {/* Signing backend depends on the host: signtool is Windows-native;
              osslsigncode is the cross-platform signer used from macOS/Linux. */}
          {hostOS === 'windows' ? (
            <StatusRow
              label="SignTool"
              configured={windows.hasSignTool}
              value={windows.hasSignTool ? 'Available' : 'Not found (Windows SDK required)'}
            />
          ) : (
            <StatusRow
              label="osslsigncode"
              configured={windows.osslsigncodeAvailable}
              value={windows.osslsigncodeAvailable ? 'Available' : 'Not found (needed to sign from ' + (hostOS === 'darwin' ? 'macOS' : 'Linux') + ')'}
            />
          )}
        </div>
      );
    }

    if (selectedPlatform === 'linux') {
      const linux = status.linux;
      return (
        <div className="space-y-4">
          <StatusRow
            label="GPG Signing Key"
            configured={linux.hasGpgKey}
            value={linux.hasGpgKey ? `Key ID: ${linux.gpgKeyID}` : 'Not configured'}
          />
        </div>
      );
    }

    return null;
  };

  const getOverallStatus = () => {
    if (!status) return { configured: 0, total: 3 };
    let configured = 0;
    if (status.darwin.hasIdentity) configured++;
    if (status.windows.hasCertificate) configured++;
    if (status.linux.hasGpgKey) configured++;
    return { configured, total: 3 };
  };

  const overallStatus = getOverallStatus();

  return (
    <motion.main
      variants={pageVariants}
      initial="initial"
      animate="animate"
      exit="exit"
      transition={{ duration: 0.3 }}
      className="flex-1 flex flex-col"
      aria-labelledby="signing-title"
    >
      <div className="flex-1 overflow-y-auto scrollbar-thin min-h-0 px-10 pb-4 pt-10">
        <header className="text-center mb-6">
          <h1
            ref={headingRef}
            id="signing-title"
            className="text-2xl font-semibold text-gray-900 dark:text-white mb-1.5 tracking-tight focus:outline-none"
            tabIndex={-1}
          >
            Code Signing
          </h1>
          <p className="text-base text-gray-500 dark:text-gray-400">
            {overallStatus.configured > 0
              ? `${overallStatus.configured} of ${overallStatus.total} platforms configured`
              : 'Sign your apps for distribution'}
          </p>
        </header>

        {loading ? (
          <div className="flex items-center justify-center h-48">
            <motion.div
              className="w-8 h-8 border-2 border-gray-300 dark:border-gray-600 border-t-red-500 rounded-full"
              animate={{ rotate: 360 }}
              transition={{ duration: 1, repeat: Infinity, ease: 'linear' }}
            />
          </div>
        ) : loadError ? (
          <div className="flex flex-col items-center justify-center h-48 gap-4">
            <p className="text-sm text-red-600 dark:text-red-400">{loadError}</p>
            <button
              onClick={() => { setLoading(true); loadData(); }}
              className="px-4 py-2 rounded-lg text-sm font-medium bg-red-500 text-white hover:bg-red-600"
            >
              Retry
            </button>
          </div>
        ) : (
          <div className="max-w-xl mx-auto">
            <div className="flex justify-end mb-2">
              <button
                type="button"
                onClick={async () => { setRechecking(true); await loadData(); setRechecking(false); }}
                disabled={rechecking}
                className="inline-flex items-center gap-1.5 text-xs font-medium text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 disabled:opacity-50"
                title="Re-detect installed signing tools"
              >
                <svg className={`w-3.5 h-3.5 ${rechecking ? 'animate-spin' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                </svg>
                {rechecking ? 'Rechecking…' : 'Recheck installed tools'}
              </button>
            </div>
            <div className="flex gap-2 mb-6" role="tablist">
              <PlatformTab
                platform="darwin"
                label="macOS"
                isActive={selectedPlatform === 'darwin'}
                hasConfig={status?.darwin.hasIdentity}
                onClick={() => { setSelectedPlatform('darwin'); setConfigStep('status'); }}
              />
              <PlatformTab
                platform="windows"
                label="Windows"
                isActive={selectedPlatform === 'windows'}
                hasConfig={status?.windows.hasCertificate}
                onClick={() => { setSelectedPlatform('windows'); setConfigStep('status'); }}
              />
              <PlatformTab
                platform="linux"
                label="Linux"
                isActive={selectedPlatform === 'linux'}
                hasConfig={status?.linux.hasGpgKey}
                onClick={() => { setSelectedPlatform('linux'); setConfigStep('status'); }}
              />
            </div>

            <AnimatePresence mode="wait">
              {configStep === 'notarize' ? (
                <motion.div
                  key="notarize"
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  transition={{ duration: 0.2 }}
                >
                  <NotarizationSetup
                    config={config!}
                    setConfig={setConfig as (c: SigningDefaults) => void}
                    teamID={config?.darwin?.teamID || ''}
                    onDone={async () => {
                      // Backend already saved keychainProfile - just reload
                      setConfigStep('status');
                      await loadData();
                    }}
                    onSkip={async () => {
                      // Save identity/teamID without notarization
                      const ok = await handleSave();
                      if (ok) { setConfigStep('status'); await loadData(); }
                    }}
                    onBack={() => setConfigStep('identity')}
                  />
                </motion.div>
              ) : configStep === 'identity' ? (
                <motion.div
                  key="config"
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  transition={{ duration: 0.2 }}
                >
                  {renderConfigForm()}
                  {saveError && (
                    <p className="mt-3 text-sm text-red-600 dark:text-red-400">{saveError}</p>
                  )}
                  <div className="flex gap-3 mt-6">
                    <button
                      onClick={() => { setSaveError(null); setConfigStep('status'); }}
                      className="flex-1 px-4 py-2 rounded-lg text-sm font-medium border border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800"
                    >
                      Cancel
                    </button>
                    {selectedPlatform === 'darwin' && hostOS === 'darwin' ? (
                      <button
                        onClick={() => setConfigStep('notarize')}
                        className="flex-1 px-4 py-2 rounded-lg text-sm font-medium bg-red-500 text-white hover:bg-red-600"
                      >
                        Next
                      </button>
                    ) : (
                      <button
                        onClick={async () => { const ok = await handleSave(); if (ok) { setConfigStep('status'); await loadData(); } }}
                        className="flex-1 px-4 py-2 rounded-lg text-sm font-medium bg-red-500 text-white hover:bg-red-600"
                      >
                        Save
                      </button>
                    )}
                  </div>
                </motion.div>
              ) : (
                <motion.div
                  key="status"
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  transition={{ duration: 0.2 }}
                  role="tabpanel"
                >
                  {renderPlatformStatus()}
                  <button
                    onClick={enterConfigMode}
                    className="w-full mt-4 px-4 py-2 rounded-lg text-sm font-medium border border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                  >
                    Configure {selectedPlatform === 'darwin' ? 'macOS' : selectedPlatform === 'windows' ? 'Windows' : 'Linux'} Signing
                  </button>
                  <p className="text-xs text-center text-gray-500 dark:text-gray-400 mt-3">
                    This configures signing globally for all projects. Want to configure a single project?{' '}
                    <a
                      href="https://v3.wails.io/guides/build/signing/#per-project-configuration"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-blue-500 hover:underline"
                    >
                      Use <code className="font-mono">wails3 setup signing</code> ↗
                    </a>
                  </p>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        )}
      </div>

      {configStep === 'status' && (
        <div className="flex-shrink-0 pt-4 pb-6 flex flex-col items-center gap-1.5">
          <div className="flex items-center gap-3">
            {canGoBack && onBack && (
              <button
                onClick={onBack}
                className="px-4 py-2 rounded-lg text-sm font-medium transition-colors border border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:focus:ring-offset-gray-900"
              >
                Back
              </button>
            )}
            <button
              onClick={onNext}
              className="px-5 py-2 rounded-lg text-sm font-medium transition-colors border border-red-500 text-red-600 dark:text-red-400 hover:bg-red-500/10 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 dark:focus:ring-offset-gray-900"
            >
              Continue
            </button>
          </div>
          <button
            onClick={onSkip}
            className="text-xs text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300 transition-colors focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:focus:ring-offset-gray-900 rounded"
          >
            Set up later
          </button>
        </div>
      )}
    </motion.main>
  );
}

function NotarizationSetup({ config, setConfig, teamID, onDone, onSkip, onBack }: {
  config: SigningDefaults;
  setConfig: (c: SigningDefaults) => void;
  teamID: string;
  onDone: () => void;
  onSkip: () => void;
  onBack: () => void;
}) {
  const [creating, setCreating] = useState(false);
  const [profileName, setProfileName] = useState(config.darwin?.keychainProfile || 'wails-notary');
  const [appleID, setAppleID] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');

  const handleCreate = async () => {
    setError('');
    setCreating(true);
    try {
      const result = await createNotarizationProfile({
        profileName,
        appleID,
        teamID,
        password,
      });
      if (result.success) {
        setConfig({
          ...config,
          darwin: { ...config.darwin, keychainProfile: profileName }
        });
        onDone();
      } else {
        setError(result.error || 'Failed to create profile');
      }
    } catch (e) {
      setError('Failed to create notarization profile');
    } finally {
      setCreating(false);
    }
  };

  return (
    <div className="space-y-4">
      <p className="text-sm text-gray-500 dark:text-gray-400">
        Stores your Apple notarization credentials securely in the macOS Keychain.
        Requires an{' '}
        <a href="https://support.apple.com/en-us/102654" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">app-specific password</a>.
      </p>

      <div>
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Profile Name</label>
        <input
          type="text"
          value={profileName}
          onChange={(e) => setProfileName(e.target.value)}
          placeholder="wails-notary"
          className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
        />
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Apple ID</label>
        <input
          type="email"
          value={appleID}
          onChange={(e) => setAppleID(e.target.value)}
          placeholder="you@example.com"
          className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
        />
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">App-Specific Password</label>
        <input
          type="password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          placeholder="xxxx-xxxx-xxxx-xxxx"
          className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
        />
        <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
          Generate at{' '}
          <a href="https://appleid.apple.com/account/manage" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">appleid.apple.com</a>
          {' '}→ Sign-In and Security → App-Specific Passwords
        </p>
      </div>

      {error && (
        <div className="p-3 rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800">
          <p className="text-sm text-red-600 dark:text-red-400">{error}</p>
        </div>
      )}

      <div className="flex gap-3 pt-2">
        <button
          type="button"
          onClick={onBack}
          className="px-4 py-2 rounded-lg text-sm font-medium border border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800"
        >
          Back
        </button>
        <button
          type="button"
          onClick={onSkip}
          className="flex-1 px-4 py-2 rounded-lg text-sm font-medium border border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800"
        >
          Skip
        </button>
        <button
          type="button"
          onClick={handleCreate}
          disabled={creating || !profileName || !appleID || !password}
          className="flex-1 px-4 py-2 rounded-lg text-sm font-medium bg-red-500 text-white hover:bg-red-600 disabled:opacity-50"
        >
          {creating ? 'Saving...' : 'Save'}
        </button>
      </div>
    </div>
  );
}

// GPGExportNotice exports a keyring key that's configured by ID only into a file
// builds can use. It tries automatically on mount (works for unprotected keys);
// if the key is passphrase-protected it falls back to asking for the passphrase.
function GPGExportNotice({ keyID, onExported }: { keyID: string; onExported: () => void }) {
  const [state, setState] = useState<'exporting' | 'needs-passphrase' | 'error'>('exporting');
  const [passphrase, setPassphrase] = useState('');
  const [error, setError] = useState('');
  const tried = useRef(false);

  const run = async (pp: string) => {
    setState('exporting');
    setError('');
    try {
      const result = await exportGPGKey({ keyID, passphrase: pp });
      if (result.success) {
        onExported();
        return;
      }
      if (result.needsPassphrase) {
        setState('needs-passphrase');
      } else {
        setError(result.error || 'Failed to export key');
        setState('error');
      }
    } catch {
      setError('Failed to export key');
      setState('error');
    }
  };

  // Attempt a passphrase-less export once on mount.
  useEffect(() => {
    if (!tried.current) {
      tried.current = true;
      run('');
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="mt-2 p-3 rounded-lg bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 text-sm">
      {state === 'exporting' && (
        <p className="text-amber-700 dark:text-amber-300 text-xs">Exporting your GPG key to a file so builds can use it…</p>
      )}
      {(state === 'needs-passphrase' || state === 'error') && (
        <div className="space-y-2">
          <p className="text-amber-800 dark:text-amber-200 text-xs">
            {state === 'needs-passphrase'
              ? 'This key is passphrase-protected. Enter its passphrase to export it for builds.'
              : `Couldn't export the key: ${error}`}
          </p>
          {state === 'needs-passphrase' && (
            <div className="flex gap-2">
              <input
                type="password"
                value={passphrase}
                onChange={(e) => setPassphrase(e.target.value)}
                placeholder="Key passphrase"
                className="flex-1 px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
              />
              <button
                type="button"
                onClick={() => run(passphrase)}
                disabled={!passphrase}
                className="px-3 py-1.5 rounded-lg text-sm font-medium bg-red-500 text-white hover:bg-red-600 disabled:opacity-50"
              >
                Export
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// GPGKeySetup generates a new GPG signing key via the backend (works on any host
// that has gpg installed).
function GPGKeySetup({ defaultName, defaultEmail, onCreated, startOpen }: {
  defaultName: string;
  defaultEmail: string;
  onCreated: () => void;
  startOpen: boolean;
}) {
  const [open, setOpen] = useState(startOpen);
  const [name, setName] = useState(defaultName);
  const [email, setEmail] = useState(defaultEmail);
  const [passphrase, setPassphrase] = useState('');
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState('');
  const [done, setDone] = useState<{ keyID: string; keyPath?: string } | null>(null);

  const handleCreate = async () => {
    setError('');
    setCreating(true);
    try {
      const result = await createGPGKey({ name, email, passphrase });
      if (result.success) {
        setDone({ keyID: result.keyID || 'created', keyPath: result.keyPath });
        onCreated();
      } else {
        setError(result.error || 'Failed to create key');
      }
    } catch {
      setError('Failed to create GPG key');
    } finally {
      setCreating(false);
    }
  };

  if (done) {
    return (
      <div className="mt-3 p-3 rounded-lg bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 text-sm text-green-700 dark:text-green-300 space-y-1">
        <p>GPG key created{done.keyID !== 'created' ? <> — ID <code className="font-mono">{done.keyID}</code></> : ''} and selected.</p>
        {done.keyPath && (
          <p className="text-xs">
            Exported to <code className="font-mono break-all">{done.keyPath}</code>. Builds sign with this
            file — set it as <code className="font-mono">PGP_KEY</code> in <code className="font-mono">build/linux/Taskfile.yml</code> (or run <code className="font-mono">wails3 setup signing</code> in your project).
          </p>
        )}
      </div>
    );
  }

  if (!open) {
    return (
      <button
        type="button"
        onClick={() => setOpen(true)}
        className="mt-2 text-sm font-medium text-red-600 dark:text-red-400 hover:underline"
      >
        + Create a new GPG key
      </button>
    );
  }

  return (
    <div className="mt-3 p-3 rounded-lg border border-gray-200 dark:border-gray-700 space-y-3">
      <p className="text-xs text-gray-500 dark:text-gray-400">
        Generates an RSA 4096 key in your GPG keyring. Leave the passphrase blank for an
        unattended (CI-friendly) key.
      </p>
      <div>
        <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">Name</label>
        <input type="text" value={name} onChange={(e) => setName(e.target.value)} placeholder="Your Name"
          className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500" />
      </div>
      <div>
        <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">Email</label>
        <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com"
          className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500" />
      </div>
      <div>
        <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">Passphrase (optional)</label>
        <input type="password" value={passphrase} onChange={(e) => setPassphrase(e.target.value)} placeholder="Leave blank for no passphrase"
          className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500" />
      </div>
      {error && <p className="text-sm text-red-600 dark:text-red-400">{error}</p>}
      <div className="flex gap-2">
        <button type="button" onClick={() => setOpen(false)}
          className="px-3 py-1.5 rounded-lg text-sm font-medium border border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800">
          Cancel
        </button>
        <button type="button" onClick={handleCreate} disabled={creating || !name || !email}
          className="flex-1 px-3 py-1.5 rounded-lg text-sm font-medium bg-red-500 text-white hover:bg-red-600 disabled:opacity-50">
          {creating ? 'Generating…' : 'Generate GPG key'}
        </button>
      </div>
    </div>
  );
}

// WindowsCertSetup generates a self-signed code-signing certificate via openssl.
// Self-signed certs are for testing/internal distribution only — production needs
// a certificate from a trusted CA.
function WindowsCertSetup({ config, setConfig, onCreated }: {
  config: SigningDefaults;
  setConfig: (c: SigningDefaults) => void;
  onCreated: () => void;
}) {
  const [open, setOpen] = useState(false);
  const [commonName, setCommonName] = useState('');
  const [password, setPassword] = useState('');
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState('');
  const [donePath, setDonePath] = useState<string | null>(null);

  const handleCreate = async () => {
    setError('');
    setCreating(true);
    try {
      const result = await createWindowsCert({ commonName, password });
      if (result.success && result.path) {
        setDonePath(result.path);
        setConfig({ ...config, windows: { ...config.windows, certificatePath: result.path } });
        onCreated();
      } else {
        setError(result.error || 'Failed to create certificate');
      }
    } catch {
      setError('Failed to create certificate');
    } finally {
      setCreating(false);
    }
  };

  if (donePath) {
    return (
      <div className="p-3 rounded-lg bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 text-sm text-green-700 dark:text-green-300">
        Self-signed certificate created at <code className="font-mono text-xs break-all">{donePath}</code> and selected below.
      </div>
    );
  }

  if (!open) {
    return (
      <button
        type="button"
        onClick={() => setOpen(true)}
        className="text-sm font-medium text-red-600 dark:text-red-400 hover:underline"
      >
        + Generate a self-signed certificate (testing)
      </button>
    );
  }

  return (
    <div className="p-3 rounded-lg border border-gray-200 dark:border-gray-700 space-y-3">
      <div className="p-2 rounded bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800">
        <p className="text-xs text-amber-700 dark:text-amber-300">
          Self-signed certificates work for testing and internal distribution, but trigger
          SmartScreen warnings for end users. Production releases need a certificate from a trusted CA.
        </p>
      </div>
      <div>
        <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">Certificate Name (CN)</label>
        <input type="text" value={commonName} onChange={(e) => setCommonName(e.target.value)} placeholder="My Company"
          className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500" />
      </div>
      <div>
        <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">.pfx Password</label>
        <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Protects the generated .pfx"
          className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-red-500" />
      </div>
      {error && <p className="text-sm text-red-600 dark:text-red-400">{error}</p>}
      <div className="flex gap-2">
        <button type="button" onClick={() => setOpen(false)}
          className="px-3 py-1.5 rounded-lg text-sm font-medium border border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800">
          Cancel
        </button>
        <button type="button" onClick={handleCreate} disabled={creating || !commonName || !password}
          className="flex-1 px-3 py-1.5 rounded-lg text-sm font-medium bg-red-500 text-white hover:bg-red-600 disabled:opacity-50">
          {creating ? 'Generating…' : 'Generate certificate'}
        </button>
      </div>
    </div>
  );
}

function StatusRow({ label, configured, value }: {
  label: string;
  configured: boolean;
  value: string;
}) {
  return (
    <div className="flex items-center gap-3 p-4 rounded-lg bg-gray-100 dark:bg-gray-900/50">
      <div className={`w-8 h-8 rounded-full flex items-center justify-center ${configured ? 'bg-green-500/20' : 'bg-gray-200 dark:bg-gray-800'}`}>
        {configured ? (
          <svg className="w-4 h-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
          </svg>
        ) : (
          <svg className="w-4 h-4 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
          </svg>
        )}
      </div>
      <div className="flex-1">
        <div className="text-sm font-medium text-gray-900 dark:text-white">{label}</div>
        <div className="text-xs text-gray-500 dark:text-gray-400">{value}</div>
      </div>
    </div>
  );
}

function PlatformTab({ platform, label, isActive, hasConfig, onClick }: {
  platform: 'darwin' | 'windows' | 'linux';
  label: string;
  isActive: boolean;
  hasConfig?: boolean;
  onClick: () => void;
}) {
  const iconClass = `w-5 h-5 ${isActive ? 'text-gray-900 dark:text-white' : 'text-gray-400 dark:text-gray-500'}`;
  
  return (
    <button
      role="tab"
      aria-selected={isActive}
      onClick={onClick}
      className={`flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-lg text-sm font-medium transition-all ${
        isActive
          ? 'bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-white'
          : 'text-gray-500 dark:text-gray-400 hover:bg-gray-50 dark:hover:bg-gray-800/50'
      }`}
    >
      {platform === 'darwin' && (
        <svg className={iconClass} viewBox="0 0 24 24" fill="currentColor">
          <path d="M18.71 19.5c-.83 1.24-1.71 2.45-3.05 2.47-1.34.03-1.77-.79-3.29-.79-1.53 0-2 .77-3.27.82-1.31.05-2.3-1.32-3.14-2.53C4.25 17 2.94 12.45 4.7 9.39c.87-1.52 2.43-2.48 4.12-2.51 1.28-.02 2.5.87 3.29.87.78 0 2.26-1.07 3.81-.91.65.03 2.47.26 3.64 1.98-.09.06-2.17 1.28-2.15 3.81.03 3.02 2.65 4.03 2.68 4.04-.03.07-.42 1.44-1.38 2.83M13 3.5c.73-.83 1.94-1.46 2.94-1.5.13 1.17-.34 2.35-1.04 3.19-.69.85-1.83 1.51-2.95 1.42-.15-1.15.41-2.35 1.05-3.11z"/>
        </svg>
      )}
      {platform === 'windows' && (
        <svg className={iconClass} viewBox="0 0 24 24" fill="currentColor">
          <path d="M0 3.449L9.75 2.1v9.451H0m10.949-9.602L24 0v11.4H10.949M0 12.6h9.75v9.451L0 20.699M10.949 12.6H24V24l-12.9-1.801"/>
        </svg>
      )}
      {platform === 'linux' && (
        <svg className={iconClass} viewBox="0 0 24 24" fill="currentColor">
          <path d="M12.504 0c-.155 0-.315.008-.48.021-4.226.333-3.105 4.807-3.17 6.298-.076 1.092-.3 1.953-1.05 3.02-.885 1.051-2.127 2.75-2.716 4.521-.278.832-.41 1.684-.287 2.489a.424.424 0 00-.11.135c-.26.268-.45.6-.663.839-.199.199-.485.267-.797.4-.313.136-.658.269-.864.68-.09.189-.136.394-.132.602 0 .199.027.4.055.536.058.399.116.728.04.97-.249.68-.28 1.145-.106 1.484.174.334.535.47.94.601.81.2 1.91.135 2.774.6.926.466 1.866.67 2.616.47.526-.116.97-.464 1.208-.946.587-.003 1.23-.269 2.26-.334.699-.058 1.574.267 2.577.2.025.134.063.198.114.333l.003.003c.391.778 1.113 1.132 1.884 1.071.771-.06 1.592-.536 2.257-1.306.631-.765 1.683-1.084 2.378-1.503.348-.199.629-.469.649-.853.023-.4-.2-.811-.714-1.376v-.097l-.003-.003c-.17-.2-.25-.535-.338-.926-.085-.401-.182-.786-.492-1.046h-.003c-.059-.054-.123-.067-.188-.135a.357.357 0 00-.19-.064c.431-1.278.264-2.55-.173-3.694-.533-1.41-1.465-2.638-2.175-3.483-.796-1.005-1.576-1.957-1.56-3.368.026-2.152.236-6.133-3.544-6.139zm.529 3.405h.013c.213 0 .396.062.584.198.19.135.33.332.438.533.105.259.158.459.166.724 0-.02.006-.04.006-.06v.105a.086.086 0 01-.004-.021l-.004-.024a1.807 1.807 0 01-.15.706.953.953 0 01-.213.335.71.71 0 00-.088-.042c-.104-.045-.198-.064-.284-.133a1.312 1.312 0 00-.22-.066c.05-.06.146-.133.183-.198.053-.128.082-.264.088-.402v-.02a1.21 1.21 0 00-.061-.4c-.045-.134-.101-.2-.183-.333-.084-.066-.167-.132-.267-.132h-.016c-.093 0-.176.03-.262.132a.8.8 0 00-.205.334 1.18 1.18 0 00-.09.4v.019c.002.089.008.179.02.267-.193-.067-.438-.135-.607-.202a1.635 1.635 0 01-.018-.2v-.02a1.772 1.772 0 01.15-.768c.082-.22.232-.406.43-.533a.985.985 0 01.594-.2zm-2.962.059h.036c.142 0 .27.048.399.135.146.129.264.288.344.465.09.199.14.4.153.667v.004c.007.134.006.2-.002.266v.08c-.03.007-.056.018-.083.024-.152.055-.274.135-.393.2.012-.09.013-.18.003-.267v-.015c-.012-.133-.04-.2-.082-.333a.613.613 0 00-.166-.267.248.248 0 00-.183-.064h-.021c-.071.006-.13.04-.186.132a.552.552 0 00-.12.27.944.944 0 00-.023.33v.015c.012.135.037.2.08.267a.86.86 0 00.153.2c.071.085.178.135.305.178l.056.02a.398.398 0 00-.104.078c-.09.088-.198.2-.318.267-.145.085-.232.135-.39.135a1.04 1.04 0 01-.507-.151c-.106-.067-.199-.135-.285-.202l-.072-.053c-.239-.2-.439-.401-.618-.535a2.494 2.494 0 01-.393-.4c-.078-.1-.143-.199-.2-.298l-.06-.135-.048.066c-.078.133-.127.266-.127.465 0 .2.049.4.127.535.078.133.2.265.35.331.148.068.313.135.47.202.234.1.438.2.59.331.15.135.234.27.234.402 0 .135-.063.265-.198.332-.142.065-.32.102-.578.102-.232 0-.465-.037-.67-.1-.204-.068-.378-.17-.51-.301-.135-.135-.237-.301-.305-.5-.066-.199-.103-.432-.103-.699 0-.265.037-.5.106-.698.068-.2.166-.366.3-.5.135-.135.301-.234.5-.3.2-.067.432-.1.699-.1.266 0 .5.033.699.1.199.066.365.165.5.3.135.134.233.3.3.5.068.198.101.433.101.698 0 .267-.033.5-.1.7-.068.199-.166.365-.301.5-.135.134-.301.233-.5.3-.199.067-.433.1-.699.1-.267 0-.5-.033-.7-.1a1.379 1.379 0 01-.5-.3c-.134-.135-.233-.301-.3-.5-.066-.2-.1-.433-.1-.7 0-.266.034-.5.1-.698.067-.2.166-.366.3-.5.135-.135.301-.234.5-.3.2-.067.433-.1.7-.1z"/>
        </svg>
      )}
      <span>{label}</span>
      {hasConfig && (
        <span className="w-2 h-2 rounded-full bg-green-500" />
      )}
    </button>
  );
}
