# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  contributors:check:
    cmds:
      - npx -y all-contributors-cli check

  contributors:update:
    cmds:
      - go run v3/tasks/contribs/main.go

  contributors:build:
    cmds:
      - npx -y all-contributors-cli generate

  release:
    dir: v2/tools/release
    cmds:
      - go run release.go
