package commands

import (
	"bytes"
	"crypto"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"crypto/sha512"
	"crypto/x509"
	"encoding/asn1"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"errors"
	"fmt"
	"hash"
	"io"
	"math/big"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/pterm/pterm"
	"github.com/wailsapp/wails/v3/internal/github"
	"github.com/wailsapp/wails/v3/internal/term"
)

// This file implements the `wails3 updater` command group: the publishing
// side of the Wails Update Manifest protocol consumed by
// pkg/updater/providers/endpoint. It covers the whole release pipeline:
//
//	wails3 updater genkey                      one-time signing keypair
//	wails3 updater sign -key ... files...      digest+signature for artifacts
//	wails3 updater manifest -version ... dir   emit a signed manifest.json
//	wails3 updater verify -manifest ...        CI check before publishing
//
// The signing scheme is the framework's ed25519ph: an Ed25519ph signature
// over the artifact's SHA-512 digest, matching what the updater verifies
// against Config.PublicKey.

// updaterManifestSchemaVersion is the protocol schemaVersion this CLI emits.
const updaterManifestSchemaVersion = 1

// --- genkey ---

// UpdaterGenKeyOptions are the flags for `wails3 updater genkey`.
type UpdaterGenKeyOptions struct {
	Out   string `name:"out" description:"Path for the private key. The public key is written alongside with a .pub extension" default:"updater.key"`
	Force bool   `name:"force" description:"Overwrite existing key files"`
}

// UpdaterGenKey generates an Ed25519 keypair for signing update artifacts.
func UpdaterGenKey(options *UpdaterGenKeyOptions) error {
	DisableFooter = true
	if options.Out == "" {
		options.Out = "updater.key"
	}
	pubPath := options.Out + ".pub"

	if !options.Force {
		for _, p := range []string{options.Out, pubPath} {
			if _, err := os.Stat(p); err == nil {
				return fmt.Errorf("%s already exists (use -force to overwrite). Losing a key in use means shipped applications can no longer verify your updates", p)
			}
		}
	}

	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return err
	}
	privDER, err := x509.MarshalPKCS8PrivateKey(priv)
	if err != nil {
		return err
	}
	pubDER, err := x509.MarshalPKIXPublicKey(pub)
	if err != nil {
		return err
	}

	if dir := filepath.Dir(options.Out); dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}
	privPEM := pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: privDER})
	if err := os.WriteFile(options.Out, privPEM, 0o600); err != nil {
		return err
	}
	pubPEM := pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: pubDER})
	if err := os.WriteFile(pubPath, pubPEM, 0o644); err != nil {
		return err
	}

	term.Header("Updater Signing Key")
	pterm.Printf("Private key: %s (keep this secret, back it up)\n", options.Out)
	pterm.Printf("Public key:  %s\n\n", pubPath)
	pterm.Println("Pin the public key in your application:")
	pterm.Println("")
	pterm.Println("    //go:embed " + filepath.Base(pubPath))
	pterm.Println("    var updaterPublicKey []byte")
	pterm.Println("")
	pterm.Println("    updater.Config{ PublicKey: updaterPublicKey, ... }")
	pterm.Println("")
	pterm.Println("Or inline as base64 of the raw key:")
	pterm.Println("")
	pterm.Println("    " + base64.StdEncoding.EncodeToString(pub))
	pterm.Println("")
	pterm.Warning.Println("Anyone with the private key can sign updates for your users. Store it like a code-signing certificate: CI secret store or password manager, never in the repository.")
	return nil
}

// --- sign ---

// UpdaterSignOptions are the flags for `wails3 updater sign`.
type UpdaterSignOptions struct {
	Key string `name:"key" description:"Path to the private key generated by 'wails3 updater genkey'"`
}

// updaterArtifactSig is the JSON shape `wails3 updater sign` prints per file.
// The field names match the manifest artifact fields so output can be pasted
// straight into a hand-written manifest.
type updaterArtifactSig struct {
	Filename      string `json:"filename"`
	Size          int64  `json:"size"`
	DigestAlgo    string `json:"digestAlgo"`
	Digest        string `json:"digest"`
	SignatureAlgo string `json:"signatureAlgo,omitempty"`
	Signature     string `json:"signature,omitempty"`
}

// UpdaterSign signs one or more artifact files and prints the digests and
// signatures as JSON.
func UpdaterSign(options *UpdaterSignOptions, files []string) error {
	DisableFooter = true
	if options.Key == "" {
		return errors.New("please provide the private key with -key")
	}
	if len(files) == 0 {
		return errors.New("please provide at least one file to sign")
	}
	priv, err := loadUpdaterPrivateKey(options.Key)
	if err != nil {
		return err
	}

	var sigs []updaterArtifactSig
	for _, f := range files {
		sig, err := signUpdaterArtifact(f, priv)
		if err != nil {
			return err
		}
		sigs = append(sigs, sig)
	}
	out, err := json.MarshalIndent(sigs, "", "  ")
	if err != nil {
		return err
	}
	fmt.Println(string(out))
	return nil
}

// --- manifest ---

// UpdaterManifestOptions are the flags for `wails3 updater manifest`.
type UpdaterManifestOptions struct {
	Version   string `name:"version" description:"Release version (semver). Required"`
	Channel   string `name:"channel" description:"Release channel, e.g. stable or beta"`
	Name      string `name:"name" description:"Human-readable release title"`
	Notes     string `name:"notes" description:"Release notes (Markdown)"`
	NotesFile string `name:"notes-file" description:"Read release notes from a Markdown file"`
	Key       string `name:"key" description:"Private key path. When set, every artifact is signed (ed25519ph over its sha512 digest)"`
	URLPrefix string `name:"url-prefix" description:"Base URL prepended to artifact filenames. Default leaves URLs relative to the manifest's own location"`
	Output    string `name:"output" description:"Where to write the manifest, or - for stdout" default:"manifest.json"`
}

// updaterManifest mirrors the wire format of the Update Manifest protocol.
// It is deliberately a separate struct from the endpoint provider's private
// decoder: this is the writer, that is the reader, and the docs page is the
// contract between them.
type updaterManifest struct {
	SchemaVersion int                       `json:"schemaVersion"`
	Version       string                    `json:"version"`
	Channel       string                    `json:"channel,omitempty"`
	Name          string                    `json:"name,omitempty"`
	Notes         string                    `json:"notes,omitempty"`
	PublishedAt   string                    `json:"publishedAt"`
	Artifacts     []updaterManifestArtifact `json:"artifacts"`
}

type updaterManifestArtifact struct {
	URL           string `json:"url"`
	Platform      string `json:"platform,omitempty"`
	Arch          string `json:"arch,omitempty"`
	Filename      string `json:"filename,omitempty"`
	Filetype      string `json:"filetype,omitempty"`
	Size          int64  `json:"size,omitempty"`
	DigestAlgo    string `json:"digestAlgo,omitempty"`
	Digest        string `json:"digest,omitempty"`
	SignatureAlgo string `json:"signatureAlgo,omitempty"`
	Signature     string `json:"signature,omitempty"`
}

// UpdaterManifest generates an update manifest for the given artifact files
// or directories, computing digests and (when a key is provided) signatures.
func UpdaterManifest(options *UpdaterManifestOptions, args []string) error {
	DisableFooter = true
	if options.Version == "" {
		return errors.New("please provide the release version with -version")
	}
	if _, err := github.NewSemanticVersion(strings.TrimPrefix(options.Version, "v")); err != nil {
		return fmt.Errorf("invalid version %q: %w", options.Version, err)
	}
	if options.Output == "" {
		options.Output = "manifest.json"
	}
	if len(args) == 0 {
		return errors.New("please provide at least one artifact file or directory")
	}
	notes := options.Notes
	if options.NotesFile != "" {
		if notes != "" {
			return errors.New("use either -notes or -notes-file, not both")
		}
		b, err := os.ReadFile(options.NotesFile)
		if err != nil {
			return err
		}
		notes = string(b)
	}
	var priv ed25519.PrivateKey
	if options.Key != "" {
		var err error
		priv, err = loadUpdaterPrivateKey(options.Key)
		if err != nil {
			return err
		}
	}

	files, err := collectUpdaterArtifacts(args, options.Output)
	if err != nil {
		return err
	}
	if len(files) == 0 {
		return errors.New("no artifact files found")
	}

	m := updaterManifest{
		SchemaVersion: updaterManifestSchemaVersion,
		Version:       options.Version,
		Channel:       options.Channel,
		Name:          options.Name,
		Notes:         notes,
		PublishedAt:   time.Now().UTC().Format(time.RFC3339),
	}
	for _, f := range files {
		sig, err := signUpdaterArtifact(f, priv)
		if err != nil {
			return err
		}
		platform := inferUpdaterPlatform(sig.Filename)
		arch, archFound := inferUpdaterArch(sig.Filename)
		if platform == "" {
			pterm.Warning.Printfln("%s: could not infer the platform from the filename; the entry will match every platform. Include the Go GOOS value (darwin, windows, linux) in the filename, or edit the manifest.", sig.Filename)
		}
		if !archFound {
			pterm.Warning.Printfln("%s: could not infer the architecture from the filename; the entry will match every architecture. Include the Go GOARCH value (amd64, arm64) in the filename, or edit the manifest.", sig.Filename)
		}
		m.Artifacts = append(m.Artifacts, updaterManifestArtifact{
			URL:           joinUpdaterURL(options.URLPrefix, sig.Filename),
			Platform:      platform,
			Arch:          arch,
			Size:          sig.Size,
			DigestAlgo:    sig.DigestAlgo,
			Digest:        sig.Digest,
			SignatureAlgo: sig.SignatureAlgo,
			Signature:     sig.Signature,
		})
	}

	out, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return err
	}
	out = append(out, '\n')
	if options.Output == "-" {
		fmt.Print(string(out))
		return nil
	}
	if err := os.WriteFile(options.Output, out, 0o644); err != nil {
		return err
	}
	signed := "unsigned (no -key given)"
	if priv != nil {
		signed = "signed"
	}
	pterm.Success.Printfln("Wrote %s: version %s, %d artifact(s), %s", options.Output, options.Version, len(m.Artifacts), signed)
	return nil
}

// --- verify ---

// UpdaterVerifyOptions are the flags for `wails3 updater verify`.
type UpdaterVerifyOptions struct {
	Manifest  string `name:"manifest" description:"Path to the manifest to verify" default:"manifest.json"`
	PublicKey string `name:"publickey" description:"Public key: path to the .pub file, or a base64 string"`
	Dir       string `name:"dir" description:"Directory containing the artifact files. Defaults to the manifest's directory"`
}

// UpdaterVerify re-checks every artifact in a manifest against the files on
// disk: recomputes digests and verifies signatures with the public key,
// exactly as a shipped application would. Intended as a CI gate before
// publishing.
func UpdaterVerify(options *UpdaterVerifyOptions) error {
	DisableFooter = true
	if options.Manifest == "" {
		options.Manifest = "manifest.json"
	}
	raw, err := os.ReadFile(options.Manifest)
	if err != nil {
		return err
	}
	var m updaterManifest
	if err := json.Unmarshal(raw, &m); err != nil {
		return fmt.Errorf("decode %s: %w", options.Manifest, err)
	}
	if m.SchemaVersion > updaterManifestSchemaVersion {
		return fmt.Errorf("manifest schemaVersion %d is newer than this CLI supports (%d)", m.SchemaVersion, updaterManifestSchemaVersion)
	}
	if m.Version == "" {
		return errors.New("manifest is missing the required version field")
	}
	if len(m.Artifacts) == 0 {
		return errors.New("manifest has no artifacts")
	}

	var pub crypto.PublicKey
	if options.PublicKey != "" {
		pub, err = loadUpdaterPublicKey(options.PublicKey)
		if err != nil {
			return err
		}
	}
	dir := options.Dir
	if dir == "" {
		dir = filepath.Dir(options.Manifest)
	}

	var failures []string
	for _, a := range m.Artifacts {
		name := a.Filename
		if name == "" {
			name = filepath.Base(strings.SplitN(a.URL, "?", 2)[0])
		}
		if err := verifyUpdaterArtifact(filepath.Join(dir, name), &a, pub); err != nil {
			failures = append(failures, fmt.Sprintf("%s: %v", name, err))
			pterm.Error.Printfln("%s: %v", name, err)
			continue
		}
		// Report only the checks that actually ran; verifyUpdaterArtifact
		// guarantees at least one of them did.
		var checks []string
		if a.Digest != "" {
			checks = append(checks, "digest ok")
		}
		if a.Signature != "" {
			checks = append(checks, "signature ok")
		}
		pterm.Success.Printfln("%s: %s", name, strings.Join(checks, ", "))
	}
	if len(failures) > 0 {
		return fmt.Errorf("%d of %d artifact(s) failed verification", len(failures), len(m.Artifacts))
	}
	pterm.Success.Printfln("Manifest %s verified: version %s, %d artifact(s)", options.Manifest, m.Version, len(m.Artifacts))
	return nil
}

// verifyUpdaterArtifact checks one artifact file against its manifest entry.
// pub may be nil, in which case a signature-bearing entry is an error (the
// same fail-closed rule the framework applies). An entry that carries
// neither a digest nor a signature is also an error: this command is a CI
// gate, and reporting an unchecked file as verified would defeat it.
func verifyUpdaterArtifact(path string, a *updaterManifestArtifact, pub crypto.PublicKey) error {
	if a.Digest == "" && a.Signature == "" {
		return errors.New("artifact has neither digest nor signature; nothing to verify")
	}
	digest, size, err := hashUpdaterFile(path, a.DigestAlgo)
	if err != nil {
		return err
	}
	if a.Size != 0 && a.Size != size {
		return fmt.Errorf("size mismatch: manifest says %d bytes, file is %d", a.Size, size)
	}
	if a.Digest != "" {
		want, err := decodeUpdaterB64(a.Digest)
		if err != nil {
			return fmt.Errorf("digest is not valid base64: %w", err)
		}
		if !bytes.Equal(digest, want) {
			return errors.New("digest mismatch")
		}
	}
	if a.Signature == "" {
		return nil
	}
	if pub == nil {
		return errors.New("artifact carries a signature but no -publickey was given")
	}
	sig, err := decodeUpdaterB64(a.Signature)
	if err != nil {
		return fmt.Errorf("signature is not valid base64: %w", err)
	}
	switch algo := strings.ToLower(a.SignatureAlgo); algo {
	case "ed25519ph":
		edPub, ok := pub.(ed25519.PublicKey)
		if !ok {
			return fmt.Errorf("ed25519ph requires an Ed25519 public key, got %T", pub)
		}
		if strings.ToLower(a.DigestAlgo) != "sha512" {
			return fmt.Errorf("ed25519ph requires a sha512 digest, manifest declares %q", a.DigestAlgo)
		}
		if err := ed25519.VerifyWithOptions(edPub, digest, sig, &ed25519.Options{Hash: crypto.SHA512}); err != nil {
			return errors.New("ed25519ph signature did not verify")
		}
	case "ed25519":
		edPub, ok := pub.(ed25519.PublicKey)
		if !ok {
			return fmt.Errorf("ed25519 requires an Ed25519 public key, got %T", pub)
		}
		if !ed25519.Verify(edPub, digest, sig) {
			return errors.New("ed25519 signature did not verify")
		}
	case "ecdsa-p256":
		ecPub, ok := pub.(*ecdsa.PublicKey)
		if !ok {
			return fmt.Errorf("ecdsa-p256 requires an ECDSA public key, got %T", pub)
		}
		if ecPub.Curve != elliptic.P256() {
			return fmt.Errorf("ecdsa-p256 requires a P-256 key, got %s", ecPub.Curve.Params().Name)
		}
		r, s, err := splitUpdaterECDSASig(sig)
		if err != nil {
			return err
		}
		if !ecdsa.Verify(ecPub, digest, r, s) {
			return errors.New("ecdsa-p256 signature did not verify")
		}
	default:
		return fmt.Errorf("cannot verify signature algorithm %q with this CLI", a.SignatureAlgo)
	}
	return nil
}

// splitUpdaterECDSASig accepts the same two encodings the framework's
// verifier does: raw r||s (64 bytes for P-256) or ASN.1 DER with no
// trailing data.
func splitUpdaterECDSASig(sig []byte) (r, s *big.Int, err error) {
	if len(sig) == 64 {
		return new(big.Int).SetBytes(sig[:32]), new(big.Int).SetBytes(sig[32:]), nil
	}
	var seq struct{ R, S *big.Int }
	rest, err := asn1.Unmarshal(sig, &seq)
	if err != nil {
		return nil, nil, fmt.Errorf("ecdsa signature format unrecognised: %w", err)
	}
	if len(rest) != 0 {
		return nil, nil, errors.New("ecdsa signature has trailing data")
	}
	if seq.R == nil || seq.S == nil {
		return nil, nil, errors.New("ecdsa signature missing r/s")
	}
	return seq.R, seq.S, nil
}

// --- shared helpers ---

// signUpdaterArtifact streams the file through SHA-512 and, when priv is
// non-nil, signs the digest with Ed25519ph. This is the framework's
// ed25519ph verification scheme.
func signUpdaterArtifact(path string, priv ed25519.PrivateKey) (updaterArtifactSig, error) {
	digest, size, err := hashUpdaterFile(path, "sha512")
	if err != nil {
		return updaterArtifactSig{}, err
	}
	sig := updaterArtifactSig{
		Filename:   filepath.Base(path),
		Size:       size,
		DigestAlgo: "sha512",
		Digest:     base64.StdEncoding.EncodeToString(digest),
	}
	if priv != nil {
		s, err := priv.Sign(nil, digest, &ed25519.Options{Hash: crypto.SHA512})
		if err != nil {
			return updaterArtifactSig{}, err
		}
		sig.SignatureAlgo = "ed25519ph"
		sig.Signature = base64.StdEncoding.EncodeToString(s)
	}
	return sig, nil
}

// hashUpdaterFile streams path through the named digest algorithm and
// returns the digest and file size.
func hashUpdaterFile(path, algo string) ([]byte, int64, error) {
	var h hash.Hash
	switch strings.ToLower(algo) {
	case "", "sha256":
		h = sha256.New()
	case "sha512":
		h = sha512.New()
	default:
		return nil, 0, fmt.Errorf("unknown digest algorithm %q", algo)
	}
	f, err := os.Open(path)
	if err != nil {
		return nil, 0, err
	}
	defer f.Close()
	size, err := io.Copy(h, f)
	if err != nil {
		return nil, 0, err
	}
	return h.Sum(nil), size, nil
}

// loadUpdaterPrivateKey reads an Ed25519 private key: the PKCS#8 PEM file
// written by genkey, or (for CI secrets passed via files) base64 of the raw
// 64-byte private key or 32-byte seed.
func loadUpdaterPrivateKey(path string) (ed25519.PrivateKey, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if block, _ := pem.Decode(raw); block != nil {
		keyAny, err := x509.ParsePKCS8PrivateKey(block.Bytes)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		priv, ok := keyAny.(ed25519.PrivateKey)
		if !ok {
			return nil, fmt.Errorf("%s holds a %T, need an Ed25519 key (generate one with 'wails3 updater genkey')", path, keyAny)
		}
		return priv, nil
	}
	if b, err := base64.StdEncoding.DecodeString(strings.TrimSpace(string(raw))); err == nil {
		switch len(b) {
		case ed25519.PrivateKeySize:
			return ed25519.PrivateKey(b), nil
		case ed25519.SeedSize:
			return ed25519.NewKeyFromSeed(b), nil
		}
	}
	return nil, fmt.Errorf("%s is not a PEM or base64 Ed25519 private key (generate one with 'wails3 updater genkey')", path)
}

// loadUpdaterPublicKey accepts a path to a PEM/DER public key file or a
// base64 string of either the raw 32-byte Ed25519 key or a DER encoding,
// the same forms updater.Config.PublicKey accepts. Ed25519 and ECDSA P-256
// keys are supported, matching the framework's verifier registry.
func loadUpdaterPublicKey(pathOrB64 string) (crypto.PublicKey, error) {
	raw := []byte(pathOrB64)
	if b, err := os.ReadFile(pathOrB64); err == nil {
		raw = b
	} else if b, err := base64.StdEncoding.DecodeString(strings.TrimSpace(pathOrB64)); err == nil {
		raw = b
	}
	if len(raw) == ed25519.PublicKeySize {
		return ed25519.PublicKey(raw), nil
	}
	if block, _ := pem.Decode(raw); block != nil {
		raw = block.Bytes
	}
	pubAny, err := x509.ParsePKIXPublicKey(raw)
	if err != nil {
		return nil, fmt.Errorf("cannot parse public key %q: %w", pathOrB64, err)
	}
	switch pubAny.(type) {
	case ed25519.PublicKey, *ecdsa.PublicKey:
		return pubAny, nil
	}
	return nil, fmt.Errorf("public key is a %T, need Ed25519 or ECDSA P-256", pubAny)
}

// collectUpdaterArtifacts expands the file and directory arguments into a
// flat list of artifact files. Directories are read non-recursively. Key
// material, signature sidecars, hidden files and the manifest being written
// are skipped for file arguments too: shell globs (build/*) arrive as
// explicit files, and silently signing a stray .pub or the manifest itself
// is worse than announcing the skip.
func collectUpdaterArtifacts(args []string, outputPath string) ([]string, error) {
	outputAbs, _ := filepath.Abs(outputPath)
	skip := func(path string) bool {
		if skipUpdaterArtifact(filepath.Base(path)) {
			return true
		}
		abs, _ := filepath.Abs(path)
		return abs == outputAbs
	}
	var files []string
	for _, arg := range args {
		info, err := os.Stat(arg)
		if err != nil {
			return nil, err
		}
		if !info.IsDir() {
			if skip(arg) {
				pterm.Printf("  skipping %s (not a release artifact)\n", arg)
				continue
			}
			files = append(files, arg)
			continue
		}
		entries, err := os.ReadDir(arg)
		if err != nil {
			return nil, err
		}
		for _, e := range entries {
			if e.IsDir() {
				continue
			}
			p := filepath.Join(arg, e.Name())
			if skip(p) {
				continue
			}
			files = append(files, p)
		}
	}
	return files, nil
}

// decodeUpdaterB64 decodes base64 in standard or raw (unpadded) form, so
// manifests from third-party tooling that emits unpadded values verify too.
func decodeUpdaterB64(s string) ([]byte, error) {
	if b, err := base64.StdEncoding.DecodeString(s); err == nil {
		return b, nil
	}
	return base64.RawStdEncoding.DecodeString(s)
}

// skipUpdaterArtifact reports whether a directory entry is clearly not a
// release artifact: hidden files, manifests, key material, checksum and
// signature sidecars.
func skipUpdaterArtifact(name string) bool {
	lower := strings.ToLower(name)
	if strings.HasPrefix(lower, ".") {
		return true
	}
	for _, ext := range []string{".json", ".key", ".pub", ".pem", ".sig", ".asc", ".txt", ".md"} {
		if strings.HasSuffix(lower, ext) {
			return true
		}
	}
	return false
}

// joinUpdaterURL prepends the configured URL prefix to a filename. An empty
// prefix leaves the URL relative, which the endpoint provider resolves
// against the manifest's own URL.
func joinUpdaterURL(prefix, filename string) string {
	if prefix == "" {
		return filename
	}
	return strings.TrimSuffix(prefix, "/") + "/" + filename
}

// Filename inference. Artifact names conventionally embed the OS and
// architecture (MyApp-2.1.0-darwin-arm64.zip); these helpers map the common
// spellings to the Go GOOS/GOARCH values the protocol standardises on.
// Matches require a non-alphanumeric boundary so that, say, the x64 in
// "linux64" does not count.

var (
	updaterPlatformRe = map[string]*regexp.Regexp{
		"darwin":  regexp.MustCompile(`(?:^|[^a-z0-9])(?:darwin|macos|osx|mac)(?:[^a-z0-9]|$)`),
		"windows": regexp.MustCompile(`(?:^|[^a-z0-9])(?:windows|win64|win32|win)(?:[^a-z0-9]|$)`),
		"linux":   regexp.MustCompile(`(?:^|[^a-z0-9])(?:linux64|linux32|linux)(?:[^a-z0-9]|$)`),
	}
	// Ordered: "_" counts as a boundary, so the "x86" alternative in the 386
	// group would match inside "x86_64" if it were tried first.
	updaterArchRes = []struct {
		goarch string
		re     *regexp.Regexp
	}{
		{"amd64", regexp.MustCompile(`(?:^|[^a-z0-9])(?:amd64|x86_64|x64)(?:[^a-z0-9]|$)`)},
		{"arm64", regexp.MustCompile(`(?:^|[^a-z0-9])(?:arm64|aarch64)(?:[^a-z0-9]|$)`)},
		{"386", regexp.MustCompile(`(?:^|[^a-z0-9])(?:i386|386|x86|ia32)(?:[^a-z0-9]|$)`)},
		{"", regexp.MustCompile(`(?:^|[^a-z0-9])universal(?:[^a-z0-9]|$)`)},
	}
	updaterPlatformExt = map[string]string{
		".exe": "windows", ".msi": "windows", ".msix": "windows",
		".dmg": "darwin", ".pkg": "darwin",
		".appimage": "linux", ".deb": "linux", ".rpm": "linux",
	}
)

func inferUpdaterPlatform(filename string) string {
	lower := strings.ToLower(filename)
	for goos, re := range updaterPlatformRe {
		if re.MatchString(lower) {
			return goos
		}
	}
	if goos, ok := updaterPlatformExt[strings.ToLower(filepath.Ext(filename))]; ok {
		return goos
	}
	return ""
}

// inferUpdaterArch returns the GOARCH value plus whether anything was
// recognised: "universal" is recognised but maps to the empty (match-all)
// arch, so the caller needs the boolean to suppress its warning.
func inferUpdaterArch(filename string) (string, bool) {
	lower := strings.ToLower(filename)
	for _, entry := range updaterArchRes {
		if entry.re.MatchString(lower) {
			return entry.goarch, true
		}
	}
	return "", false
}
