// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GreetService is great
 * @module
 */

import {Call as $Call, Create as $Create} from "@wailsio/runtime";

import * as services$0 from "./services/models.js";

/**
 * Greet does XYZ
 * @param {string} name
 * @param {services$0.Title} title
 * @returns {Promise<string> & { cancel(): void }}
 */
export function Greet(name, title) {
    let $resultPromise = $Call.ByID(1411160069, name, title);
    return /** @type {any} */($resultPromise);
}
