// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Call} from '@wailsio/runtime';
// Greet someone
export async function Greet(name: string) : Promise<string> {
	return Call.ByID(1411160069, name);
}

// Greet someone
export async function GreetWithContext(name: string) : Promise<string> {
	return Call.ByID(1310150960, name);
}

