package events

var Mac = newMacEvents()

type macEvents struct {
	ApplicationDidBecomeActive               uint
	ApplicationDidChangeBackingProperties    uint
	ApplicationDidChangeEffectiveAppearance  uint
	ApplicationDidChangeIcon                 uint
	ApplicationDidChangeOcclusionState       uint
	ApplicationDidChangeScreenParameters     uint
	ApplicationDidChangeStatusBarFrame       uint
	ApplicationDidChangeStatusBarOrientation uint
	ApplicationDidFinishLaunching            uint
	ApplicationDidHide                       uint
	ApplicationDidResignActive               uint
	ApplicationDidUnhide                     uint
	ApplicationDidUpdate                     uint
	ApplicationWillBecomeActive              uint
	ApplicationWillFinishLaunching           uint
	ApplicationWillHide                      uint
	ApplicationWillResignActive              uint
	ApplicationWillTerminate                 uint
	ApplicationWillUnhide                    uint
	ApplicationWillUpdate                    uint
	WindowDidBecomeKey                       uint
	WindowDidBecomeMain                      uint
	WindowDidBeginSheet                      uint
	WindowDidChangeAlpha                     uint
	WindowDidChangeBackingLocation           uint
	WindowDidChangeBackingProperties         uint
	WindowDidChangeCollectionBehavior        uint
	WindowDidChangeEffectiveAppearance       uint
	WindowDidChangeOcclusionState            uint
	WindowDidChangeOrderingMode              uint
	WindowDidChangeScreen                    uint
	WindowDidChangeScreenParameters          uint
	WindowDidChangeScreenProfile             uint
	WindowDidChangeScreenSpace               uint
	WindowDidChangeScreenSpaceProperties     uint
	WindowDidChangeSharingType               uint
	WindowDidChangeSpace                     uint
	WindowDidChangeSpaceOrderingMode         uint
	WindowDidChangeTitle                     uint
	WindowDidChangeToolbar                   uint
	WindowDidChangeVisibility                uint
	WindowDidClose                           uint
	WindowDidDeminiaturize                   uint
	WindowDidEndSheet                        uint
	WindowDidEnterFullScreen                 uint
	WindowDidEnterVersionBrowser             uint
	WindowDidExitFullScreen                  uint
	WindowDidExitVersionBrowser              uint
	WindowDidExpose                          uint
	WindowDidFocus                           uint
	WindowDidMiniaturize                     uint
	WindowDidMove                            uint
	WindowDidOrderOffScreen                  uint
	WindowDidOrderOnScreen                   uint
	WindowDidResignKey                       uint
	WindowDidResignMain                      uint
	WindowDidResize                          uint
	WindowDidUnfocus                         uint
	WindowDidUpdate                          uint
	WindowDidUpdateAlpha                     uint
	WindowDidUpdateCollectionBehavior        uint
	WindowDidUpdateCollectionProperties      uint
	WindowDidUpdateShadow                    uint
	WindowDidUpdateTitle                     uint
	WindowDidUpdateToolbar                   uint
	WindowDidUpdateVisibility                uint
	WindowWillBecomeKey                      uint
	WindowWillBecomeMain                     uint
	WindowWillBeginSheet                     uint
	WindowWillChangeOrderingMode             uint
	WindowWillClose                          uint
	WindowWillDeminiaturize                  uint
	WindowWillEnterFullScreen                uint
	WindowWillEnterVersionBrowser            uint
	WindowWillExitFullScreen                 uint
	WindowWillExitVersionBrowser             uint
	WindowWillFocus                          uint
	WindowWillMiniaturize                    uint
	WindowWillMove                           uint
	WindowWillOrderOffScreen                 uint
	WindowWillOrderOnScreen                  uint
	WindowWillResignMain                     uint
	WindowWillResize                         uint
	WindowWillUnfocus                        uint
	WindowWillUpdate                         uint
	WindowWillUpdateAlpha                    uint
	WindowWillUpdateCollectionBehavior       uint
	WindowWillUpdateCollectionProperties     uint
	WindowWillUpdateShadow                   uint
	WindowWillUpdateTitle                    uint
	WindowWillUpdateToolbar                  uint
	WindowWillUpdateVisibility               uint
	WindowWillUseStandardFrame               uint
}

func newMacEvents() macEvents {
	return macEvents{
		ApplicationDidBecomeActive:               0,
		ApplicationDidChangeBackingProperties:    1,
		ApplicationDidChangeEffectiveAppearance:  2,
		ApplicationDidChangeIcon:                 3,
		ApplicationDidChangeOcclusionState:       4,
		ApplicationDidChangeScreenParameters:     5,
		ApplicationDidChangeStatusBarFrame:       6,
		ApplicationDidChangeStatusBarOrientation: 7,
		ApplicationDidFinishLaunching:            8,
		ApplicationDidHide:                       9,
		ApplicationDidResignActive:               10,
		ApplicationDidUnhide:                     11,
		ApplicationDidUpdate:                     12,
		ApplicationWillBecomeActive:              13,
		ApplicationWillFinishLaunching:           14,
		ApplicationWillHide:                      15,
		ApplicationWillResignActive:              16,
		ApplicationWillTerminate:                 17,
		ApplicationWillUnhide:                    18,
		ApplicationWillUpdate:                    19,
		WindowDidBecomeKey:                       20,
		WindowDidBecomeMain:                      21,
		WindowDidBeginSheet:                      22,
		WindowDidChangeAlpha:                     23,
		WindowDidChangeBackingLocation:           24,
		WindowDidChangeBackingProperties:         25,
		WindowDidChangeCollectionBehavior:        26,
		WindowDidChangeEffectiveAppearance:       27,
		WindowDidChangeOcclusionState:            28,
		WindowDidChangeOrderingMode:              29,
		WindowDidChangeScreen:                    30,
		WindowDidChangeScreenParameters:          31,
		WindowDidChangeScreenProfile:             32,
		WindowDidChangeScreenSpace:               33,
		WindowDidChangeScreenSpaceProperties:     34,
		WindowDidChangeSharingType:               35,
		WindowDidChangeSpace:                     36,
		WindowDidChangeSpaceOrderingMode:         37,
		WindowDidChangeTitle:                     38,
		WindowDidChangeToolbar:                   39,
		WindowDidChangeVisibility:                40,
		WindowDidClose:                           41,
		WindowDidDeminiaturize:                   42,
		WindowDidEndSheet:                        43,
		WindowDidEnterFullScreen:                 44,
		WindowDidEnterVersionBrowser:             45,
		WindowDidExitFullScreen:                  46,
		WindowDidExitVersionBrowser:              47,
		WindowDidExpose:                          48,
		WindowDidFocus:                           49,
		WindowDidMiniaturize:                     50,
		WindowDidMove:                            51,
		WindowDidOrderOffScreen:                  52,
		WindowDidOrderOnScreen:                   53,
		WindowDidResignKey:                       54,
		WindowDidResignMain:                      55,
		WindowDidResize:                          56,
		WindowDidUnfocus:                         57,
		WindowDidUpdate:                          58,
		WindowDidUpdateAlpha:                     59,
		WindowDidUpdateCollectionBehavior:        60,
		WindowDidUpdateCollectionProperties:      61,
		WindowDidUpdateShadow:                    62,
		WindowDidUpdateTitle:                     63,
		WindowDidUpdateToolbar:                   64,
		WindowDidUpdateVisibility:                65,
		WindowWillBecomeKey:                      66,
		WindowWillBecomeMain:                     67,
		WindowWillBeginSheet:                     68,
		WindowWillChangeOrderingMode:             69,
		WindowWillClose:                          70,
		WindowWillDeminiaturize:                  71,
		WindowWillEnterFullScreen:                72,
		WindowWillEnterVersionBrowser:            73,
		WindowWillExitFullScreen:                 74,
		WindowWillExitVersionBrowser:             75,
		WindowWillFocus:                          76,
		WindowWillMiniaturize:                    77,
		WindowWillMove:                           78,
		WindowWillOrderOffScreen:                 79,
		WindowWillOrderOnScreen:                  80,
		WindowWillResignMain:                     81,
		WindowWillResize:                         82,
		WindowWillUnfocus:                        83,
		WindowWillUpdate:                         84,
		WindowWillUpdateAlpha:                    85,
		WindowWillUpdateCollectionBehavior:       86,
		WindowWillUpdateCollectionProperties:     87,
		WindowWillUpdateShadow:                   88,
		WindowWillUpdateTitle:                    89,
		WindowWillUpdateToolbar:                  90,
		WindowWillUpdateVisibility:               91,
		WindowWillUseStandardFrame:               92,
	}
}
