// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Call} from "/wails/runtime.js";

import * as debug from "../runtime/debug/models.js";
import * as uuid from "../github.com/google/uuid/models.js";

/**
 * @returns {Promise<[debug.BuildInfo | null, boolean]>}
 */
export function BuildInfo() {
    return Call.ByID(2776941280);
}

/**
 * @param {string} name
 * @returns {Promise<string>}
 */
export function Greet(name) {
    return Call.ByID(1411160069, name);
}

/**
 * @returns {Promise<uuid.UUID>}
 */
export function UUID() {
    return Call.ByID(478608279);
}
