// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Call} from "/wails/runtime.js";

import * as debug from "../runtime-debug/models";

export function BuildInfo(): Promise<[debug.BuildInfo | null, boolean]> {
    return Call.ByName("main.GreetService.BuildInfo");
}

export function Greet(name: string): Promise<string> {
    return Call.ByName("main.GreetService.Greet", name);
}
