# https://taskfile.dev

version: "3"

tasks:
  release:
    summary: Release a new version of Task. Call with `task v2:release -- <version>`
    dir: tools/release
    cmds:
      - go run release.go {{.CLI_ARGS}}

  format:md:
    cmds:
      - npx prettier --write "**/*.md"

  format:
    cmds:
      - task: format:md
