package manifest

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func writeManifest(t *testing.T, root, contents string) string {
	t.Helper()
	path := filepath.Join(root, Filename)
	require.NoError(t, os.WriteFile(path, []byte(contents), 0o644))
	return path
}

const minimalHCL = `version = 3

project {
  name = "hello"
  product_name = "Hello"
  identifier = "com.example.hello"
  version = "0.1.0"
}

frontend {
  directory = "frontend"
  install = ["pnpm", "install", "--frozen-lockfile"]
  build = ["pnpm", "run", "build"]
  dev = ["pnpm", "run", "dev"]
  output = "frontend/dist"
}

build {
  output = "bin"
}
`

func TestLoadHCLConfiguration(t *testing.T) {
	root := t.TempDir()
	writeManifest(t, root, minimalHCL)
	loaded, err := Load(root, "")
	require.NoError(t, err)
	assert.Equal(t, root, loaded.Config.Root)
	assert.Equal(t, "hello", loaded.Config.Project.BinaryName)
	assert.Equal(t, "pnpm", loaded.Config.Frontend.PackageManager)
	assert.Equal(t, []string{"pnpm", "install", "--frozen-lockfile"}, loaded.Config.Frontend.Install)
	assert.Equal(t, "frontend/dist", loaded.Config.Frontend.OutputDirectory)
	assert.Equal(t, "bin", loaded.Config.Build.OutputDirectory)
}

func TestVersionIsTheFirstAttribute(t *testing.T) {
	root := t.TempDir()
	writeManifest(t, root, `project { name = "hello" }
version = 3`)
	_, err := Load(root, "")
	require.ErrorContains(t, err, "version must be the first attribute")
}

func TestOnlyLiteralExpressionsAreAccepted(t *testing.T) {
	root := t.TempDir()
	writeManifest(t, root, `version = 3
project {
  name = "hello"
  product_name = "Hello"
  identifier = "com.example.hello"
  version = "0.1.0"
  binary_name = lower("HELLO")
}`)
	_, err := Load(root, "")
	require.ErrorContains(t, err, "only literal values are allowed")
}

func TestUnknownFieldsAndBlocksAreRejected(t *testing.T) {
	root := t.TempDir()
	writeManifest(t, root, `version = 3
project {
  name = "hello"
  product_name = "Hello"
  identifier = "com.example.hello"
  version = "0.1.0"
  surprise = true
}`)
	_, err := Load(root, "")
	require.Error(t, err)
	require.Contains(t, err.Error(), "Unsupported argument")
}

func TestProfileIsACompleteBuildRequest(t *testing.T) {
	root := t.TempDir()
	writeManifest(t, root, minimalHCL+`
profile "release" {
  target "windows/amd64" {
    formats = ["nsis"]
    sign = true
  }
  target "darwin/universal" {
    formats = ["dmg"]
    sign = true
    notarize = true
  }
}`)
	loaded, err := Load(root, "release")
	require.NoError(t, err)
	require.Equal(t, "release", loaded.Config.Selected.Name)
	require.Len(t, loaded.Config.Selected.Targets, 2)
	assert.Equal(t, []string{"dmg"}, loaded.Config.Selected.Targets[1].Formats)
}

func TestProfileMustHaveTargets(t *testing.T) {
	root := t.TempDir()
	writeManifest(t, root, minimalHCL+`profile "release" {}`)
	_, err := Load(root, "")
	require.ErrorContains(t, err, "requires at least one target")
}

func TestDiscoverUsesNearestManifest(t *testing.T) {
	root := t.TempDir()
	writeManifest(t, root, minimalHCL)
	nested := filepath.Join(root, "frontend", "src")
	require.NoError(t, os.MkdirAll(nested, 0o755))
	loaded, err := Load(nested, "")
	require.NoError(t, err)
	assert.Equal(t, root, loaded.Config.Root)
}

func TestEjectCreatesAnInactiveSibling(t *testing.T) {
	root := t.TempDir()
	writeManifest(t, root, minimalHCL)
	require.NoError(t, Eject(root, "", "v3.0.0", false))
	data, err := os.ReadFile(filepath.Join(root, EjectedFilename))
	require.NoError(t, err)
	assert.Contains(t, string(data), "Generated by Wails CLI v3.0.0")
	assert.FileExists(t, filepath.Join(root, Filename))
	_, err = LoadFile(root, filepath.Join(root, EjectedFilename), "")
	require.NoError(t, err)
	original := append([]byte(nil), data...)
	require.ErrorContains(t, Eject(root, "", "v3.0.0", false), "refusing to overwrite")
	after, err := os.ReadFile(filepath.Join(root, EjectedFilename))
	require.NoError(t, err)
	assert.Equal(t, original, after)
}

func TestMinimalEscapesHCLTemplateAndControlSequences(t *testing.T) {
	root := t.TempDir()
	project := Project{
		Name:        "app-${name}",
		ProductName: "App %{" + string([]byte{1}) + "}",
		Identifier:  "com.example.app",
		Version:     "1.0.0",
	}
	require.NoError(t, WriteMinimal(root, project))
	loaded, err := Load(root, "")
	require.NoError(t, err)
	assert.Equal(t, project.Name, loaded.Config.Project.Name)
	assert.Equal(t, project.ProductName, loaded.Config.Project.ProductName)
}
