package manifest

import (
	"bytes"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

func encodeInitialYAML(state InitialState) []byte {
	root := yamlMap()
	root.HeadComment = "yaml-language-server: $schema=" + JSONSchemaURL
	yamlSet(root, "version", yamlInt(3))
	project := yamlMap()
	yamlSetString(project, "name", state.Project.Name)
	yamlSetString(project, "product_name", state.Project.ProductName)
	yamlSetString(project, "identifier", state.Project.Identifier)
	yamlSetString(project, "version", state.Project.Version)
	yamlSetString(project, "binary_name", deriveBinaryName(state.Project.Name))
	yamlSetOptionalString(project, "company", state.Project.CompanyName)
	yamlSetOptionalString(project, "description", state.Project.Description)
	yamlSetOptionalString(project, "copyright", state.Project.Copyright)
	yamlSetOptionalString(project, "comments", state.Project.Comments)
	yamlSet(root, "project", project)
	frontend := yamlMap()
	yamlSetString(frontend, "directory", "frontend")
	yamlSet(frontend, "install", yamlStrings([]string{"npm", "install"}))
	yamlSet(frontend, "build", yamlStrings([]string{"npm", "run", "build"}))
	yamlSet(frontend, "dev", yamlStrings([]string{"npm", "run", "dev"}))
	yamlSetString(frontend, "output", "frontend/dist")
	bindings := yamlMap()
	yamlSet(bindings, "typescript", yamlBool(state.TypeScript))
	yamlSet(bindings, "interfaces", yamlBool(state.TypeScript && state.Interfaces))
	yamlSet(frontend, "bindings", bindings)
	yamlSet(root, "frontend", frontend)
	build := yamlMap()
	yamlSetString(build, "output", "bin")
	yamlSet(root, "build", build)
	data, _ := marshalYAML(root)
	return data
}

func EncodeEjectedYAML(config Config, cliVersion string) ([]byte, error) {
	header := "Fully resolved Wails build configuration"
	if cliVersion != "" {
		header += " — Generated by Wails CLI " + cliVersion
	}
	return encodeConfigYAML(config, header)
}

func encodeConfigYAML(config Config, header string) ([]byte, error) {
	root := yamlMap()
	root.HeadComment = header
	yamlSet(root, "version", yamlInt(3))

	project := yamlMap()
	yamlSetOptionalStrings(project, "supported_platforms", config.Project.SupportedPlatforms, false)
	yamlSetString(project, "name", config.Project.Name)
	yamlSetString(project, "product_name", config.Project.ProductName)
	yamlSetString(project, "identifier", config.Project.Identifier)
	yamlSetString(project, "version", config.Project.Version)
	yamlSetString(project, "binary_name", config.Project.BinaryName)
	yamlSet(project, "build_number", yamlInt(config.Project.BuildNumber))
	yamlSetOptionalString(project, "company", config.Project.CompanyName)
	yamlSetOptionalString(project, "description", config.Project.Description)
	yamlSetOptionalString(project, "copyright", config.Project.Copyright)
	yamlSetOptionalString(project, "comments", config.Project.Comments)
	yamlSetOptionalString(project, "icon", config.Project.Icon)
	yamlSet(root, "project", project)

	frontend := yamlMap()
	yamlSet(frontend, "disabled", yamlBool(config.Frontend.Disabled))
	yamlSetString(frontend, "directory", config.Frontend.Directory)
	yamlSet(frontend, "install", yamlStrings(config.Frontend.Install))
	yamlSet(frontend, "build", yamlStrings(config.Frontend.Build))
	yamlSet(frontend, "dev", yamlStrings(config.Frontend.Dev))
	yamlSetString(frontend, "output", config.Frontend.OutputDirectory)
	yamlSetOptionalStringMap(frontend, "environment", config.Frontend.Environment)
	bindings := yamlMap()
	yamlSet(bindings, "typescript", yamlBool(config.Frontend.Bindings.TypeScript))
	yamlSet(bindings, "interfaces", yamlBool(config.Frontend.Bindings.Interfaces))
	yamlSetString(bindings, "output", config.Frontend.Bindings.OutputDirectory)
	yamlSetString(bindings, "models_filename", config.Frontend.Bindings.ModelsFilename)
	yamlSetString(bindings, "index_filename", config.Frontend.Bindings.IndexFilename)
	yamlSetString(bindings, "time_type", config.Frontend.Bindings.TimeType)
	yamlSet(frontend, "bindings", bindings)
	yamlSet(root, "frontend", frontend)

	build := yamlMap()
	yamlSetString(build, "output", config.Build.OutputDirectory)
	yamlSet(build, "tags", yamlStrings(config.Build.Go.Tags))
	yamlSet(build, "trim_path", yamlBool(config.Build.TrimPath))
	yamlSet(build, "strip", yamlBool(config.Build.Strip))
	yamlSet(build, "vcs_info", yamlBool(config.Build.VCSInfo))
	yamlSet(build, "obfuscated", yamlBool(config.Build.Obfuscation))
	yamlSetOptionalStringMap(build, "environment", config.Build.Environment)
	yamlSetOptionalStrings(build, "garble_args", config.Build.Go.GarbleArgs, false)
	yamlSetOptionalStrings(build, "ldflags", config.Build.Go.LinkerFlags, false)
	yamlSetOptionalStrings(build, "compiler_flags", config.Build.Go.CompilerFlags, false)
	yamlSet(root, "build", build)

	dev := yamlMap()
	yamlSetOptionalStrings(dev, "args", config.Dev.Args, config.Dev.ArgsSet)
	yamlSet(dev, "tags", yamlStrings(config.Dev.Tags))
	yamlSet(dev, "debounce_ms", yamlInt(config.Dev.DebounceMS))
	yamlSetString(dev, "log_level", config.Dev.LogLevel)
	yamlSetOptionalStrings(dev, "watch", config.Dev.Watch, manifestValueWasExplicit(config.Origins, "dev.watch"))
	yamlSetOptionalStrings(dev, "exclude", config.Dev.Exclude, manifestValueWasExplicit(config.Origins, "dev.exclude"))
	yamlSet(dev, "use_git_ignore", yamlBool(config.Dev.UseGitIgnore))
	yamlSet(dev, "grace_period_ms", yamlInt(config.Dev.GracePeriodMS))
	yamlSet(root, "dev", dev)
	yamlSetRun(root, "run", config.Run)

	for _, item := range []struct {
		name    string
		value   Platform
		signing SigningPlatform
	}{{"windows", config.Targets.Windows, config.Signing.Windows}, {"darwin", config.Targets.Darwin, config.Signing.Darwin}, {"linux", config.Targets.Linux, config.Signing.Linux}, {"ios", config.Targets.IOS, config.Signing.IOS}, {"android", config.Targets.Android, config.Signing.Android}} {
		if platform := encodeYAMLPlatform(item.name, item.value, item.signing); platform != nil {
			yamlSet(root, item.name, platform)
		}
	}

	targets := yamlMap()
	for _, item := range []struct {
		name  string
		value Target
	}{
		{"windows/amd64", config.Targets.Windows.AMD64}, {"windows/arm64", config.Targets.Windows.ARM64},
		{"darwin/amd64", config.Targets.Darwin.AMD64}, {"darwin/arm64", config.Targets.Darwin.ARM64}, {"darwin/universal", config.Targets.Darwin.Universal},
		{"linux/amd64", config.Targets.Linux.AMD64}, {"linux/arm64", config.Targets.Linux.ARM64},
		{"ios/arm64", config.Targets.IOS.ARM64},
		{"android/amd64", config.Targets.Android.AMD64}, {"android/arm64", config.Targets.Android.ARM64}, {"android/universal", config.Targets.Android.Universal},
	} {
		if target := encodeYAMLTarget(item.value); target != nil {
			yamlSet(targets, item.name, target)
		}
	}
	if len(targets.Content) > 0 {
		yamlSet(root, "targets", targets)
	}

	packages := yamlMap()
	for _, item := range []struct{ platform, format string }{
		{"windows", "nsis"}, {"windows", "msix"}, {"darwin", "dmg"},
		{"linux", "appimage"}, {"linux", "deb"}, {"linux", "rpm"}, {"linux", "archlinux"},
	} {
		value, err := ResolvePackageFormat(config.Package, item.platform, item.format)
		if err != nil {
			return nil, err
		}
		if node := encodeYAMLPackage(item.format, value); node != nil {
			yamlSet(packages, item.format, node)
		}
	}
	if len(packages.Content) > 0 {
		yamlSet(root, "packages", packages)
	}

	hooks := yamlMap()
	for _, phase := range HookPhases {
		hook, ok := config.Hooks[phase]
		if !ok {
			continue
		}
		entry := yamlMap()
		yamlSetString(entry, "script", hook.Script)
		yamlSetOptionalString(entry, "directory", hook.Directory)
		yamlSet(entry, "cache", yamlBool(hook.Cache))
		yamlSetOptionalStrings(entry, "inputs", hook.Inputs, false)
		yamlSetOptionalStrings(entry, "outputs", hook.Outputs, false)
		yamlSet(hooks, string(phase), entry)
	}
	if len(hooks.Content) > 0 {
		yamlSet(root, "hooks", hooks)
	}

	associations := yamlMap()
	associationKeys := make(map[string]struct{}, len(config.Associations))
	for _, association := range config.Associations {
		key := association.Name
		if key == "" && len(association.Extensions) > 0 {
			key = strings.TrimSpace(strings.TrimPrefix(association.Extensions[0], "."))
		}
		if strings.TrimSpace(key) == "" {
			return nil, fmt.Errorf("encode file association: a non-empty name or extension is required")
		}
		if _, exists := associationKeys[key]; exists {
			return nil, fmt.Errorf("encode file association %q: duplicate mapping key", key)
		}
		associationKeys[key] = struct{}{}
		entry := yamlMap()
		yamlSet(entry, "extensions", yamlStrings(association.Extensions))
		yamlSetOptionalString(entry, "name", association.Name)
		yamlSetOptionalString(entry, "description", association.Description)
		yamlSetOptionalString(entry, "icon", association.Icon)
		yamlSetOptionalString(entry, "role", association.Role)
		yamlSetOptionalString(entry, "mime_type", association.MIMEType)
		yamlSetOptionalStrings(entry, "platforms", association.Platforms, false)
		yamlSet(associations, key, entry)
	}
	if len(associations.Content) > 0 {
		yamlSet(root, "file_associations", associations)
	}

	protocols := yamlMap()
	for _, protocol := range config.Protocols {
		entry := yamlMap()
		yamlSetOptionalString(entry, "description", protocol.Description)
		yamlSetOptionalStrings(entry, "platforms", protocol.Platforms, false)
		yamlSet(protocols, protocol.Scheme, entry)
	}
	if len(protocols.Content) > 0 {
		yamlSet(root, "protocols", protocols)
	}

	profiles := yamlMap()
	for _, profile := range sortedProfiles(config.Profiles) {
		entry := yamlMap()
		profileTargets := yamlMap()
		for _, target := range profile.Targets {
			targetNode := yamlMap()
			yamlSetOptionalStrings(targetNode, "formats", target.Formats, false)
			if target.Sign {
				yamlSet(targetNode, "sign", yamlBool(true))
			}
			if target.Notarize {
				yamlSet(targetNode, "notarize", yamlBool(true))
			}
			yamlSetOptionalString(targetNode, "destination", target.Destination)
			yamlSet(profileTargets, target.Target, targetNode)
		}
		yamlSet(entry, "targets", profileTargets)
		yamlSet(profiles, profile.Name, entry)
	}
	if len(profiles.Content) > 0 {
		yamlSet(root, "profiles", profiles)
	}
	return marshalYAML(root)
}

func encodeYAMLPlatform(name string, platform Platform, signing SigningPlatform) *yaml.Node {
	if !platformConfigured(platform) && signing == (SigningPlatform{}) {
		return nil
	}
	result := yamlMap()
	switch name {
	case "ios":
		yamlSetOptionalString(result, "display_name", platform.ProductName)
		yamlSetOptionalString(result, "bundle_id", platform.Identifier)
	case "android":
		yamlSetOptionalString(result, "display_name", platform.ProductName)
		yamlSetOptionalString(result, "application_id", platform.Identifier)
	default:
		yamlSetOptionalString(result, "product_name", platform.ProductName)
		yamlSetOptionalString(result, "identifier", platform.Identifier)
	}
	for _, entry := range []struct{ key, value string }{
		{"minimum_version", platform.MinimumVersion}, {"icon", platform.Icon}, {"manifest", platform.Manifest},
		{"assets_car", platform.AssetsCar}, {"info_plist", platform.InfoPlist}, {"publisher", platform.Publisher},
		{"desktop_entry", platform.DesktopEntry}, {"company", platform.CompanyName}, {"comments", platform.Comments},
		{"cf_bundle_icon_name", platform.CFBundleIconName}, {"version_name", platform.VersionName},
	} {
		if platformAttributeAllowed(name, entry.key) {
			yamlSetOptionalString(result, entry.key, entry.value)
		}
	}
	for _, entry := range []struct {
		key   string
		value int
	}{{"build_number", platform.BuildNumber}, {"version_code", platform.VersionCode}, {"minimum_sdk", platform.MinimumSDK}, {"target_sdk", platform.TargetSDK}} {
		if entry.value != 0 && platformAttributeAllowed(name, entry.key) {
			yamlSet(result, entry.key, yamlInt(entry.value))
		}
	}
	if platformAttributeAllowed(name, "capabilities") {
		yamlSetOptionalStrings(result, "capabilities", platform.Capabilities, false)
	}
	if platformAttributeAllowed(name, "background_modes") {
		yamlSetOptionalStrings(result, "background_modes", platform.BackgroundModes, false)
	}
	if signing.Enabled || signingHasValues(signing) {
		node := yamlMap()
		for _, entry := range []struct{ key, value string }{
			{"credential", signing.Credential}, {"identity", signing.Identity}, {"certificate", signing.Certificate},
			{"thumbprint", signing.Thumbprint}, {"timestamp_server", signing.TimestampServer}, {"entitlements", signing.Entitlements},
			{"provisioning_profile", signing.ProvisioningProfile}, {"key_alias", signing.KeyAlias},
		} {
			yamlSetOptionalString(node, entry.key, entry.value)
		}
		yamlSet(result, "signing", node)
	}
	if signing.Notarize && platformBlockAllowed(name, "notarization") {
		node := yamlMap()
		yamlSetOptionalString(node, "credential", signing.NotarizationCredential)
		yamlSet(result, "notarization", node)
	}
	return result
}

func encodeYAMLTarget(target Target) *yaml.Node {
	if !target.valueConfigured() {
		return nil
	}
	result := yamlMap()
	yamlSetOptionalStrings(result, "tags", target.Tags, false)
	yamlSetRun(result, "run", target.Run)
	if target.Dev.ArgsSet {
		dev := yamlMap()
		yamlSet(dev, "args", yamlStrings(target.Dev.Args))
		yamlSet(result, "dev", dev)
	}
	yamlSetOptionalString(result, "minimum_version", target.MinimumVersion)
	if target.BuildNumber != 0 {
		yamlSet(result, "build_number", yamlInt(target.BuildNumber))
	}
	yamlSetOptionalString(result, "toolchain", target.Toolchain)
	yamlSetOptionalStringMap(result, "environment", target.Environment)
	yamlSetOptionalStrings(result, "ldflags", target.LinkerFlags, false)
	yamlSetOptionalStrings(result, "compiler_flags", target.CompilerFlags, false)
	yamlSetOptionalStrings(result, "garble_args", target.GarbleArgs, false)
	if target.ObfuscatedSet {
		yamlSet(result, "obfuscated", yamlBool(target.Obfuscated))
	}
	return result
}

func (target Target) valueConfigured() bool {
	return target.Enabled || len(target.Tags) > 0 || target.MinimumVersion != "" || target.BuildNumber != 0 || target.Toolchain != "" || len(target.Environment) > 0 || len(target.LinkerFlags) > 0 || len(target.CompilerFlags) > 0 || len(target.GarbleArgs) > 0 || target.ObfuscatedSet || runConfigured(target.Run) || target.Dev.ArgsSet
}

func encodeYAMLPackage(format string, value PackageFormat) *yaml.Node {
	if !packageConfigured(value) {
		return nil
	}
	result := yamlMap()
	for _, entry := range []struct{ key, value string }{
		{"template", value.Template}, {"install_scope", value.InstallScope}, {"publisher", value.Publisher}, {"manifest", value.Manifest},
		{"background", value.Background}, {"volume_icon", value.VolumeIcon}, {"file_icon", value.FileIcon}, {"icon", value.Icon},
		{"desktop_entry", value.DesktopEntry}, {"maintainer", value.Maintainer}, {"section", value.Section},
		{"pre_install", value.PreInstall}, {"post_install", value.PostInstall}, {"pre_remove", value.PreRemove}, {"post_remove", value.PostRemove},
	} {
		if packageAttributeAllowed(format, entry.key) {
			yamlSetOptionalString(result, entry.key, entry.value)
		}
	}
	if packageAttributeAllowed(format, "files") {
		yamlSetOptionalStringMap(result, "files", value.Files)
	}
	if value.WindowWidth != 0 && packageAttributeAllowed(format, "window_width") {
		yamlSet(result, "window_width", yamlInt(value.WindowWidth))
	}
	if value.WindowHeight != 0 && packageAttributeAllowed(format, "window_height") {
		yamlSet(result, "window_height", yamlInt(value.WindowHeight))
	}
	if packageAttributeAllowed(format, "categories") {
		yamlSetOptionalStrings(result, "categories", value.Categories, false)
	}
	if packageAttributeAllowed(format, "dependencies") {
		yamlSetOptionalStrings(result, "dependencies", value.Dependencies, false)
	}
	return result
}

func yamlSetRun(parent *yaml.Node, name string, run Run) {
	if !runConfigured(run) {
		return
	}
	result := yamlMap()
	yamlSetOptionalStrings(result, "tags", run.Tags, false)
	yamlSetOptionalStrings(result, "args", run.Args, run.ArgsSet)
	yamlSetOptionalStringMap(result, "environment", run.Environment)
	yamlSet(parent, name, result)
}

func yamlMap() *yaml.Node { return &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"} }

func yamlString(value string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: value}
}

func yamlBool(value bool) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: strconv.FormatBool(value)}
}

func yamlInt(value int) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!int", Value: strconv.Itoa(value)}
}

func yamlStrings(values []string) *yaml.Node {
	result := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq", Style: yaml.FlowStyle}
	for _, value := range values {
		result.Content = append(result.Content, yamlString(value))
	}
	return result
}

func yamlStringMap(values map[string]string) *yaml.Node {
	result := yamlMap()
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		yamlSet(result, key, yamlString(values[key]))
	}
	return result
}

func yamlSet(mapping *yaml.Node, key string, value *yaml.Node) {
	mapping.Content = append(mapping.Content, yamlString(key), value)
}

func yamlSetString(mapping *yaml.Node, key, value string) { yamlSet(mapping, key, yamlString(value)) }

func yamlSetOptionalString(mapping *yaml.Node, key, value string) {
	if value != "" {
		yamlSetString(mapping, key, value)
	}
}

func yamlSetOptionalStrings(mapping *yaml.Node, key string, values []string, present bool) {
	if len(values) > 0 || present {
		yamlSet(mapping, key, yamlStrings(values))
	}
}

func yamlSetOptionalStringMap(mapping *yaml.Node, key string, values map[string]string) {
	if len(values) > 0 {
		yamlSet(mapping, key, yamlStringMap(values))
	}
}

func marshalYAML(root *yaml.Node) ([]byte, error) {
	var output bytes.Buffer
	encoder := yaml.NewEncoder(&output)
	encoder.SetIndent(2)
	if err := encoder.Encode(root); err != nil {
		return nil, fmt.Errorf("encode %s: %w", Filename, err)
	}
	if err := encoder.Close(); err != nil {
		return nil, fmt.Errorf("encode %s: %w", Filename, err)
	}
	return output.Bytes(), nil
}
