// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export * as EmbedOther from "./embedother.js";
export * as EmbedService from "./embedservice.js";
export * as GreetService from "./greetservice.js";
