// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Call} from "@wailsio/runtime";

import {Person} from "./models";

export function ArrayInt($in: number[]): Promise<void> {
    return Call.ByID(3862002418, $in);
}

export function BoolInBoolOut($in: boolean): Promise<boolean> {
    return Call.ByID(2424639793, $in);
}

export function Float32InFloat32Out($in: number): Promise<number> {
    return Call.ByID(3132595881, $in);
}

export function Float64InFloat64Out($in: number): Promise<number> {
    return Call.ByID(2182412247, $in);
}

/**
 * Greet someone
 */
export function Greet(name: string): Promise<string> {
    return Call.ByID(1411160069, name);
}

export function Int16InIntOut($in: number): Promise<number> {
    return Call.ByID(3306292566, $in);
}

export function Int16PointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByID(1754277916, $in);
}

export function Int32InIntOut($in: number): Promise<number> {
    return Call.ByID(1909469092, $in);
}

export function Int32PointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByID(4251088558, $in);
}

export function Int64InIntOut($in: number): Promise<number> {
    return Call.ByID(1343888303, $in);
}

export function Int64PointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByID(2205561041, $in);
}

export function Int8InIntOut($in: number): Promise<number> {
    return Call.ByID(572240879, $in);
}

export function Int8PointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByID(2189402897, $in);
}

export function IntInIntOut($in: number): Promise<number> {
    return Call.ByID(642881729, $in);
}

export function IntPointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByID(1066151743, $in);
}

export function IntPointerInputNamedOutputs($in: number | null): Promise<number | null> {
    return Call.ByID(2718999663, $in);
}

export function MapIntInt($in: { [_: string]: number }): Promise<void> {
    return Call.ByID(2386486356, $in);
}

export function MapIntPointerInt($in: { [_: string]: number }): Promise<void> {
    return Call.ByID(550413585, $in);
}

export function MapIntSliceInt($in: { [_: string]: number[] }): Promise<void> {
    return Call.ByID(2900172572, $in);
}

export function MapIntSliceIntInMapIntSliceIntOut($in: { [_: string]: number[] }): Promise<{ [_: string]: number[] }> {
    return Call.ByID(881980169, $in);
}

export function NoInputsStringOut(): Promise<string> {
    return Call.ByID(1075577233);
}

export function PointerBoolInBoolOut($in: boolean | null): Promise<boolean | null> {
    return Call.ByID(3589606958, $in);
}

export function PointerFloat32InFloat32Out($in: number | null): Promise<number | null> {
    return Call.ByID(224675106, $in);
}

export function PointerFloat64InFloat64Out($in: number | null): Promise<number | null> {
    return Call.ByID(2124953624, $in);
}

export function PointerMapIntInt($in: { [_: string]: number } | null): Promise<void> {
    return Call.ByID(3516977899, $in);
}

export function PointerStringInStringOut($in: string | null): Promise<string | null> {
    return Call.ByID(229603958, $in);
}

export function StringArrayInputNamedOutput($in: string[]): Promise<string[]> {
    return Call.ByID(3678582682, $in);
}

export function StringArrayInputNamedOutputs($in: string[]): Promise<string[]> {
    return Call.ByID(319259595, $in);
}

export function StringArrayInputStringArrayOut($in: string[]): Promise<string[]> {
    return Call.ByID(383995060, $in);
}

export function StringArrayInputStringOut($in: string[]): Promise<string> {
    return Call.ByID(1091960237, $in);
}

export function StructInputStructOutput($in: Person): Promise<Person> {
    return Call.ByID(3835643147, $in);
}

export function StructPointerInputErrorOutput($in: Person | null): Promise<void> {
    return Call.ByID(2447692557, $in);
}

export function StructPointerInputStructPointerOutput($in: Person | null): Promise<Person | null> {
    return Call.ByID(2943477349, $in);
}

export function UInt16InUIntOut($in: number): Promise<number> {
    return Call.ByID(3401034892, $in);
}

export function UInt16PointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByID(1236957573, $in);
}

export function UInt32InUIntOut($in: number): Promise<number> {
    return Call.ByID(1160383782, $in);
}

export function UInt32PointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByID(1739300671, $in);
}

export function UInt64InUIntOut($in: number): Promise<number> {
    return Call.ByID(793803239, $in);
}

export function UInt64PointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByID(1403757716, $in);
}

export function UInt8InUIntOut($in: number): Promise<number> {
    return Call.ByID(2988345717, $in);
}

export function UInt8PointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByID(518250834, $in);
}

export function UIntInUIntOut($in: number): Promise<number> {
    return Call.ByID(2836661285, $in);
}

export function UIntPointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByID(1367187362, $in);
}
