// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Call} from '@wailsio/runtime';
/**
 * @typedef {import('./models').Person} Person
 */

/**
 * @function ArrayInt
 * @param _in {number[]}
 * @returns {Promise<void>}
 **/
export async function ArrayInt(_in) {
	return Call.ByID(3862002418, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function BoolInBoolOut
 * @param _in {boolean}
 * @returns {Promise<boolean>}
 **/
export async function BoolInBoolOut(_in) {
	return Call.ByID(2424639793, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function Float32InFloat32Out
 * @param _in {number}
 * @returns {Promise<number>}
 **/
export async function Float32InFloat32Out(_in) {
	return Call.ByID(3132595881, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function Float64InFloat64Out
 * @param _in {number}
 * @returns {Promise<number>}
 **/
export async function Float64InFloat64Out(_in) {
	return Call.ByID(2182412247, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * Greet someone
 * @function Greet
 * @param name {string}
 * @returns {Promise<string>}
 **/
export async function Greet(name) {
	return Call.ByID(1411160069, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function Int16InIntOut
 * @param _in {number}
 * @returns {Promise<number>}
 **/
export async function Int16InIntOut(_in) {
	return Call.ByID(3306292566, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function Int16PointerInAndOutput
 * @param _in {number | null}
 * @returns {Promise<number | null>}
 **/
export async function Int16PointerInAndOutput(_in) {
	return Call.ByID(1754277916, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function Int32InIntOut
 * @param _in {number}
 * @returns {Promise<number>}
 **/
export async function Int32InIntOut(_in) {
	return Call.ByID(1909469092, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function Int32PointerInAndOutput
 * @param _in {number | null}
 * @returns {Promise<number | null>}
 **/
export async function Int32PointerInAndOutput(_in) {
	return Call.ByID(4251088558, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function Int64InIntOut
 * @param _in {number}
 * @returns {Promise<number>}
 **/
export async function Int64InIntOut(_in) {
	return Call.ByID(1343888303, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function Int64PointerInAndOutput
 * @param _in {number | null}
 * @returns {Promise<number | null>}
 **/
export async function Int64PointerInAndOutput(_in) {
	return Call.ByID(2205561041, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function Int8InIntOut
 * @param _in {number}
 * @returns {Promise<number>}
 **/
export async function Int8InIntOut(_in) {
	return Call.ByID(572240879, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function Int8PointerInAndOutput
 * @param _in {number | null}
 * @returns {Promise<number | null>}
 **/
export async function Int8PointerInAndOutput(_in) {
	return Call.ByID(2189402897, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function IntInIntOut
 * @param _in {number}
 * @returns {Promise<number>}
 **/
export async function IntInIntOut(_in) {
	return Call.ByID(642881729, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function IntPointerInAndOutput
 * @param _in {number | null}
 * @returns {Promise<number | null>}
 **/
export async function IntPointerInAndOutput(_in) {
	return Call.ByID(1066151743, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function IntPointerInputNamedOutputs
 * @param _in {number | null}
 * @returns {Promise<number | null, void>}
 **/
export async function IntPointerInputNamedOutputs(_in) {
	return Call.ByID(2718999663, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function MapIntInt
 * @param _in {map}
 * @returns {Promise<void>}
 **/
export async function MapIntInt(_in) {
	return Call.ByID(2386486356, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function MapIntPointerInt
 * @param _in {map}
 * @returns {Promise<void>}
 **/
export async function MapIntPointerInt(_in) {
	return Call.ByID(550413585, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function MapIntSliceInt
 * @param _in {map}
 * @returns {Promise<void>}
 **/
export async function MapIntSliceInt(_in) {
	return Call.ByID(2900172572, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function MapIntSliceIntInMapIntSliceIntOut
 * @param _in {map}
 * @returns {Promise<map>}
 **/
export async function MapIntSliceIntInMapIntSliceIntOut(_in) {
	return Call.ByID(881980169, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function NoInputsStringOut
 * @returns {Promise<string>}
 **/
export async function NoInputsStringOut() {
	return Call.ByID(1075577233, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function PointerBoolInBoolOut
 * @param _in {boolean | null}
 * @returns {Promise<boolean | null>}
 **/
export async function PointerBoolInBoolOut(_in) {
	return Call.ByID(3589606958, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function PointerFloat32InFloat32Out
 * @param _in {number | null}
 * @returns {Promise<number | null>}
 **/
export async function PointerFloat32InFloat32Out(_in) {
	return Call.ByID(224675106, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function PointerFloat64InFloat64Out
 * @param _in {number | null}
 * @returns {Promise<number | null>}
 **/
export async function PointerFloat64InFloat64Out(_in) {
	return Call.ByID(2124953624, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function PointerMapIntInt
 * @param _in {map | null}
 * @returns {Promise<void>}
 **/
export async function PointerMapIntInt(_in) {
	return Call.ByID(3516977899, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function PointerStringInStringOut
 * @param _in {string | null}
 * @returns {Promise<string | null>}
 **/
export async function PointerStringInStringOut(_in) {
	return Call.ByID(229603958, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function StringArrayInputNamedOutput
 * @param _in {string[]}
 * @returns {Promise<string[]>}
 **/
export async function StringArrayInputNamedOutput(_in) {
	return Call.ByID(3678582682, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function StringArrayInputNamedOutputs
 * @param _in {string[]}
 * @returns {Promise<string[], void>}
 **/
export async function StringArrayInputNamedOutputs(_in) {
	return Call.ByID(319259595, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function StringArrayInputStringArrayOut
 * @param _in {string[]}
 * @returns {Promise<string[]>}
 **/
export async function StringArrayInputStringArrayOut(_in) {
	return Call.ByID(383995060, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function StringArrayInputStringOut
 * @param _in {string[]}
 * @returns {Promise<string>}
 **/
export async function StringArrayInputStringOut(_in) {
	return Call.ByID(1091960237, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function StructInputStructOutput
 * @param _in {Person}
 * @returns {Promise<Person>}
 **/
export async function StructInputStructOutput(_in) {
	return Call.ByID(3835643147, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function StructPointerInputErrorOutput
 * @param _in {Person | null}
 * @returns {Promise<void>}
 **/
export async function StructPointerInputErrorOutput(_in) {
	return Call.ByID(2447692557, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function StructPointerInputStructPointerOutput
 * @param _in {Person | null}
 * @returns {Promise<Person>}
 **/
export async function StructPointerInputStructPointerOutput(_in) {
	return Call.ByID(2943477349, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function UInt16InUIntOut
 * @param _in {number}
 * @returns {Promise<number>}
 **/
export async function UInt16InUIntOut(_in) {
	return Call.ByID(3401034892, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function UInt16PointerInAndOutput
 * @param _in {number | null}
 * @returns {Promise<number | null>}
 **/
export async function UInt16PointerInAndOutput(_in) {
	return Call.ByID(1236957573, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function UInt32InUIntOut
 * @param _in {number}
 * @returns {Promise<number>}
 **/
export async function UInt32InUIntOut(_in) {
	return Call.ByID(1160383782, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function UInt32PointerInAndOutput
 * @param _in {number | null}
 * @returns {Promise<number | null>}
 **/
export async function UInt32PointerInAndOutput(_in) {
	return Call.ByID(1739300671, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function UInt64InUIntOut
 * @param _in {number}
 * @returns {Promise<number>}
 **/
export async function UInt64InUIntOut(_in) {
	return Call.ByID(793803239, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function UInt64PointerInAndOutput
 * @param _in {number | null}
 * @returns {Promise<number | null>}
 **/
export async function UInt64PointerInAndOutput(_in) {
	return Call.ByID(1403757716, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function UInt8InUIntOut
 * @param _in {number}
 * @returns {Promise<number>}
 **/
export async function UInt8InUIntOut(_in) {
	return Call.ByID(2988345717, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function UInt8PointerInAndOutput
 * @param _in {number | null}
 * @returns {Promise<number | null>}
 **/
export async function UInt8PointerInAndOutput(_in) {
	return Call.ByID(518250834, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function UIntInUIntOut
 * @param _in {number}
 * @returns {Promise<number>}
 **/
export async function UIntInUIntOut(_in) {
	return Call.ByID(2836661285, ...Array.prototype.slice.call(arguments, 0));
}

/**
 * @function UIntPointerInAndOutput
 * @param _in {number | null}
 * @returns {Promise<number | null>}
 **/
export async function UIntPointerInAndOutput(_in) {
	return Call.ByID(1367187362, ...Array.prototype.slice.call(arguments, 0));
}
