// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Call} from "@wailsio/runtime";

import {Person} from "./models";

export function ArrayInt($in: number[]): Promise<void> {
    return Call.ByName("main.GreetService.ArrayInt", $in);
}

export function BoolInBoolOut($in: boolean): Promise<boolean> {
    return Call.ByName("main.GreetService.BoolInBoolOut", $in);
}

export function Float32InFloat32Out($in: number): Promise<number> {
    return Call.ByName("main.GreetService.Float32InFloat32Out", $in);
}

export function Float64InFloat64Out($in: number): Promise<number> {
    return Call.ByName("main.GreetService.Float64InFloat64Out", $in);
}

/**
 * Greet someone
 */
export function Greet(name: string): Promise<string> {
    return Call.ByName("main.GreetService.Greet", name);
}

export function Int16InIntOut($in: number): Promise<number> {
    return Call.ByName("main.GreetService.Int16InIntOut", $in);
}

export function Int16PointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByName("main.GreetService.Int16PointerInAndOutput", $in);
}

export function Int32InIntOut($in: number): Promise<number> {
    return Call.ByName("main.GreetService.Int32InIntOut", $in);
}

export function Int32PointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByName("main.GreetService.Int32PointerInAndOutput", $in);
}

export function Int64InIntOut($in: number): Promise<number> {
    return Call.ByName("main.GreetService.Int64InIntOut", $in);
}

export function Int64PointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByName("main.GreetService.Int64PointerInAndOutput", $in);
}

export function Int8InIntOut($in: number): Promise<number> {
    return Call.ByName("main.GreetService.Int8InIntOut", $in);
}

export function Int8PointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByName("main.GreetService.Int8PointerInAndOutput", $in);
}

export function IntInIntOut($in: number): Promise<number> {
    return Call.ByName("main.GreetService.IntInIntOut", $in);
}

export function IntPointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByName("main.GreetService.IntPointerInAndOutput", $in);
}

export function IntPointerInputNamedOutputs($in: number | null): Promise<number | null> {
    return Call.ByName("main.GreetService.IntPointerInputNamedOutputs", $in);
}

export function MapIntInt($in: { [_: string]: number }): Promise<void> {
    return Call.ByName("main.GreetService.MapIntInt", $in);
}

export function MapIntPointerInt($in: { [_: string]: number }): Promise<void> {
    return Call.ByName("main.GreetService.MapIntPointerInt", $in);
}

export function MapIntSliceInt($in: { [_: string]: number[] }): Promise<void> {
    return Call.ByName("main.GreetService.MapIntSliceInt", $in);
}

export function MapIntSliceIntInMapIntSliceIntOut($in: { [_: string]: number[] }): Promise<{ [_: string]: number[] }> {
    return Call.ByName("main.GreetService.MapIntSliceIntInMapIntSliceIntOut", $in);
}

export function NoInputsStringOut(): Promise<string> {
    return Call.ByName("main.GreetService.NoInputsStringOut");
}

export function PointerBoolInBoolOut($in: boolean | null): Promise<boolean | null> {
    return Call.ByName("main.GreetService.PointerBoolInBoolOut", $in);
}

export function PointerFloat32InFloat32Out($in: number | null): Promise<number | null> {
    return Call.ByName("main.GreetService.PointerFloat32InFloat32Out", $in);
}

export function PointerFloat64InFloat64Out($in: number | null): Promise<number | null> {
    return Call.ByName("main.GreetService.PointerFloat64InFloat64Out", $in);
}

export function PointerMapIntInt($in: { [_: string]: number } | null): Promise<void> {
    return Call.ByName("main.GreetService.PointerMapIntInt", $in);
}

export function PointerStringInStringOut($in: string | null): Promise<string | null> {
    return Call.ByName("main.GreetService.PointerStringInStringOut", $in);
}

export function StringArrayInputNamedOutput($in: string[]): Promise<string[]> {
    return Call.ByName("main.GreetService.StringArrayInputNamedOutput", $in);
}

export function StringArrayInputNamedOutputs($in: string[]): Promise<string[]> {
    return Call.ByName("main.GreetService.StringArrayInputNamedOutputs", $in);
}

export function StringArrayInputStringArrayOut($in: string[]): Promise<string[]> {
    return Call.ByName("main.GreetService.StringArrayInputStringArrayOut", $in);
}

export function StringArrayInputStringOut($in: string[]): Promise<string> {
    return Call.ByName("main.GreetService.StringArrayInputStringOut", $in);
}

export function StructInputStructOutput($in: Person): Promise<Person> {
    return Call.ByName("main.GreetService.StructInputStructOutput", $in);
}

export function StructPointerInputErrorOutput($in: Person | null): Promise<void> {
    return Call.ByName("main.GreetService.StructPointerInputErrorOutput", $in);
}

export function StructPointerInputStructPointerOutput($in: Person | null): Promise<Person | null> {
    return Call.ByName("main.GreetService.StructPointerInputStructPointerOutput", $in);
}

export function UInt16InUIntOut($in: number): Promise<number> {
    return Call.ByName("main.GreetService.UInt16InUIntOut", $in);
}

export function UInt16PointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByName("main.GreetService.UInt16PointerInAndOutput", $in);
}

export function UInt32InUIntOut($in: number): Promise<number> {
    return Call.ByName("main.GreetService.UInt32InUIntOut", $in);
}

export function UInt32PointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByName("main.GreetService.UInt32PointerInAndOutput", $in);
}

export function UInt64InUIntOut($in: number): Promise<number> {
    return Call.ByName("main.GreetService.UInt64InUIntOut", $in);
}

export function UInt64PointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByName("main.GreetService.UInt64PointerInAndOutput", $in);
}

export function UInt8InUIntOut($in: number): Promise<number> {
    return Call.ByName("main.GreetService.UInt8InUIntOut", $in);
}

export function UInt8PointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByName("main.GreetService.UInt8PointerInAndOutput", $in);
}

export function UIntInUIntOut($in: number): Promise<number> {
    return Call.ByName("main.GreetService.UIntInUIntOut", $in);
}

export function UIntPointerInAndOutput($in: number | null): Promise<number | null> {
    return Call.ByName("main.GreetService.UIntPointerInAndOutput", $in);
}
