// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface $anon1 {
    "Age": number;
    "Address": $anon2;
}

export interface $anon2 {
    "Street": string;
}

export interface Person {
    "Name": string;
    "Parent": Person | null;
    "Details": $anon1;
}
