package migrate

import (
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// copyTree copies src into dst, creating directories as needed. The include
// callback receives the path relative to src and can veto files and whole
// directories.
func copyTree(src, dst string, include func(rel string, isDir bool) bool) error {
	return filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return os.MkdirAll(dst, 0o755)
		}
		if include != nil && !include(rel, info.IsDir()) {
			if info.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		target := filepath.Join(dst, rel)
		if info.IsDir() {
			return os.MkdirAll(target, info.Mode().Perm())
		}
		return copyFile(path, target, info.Mode().Perm())
	})
}

func copyFile(src, dst string, perm os.FileMode) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	out, err := os.OpenFile(dst, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, perm)
	if err != nil {
		return err
	}
	defer out.Close()
	_, err = io.Copy(out, in)
	return err
}

// CopyProjectFiles copies the remaining project files (everything except the
// frontend, the v2 build directory, generated/replaced files and VCS
// internals) into the output directory. Go files get their v2 runtime import
// rewritten to the v3 compatibility bridge.
func CopyProjectFiles(proj *V2Project, outDir string) error {
	mainRel, err := filepath.Rel(proj.Dir, proj.Main.Path)
	if err != nil {
		return err
	}
	frontendRel, err := filepath.Rel(proj.Dir, proj.FrontendDir)
	if err != nil {
		return err
	}
	buildRel := proj.Config.BuildDir

	skip := map[string]bool{
		mainRel:      true, // regenerated by GenerateMain
		"wails.json": true, // superseded by build/config.yml + Taskfile
		"go.mod":     true, // transformed separately
		"go.sum":     true, // regenerated by go mod tidy
	}

	return filepath.Walk(proj.Dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(proj.Dir, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}
		if info.IsDir() {
			name := info.Name()
			if name == ".git" || name == "node_modules" || rel == frontendRel || rel == buildRel {
				return filepath.SkipDir
			}
			return nil
		}
		if skip[rel] || info.Name() == ".DS_Store" {
			return nil
		}
		target := filepath.Join(outDir, rel)
		if strings.HasSuffix(path, ".go") {
			data, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			data = RewriteGoImports(proj, rel, data)
			if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
				return err
			}
			return os.WriteFile(target, data, info.Mode().Perm())
		}
		return copyFile(path, target, info.Mode().Perm())
	})
}

// RewriteGoImports rewrites the v2 runtime import to the v3 compatibility
// bridge and records remaining v2 imports as manual steps.
func RewriteGoImports(proj *V2Project, rel string, src []byte) []byte {
	content := string(src)
	if strings.Contains(content, strconv.Quote(V2RuntimeImport)) {
		content = strings.ReplaceAll(content, strconv.Quote(V2RuntimeImport), strconv.Quote(V2CompatRuntimeImport))
		proj.Report.Mapped(rel+": "+V2RuntimeImport, V2CompatRuntimeImport)
	}

	// Report any other v2 imports that remain.
	for _, line := range strings.Split(content, "\n") {
		trimmed := strings.TrimSpace(line)
		idx := strings.Index(trimmed, `"github.com/wailsapp/wails/v2`)
		if idx < 0 {
			continue
		}
		importPath := strings.Trim(trimmed[idx:], `"`)
		proj.Report.Manual(rel+": import "+importPath,
			"This Wails v2 package has no automatic v3 replacement; port the code using it to the v3 API (github.com/wailsapp/wails/v3/pkg/application).")
	}

	return []byte(content)
}
