package migrate

import (
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

//go:embed assets/wailsjs-runtime.js
var wailsjsRuntimeJS []byte

//go:embed assets/wailsjs-runtime.d.ts
var wailsjsRuntimeDTS []byte

// MigrateFrontend copies the v2 frontend into the output project, replaces
// the generated wailsjs directory with a v3-backed compatibility layer and
// adds the @wailsio/runtime dependency to package.json.
func MigrateFrontend(proj *V2Project, outDir string) error {
	srcFrontend := proj.FrontendDir
	dstFrontend := filepath.Join(outDir, "frontend")

	if _, err := os.Stat(srcFrontend); os.IsNotExist(err) {
		proj.Report.Manual("frontend", "No frontend directory was found; create one or point the v3 Taskfile at your assets.")
		return nil
	}

	err := copyTree(srcFrontend, dstFrontend, func(rel string, isDir bool) bool {
		switch {
		case rel == "node_modules" || strings.HasPrefix(rel, "node_modules"+string(filepath.Separator)):
			return false
		case rel == "wailsjs" || strings.HasPrefix(rel, "wailsjs"+string(filepath.Separator)):
			return false
		}
		return true
	})
	if err != nil {
		return err
	}

	// Ensure frontend/dist exists so `go build` can embed it before the first
	// frontend build.
	distDir := filepath.Join(dstFrontend, "dist")
	if err := os.MkdirAll(distDir, 0o755); err != nil {
		return err
	}
	gitkeep := filepath.Join(distDir, ".gitkeep")
	if _, err := os.Stat(gitkeep); os.IsNotExist(err) {
		if err := os.WriteFile(gitkeep, nil, 0o644); err != nil {
			return err
		}
	}

	if err := writeWailsJSShims(proj, dstFrontend); err != nil {
		return err
	}

	if err := addRuntimeDependency(proj, dstFrontend); err != nil {
		return err
	}

	return nil
}

// writeWailsJSShims regenerates frontend/wailsjs as a compatibility layer:
// the runtime module delegates to @wailsio/runtime and the go bindings
// delegate to Call.ByName.
func writeWailsJSShims(proj *V2Project, frontendDir string) error {
	runtimeDir := filepath.Join(frontendDir, "wailsjs", "runtime")
	if err := os.MkdirAll(runtimeDir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(runtimeDir, "runtime.js"), wailsjsRuntimeJS, 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(runtimeDir, "runtime.d.ts"), wailsjsRuntimeDTS, 0o644); err != nil {
		return err
	}

	for _, bt := range proj.BoundTypes {
		if bt.Name == "" || bt.PkgName == "" || len(bt.Methods) == 0 {
			continue
		}
		dir := filepath.Join(frontendDir, "wailsjs", "go", bt.PkgName)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
		js, dts := generateBindingShim(bt)
		if err := os.WriteFile(filepath.Join(dir, bt.Name+".js"), []byte(js), 0o644); err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(dir, bt.Name+".d.ts"), []byte(dts), 0o644); err != nil {
			return err
		}
	}

	if len(proj.BoundTypes) > 0 {
		proj.Report.Note("The frontend `wailsjs/` directory was regenerated as a compatibility layer over `@wailsio/runtime`. If your frontend imports `wailsjs/go/models`, port those types to the models generated by `wails3 generate bindings` (in `frontend/bindings`).")
	}

	return nil
}

// generateBindingShim renders the wailsjs/go/<pkg>/<Type>.js compatibility
// module and its .d.ts for one bound struct.
func generateBindingShim(bt *BoundType) (js string, dts string) {
	var sbJS, sbDTS strings.Builder

	header := "// Wails v2 bindings compatibility layer, generated by `wails3 migrate`.\n" +
		"// Calls are routed by name through the Wails v3 runtime.\n" +
		"// Prefer the generated v3 bindings in frontend/bindings for new code.\n\n"
	sbJS.WriteString(header)
	sbJS.WriteString("import {Call} from '@wailsio/runtime';\n")
	sbDTS.WriteString(header)

	for _, method := range bt.Methods {
		var callArgs, jsParams, tsParams []string
		for i, p := range method.Params {
			name := p.Name
			if name == "" || name == "_" {
				name = fmt.Sprintf("arg%d", i+1)
			}
			jsParams = append(jsParams, name)
			tsParams = append(tsParams, fmt.Sprintf("%s: %s", name, p.TSType))
			callArgs = append(callArgs, name)
		}

		fqn := bt.PkgPath + "." + bt.Name + "." + method.Name
		sbJS.WriteString(fmt.Sprintf("\nexport function %s(%s) {\n", method.Name, strings.Join(jsParams, ", ")))
		args := ""
		if len(callArgs) > 0 {
			args = ", " + strings.Join(callArgs, ", ")
		}
		sbJS.WriteString(fmt.Sprintf("    return Call.ByName(%q%s);\n}\n", fqn, args))

		retType := "void"
		for _, r := range method.Results {
			if r.GoType != "error" {
				retType = r.TSType
				break
			}
		}
		sbDTS.WriteString(fmt.Sprintf("\nexport function %s(%s): Promise<%s>;\n", method.Name, strings.Join(tsParams, ", "), retType))
	}

	return sbJS.String(), sbDTS.String()
}

var dependenciesRe = regexp.MustCompile(`("dependencies"\s*:\s*\{)`)

// addRuntimeDependency inserts "@wailsio/runtime" into the frontend
// package.json dependencies, preserving the file's formatting.
func addRuntimeDependency(proj *V2Project, frontendDir string) error {
	path := filepath.Join(frontendDir, "package.json")
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			proj.Report.Manual("frontend/package.json",
				"No package.json found. The regenerated wailsjs compatibility layer imports `@wailsio/runtime`, which requires a bundler; plain-JS frontends must load the runtime differently (see the v3 docs).")
			return nil
		}
		return err
	}
	content := string(data)
	if strings.Contains(content, `"@wailsio/runtime"`) {
		return nil
	}

	if dependenciesRe.MatchString(content) {
		content = dependenciesRe.ReplaceAllString(content, "$1\n    \"@wailsio/runtime\": \"latest\",")
	} else if idx := strings.Index(content, "{"); idx >= 0 {
		content = content[:idx+1] + "\n  \"dependencies\": {\n    \"@wailsio/runtime\": \"latest\"\n  }," + content[idx+1:]
	} else {
		proj.Report.Manual("frontend/package.json", "Could not add the `@wailsio/runtime` dependency automatically; add it and run your package manager's install.")
		return nil
	}

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return err
	}
	proj.Report.Note("Added `@wailsio/runtime` to frontend/package.json; run your package manager's install (or let the Taskfile do it on first build).")
	return nil
}
