// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nobindingshere$0 from "../no_bindings_here/models.js";

/**
 * SomeClass renders as a TS class.
 */
export interface SomeClass {
    "Field": string;
    "Meadow": nobindingshere$0.HowDifferent<number>;
}
