// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Create as $Create} from "@wailsio/runtime";

export class Person<T> {
    "Name": T | null;

    "AliasedField": number;

    /** Creates a new Person instance. */
    constructor($$source: Partial<Person<T>> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = null;
        }
        if (!("AliasedField" in $$source)) {
            this["AliasedField"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Person instance from a string or object.
     * Generic types also need creation functions for each type parameter.
     */
    static createFrom<T>($$createT: (any) => T, $$source: any = {}): Person<T> {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Name" in $$parsedSource) {
            $$parsedSource["Name"] = $$createT($$parsedSource["Name"]);
        }
        return new Person<T>($$parsedSource as Partial<Person<T>>);
    }
}
