// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as Service from "./service.js";
export {
    Service
};

export type {
    AliasJsonMarshaler,
    AliasMarshaler,
    AliasNonMarshaler,
    AliasTextMarshaler,
    Data,
    ImplicitJsonButText,
    ImplicitJsonMarshaler,
    ImplicitMarshaler,
    ImplicitNonJson,
    ImplicitNonMarshaler,
    ImplicitNonText,
    ImplicitTextButJson,
    ImplicitTextMarshaler,
    NonMarshaler,
    PointerJsonMarshaler,
    PointerMarshaler,
    PointerTextMarshaler,
    UnderlyingJsonMarshaler,
    UnderlyingMarshaler,
    UnderlyingTextMarshaler,
    ValueJsonMarshaler,
    ValueMarshaler,
    ValueTextMarshaler
} from "./models.js";
