// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export * from "./github.com/wailsapp/wails/v3/internal/parser/testcases/function_from_nested_imported_package/index.js";
