// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface StructA {
    "B": structB | null;
}

export interface StructC {
    "D": structD;
}

export interface StructE {
}

export interface structB {
    "A": StructA | null;
}

export interface structD {
    "E": StructE;
}
