// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Call as $Call, Create as $Create} from "/wails/runtime.js";

export function TestMethod2(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1859696033) as any;
    return $resultPromise;
}
