blank_issues_enabled: true
contact_links:
  - name: Discord Chat
    url: https://discord.gg/BrRSWTaxVK
    about: Ask questions and discuss with other Wails users in real time.

  - name: GitHub Community Discussions
    url: https://github.com/wailsapp/wails/discussions
    about: If your question is not a feature or a bug, please go to the discussion panel and retrieve if your question already exists before submitting.
