blank_issues_enabled: true
contact_links:
  - name: GitHub Community Discussions
    url: https://github.com/wailsapp/wails/discussions
    about: If your question is not a feature or a bug, please go to the discussion panel and retrieve if your question already exists before submitting.
