// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Person} from './models';
import {Title} from './models';

// Greet does XYZ
export async function Greet(name: string, title: Title) : Promise<string> {
	return wails.CallByName("main.GreetService.Greet", name, title);
}

// NewPerson creates a new person
export async function NewPerson(name: string) : Promise<Person> {
	return wails.CallByName("main.GreetService.NewPerson", name);
}

