// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Call} from "@wailsio/runtime";

import {Person, Title} from "./models.js";

/**
 * Greet does XYZ
 * @param {string} name
 * @param {Title} title
 * @returns {Promise<string>}
 */
export function Greet(name, title) {
    return Call.ByName("main.GreetService.Greet", name, title);
}

/**
 * NewPerson creates a new person
 * @param {string} name
 * @returns {Promise<Person | null>}
 */
export function NewPerson(name) {
    return Call.ByName("main.GreetService.NewPerson", name);
}
