// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Call} from "@wailsio/runtime";

import {Person} from "./models";

export function Greet(person: Person): Promise<string> {
    return Call.ByName("github.com/wailsapp/wails/v3/internal/parser/testdata/app_outside_main/app.GreetService.Greet", person);
}
