// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseAfterCurrentByName calls App.Window.Current() first, then closes the window by name.
 * This is the variant intended to reproduce the bug.
 * @param {string} name
 * @returns {$CancellablePromise<boolean>}
 */
export function CloseAfterCurrentByName(name) {
    return $Call.ByID(2322035781, name);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<boolean>}
 */
export function CloseByName(name) {
    return $Call.ByID(2115852398, name);
}

/**
 * CloseUsingCurrent closes whichever window Wails considers "current".
 * @returns {$CancellablePromise<$models.WindowSummary>}
 */
export function CloseUsingCurrent() {
    return $Call.ByID(3808447745).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(1411160069, name);
}

/**
 * @returns {$CancellablePromise<$models.WindowSummary[]>}
 */
export function ListWindows() {
    return $Call.ByID(141987601).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * OpenChildWindow creates a new window that loads the same frontend entrypoint,
 * but with query parameters enabling the "child window" UI.
 * @returns {$CancellablePromise<string>}
 */
export function OpenChildWindow() {
    return $Call.ByID(4214282726);
}

/**
 * ReportCurrent returns which window made this call (Caller) and what
 * App.Window.Current() returns at that moment (Current).
 * @returns {$CancellablePromise<$models.CurrentWindowReport>}
 */
export function ReportCurrent() {
    return $Call.ByID(3281355303).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.WindowSummary.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.CurrentWindowReport.createFrom;
