package events

type ApplicationEventType uint
type WindowEventType uint

var Common = newCommonEvents()

type commonEvents struct {
	ApplicationStarted   ApplicationEventType
	WindowMaximise       WindowEventType
	WindowUnMaximise     WindowEventType
	WindowFullscreen     WindowEventType
	WindowUnFullscreen   WindowEventType
	WindowRestore        WindowEventType
	WindowMinimise       WindowEventType
	WindowUnMinimise     WindowEventType
	WindowClosing        WindowEventType
	WindowZoom           WindowEventType
	WindowZoomIn         WindowEventType
	WindowZoomOut        WindowEventType
	WindowZoomReset      WindowEventType
	WindowFocus          WindowEventType
	WindowLostFocus      WindowEventType
	WindowShow           WindowEventType
	WindowHide           WindowEventType
	WindowDPIChanged     WindowEventType
	WindowFilesDropped   WindowEventType
	ThemeChanged         ApplicationEventType
	ApplicationTerminate ApplicationEventType
}

func newCommonEvents() commonEvents {
	return commonEvents{
		ApplicationStarted:   1175,
		WindowMaximise:       1176,
		WindowUnMaximise:     1177,
		WindowFullscreen:     1178,
		WindowUnFullscreen:   1179,
		WindowRestore:        1180,
		WindowMinimise:       1181,
		WindowUnMinimise:     1182,
		WindowClosing:        1183,
		WindowZoom:           1184,
		WindowZoomIn:         1185,
		WindowZoomOut:        1186,
		WindowZoomReset:      1187,
		WindowFocus:          1188,
		WindowLostFocus:      1189,
		WindowShow:           1190,
		WindowHide:           1191,
		WindowDPIChanged:     1192,
		WindowFilesDropped:   1193,
		ThemeChanged:         1194,
		ApplicationTerminate: 1195,
	}
}

var Linux = newLinuxEvents()

type linuxEvents struct {
	SystemThemeChanged ApplicationEventType
}

func newLinuxEvents() linuxEvents {
	return linuxEvents{
		SystemThemeChanged: 1024,
	}
}

var Mac = newMacEvents()

type macEvents struct {
	ApplicationDidBecomeActive                              ApplicationEventType
	ApplicationDidChangeBackingProperties                   ApplicationEventType
	ApplicationDidChangeEffectiveAppearance                 ApplicationEventType
	ApplicationDidChangeIcon                                ApplicationEventType
	ApplicationDidChangeOcclusionState                      ApplicationEventType
	ApplicationDidChangeScreenParameters                    ApplicationEventType
	ApplicationDidChangeStatusBarFrame                      ApplicationEventType
	ApplicationDidChangeStatusBarOrientation                ApplicationEventType
	ApplicationDidFinishLaunching                           ApplicationEventType
	ApplicationDidHide                                      ApplicationEventType
	ApplicationDidResignActiveNotification                  ApplicationEventType
	ApplicationDidUnhide                                    ApplicationEventType
	ApplicationDidUpdate                                    ApplicationEventType
	ApplicationWillBecomeActive                             ApplicationEventType
	ApplicationWillFinishLaunching                          ApplicationEventType
	ApplicationWillHide                                     ApplicationEventType
	ApplicationWillResignActive                             ApplicationEventType
	ApplicationWillTerminate                                ApplicationEventType
	ApplicationWillUnhide                                   ApplicationEventType
	ApplicationWillUpdate                                   ApplicationEventType
	ApplicationTerminate                                    ApplicationEventType
	ApplicationDidChangeTheme                               ApplicationEventType
	ApplicationShouldHandleReopen                           ApplicationEventType
	WindowDidBecomeKey                                      WindowEventType
	WindowDidBecomeMain                                     WindowEventType
	WindowDidBeginSheet                                     WindowEventType
	WindowDidChangeAlpha                                    WindowEventType
	WindowDidChangeBackingLocation                          WindowEventType
	WindowDidChangeBackingProperties                        WindowEventType
	WindowDidChangeCollectionBehavior                       WindowEventType
	WindowDidChangeEffectiveAppearance                      WindowEventType
	WindowDidChangeOcclusionState                           WindowEventType
	WindowDidChangeOrderingMode                             WindowEventType
	WindowDidChangeScreen                                   WindowEventType
	WindowDidChangeScreenParameters                         WindowEventType
	WindowDidChangeScreenProfile                            WindowEventType
	WindowDidChangeScreenSpace                              WindowEventType
	WindowDidChangeScreenSpaceProperties                    WindowEventType
	WindowDidChangeSharingType                              WindowEventType
	WindowDidChangeSpace                                    WindowEventType
	WindowDidChangeSpaceOrderingMode                        WindowEventType
	WindowDidChangeTitle                                    WindowEventType
	WindowDidChangeToolbar                                  WindowEventType
	WindowDidChangeVisibility                               WindowEventType
	WindowDidDeminiaturize                                  WindowEventType
	WindowDidEndSheet                                       WindowEventType
	WindowDidEnterFullScreen                                WindowEventType
	WindowDidEnterVersionBrowser                            WindowEventType
	WindowDidExitFullScreen                                 WindowEventType
	WindowDidExitVersionBrowser                             WindowEventType
	WindowDidExpose                                         WindowEventType
	WindowDidFocus                                          WindowEventType
	WindowDidMiniaturize                                    WindowEventType
	WindowDidMove                                           WindowEventType
	WindowDidOrderOffScreen                                 WindowEventType
	WindowDidOrderOnScreen                                  WindowEventType
	WindowDidResignKey                                      WindowEventType
	WindowDidResignMain                                     WindowEventType
	WindowDidResize                                         WindowEventType
	WindowDidUpdate                                         WindowEventType
	WindowDidUpdateAlpha                                    WindowEventType
	WindowDidUpdateCollectionBehavior                       WindowEventType
	WindowDidUpdateCollectionProperties                     WindowEventType
	WindowDidUpdateShadow                                   WindowEventType
	WindowDidUpdateTitle                                    WindowEventType
	WindowDidUpdateToolbar                                  WindowEventType
	WindowDidUpdateVisibility                               WindowEventType
	WindowShouldClose                                       WindowEventType
	WindowWillBecomeKey                                     WindowEventType
	WindowWillBecomeMain                                    WindowEventType
	WindowWillBeginSheet                                    WindowEventType
	WindowWillChangeOrderingMode                            WindowEventType
	WindowWillClose                                         WindowEventType
	WindowWillDeminiaturize                                 WindowEventType
	WindowWillEnterFullScreen                               WindowEventType
	WindowWillEnterVersionBrowser                           WindowEventType
	WindowWillExitFullScreen                                WindowEventType
	WindowWillExitVersionBrowser                            WindowEventType
	WindowWillFocus                                         WindowEventType
	WindowWillMiniaturize                                   WindowEventType
	WindowWillMove                                          WindowEventType
	WindowWillOrderOffScreen                                WindowEventType
	WindowWillOrderOnScreen                                 WindowEventType
	WindowWillResignMain                                    WindowEventType
	WindowWillResize                                        WindowEventType
	WindowWillUnfocus                                       WindowEventType
	WindowWillUpdate                                        WindowEventType
	WindowWillUpdateAlpha                                   WindowEventType
	WindowWillUpdateCollectionBehavior                      WindowEventType
	WindowWillUpdateCollectionProperties                    WindowEventType
	WindowWillUpdateShadow                                  WindowEventType
	WindowWillUpdateTitle                                   WindowEventType
	WindowWillUpdateToolbar                                 WindowEventType
	WindowWillUpdateVisibility                              WindowEventType
	WindowWillUseStandardFrame                              WindowEventType
	MenuWillOpen                                            ApplicationEventType
	MenuDidOpen                                             ApplicationEventType
	MenuDidClose                                            ApplicationEventType
	MenuWillSendAction                                      ApplicationEventType
	MenuDidSendAction                                       ApplicationEventType
	MenuWillHighlightItem                                   ApplicationEventType
	MenuDidHighlightItem                                    ApplicationEventType
	MenuWillDisplayItem                                     ApplicationEventType
	MenuDidDisplayItem                                      ApplicationEventType
	MenuWillAddItem                                         ApplicationEventType
	MenuDidAddItem                                          ApplicationEventType
	MenuWillRemoveItem                                      ApplicationEventType
	MenuDidRemoveItem                                       ApplicationEventType
	MenuWillBeginTracking                                   ApplicationEventType
	MenuDidBeginTracking                                    ApplicationEventType
	MenuWillEndTracking                                     ApplicationEventType
	MenuDidEndTracking                                      ApplicationEventType
	MenuWillUpdate                                          ApplicationEventType
	MenuDidUpdate                                           ApplicationEventType
	MenuWillPopUp                                           ApplicationEventType
	MenuDidPopUp                                            ApplicationEventType
	MenuWillSendActionToItem                                ApplicationEventType
	MenuDidSendActionToItem                                 ApplicationEventType
	WebViewDidStartProvisionalNavigation                    WindowEventType
	WebViewDidReceiveServerRedirectForProvisionalNavigation WindowEventType
	WebViewDidFinishNavigation                              WindowEventType
	WebViewDidCommitNavigation                              WindowEventType
	WindowFileDraggingEntered                               WindowEventType
	WindowFileDraggingPerformed                             WindowEventType
	WindowFileDraggingExited                                WindowEventType
}

func newMacEvents() macEvents {
	return macEvents{
		ApplicationDidBecomeActive:               1025,
		ApplicationDidChangeBackingProperties:    1026,
		ApplicationDidChangeEffectiveAppearance:  1027,
		ApplicationDidChangeIcon:                 1028,
		ApplicationDidChangeOcclusionState:       1029,
		ApplicationDidChangeScreenParameters:     1030,
		ApplicationDidChangeStatusBarFrame:       1031,
		ApplicationDidChangeStatusBarOrientation: 1032,
		ApplicationDidFinishLaunching:            1033,
		ApplicationDidHide:                       1034,
		ApplicationDidResignActiveNotification:   1035,
		ApplicationDidUnhide:                     1036,
		ApplicationDidUpdate:                     1037,
		ApplicationWillBecomeActive:              1038,
		ApplicationWillFinishLaunching:           1039,
		ApplicationWillHide:                      1040,
		ApplicationWillResignActive:              1041,
		ApplicationWillTerminate:                 1042,
		ApplicationWillUnhide:                    1043,
		ApplicationWillUpdate:                    1044,
		ApplicationTerminate:                     1045,
		ApplicationDidChangeTheme:                1046,
		ApplicationShouldHandleReopen:            1047,
		WindowDidBecomeKey:                       1048,
		WindowDidBecomeMain:                      1049,
		WindowDidBeginSheet:                      1050,
		WindowDidChangeAlpha:                     1051,
		WindowDidChangeBackingLocation:           1052,
		WindowDidChangeBackingProperties:         1053,
		WindowDidChangeCollectionBehavior:        1054,
		WindowDidChangeEffectiveAppearance:       1055,
		WindowDidChangeOcclusionState:            1056,
		WindowDidChangeOrderingMode:              1057,
		WindowDidChangeScreen:                    1058,
		WindowDidChangeScreenParameters:          1059,
		WindowDidChangeScreenProfile:             1060,
		WindowDidChangeScreenSpace:               1061,
		WindowDidChangeScreenSpaceProperties:     1062,
		WindowDidChangeSharingType:               1063,
		WindowDidChangeSpace:                     1064,
		WindowDidChangeSpaceOrderingMode:         1065,
		WindowDidChangeTitle:                     1066,
		WindowDidChangeToolbar:                   1067,
		WindowDidChangeVisibility:                1068,
		WindowDidDeminiaturize:                   1069,
		WindowDidEndSheet:                        1070,
		WindowDidEnterFullScreen:                 1071,
		WindowDidEnterVersionBrowser:             1072,
		WindowDidExitFullScreen:                  1073,
		WindowDidExitVersionBrowser:              1074,
		WindowDidExpose:                          1075,
		WindowDidFocus:                           1076,
		WindowDidMiniaturize:                     1077,
		WindowDidMove:                            1078,
		WindowDidOrderOffScreen:                  1079,
		WindowDidOrderOnScreen:                   1080,
		WindowDidResignKey:                       1081,
		WindowDidResignMain:                      1082,
		WindowDidResize:                          1083,
		WindowDidUpdate:                          1084,
		WindowDidUpdateAlpha:                     1085,
		WindowDidUpdateCollectionBehavior:        1086,
		WindowDidUpdateCollectionProperties:      1087,
		WindowDidUpdateShadow:                    1088,
		WindowDidUpdateTitle:                     1089,
		WindowDidUpdateToolbar:                   1090,
		WindowDidUpdateVisibility:                1091,
		WindowShouldClose:                        1092,
		WindowWillBecomeKey:                      1093,
		WindowWillBecomeMain:                     1094,
		WindowWillBeginSheet:                     1095,
		WindowWillChangeOrderingMode:             1096,
		WindowWillClose:                          1097,
		WindowWillDeminiaturize:                  1098,
		WindowWillEnterFullScreen:                1099,
		WindowWillEnterVersionBrowser:            1100,
		WindowWillExitFullScreen:                 1101,
		WindowWillExitVersionBrowser:             1102,
		WindowWillFocus:                          1103,
		WindowWillMiniaturize:                    1104,
		WindowWillMove:                           1105,
		WindowWillOrderOffScreen:                 1106,
		WindowWillOrderOnScreen:                  1107,
		WindowWillResignMain:                     1108,
		WindowWillResize:                         1109,
		WindowWillUnfocus:                        1110,
		WindowWillUpdate:                         1111,
		WindowWillUpdateAlpha:                    1112,
		WindowWillUpdateCollectionBehavior:       1113,
		WindowWillUpdateCollectionProperties:     1114,
		WindowWillUpdateShadow:                   1115,
		WindowWillUpdateTitle:                    1116,
		WindowWillUpdateToolbar:                  1117,
		WindowWillUpdateVisibility:               1118,
		WindowWillUseStandardFrame:               1119,
		MenuWillOpen:                             1120,
		MenuDidOpen:                              1121,
		MenuDidClose:                             1122,
		MenuWillSendAction:                       1123,
		MenuDidSendAction:                        1124,
		MenuWillHighlightItem:                    1125,
		MenuDidHighlightItem:                     1126,
		MenuWillDisplayItem:                      1127,
		MenuDidDisplayItem:                       1128,
		MenuWillAddItem:                          1129,
		MenuDidAddItem:                           1130,
		MenuWillRemoveItem:                       1131,
		MenuDidRemoveItem:                        1132,
		MenuWillBeginTracking:                    1133,
		MenuDidBeginTracking:                     1134,
		MenuWillEndTracking:                      1135,
		MenuDidEndTracking:                       1136,
		MenuWillUpdate:                           1137,
		MenuDidUpdate:                            1138,
		MenuWillPopUp:                            1139,
		MenuDidPopUp:                             1140,
		MenuWillSendActionToItem:                 1141,
		MenuDidSendActionToItem:                  1142,
		WebViewDidStartProvisionalNavigation:     1143,
		WebViewDidReceiveServerRedirectForProvisionalNavigation: 1144,
		WebViewDidFinishNavigation:                              1145,
		WebViewDidCommitNavigation:                              1146,
		WindowFileDraggingEntered:                               1147,
		WindowFileDraggingPerformed:                             1148,
		WindowFileDraggingExited:                                1149,
	}
}

var Windows = newWindowsEvents()

type windowsEvents struct {
	SystemThemeChanged         ApplicationEventType
	APMPowerStatusChange       ApplicationEventType
	APMSuspend                 ApplicationEventType
	APMResumeAutomatic         ApplicationEventType
	APMResumeSuspend           ApplicationEventType
	APMPowerSettingChange      ApplicationEventType
	ApplicationStarted         ApplicationEventType
	WebViewNavigationCompleted WindowEventType
	WindowInactive             WindowEventType
	WindowActive               WindowEventType
	WindowClickActive          WindowEventType
	WindowMaximise             WindowEventType
	WindowUnMaximise           WindowEventType
	WindowFullscreen           WindowEventType
	WindowUnFullscreen         WindowEventType
	WindowRestore              WindowEventType
	WindowMinimise             WindowEventType
	WindowUnMinimise           WindowEventType
	WindowClose                WindowEventType
	WindowSetFocus             WindowEventType
	WindowKillFocus            WindowEventType
	WindowDragDrop             WindowEventType
	WindowDragEnter            WindowEventType
	WindowDragLeave            WindowEventType
	WindowDragOver             WindowEventType
}

func newWindowsEvents() windowsEvents {
	return windowsEvents{
		SystemThemeChanged:         1150,
		APMPowerStatusChange:       1151,
		APMSuspend:                 1152,
		APMResumeAutomatic:         1153,
		APMResumeSuspend:           1154,
		APMPowerSettingChange:      1155,
		ApplicationStarted:         1156,
		WebViewNavigationCompleted: 1157,
		WindowInactive:             1158,
		WindowActive:               1159,
		WindowClickActive:          1160,
		WindowMaximise:             1161,
		WindowUnMaximise:           1162,
		WindowFullscreen:           1163,
		WindowUnFullscreen:         1164,
		WindowRestore:              1165,
		WindowMinimise:             1166,
		WindowUnMinimise:           1167,
		WindowClose:                1168,
		WindowSetFocus:             1169,
		WindowKillFocus:            1170,
		WindowDragDrop:             1171,
		WindowDragEnter:            1172,
		WindowDragLeave:            1173,
		WindowDragOver:             1174,
	}
}

func JSEvent(event uint) string {
	return eventToJS[event]
}

var eventToJS = map[uint]string{
	1024: "linux:SystemThemeChanged",
	1025: "mac:ApplicationDidBecomeActive",
	1026: "mac:ApplicationDidChangeBackingProperties",
	1027: "mac:ApplicationDidChangeEffectiveAppearance",
	1028: "mac:ApplicationDidChangeIcon",
	1029: "mac:ApplicationDidChangeOcclusionState",
	1030: "mac:ApplicationDidChangeScreenParameters",
	1031: "mac:ApplicationDidChangeStatusBarFrame",
	1032: "mac:ApplicationDidChangeStatusBarOrientation",
	1033: "mac:ApplicationDidFinishLaunching",
	1034: "mac:ApplicationDidHide",
	1035: "mac:ApplicationDidResignActiveNotification",
	1036: "mac:ApplicationDidUnhide",
	1037: "mac:ApplicationDidUpdate",
	1038: "mac:ApplicationWillBecomeActive",
	1039: "mac:ApplicationWillFinishLaunching",
	1040: "mac:ApplicationWillHide",
	1041: "mac:ApplicationWillResignActive",
	1042: "mac:ApplicationWillTerminate",
	1043: "mac:ApplicationWillUnhide",
	1044: "mac:ApplicationWillUpdate",
	1045: "mac:ApplicationTerminate",
	1046: "mac:ApplicationDidChangeTheme!",
	1047: "mac:ApplicationShouldHandleReopen!",
	1048: "mac:WindowDidBecomeKey",
	1049: "mac:WindowDidBecomeMain",
	1050: "mac:WindowDidBeginSheet",
	1051: "mac:WindowDidChangeAlpha",
	1052: "mac:WindowDidChangeBackingLocation",
	1053: "mac:WindowDidChangeBackingProperties",
	1054: "mac:WindowDidChangeCollectionBehavior",
	1055: "mac:WindowDidChangeEffectiveAppearance",
	1056: "mac:WindowDidChangeOcclusionState",
	1057: "mac:WindowDidChangeOrderingMode",
	1058: "mac:WindowDidChangeScreen",
	1059: "mac:WindowDidChangeScreenParameters",
	1060: "mac:WindowDidChangeScreenProfile",
	1061: "mac:WindowDidChangeScreenSpace",
	1062: "mac:WindowDidChangeScreenSpaceProperties",
	1063: "mac:WindowDidChangeSharingType",
	1064: "mac:WindowDidChangeSpace",
	1065: "mac:WindowDidChangeSpaceOrderingMode",
	1066: "mac:WindowDidChangeTitle",
	1067: "mac:WindowDidChangeToolbar",
	1068: "mac:WindowDidChangeVisibility",
	1069: "mac:WindowDidDeminiaturize",
	1070: "mac:WindowDidEndSheet",
	1071: "mac:WindowDidEnterFullScreen",
	1072: "mac:WindowDidEnterVersionBrowser",
	1073: "mac:WindowDidExitFullScreen",
	1074: "mac:WindowDidExitVersionBrowser",
	1075: "mac:WindowDidExpose",
	1076: "mac:WindowDidFocus",
	1077: "mac:WindowDidMiniaturize",
	1078: "mac:WindowDidMove",
	1079: "mac:WindowDidOrderOffScreen",
	1080: "mac:WindowDidOrderOnScreen",
	1081: "mac:WindowDidResignKey",
	1082: "mac:WindowDidResignMain",
	1083: "mac:WindowDidResize",
	1084: "mac:WindowDidUpdate",
	1085: "mac:WindowDidUpdateAlpha",
	1086: "mac:WindowDidUpdateCollectionBehavior",
	1087: "mac:WindowDidUpdateCollectionProperties",
	1088: "mac:WindowDidUpdateShadow",
	1089: "mac:WindowDidUpdateTitle",
	1090: "mac:WindowDidUpdateToolbar",
	1091: "mac:WindowDidUpdateVisibility",
	1092: "mac:WindowShouldClose!",
	1093: "mac:WindowWillBecomeKey",
	1094: "mac:WindowWillBecomeMain",
	1095: "mac:WindowWillBeginSheet",
	1096: "mac:WindowWillChangeOrderingMode",
	1097: "mac:WindowWillClose",
	1098: "mac:WindowWillDeminiaturize",
	1099: "mac:WindowWillEnterFullScreen",
	1100: "mac:WindowWillEnterVersionBrowser",
	1101: "mac:WindowWillExitFullScreen",
	1102: "mac:WindowWillExitVersionBrowser",
	1103: "mac:WindowWillFocus",
	1104: "mac:WindowWillMiniaturize",
	1105: "mac:WindowWillMove",
	1106: "mac:WindowWillOrderOffScreen",
	1107: "mac:WindowWillOrderOnScreen",
	1108: "mac:WindowWillResignMain",
	1109: "mac:WindowWillResize",
	1110: "mac:WindowWillUnfocus",
	1111: "mac:WindowWillUpdate",
	1112: "mac:WindowWillUpdateAlpha",
	1113: "mac:WindowWillUpdateCollectionBehavior",
	1114: "mac:WindowWillUpdateCollectionProperties",
	1115: "mac:WindowWillUpdateShadow",
	1116: "mac:WindowWillUpdateTitle",
	1117: "mac:WindowWillUpdateToolbar",
	1118: "mac:WindowWillUpdateVisibility",
	1119: "mac:WindowWillUseStandardFrame",
	1120: "mac:MenuWillOpen",
	1121: "mac:MenuDidOpen",
	1122: "mac:MenuDidClose",
	1123: "mac:MenuWillSendAction",
	1124: "mac:MenuDidSendAction",
	1125: "mac:MenuWillHighlightItem",
	1126: "mac:MenuDidHighlightItem",
	1127: "mac:MenuWillDisplayItem",
	1128: "mac:MenuDidDisplayItem",
	1129: "mac:MenuWillAddItem",
	1130: "mac:MenuDidAddItem",
	1131: "mac:MenuWillRemoveItem",
	1132: "mac:MenuDidRemoveItem",
	1133: "mac:MenuWillBeginTracking",
	1134: "mac:MenuDidBeginTracking",
	1135: "mac:MenuWillEndTracking",
	1136: "mac:MenuDidEndTracking",
	1137: "mac:MenuWillUpdate",
	1138: "mac:MenuDidUpdate",
	1139: "mac:MenuWillPopUp",
	1140: "mac:MenuDidPopUp",
	1141: "mac:MenuWillSendActionToItem",
	1142: "mac:MenuDidSendActionToItem",
	1143: "mac:WebViewDidStartProvisionalNavigation",
	1144: "mac:WebViewDidReceiveServerRedirectForProvisionalNavigation",
	1145: "mac:WebViewDidFinishNavigation",
	1146: "mac:WebViewDidCommitNavigation",
	1147: "mac:WindowFileDraggingEntered",
	1148: "mac:WindowFileDraggingPerformed",
	1149: "mac:WindowFileDraggingExited",
	1150: "windows:SystemThemeChanged",
	1151: "windows:APMPowerStatusChange",
	1152: "windows:APMSuspend",
	1153: "windows:APMResumeAutomatic",
	1154: "windows:APMResumeSuspend",
	1155: "windows:APMPowerSettingChange",
	1156: "windows:ApplicationStarted",
	1157: "windows:WebViewNavigationCompleted",
	1158: "windows:WindowInactive",
	1159: "windows:WindowActive",
	1160: "windows:WindowClickActive",
	1161: "windows:WindowMaximise",
	1162: "windows:WindowUnMaximise",
	1163: "windows:WindowFullscreen",
	1164: "windows:WindowUnFullscreen",
	1165: "windows:WindowRestore",
	1166: "windows:WindowMinimise",
	1167: "windows:WindowUnMinimise",
	1168: "windows:WindowClose",
	1169: "windows:WindowSetFocus",
	1170: "windows:WindowKillFocus",
	1171: "windows:WindowDragDrop",
	1172: "windows:WindowDragEnter",
	1173: "windows:WindowDragLeave",
	1174: "windows:WindowDragOver",
	1175: "common:ApplicationStarted",
	1176: "common:WindowMaximise",
	1177: "common:WindowUnMaximise",
	1178: "common:WindowFullscreen",
	1179: "common:WindowUnFullscreen",
	1180: "common:WindowRestore",
	1181: "common:WindowMinimise",
	1182: "common:WindowUnMinimise",
	1183: "common:WindowClosing",
	1184: "common:WindowZoom",
	1185: "common:WindowZoomIn",
	1186: "common:WindowZoomOut",
	1187: "common:WindowZoomReset",
	1188: "common:WindowFocus",
	1189: "common:WindowLostFocus",
	1190: "common:WindowShow",
	1191: "common:WindowHide",
	1192: "common:WindowDPIChanged",
	1193: "common:WindowFilesDropped",
	1194: "common:ThemeChanged",
	1195: "common:ApplicationTerminate",
}
