//go:build darwin

#ifndef _events_h
#define _events_h

extern void processApplicationEvent(unsigned int, void* data);
extern void processWindowEvent(unsigned int, unsigned int);

#define EventApplicationDidBecomeActive 1056
#define EventApplicationDidChangeBackingProperties 1057
#define EventApplicationDidChangeEffectiveAppearance 1058
#define EventApplicationDidChangeIcon 1059
#define EventApplicationDidChangeOcclusionState 1060
#define EventApplicationDidChangeScreenParameters 1061
#define EventApplicationDidChangeStatusBarFrame 1062
#define EventApplicationDidChangeStatusBarOrientation 1063
#define EventApplicationDidChangeTheme 1064
#define EventApplicationDidFinishLaunching 1065
#define EventApplicationDidHide 1066
#define EventApplicationDidResignActive 1067
#define EventApplicationDidUnhide 1068
#define EventApplicationDidUpdate 1069
#define EventApplicationShouldHandleReopen 1070
#define EventApplicationWillBecomeActive 1071
#define EventApplicationWillFinishLaunching 1072
#define EventApplicationWillHide 1073
#define EventApplicationWillResignActive 1074
#define EventApplicationWillTerminate 1075
#define EventApplicationWillUnhide 1076
#define EventApplicationWillUpdate 1077
#define EventMenuDidAddItem 1078
#define EventMenuDidBeginTracking 1079
#define EventMenuDidClose 1080
#define EventMenuDidDisplayItem 1081
#define EventMenuDidEndTracking 1082
#define EventMenuDidHighlightItem 1083
#define EventMenuDidOpen 1084
#define EventMenuDidPopUp 1085
#define EventMenuDidRemoveItem 1086
#define EventMenuDidSendAction 1087
#define EventMenuDidSendActionToItem 1088
#define EventMenuDidUpdate 1089
#define EventMenuWillAddItem 1090
#define EventMenuWillBeginTracking 1091
#define EventMenuWillDisplayItem 1092
#define EventMenuWillEndTracking 1093
#define EventMenuWillHighlightItem 1094
#define EventMenuWillOpen 1095
#define EventMenuWillPopUp 1096
#define EventMenuWillRemoveItem 1097
#define EventMenuWillSendAction 1098
#define EventMenuWillSendActionToItem 1099
#define EventMenuWillUpdate 1100
#define EventWebViewDidCommitNavigation 1101
#define EventWebViewDidFinishNavigation 1102
#define EventWebViewDidReceiveServerRedirectForProvisionalNavigation 1103
#define EventWebViewDidStartProvisionalNavigation 1104
#define EventWindowDidBecomeKey 1105
#define EventWindowDidBecomeMain 1106
#define EventWindowDidBeginSheet 1107
#define EventWindowDidChangeAlpha 1108
#define EventWindowDidChangeBackingLocation 1109
#define EventWindowDidChangeBackingProperties 1110
#define EventWindowDidChangeCollectionBehavior 1111
#define EventWindowDidChangeEffectiveAppearance 1112
#define EventWindowDidChangeOcclusionState 1113
#define EventWindowDidChangeOrderingMode 1114
#define EventWindowDidChangeScreen 1115
#define EventWindowDidChangeScreenParameters 1116
#define EventWindowDidChangeScreenProfile 1117
#define EventWindowDidChangeScreenSpace 1118
#define EventWindowDidChangeScreenSpaceProperties 1119
#define EventWindowDidChangeSharingType 1120
#define EventWindowDidChangeSpace 1121
#define EventWindowDidChangeSpaceOrderingMode 1122
#define EventWindowDidChangeTitle 1123
#define EventWindowDidChangeToolbar 1124
#define EventWindowDidDeminiaturize 1125
#define EventWindowDidEndSheet 1126
#define EventWindowDidEnterFullScreen 1127
#define EventWindowDidEnterVersionBrowser 1128
#define EventWindowDidExitFullScreen 1129
#define EventWindowDidExitVersionBrowser 1130
#define EventWindowDidExpose 1131
#define EventWindowDidFocus 1132
#define EventWindowDidMiniaturize 1133
#define EventWindowDidMove 1134
#define EventWindowDidOrderOffScreen 1135
#define EventWindowDidOrderOnScreen 1136
#define EventWindowDidResignKey 1137
#define EventWindowDidResignMain 1138
#define EventWindowDidResize 1139
#define EventWindowDidUpdate 1140
#define EventWindowDidUpdateAlpha 1141
#define EventWindowDidUpdateCollectionBehavior 1142
#define EventWindowDidUpdateCollectionProperties 1143
#define EventWindowDidUpdateShadow 1144
#define EventWindowDidUpdateTitle 1145
#define EventWindowDidUpdateToolbar 1146
#define EventWindowDidZoom 1147
#define EventWindowFileDraggingEntered 1148
#define EventWindowFileDraggingExited 1149
#define EventWindowFileDraggingPerformed 1150
#define EventWindowHide 1151
#define EventWindowMaximise 1152
#define EventWindowUnMaximise 1153
#define EventWindowMinimise 1154
#define EventWindowUnMinimise 1155
#define EventWindowShouldClose 1156
#define EventWindowShow 1157
#define EventWindowWillBecomeKey 1158
#define EventWindowWillBecomeMain 1159
#define EventWindowWillBeginSheet 1160
#define EventWindowWillChangeOrderingMode 1161
#define EventWindowWillClose 1162
#define EventWindowWillDeminiaturize 1163
#define EventWindowWillEnterFullScreen 1164
#define EventWindowWillEnterVersionBrowser 1165
#define EventWindowWillExitFullScreen 1166
#define EventWindowWillExitVersionBrowser 1167
#define EventWindowWillFocus 1168
#define EventWindowWillMiniaturize 1169
#define EventWindowWillMove 1170
#define EventWindowWillOrderOffScreen 1171
#define EventWindowWillOrderOnScreen 1172
#define EventWindowWillResignMain 1173
#define EventWindowWillResize 1174
#define EventWindowWillUnfocus 1175
#define EventWindowWillUpdate 1176
#define EventWindowWillUpdateAlpha 1177
#define EventWindowWillUpdateCollectionBehavior 1178
#define EventWindowWillUpdateCollectionProperties 1179
#define EventWindowWillUpdateShadow 1180
#define EventWindowWillUpdateTitle 1181
#define EventWindowWillUpdateToolbar 1182
#define EventWindowWillUpdateVisibility 1183
#define EventWindowWillUseStandardFrame 1184
#define EventWindowZoomIn 1185
#define EventWindowZoomOut 1186
#define EventWindowZoomReset 1187

#define MAX_EVENTS 1188


#endif