//go:build darwin

#ifndef _events_h
#define _events_h

extern void processApplicationEvent(unsigned int, void* data);
extern void processWindowEvent(unsigned int, unsigned int);

#define EventApplicationDidBecomeActive 1063
#define EventApplicationDidChangeBackingProperties 1064
#define EventApplicationDidChangeEffectiveAppearance 1065
#define EventApplicationDidChangeIcon 1066
#define EventApplicationDidChangeOcclusionState 1067
#define EventApplicationDidChangeScreenParameters 1068
#define EventApplicationDidChangeStatusBarFrame 1069
#define EventApplicationDidChangeStatusBarOrientation 1070
#define EventApplicationDidChangeTheme 1071
#define EventApplicationDidFinishLaunching 1072
#define EventApplicationDidHide 1073
#define EventApplicationDidResignActive 1074
#define EventApplicationDidUnhide 1075
#define EventApplicationDidUpdate 1076
#define EventApplicationDidWake 1077
#define EventApplicationScreensDidSleep 1078
#define EventApplicationScreensDidWake 1079
#define EventApplicationShouldHandleReopen 1080
#define EventApplicationWillBecomeActive 1081
#define EventApplicationWillFinishLaunching 1082
#define EventApplicationWillHide 1083
#define EventApplicationWillResignActive 1084
#define EventApplicationWillSleep 1085
#define EventApplicationWillTerminate 1086
#define EventApplicationWillUnhide 1087
#define EventApplicationWillUpdate 1088
#define EventMenuDidAddItem 1089
#define EventMenuDidBeginTracking 1090
#define EventMenuDidClose 1091
#define EventMenuDidDisplayItem 1092
#define EventMenuDidEndTracking 1093
#define EventMenuDidHighlightItem 1094
#define EventMenuDidOpen 1095
#define EventMenuDidPopUp 1096
#define EventMenuDidRemoveItem 1097
#define EventMenuDidSendAction 1098
#define EventMenuDidSendActionToItem 1099
#define EventMenuDidUpdate 1100
#define EventMenuWillAddItem 1101
#define EventMenuWillBeginTracking 1102
#define EventMenuWillDisplayItem 1103
#define EventMenuWillEndTracking 1104
#define EventMenuWillHighlightItem 1105
#define EventMenuWillOpen 1106
#define EventMenuWillPopUp 1107
#define EventMenuWillRemoveItem 1108
#define EventMenuWillSendAction 1109
#define EventMenuWillSendActionToItem 1110
#define EventMenuWillUpdate 1111
#define EventWebViewDidCommitNavigation 1112
#define EventWebViewDidFinishNavigation 1113
#define EventWebViewDidReceiveServerRedirectForProvisionalNavigation 1114
#define EventWebViewDidStartProvisionalNavigation 1115
#define EventWindowDidBecomeKey 1116
#define EventWindowDidBecomeMain 1117
#define EventWindowDidBeginSheet 1118
#define EventWindowDidChangeAlpha 1119
#define EventWindowDidChangeBackingLocation 1120
#define EventWindowDidChangeBackingProperties 1121
#define EventWindowDidChangeCollectionBehavior 1122
#define EventWindowDidChangeEffectiveAppearance 1123
#define EventWindowDidChangeOcclusionState 1124
#define EventWindowDidChangeOrderingMode 1125
#define EventWindowDidChangeScreen 1126
#define EventWindowDidChangeScreenParameters 1127
#define EventWindowDidChangeScreenProfile 1128
#define EventWindowDidChangeScreenSpace 1129
#define EventWindowDidChangeScreenSpaceProperties 1130
#define EventWindowDidChangeSharingType 1131
#define EventWindowDidChangeSpace 1132
#define EventWindowDidChangeSpaceOrderingMode 1133
#define EventWindowDidChangeTitle 1134
#define EventWindowDidChangeToolbar 1135
#define EventWindowDidDeminiaturize 1136
#define EventWindowDidEndSheet 1137
#define EventWindowDidEnterFullScreen 1138
#define EventWindowDidEnterVersionBrowser 1139
#define EventWindowDidExitFullScreen 1140
#define EventWindowDidExitVersionBrowser 1141
#define EventWindowDidExpose 1142
#define EventWindowDidFocus 1143
#define EventWindowDidMiniaturize 1144
#define EventWindowDidMove 1145
#define EventWindowDidOrderOffScreen 1146
#define EventWindowDidOrderOnScreen 1147
#define EventWindowDidResignKey 1148
#define EventWindowDidResignMain 1149
#define EventWindowDidResize 1150
#define EventWindowDidUpdate 1151
#define EventWindowDidUpdateAlpha 1152
#define EventWindowDidUpdateCollectionBehavior 1153
#define EventWindowDidUpdateCollectionProperties 1154
#define EventWindowDidUpdateShadow 1155
#define EventWindowDidUpdateTitle 1156
#define EventWindowDidUpdateToolbar 1157
#define EventWindowDidZoom 1158
#define EventWindowFileDraggingEntered 1159
#define EventWindowFileDraggingExited 1160
#define EventWindowFileDraggingPerformed 1161
#define EventWindowHide 1162
#define EventWindowMaximise 1163
#define EventWindowUnMaximise 1164
#define EventWindowMinimise 1165
#define EventWindowUnMinimise 1166
#define EventWindowShouldClose 1167
#define EventWindowShow 1168
#define EventWindowWillBecomeKey 1169
#define EventWindowWillBecomeMain 1170
#define EventWindowWillBeginSheet 1171
#define EventWindowWillChangeOrderingMode 1172
#define EventWindowWillClose 1173
#define EventWindowWillDeminiaturize 1174
#define EventWindowWillEnterFullScreen 1175
#define EventWindowWillEnterVersionBrowser 1176
#define EventWindowWillExitFullScreen 1177
#define EventWindowWillExitVersionBrowser 1178
#define EventWindowWillFocus 1179
#define EventWindowWillMiniaturize 1180
#define EventWindowWillMove 1181
#define EventWindowWillOrderOffScreen 1182
#define EventWindowWillOrderOnScreen 1183
#define EventWindowWillResignMain 1184
#define EventWindowWillResize 1185
#define EventWindowWillUnfocus 1186
#define EventWindowWillUpdate 1187
#define EventWindowWillUpdateAlpha 1188
#define EventWindowWillUpdateCollectionBehavior 1189
#define EventWindowWillUpdateCollectionProperties 1190
#define EventWindowWillUpdateShadow 1191
#define EventWindowWillUpdateTitle 1192
#define EventWindowWillUpdateToolbar 1193
#define EventWindowWillUpdateVisibility 1194
#define EventWindowWillUseStandardFrame 1195
#define EventWindowZoomIn 1196
#define EventWindowZoomOut 1197
#define EventWindowZoomReset 1198

#define MAX_EVENTS 1199


#endif