package events

type ApplicationEventType uint
type WindowEventType      uint

var Common = newCommonEvents()

type commonEvents struct {
	ApplicationStarted ApplicationEventType
	WindowMaximise WindowEventType
	WindowUnMaximise WindowEventType
	WindowFullscreen WindowEventType
	WindowUnFullscreen WindowEventType
	WindowRestore WindowEventType
	WindowMinimise WindowEventType
	WindowUnMinimise WindowEventType
	WindowClosing WindowEventType
	WindowZoom WindowEventType
	WindowZoomIn WindowEventType
	WindowZoomOut WindowEventType
	WindowZoomReset WindowEventType
	WindowFocus WindowEventType
	WindowLostFocus WindowEventType
	WindowShow WindowEventType
	WindowHide WindowEventType
	WindowDPIChanged WindowEventType
	WindowFilesDropped WindowEventType
	ThemeChanged ApplicationEventType
}

func newCommonEvents() commonEvents {
	return commonEvents{
		ApplicationStarted: 1176,
		WindowMaximise: 1177,
		WindowUnMaximise: 1178,
		WindowFullscreen: 1179,
		WindowUnFullscreen: 1180,
		WindowRestore: 1181,
		WindowMinimise: 1182,
		WindowUnMinimise: 1183,
		WindowClosing: 1184,
		WindowZoom: 1185,
		WindowZoomIn: 1186,
		WindowZoomOut: 1187,
		WindowZoomReset: 1188,
		WindowFocus: 1189,
		WindowLostFocus: 1190,
		WindowShow: 1191,
		WindowHide: 1192,
		WindowDPIChanged: 1193,
		WindowFilesDropped: 1194,
		ThemeChanged: 1195,
	}
}

var Linux = newLinuxEvents()

type linuxEvents struct {
	ApplicationStarted ApplicationEventType
	SystemThemeChanged ApplicationEventType
	WindowClosing WindowEventType
}

func newLinuxEvents() linuxEvents {
	return linuxEvents{
		ApplicationStarted: 1024,
		SystemThemeChanged: 1025,
		WindowClosing: 1026,
	}
}

var Mac = newMacEvents()

type macEvents struct {
	ApplicationDidBecomeActive ApplicationEventType
	ApplicationDidChangeBackingProperties ApplicationEventType
	ApplicationDidChangeEffectiveAppearance ApplicationEventType
	ApplicationDidChangeIcon ApplicationEventType
	ApplicationDidChangeOcclusionState ApplicationEventType
	ApplicationDidChangeScreenParameters ApplicationEventType
	ApplicationDidChangeStatusBarFrame ApplicationEventType
	ApplicationDidChangeStatusBarOrientation ApplicationEventType
	ApplicationDidFinishLaunching ApplicationEventType
	ApplicationDidHide ApplicationEventType
	ApplicationDidResignActiveNotification ApplicationEventType
	ApplicationDidUnhide ApplicationEventType
	ApplicationDidUpdate ApplicationEventType
	ApplicationWillBecomeActive ApplicationEventType
	ApplicationWillFinishLaunching ApplicationEventType
	ApplicationWillHide ApplicationEventType
	ApplicationWillResignActive ApplicationEventType
	ApplicationWillTerminate ApplicationEventType
	ApplicationWillUnhide ApplicationEventType
	ApplicationWillUpdate ApplicationEventType
	ApplicationDidChangeTheme ApplicationEventType
	ApplicationShouldHandleReopen ApplicationEventType
	WindowDidBecomeKey WindowEventType
	WindowDidBecomeMain WindowEventType
	WindowDidBeginSheet WindowEventType
	WindowDidChangeAlpha WindowEventType
	WindowDidChangeBackingLocation WindowEventType
	WindowDidChangeBackingProperties WindowEventType
	WindowDidChangeCollectionBehavior WindowEventType
	WindowDidChangeEffectiveAppearance WindowEventType
	WindowDidChangeOcclusionState WindowEventType
	WindowDidChangeOrderingMode WindowEventType
	WindowDidChangeScreen WindowEventType
	WindowDidChangeScreenParameters WindowEventType
	WindowDidChangeScreenProfile WindowEventType
	WindowDidChangeScreenSpace WindowEventType
	WindowDidChangeScreenSpaceProperties WindowEventType
	WindowDidChangeSharingType WindowEventType
	WindowDidChangeSpace WindowEventType
	WindowDidChangeSpaceOrderingMode WindowEventType
	WindowDidChangeTitle WindowEventType
	WindowDidChangeToolbar WindowEventType
	WindowDidChangeVisibility WindowEventType
	WindowDidDeminiaturize WindowEventType
	WindowDidEndSheet WindowEventType
	WindowDidEnterFullScreen WindowEventType
	WindowDidEnterVersionBrowser WindowEventType
	WindowDidExitFullScreen WindowEventType
	WindowDidExitVersionBrowser WindowEventType
	WindowDidExpose WindowEventType
	WindowDidFocus WindowEventType
	WindowDidMiniaturize WindowEventType
	WindowDidMove WindowEventType
	WindowDidOrderOffScreen WindowEventType
	WindowDidOrderOnScreen WindowEventType
	WindowDidResignKey WindowEventType
	WindowDidResignMain WindowEventType
	WindowDidResize WindowEventType
	WindowDidUpdate WindowEventType
	WindowDidUpdateAlpha WindowEventType
	WindowDidUpdateCollectionBehavior WindowEventType
	WindowDidUpdateCollectionProperties WindowEventType
	WindowDidUpdateShadow WindowEventType
	WindowDidUpdateTitle WindowEventType
	WindowDidUpdateToolbar WindowEventType
	WindowDidUpdateVisibility WindowEventType
	WindowShouldClose WindowEventType
	WindowWillBecomeKey WindowEventType
	WindowWillBecomeMain WindowEventType
	WindowWillBeginSheet WindowEventType
	WindowWillChangeOrderingMode WindowEventType
	WindowWillClose WindowEventType
	WindowWillDeminiaturize WindowEventType
	WindowWillEnterFullScreen WindowEventType
	WindowWillEnterVersionBrowser WindowEventType
	WindowWillExitFullScreen WindowEventType
	WindowWillExitVersionBrowser WindowEventType
	WindowWillFocus WindowEventType
	WindowWillMiniaturize WindowEventType
	WindowWillMove WindowEventType
	WindowWillOrderOffScreen WindowEventType
	WindowWillOrderOnScreen WindowEventType
	WindowWillResignMain WindowEventType
	WindowWillResize WindowEventType
	WindowWillUnfocus WindowEventType
	WindowWillUpdate WindowEventType
	WindowWillUpdateAlpha WindowEventType
	WindowWillUpdateCollectionBehavior WindowEventType
	WindowWillUpdateCollectionProperties WindowEventType
	WindowWillUpdateShadow WindowEventType
	WindowWillUpdateTitle WindowEventType
	WindowWillUpdateToolbar WindowEventType
	WindowWillUpdateVisibility WindowEventType
	WindowWillUseStandardFrame WindowEventType
	MenuWillOpen ApplicationEventType
	MenuDidOpen ApplicationEventType
	MenuDidClose ApplicationEventType
	MenuWillSendAction ApplicationEventType
	MenuDidSendAction ApplicationEventType
	MenuWillHighlightItem ApplicationEventType
	MenuDidHighlightItem ApplicationEventType
	MenuWillDisplayItem ApplicationEventType
	MenuDidDisplayItem ApplicationEventType
	MenuWillAddItem ApplicationEventType
	MenuDidAddItem ApplicationEventType
	MenuWillRemoveItem ApplicationEventType
	MenuDidRemoveItem ApplicationEventType
	MenuWillBeginTracking ApplicationEventType
	MenuDidBeginTracking ApplicationEventType
	MenuWillEndTracking ApplicationEventType
	MenuDidEndTracking ApplicationEventType
	MenuWillUpdate ApplicationEventType
	MenuDidUpdate ApplicationEventType
	MenuWillPopUp ApplicationEventType
	MenuDidPopUp ApplicationEventType
	MenuWillSendActionToItem ApplicationEventType
	MenuDidSendActionToItem ApplicationEventType
	WebViewDidStartProvisionalNavigation WindowEventType
	WebViewDidReceiveServerRedirectForProvisionalNavigation WindowEventType
	WebViewDidFinishNavigation WindowEventType
	WebViewDidCommitNavigation WindowEventType
	WindowFileDraggingEntered WindowEventType
	WindowFileDraggingPerformed WindowEventType
	WindowFileDraggingExited WindowEventType
}

func newMacEvents() macEvents {
	return macEvents{
		ApplicationDidBecomeActive: 1027,
		ApplicationDidChangeBackingProperties: 1028,
		ApplicationDidChangeEffectiveAppearance: 1029,
		ApplicationDidChangeIcon: 1030,
		ApplicationDidChangeOcclusionState: 1031,
		ApplicationDidChangeScreenParameters: 1032,
		ApplicationDidChangeStatusBarFrame: 1033,
		ApplicationDidChangeStatusBarOrientation: 1034,
		ApplicationDidFinishLaunching: 1035,
		ApplicationDidHide: 1036,
		ApplicationDidResignActiveNotification: 1037,
		ApplicationDidUnhide: 1038,
		ApplicationDidUpdate: 1039,
		ApplicationWillBecomeActive: 1040,
		ApplicationWillFinishLaunching: 1041,
		ApplicationWillHide: 1042,
		ApplicationWillResignActive: 1043,
		ApplicationWillTerminate: 1044,
		ApplicationWillUnhide: 1045,
		ApplicationWillUpdate: 1046,
		ApplicationDidChangeTheme: 1047,
		ApplicationShouldHandleReopen: 1048,
		WindowDidBecomeKey: 1049,
		WindowDidBecomeMain: 1050,
		WindowDidBeginSheet: 1051,
		WindowDidChangeAlpha: 1052,
		WindowDidChangeBackingLocation: 1053,
		WindowDidChangeBackingProperties: 1054,
		WindowDidChangeCollectionBehavior: 1055,
		WindowDidChangeEffectiveAppearance: 1056,
		WindowDidChangeOcclusionState: 1057,
		WindowDidChangeOrderingMode: 1058,
		WindowDidChangeScreen: 1059,
		WindowDidChangeScreenParameters: 1060,
		WindowDidChangeScreenProfile: 1061,
		WindowDidChangeScreenSpace: 1062,
		WindowDidChangeScreenSpaceProperties: 1063,
		WindowDidChangeSharingType: 1064,
		WindowDidChangeSpace: 1065,
		WindowDidChangeSpaceOrderingMode: 1066,
		WindowDidChangeTitle: 1067,
		WindowDidChangeToolbar: 1068,
		WindowDidChangeVisibility: 1069,
		WindowDidDeminiaturize: 1070,
		WindowDidEndSheet: 1071,
		WindowDidEnterFullScreen: 1072,
		WindowDidEnterVersionBrowser: 1073,
		WindowDidExitFullScreen: 1074,
		WindowDidExitVersionBrowser: 1075,
		WindowDidExpose: 1076,
		WindowDidFocus: 1077,
		WindowDidMiniaturize: 1078,
		WindowDidMove: 1079,
		WindowDidOrderOffScreen: 1080,
		WindowDidOrderOnScreen: 1081,
		WindowDidResignKey: 1082,
		WindowDidResignMain: 1083,
		WindowDidResize: 1084,
		WindowDidUpdate: 1085,
		WindowDidUpdateAlpha: 1086,
		WindowDidUpdateCollectionBehavior: 1087,
		WindowDidUpdateCollectionProperties: 1088,
		WindowDidUpdateShadow: 1089,
		WindowDidUpdateTitle: 1090,
		WindowDidUpdateToolbar: 1091,
		WindowDidUpdateVisibility: 1092,
		WindowShouldClose: 1093,
		WindowWillBecomeKey: 1094,
		WindowWillBecomeMain: 1095,
		WindowWillBeginSheet: 1096,
		WindowWillChangeOrderingMode: 1097,
		WindowWillClose: 1098,
		WindowWillDeminiaturize: 1099,
		WindowWillEnterFullScreen: 1100,
		WindowWillEnterVersionBrowser: 1101,
		WindowWillExitFullScreen: 1102,
		WindowWillExitVersionBrowser: 1103,
		WindowWillFocus: 1104,
		WindowWillMiniaturize: 1105,
		WindowWillMove: 1106,
		WindowWillOrderOffScreen: 1107,
		WindowWillOrderOnScreen: 1108,
		WindowWillResignMain: 1109,
		WindowWillResize: 1110,
		WindowWillUnfocus: 1111,
		WindowWillUpdate: 1112,
		WindowWillUpdateAlpha: 1113,
		WindowWillUpdateCollectionBehavior: 1114,
		WindowWillUpdateCollectionProperties: 1115,
		WindowWillUpdateShadow: 1116,
		WindowWillUpdateTitle: 1117,
		WindowWillUpdateToolbar: 1118,
		WindowWillUpdateVisibility: 1119,
		WindowWillUseStandardFrame: 1120,
		MenuWillOpen: 1121,
		MenuDidOpen: 1122,
		MenuDidClose: 1123,
		MenuWillSendAction: 1124,
		MenuDidSendAction: 1125,
		MenuWillHighlightItem: 1126,
		MenuDidHighlightItem: 1127,
		MenuWillDisplayItem: 1128,
		MenuDidDisplayItem: 1129,
		MenuWillAddItem: 1130,
		MenuDidAddItem: 1131,
		MenuWillRemoveItem: 1132,
		MenuDidRemoveItem: 1133,
		MenuWillBeginTracking: 1134,
		MenuDidBeginTracking: 1135,
		MenuWillEndTracking: 1136,
		MenuDidEndTracking: 1137,
		MenuWillUpdate: 1138,
		MenuDidUpdate: 1139,
		MenuWillPopUp: 1140,
		MenuDidPopUp: 1141,
		MenuWillSendActionToItem: 1142,
		MenuDidSendActionToItem: 1143,
		WebViewDidStartProvisionalNavigation: 1144,
		WebViewDidReceiveServerRedirectForProvisionalNavigation: 1145,
		WebViewDidFinishNavigation: 1146,
		WebViewDidCommitNavigation: 1147,
		WindowFileDraggingEntered: 1148,
		WindowFileDraggingPerformed: 1149,
		WindowFileDraggingExited: 1150,
	}
}

var Windows = newWindowsEvents()

type windowsEvents struct {
	SystemThemeChanged ApplicationEventType
	APMPowerStatusChange ApplicationEventType
	APMSuspend ApplicationEventType
	APMResumeAutomatic ApplicationEventType
	APMResumeSuspend ApplicationEventType
	APMPowerSettingChange ApplicationEventType
	ApplicationStarted ApplicationEventType
	WebViewNavigationCompleted WindowEventType
	WindowInactive WindowEventType
	WindowActive WindowEventType
	WindowClickActive WindowEventType
	WindowMaximise WindowEventType
	WindowUnMaximise WindowEventType
	WindowFullscreen WindowEventType
	WindowUnFullscreen WindowEventType
	WindowRestore WindowEventType
	WindowMinimise WindowEventType
	WindowUnMinimise WindowEventType
	WindowClose WindowEventType
	WindowSetFocus WindowEventType
	WindowKillFocus WindowEventType
	WindowDragDrop WindowEventType
	WindowDragEnter WindowEventType
	WindowDragLeave WindowEventType
	WindowDragOver WindowEventType
}

func newWindowsEvents() windowsEvents {
	return windowsEvents{
		SystemThemeChanged: 1151,
		APMPowerStatusChange: 1152,
		APMSuspend: 1153,
		APMResumeAutomatic: 1154,
		APMResumeSuspend: 1155,
		APMPowerSettingChange: 1156,
		ApplicationStarted: 1157,
		WebViewNavigationCompleted: 1158,
		WindowInactive: 1159,
		WindowActive: 1160,
		WindowClickActive: 1161,
		WindowMaximise: 1162,
		WindowUnMaximise: 1163,
		WindowFullscreen: 1164,
		WindowUnFullscreen: 1165,
		WindowRestore: 1166,
		WindowMinimise: 1167,
		WindowUnMinimise: 1168,
		WindowClose: 1169,
		WindowSetFocus: 1170,
		WindowKillFocus: 1171,
		WindowDragDrop: 1172,
		WindowDragEnter: 1173,
		WindowDragLeave: 1174,
		WindowDragOver: 1175,
	}
}

func JSEvent(event uint) string {
	return eventToJS[event]
}

var eventToJS = map[uint]string{
	1024: "linux:ApplicationStarted",
	1025: "linux:SystemThemeChanged",
	1026: "linux:WindowClosing",
	1027: "mac:ApplicationDidBecomeActive",
	1028: "mac:ApplicationDidChangeBackingProperties",
	1029: "mac:ApplicationDidChangeEffectiveAppearance",
	1030: "mac:ApplicationDidChangeIcon",
	1031: "mac:ApplicationDidChangeOcclusionState",
	1032: "mac:ApplicationDidChangeScreenParameters",
	1033: "mac:ApplicationDidChangeStatusBarFrame",
	1034: "mac:ApplicationDidChangeStatusBarOrientation",
	1035: "mac:ApplicationDidFinishLaunching",
	1036: "mac:ApplicationDidHide",
	1037: "mac:ApplicationDidResignActiveNotification",
	1038: "mac:ApplicationDidUnhide",
	1039: "mac:ApplicationDidUpdate",
	1040: "mac:ApplicationWillBecomeActive",
	1041: "mac:ApplicationWillFinishLaunching",
	1042: "mac:ApplicationWillHide",
	1043: "mac:ApplicationWillResignActive",
	1044: "mac:ApplicationWillTerminate",
	1045: "mac:ApplicationWillUnhide",
	1046: "mac:ApplicationWillUpdate",
	1047: "mac:ApplicationDidChangeTheme!",
	1048: "mac:ApplicationShouldHandleReopen!",
	1049: "mac:WindowDidBecomeKey",
	1050: "mac:WindowDidBecomeMain",
	1051: "mac:WindowDidBeginSheet",
	1052: "mac:WindowDidChangeAlpha",
	1053: "mac:WindowDidChangeBackingLocation",
	1054: "mac:WindowDidChangeBackingProperties",
	1055: "mac:WindowDidChangeCollectionBehavior",
	1056: "mac:WindowDidChangeEffectiveAppearance",
	1057: "mac:WindowDidChangeOcclusionState",
	1058: "mac:WindowDidChangeOrderingMode",
	1059: "mac:WindowDidChangeScreen",
	1060: "mac:WindowDidChangeScreenParameters",
	1061: "mac:WindowDidChangeScreenProfile",
	1062: "mac:WindowDidChangeScreenSpace",
	1063: "mac:WindowDidChangeScreenSpaceProperties",
	1064: "mac:WindowDidChangeSharingType",
	1065: "mac:WindowDidChangeSpace",
	1066: "mac:WindowDidChangeSpaceOrderingMode",
	1067: "mac:WindowDidChangeTitle",
	1068: "mac:WindowDidChangeToolbar",
	1069: "mac:WindowDidChangeVisibility",
	1070: "mac:WindowDidDeminiaturize",
	1071: "mac:WindowDidEndSheet",
	1072: "mac:WindowDidEnterFullScreen",
	1073: "mac:WindowDidEnterVersionBrowser",
	1074: "mac:WindowDidExitFullScreen",
	1075: "mac:WindowDidExitVersionBrowser",
	1076: "mac:WindowDidExpose",
	1077: "mac:WindowDidFocus",
	1078: "mac:WindowDidMiniaturize",
	1079: "mac:WindowDidMove",
	1080: "mac:WindowDidOrderOffScreen",
	1081: "mac:WindowDidOrderOnScreen",
	1082: "mac:WindowDidResignKey",
	1083: "mac:WindowDidResignMain",
	1084: "mac:WindowDidResize",
	1085: "mac:WindowDidUpdate",
	1086: "mac:WindowDidUpdateAlpha",
	1087: "mac:WindowDidUpdateCollectionBehavior",
	1088: "mac:WindowDidUpdateCollectionProperties",
	1089: "mac:WindowDidUpdateShadow",
	1090: "mac:WindowDidUpdateTitle",
	1091: "mac:WindowDidUpdateToolbar",
	1092: "mac:WindowDidUpdateVisibility",
	1093: "mac:WindowShouldClose!",
	1094: "mac:WindowWillBecomeKey",
	1095: "mac:WindowWillBecomeMain",
	1096: "mac:WindowWillBeginSheet",
	1097: "mac:WindowWillChangeOrderingMode",
	1098: "mac:WindowWillClose",
	1099: "mac:WindowWillDeminiaturize",
	1100: "mac:WindowWillEnterFullScreen",
	1101: "mac:WindowWillEnterVersionBrowser",
	1102: "mac:WindowWillExitFullScreen",
	1103: "mac:WindowWillExitVersionBrowser",
	1104: "mac:WindowWillFocus",
	1105: "mac:WindowWillMiniaturize",
	1106: "mac:WindowWillMove",
	1107: "mac:WindowWillOrderOffScreen",
	1108: "mac:WindowWillOrderOnScreen",
	1109: "mac:WindowWillResignMain",
	1110: "mac:WindowWillResize",
	1111: "mac:WindowWillUnfocus",
	1112: "mac:WindowWillUpdate",
	1113: "mac:WindowWillUpdateAlpha",
	1114: "mac:WindowWillUpdateCollectionBehavior",
	1115: "mac:WindowWillUpdateCollectionProperties",
	1116: "mac:WindowWillUpdateShadow",
	1117: "mac:WindowWillUpdateTitle",
	1118: "mac:WindowWillUpdateToolbar",
	1119: "mac:WindowWillUpdateVisibility",
	1120: "mac:WindowWillUseStandardFrame",
	1121: "mac:MenuWillOpen",
	1122: "mac:MenuDidOpen",
	1123: "mac:MenuDidClose",
	1124: "mac:MenuWillSendAction",
	1125: "mac:MenuDidSendAction",
	1126: "mac:MenuWillHighlightItem",
	1127: "mac:MenuDidHighlightItem",
	1128: "mac:MenuWillDisplayItem",
	1129: "mac:MenuDidDisplayItem",
	1130: "mac:MenuWillAddItem",
	1131: "mac:MenuDidAddItem",
	1132: "mac:MenuWillRemoveItem",
	1133: "mac:MenuDidRemoveItem",
	1134: "mac:MenuWillBeginTracking",
	1135: "mac:MenuDidBeginTracking",
	1136: "mac:MenuWillEndTracking",
	1137: "mac:MenuDidEndTracking",
	1138: "mac:MenuWillUpdate",
	1139: "mac:MenuDidUpdate",
	1140: "mac:MenuWillPopUp",
	1141: "mac:MenuDidPopUp",
	1142: "mac:MenuWillSendActionToItem",
	1143: "mac:MenuDidSendActionToItem",
	1144: "mac:WebViewDidStartProvisionalNavigation",
	1145: "mac:WebViewDidReceiveServerRedirectForProvisionalNavigation",
	1146: "mac:WebViewDidFinishNavigation",
	1147: "mac:WebViewDidCommitNavigation",
	1148: "mac:WindowFileDraggingEntered",
	1149: "mac:WindowFileDraggingPerformed",
	1150: "mac:WindowFileDraggingExited",
	1151: "windows:SystemThemeChanged",
	1152: "windows:APMPowerStatusChange",
	1153: "windows:APMSuspend",
	1154: "windows:APMResumeAutomatic",
	1155: "windows:APMResumeSuspend",
	1156: "windows:APMPowerSettingChange",
	1157: "windows:ApplicationStarted",
	1158: "windows:WebViewNavigationCompleted",
	1159: "windows:WindowInactive",
	1160: "windows:WindowActive",
	1161: "windows:WindowClickActive",
	1162: "windows:WindowMaximise",
	1163: "windows:WindowUnMaximise",
	1164: "windows:WindowFullscreen",
	1165: "windows:WindowUnFullscreen",
	1166: "windows:WindowRestore",
	1167: "windows:WindowMinimise",
	1168: "windows:WindowUnMinimise",
	1169: "windows:WindowClose",
	1170: "windows:WindowSetFocus",
	1171: "windows:WindowKillFocus",
	1172: "windows:WindowDragDrop",
	1173: "windows:WindowDragEnter",
	1174: "windows:WindowDragLeave",
	1175: "windows:WindowDragOver",
	1176: "common:ApplicationStarted",
	1177: "common:WindowMaximise",
	1178: "common:WindowUnMaximise",
	1179: "common:WindowFullscreen",
	1180: "common:WindowUnFullscreen",
	1181: "common:WindowRestore",
	1182: "common:WindowMinimise",
	1183: "common:WindowUnMinimise",
	1184: "common:WindowClosing",
	1185: "common:WindowZoom",
	1186: "common:WindowZoomIn",
	1187: "common:WindowZoomOut",
	1188: "common:WindowZoomReset",
	1189: "common:WindowFocus",
	1190: "common:WindowLostFocus",
	1191: "common:WindowShow",
	1192: "common:WindowHide",
	1193: "common:WindowDPIChanged",
	1194: "common:WindowFilesDropped",
	1195: "common:ThemeChanged",
}

