//go:build darwin

/*
 _	   __	  _ __
| |	 / /___ _(_) /____
| | /| / / __ `/ / / ___/
| |/ |/ / /_/ / / (__  )
|__/|__/\__,_/_/_/____/
The electron alternative for Go
(c) Lea Anthony 2019-present
*/

// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

#ifndef _events_h
#define _events_h

extern void processApplicationEvent(unsigned int, void* data);
extern void processWindowEvent(unsigned int, unsigned int);

#define EventApplicationDidBecomeActive 1063
#define EventApplicationDidChangeBackingProperties 1064
#define EventApplicationDidChangeEffectiveAppearance 1065
#define EventApplicationDidChangeIcon 1066
#define EventApplicationDidChangeOcclusionState 1067
#define EventApplicationDidChangeScreenParameters 1068
#define EventApplicationDidChangeStatusBarFrame 1069
#define EventApplicationDidChangeStatusBarOrientation 1070
#define EventApplicationDidChangeTheme 1071
#define EventApplicationDidFinishLaunching 1072
#define EventApplicationDidHide 1073
#define EventApplicationDidResignActive 1074
#define EventApplicationDidUnhide 1075
#define EventApplicationDidUpdate 1076
#define EventApplicationShouldHandleReopen 1077
#define EventApplicationWillBecomeActive 1078
#define EventApplicationWillFinishLaunching 1079
#define EventApplicationWillHide 1080
#define EventApplicationWillResignActive 1081
#define EventApplicationWillTerminate 1082
#define EventApplicationWillUnhide 1083
#define EventApplicationWillUpdate 1084
#define EventMenuDidAddItem 1085
#define EventMenuDidBeginTracking 1086
#define EventMenuDidClose 1087
#define EventMenuDidDisplayItem 1088
#define EventMenuDidEndTracking 1089
#define EventMenuDidHighlightItem 1090
#define EventMenuDidOpen 1091
#define EventMenuDidPopUp 1092
#define EventMenuDidRemoveItem 1093
#define EventMenuDidSendAction 1094
#define EventMenuDidSendActionToItem 1095
#define EventMenuDidUpdate 1096
#define EventMenuWillAddItem 1097
#define EventMenuWillBeginTracking 1098
#define EventMenuWillDisplayItem 1099
#define EventMenuWillEndTracking 1100
#define EventMenuWillHighlightItem 1101
#define EventMenuWillOpen 1102
#define EventMenuWillPopUp 1103
#define EventMenuWillRemoveItem 1104
#define EventMenuWillSendAction 1105
#define EventMenuWillSendActionToItem 1106
#define EventMenuWillUpdate 1107
#define EventWebViewDidCommitNavigation 1108
#define EventWebViewDidFinishNavigation 1109
#define EventWebViewDidReceiveServerRedirectForProvisionalNavigation 1110
#define EventWebViewDidStartProvisionalNavigation 1111
#define EventWindowDidBecomeKey 1112
#define EventWindowDidBecomeMain 1113
#define EventWindowDidBeginSheet 1114
#define EventWindowDidChangeAlpha 1115
#define EventWindowDidChangeBackingLocation 1116
#define EventWindowDidChangeBackingProperties 1117
#define EventWindowDidChangeCollectionBehavior 1118
#define EventWindowDidChangeEffectiveAppearance 1119
#define EventWindowDidChangeOcclusionState 1120
#define EventWindowDidChangeOrderingMode 1121
#define EventWindowDidChangeScreen 1122
#define EventWindowDidChangeScreenParameters 1123
#define EventWindowDidChangeScreenProfile 1124
#define EventWindowDidChangeScreenSpace 1125
#define EventWindowDidChangeScreenSpaceProperties 1126
#define EventWindowDidChangeSharingType 1127
#define EventWindowDidChangeSpace 1128
#define EventWindowDidChangeSpaceOrderingMode 1129
#define EventWindowDidChangeTitle 1130
#define EventWindowDidChangeToolbar 1131
#define EventWindowDidDeminiaturize 1132
#define EventWindowDidEndSheet 1133
#define EventWindowDidEnterFullScreen 1134
#define EventWindowDidEnterVersionBrowser 1135
#define EventWindowDidExitFullScreen 1136
#define EventWindowDidExitVersionBrowser 1137
#define EventWindowDidExpose 1138
#define EventWindowDidFocus 1139
#define EventWindowDidMiniaturize 1140
#define EventWindowDidMove 1141
#define EventWindowDidOrderOffScreen 1142
#define EventWindowDidOrderOnScreen 1143
#define EventWindowDidResignKey 1144
#define EventWindowDidResignMain 1145
#define EventWindowDidResize 1146
#define EventWindowDidUpdate 1147
#define EventWindowDidUpdateAlpha 1148
#define EventWindowDidUpdateCollectionBehavior 1149
#define EventWindowDidUpdateCollectionProperties 1150
#define EventWindowDidUpdateShadow 1151
#define EventWindowDidUpdateTitle 1152
#define EventWindowDidUpdateToolbar 1153
#define EventWindowDidZoom 1154
#define EventWindowFileDraggingEntered 1155
#define EventWindowFileDraggingExited 1156
#define EventWindowFileDraggingPerformed 1157
#define EventWindowHide 1158
#define EventWindowMaximise 1159
#define EventWindowUnMaximise 1160
#define EventWindowMinimise 1161
#define EventWindowUnMinimise 1162
#define EventWindowShouldClose 1163
#define EventWindowShow 1164
#define EventWindowWillBecomeKey 1165
#define EventWindowWillBecomeMain 1166
#define EventWindowWillBeginSheet 1167
#define EventWindowWillChangeOrderingMode 1168
#define EventWindowWillClose 1169
#define EventWindowWillDeminiaturize 1170
#define EventWindowWillEnterFullScreen 1171
#define EventWindowWillEnterVersionBrowser 1172
#define EventWindowWillExitFullScreen 1173
#define EventWindowWillExitVersionBrowser 1174
#define EventWindowWillFocus 1175
#define EventWindowWillMiniaturize 1176
#define EventWindowWillMove 1177
#define EventWindowWillOrderOffScreen 1178
#define EventWindowWillOrderOnScreen 1179
#define EventWindowWillResignMain 1180
#define EventWindowWillResize 1181
#define EventWindowWillUnfocus 1182
#define EventWindowWillUpdate 1183
#define EventWindowWillUpdateAlpha 1184
#define EventWindowWillUpdateCollectionBehavior 1185
#define EventWindowWillUpdateCollectionProperties 1186
#define EventWindowWillUpdateShadow 1187
#define EventWindowWillUpdateTitle 1188
#define EventWindowWillUpdateToolbar 1189
#define EventWindowWillUpdateVisibility 1190
#define EventWindowWillUseStandardFrame 1191
#define EventWindowZoomIn 1192
#define EventWindowZoomOut 1193
#define EventWindowZoomReset 1194

#define MAX_EVENTS 1195


#endif