package events

type ApplicationEventType uint
type WindowEventType uint

var Common = newCommonEvents()

type commonEvents struct {
	ApplicationOpenedWithFile ApplicationEventType
	ApplicationStarted        ApplicationEventType
	ThemeChanged              ApplicationEventType
	WindowClosing             WindowEventType
	WindowDidMove             WindowEventType
	WindowDidResize           WindowEventType
	WindowDPIChanged          WindowEventType
	WindowFilesDropped        WindowEventType
	WindowFocus               WindowEventType
	WindowFullscreen          WindowEventType
	WindowHide                WindowEventType
	WindowLostFocus           WindowEventType
	WindowMaximise            WindowEventType
	WindowMinimise            WindowEventType
	WindowRestore             WindowEventType
	WindowRuntimeReady        WindowEventType
	WindowShow                WindowEventType
	WindowUnFullscreen        WindowEventType
	WindowUnMaximise          WindowEventType
	WindowUnMinimise          WindowEventType
	WindowZoom                WindowEventType
	WindowZoomIn              WindowEventType
	WindowZoomOut             WindowEventType
	WindowZoomReset           WindowEventType
}

func newCommonEvents() commonEvents {
	return commonEvents{
		ApplicationOpenedWithFile: 1024,
		ApplicationStarted:        1025,
		ThemeChanged:              1026,
		WindowClosing:             1027,
		WindowDidMove:             1028,
		WindowDidResize:           1029,
		WindowDPIChanged:          1030,
		WindowFilesDropped:        1031,
		WindowFocus:               1032,
		WindowFullscreen:          1033,
		WindowHide:                1034,
		WindowLostFocus:           1035,
		WindowMaximise:            1036,
		WindowMinimise:            1037,
		WindowRestore:             1038,
		WindowRuntimeReady:        1039,
		WindowShow:                1040,
		WindowUnFullscreen:        1041,
		WindowUnMaximise:          1042,
		WindowUnMinimise:          1043,
		WindowZoom:                1044,
		WindowZoomIn:              1045,
		WindowZoomOut:             1046,
		WindowZoomReset:           1047,
	}
}

var Linux = newLinuxEvents()

type linuxEvents struct {
	ApplicationStartup ApplicationEventType
	SystemThemeChanged ApplicationEventType
	WindowDeleteEvent  WindowEventType
	WindowDidMove      WindowEventType
	WindowDidResize    WindowEventType
	WindowFocusIn      WindowEventType
	WindowFocusOut     WindowEventType
	WindowLoadChanged  WindowEventType
}

func newLinuxEvents() linuxEvents {
	return linuxEvents{
		ApplicationStartup: 1048,
		SystemThemeChanged: 1049,
		WindowDeleteEvent:  1050,
		WindowDidMove:      1051,
		WindowDidResize:    1052,
		WindowFocusIn:      1053,
		WindowFocusOut:     1054,
		WindowLoadChanged:  1055,
	}
}

var Mac = newMacEvents()

type macEvents struct {
	ApplicationDidBecomeActive                              ApplicationEventType
	ApplicationDidChangeBackingProperties                   ApplicationEventType
	ApplicationDidChangeEffectiveAppearance                 ApplicationEventType
	ApplicationDidChangeIcon                                ApplicationEventType
	ApplicationDidChangeOcclusionState                      ApplicationEventType
	ApplicationDidChangeScreenParameters                    ApplicationEventType
	ApplicationDidChangeStatusBarFrame                      ApplicationEventType
	ApplicationDidChangeStatusBarOrientation                ApplicationEventType
	ApplicationDidChangeTheme                               ApplicationEventType
	ApplicationDidFinishLaunching                           ApplicationEventType
	ApplicationDidHide                                      ApplicationEventType
	ApplicationDidResignActiveNotification                  ApplicationEventType
	ApplicationDidUnhide                                    ApplicationEventType
	ApplicationDidUpdate                                    ApplicationEventType
	ApplicationShouldHandleReopen                           ApplicationEventType
	ApplicationWillBecomeActive                             ApplicationEventType
	ApplicationWillFinishLaunching                          ApplicationEventType
	ApplicationWillHide                                     ApplicationEventType
	ApplicationWillResignActive                             ApplicationEventType
	ApplicationWillTerminate                                ApplicationEventType
	ApplicationWillUnhide                                   ApplicationEventType
	ApplicationWillUpdate                                   ApplicationEventType
	MenuDidAddItem                                          ApplicationEventType
	MenuDidBeginTracking                                    ApplicationEventType
	MenuDidClose                                            ApplicationEventType
	MenuDidDisplayItem                                      ApplicationEventType
	MenuDidEndTracking                                      ApplicationEventType
	MenuDidHighlightItem                                    ApplicationEventType
	MenuDidOpen                                             ApplicationEventType
	MenuDidPopUp                                            ApplicationEventType
	MenuDidRemoveItem                                       ApplicationEventType
	MenuDidSendAction                                       ApplicationEventType
	MenuDidSendActionToItem                                 ApplicationEventType
	MenuDidUpdate                                           ApplicationEventType
	MenuWillAddItem                                         ApplicationEventType
	MenuWillBeginTracking                                   ApplicationEventType
	MenuWillDisplayItem                                     ApplicationEventType
	MenuWillEndTracking                                     ApplicationEventType
	MenuWillHighlightItem                                   ApplicationEventType
	MenuWillOpen                                            ApplicationEventType
	MenuWillPopUp                                           ApplicationEventType
	MenuWillRemoveItem                                      ApplicationEventType
	MenuWillSendAction                                      ApplicationEventType
	MenuWillSendActionToItem                                ApplicationEventType
	MenuWillUpdate                                          ApplicationEventType
	WebViewDidCommitNavigation                              WindowEventType
	WebViewDidFinishNavigation                              WindowEventType
	WebViewDidReceiveServerRedirectForProvisionalNavigation WindowEventType
	WebViewDidStartProvisionalNavigation                    WindowEventType
	WindowDidBecomeKey                                      WindowEventType
	WindowDidBecomeMain                                     WindowEventType
	WindowDidBeginSheet                                     WindowEventType
	WindowDidChangeAlpha                                    WindowEventType
	WindowDidChangeBackingLocation                          WindowEventType
	WindowDidChangeBackingProperties                        WindowEventType
	WindowDidChangeCollectionBehavior                       WindowEventType
	WindowDidChangeEffectiveAppearance                      WindowEventType
	WindowDidChangeOcclusionState                           WindowEventType
	WindowDidChangeOrderingMode                             WindowEventType
	WindowDidChangeScreen                                   WindowEventType
	WindowDidChangeScreenParameters                         WindowEventType
	WindowDidChangeScreenProfile                            WindowEventType
	WindowDidChangeScreenSpace                              WindowEventType
	WindowDidChangeScreenSpaceProperties                    WindowEventType
	WindowDidChangeSharingType                              WindowEventType
	WindowDidChangeSpace                                    WindowEventType
	WindowDidChangeSpaceOrderingMode                        WindowEventType
	WindowDidChangeTitle                                    WindowEventType
	WindowDidChangeToolbar                                  WindowEventType
	WindowDidDeminiaturize                                  WindowEventType
	WindowDidEndSheet                                       WindowEventType
	WindowDidEnterFullScreen                                WindowEventType
	WindowDidEnterVersionBrowser                            WindowEventType
	WindowDidExitFullScreen                                 WindowEventType
	WindowDidExitVersionBrowser                             WindowEventType
	WindowDidExpose                                         WindowEventType
	WindowDidFocus                                          WindowEventType
	WindowDidMiniaturize                                    WindowEventType
	WindowDidMove                                           WindowEventType
	WindowDidOrderOffScreen                                 WindowEventType
	WindowDidOrderOnScreen                                  WindowEventType
	WindowDidResignKey                                      WindowEventType
	WindowDidResignMain                                     WindowEventType
	WindowDidResize                                         WindowEventType
	WindowDidUpdate                                         WindowEventType
	WindowDidUpdateAlpha                                    WindowEventType
	WindowDidUpdateCollectionBehavior                       WindowEventType
	WindowDidUpdateCollectionProperties                     WindowEventType
	WindowDidUpdateShadow                                   WindowEventType
	WindowDidUpdateTitle                                    WindowEventType
	WindowDidUpdateToolbar                                  WindowEventType
	WindowDidZoom                                           WindowEventType
	WindowFileDraggingEntered                               WindowEventType
	WindowFileDraggingExited                                WindowEventType
	WindowFileDraggingPerformed                             WindowEventType
	WindowHide                                              WindowEventType
	WindowMaximize                                          WindowEventType
	WindowShouldClose                                       WindowEventType
	WindowShow                                              WindowEventType
	WindowUnMaximise                                        WindowEventType
	WindowWillBecomeKey                                     WindowEventType
	WindowWillBecomeMain                                    WindowEventType
	WindowWillBeginSheet                                    WindowEventType
	WindowWillChangeOrderingMode                            WindowEventType
	WindowWillClose                                         WindowEventType
	WindowWillDeminiaturize                                 WindowEventType
	WindowWillEnterFullScreen                               WindowEventType
	WindowWillEnterVersionBrowser                           WindowEventType
	WindowWillExitFullScreen                                WindowEventType
	WindowWillExitVersionBrowser                            WindowEventType
	WindowWillFocus                                         WindowEventType
	WindowWillMiniaturize                                   WindowEventType
	WindowWillMove                                          WindowEventType
	WindowWillOrderOffScreen                                WindowEventType
	WindowWillOrderOnScreen                                 WindowEventType
	WindowWillResignMain                                    WindowEventType
	WindowWillResize                                        WindowEventType
	WindowWillUnfocus                                       WindowEventType
	WindowWillUpdate                                        WindowEventType
	WindowWillUpdateAlpha                                   WindowEventType
	WindowWillUpdateCollectionBehavior                      WindowEventType
	WindowWillUpdateCollectionProperties                    WindowEventType
	WindowWillUpdateShadow                                  WindowEventType
	WindowWillUpdateTitle                                   WindowEventType
	WindowWillUpdateToolbar                                 WindowEventType
	WindowWillUpdateVisibility                              WindowEventType
	WindowWillUseStandardFrame                              WindowEventType
	WindowZoomIn                                            WindowEventType
	WindowZoomOut                                           WindowEventType
	WindowZoomReset                                         WindowEventType
}

func newMacEvents() macEvents {
	return macEvents{
		ApplicationDidBecomeActive:               1056,
		ApplicationDidChangeBackingProperties:    1057,
		ApplicationDidChangeEffectiveAppearance:  1058,
		ApplicationDidChangeIcon:                 1059,
		ApplicationDidChangeOcclusionState:       1060,
		ApplicationDidChangeScreenParameters:     1061,
		ApplicationDidChangeStatusBarFrame:       1062,
		ApplicationDidChangeStatusBarOrientation: 1063,
		ApplicationDidChangeTheme:                1064,
		ApplicationDidFinishLaunching:            1065,
		ApplicationDidHide:                       1066,
		ApplicationDidResignActiveNotification:   1067,
		ApplicationDidUnhide:                     1068,
		ApplicationDidUpdate:                     1069,
		ApplicationShouldHandleReopen:            1070,
		ApplicationWillBecomeActive:              1071,
		ApplicationWillFinishLaunching:           1072,
		ApplicationWillHide:                      1073,
		ApplicationWillResignActive:              1074,
		ApplicationWillTerminate:                 1075,
		ApplicationWillUnhide:                    1076,
		ApplicationWillUpdate:                    1077,
		MenuDidAddItem:                           1078,
		MenuDidBeginTracking:                     1079,
		MenuDidClose:                             1080,
		MenuDidDisplayItem:                       1081,
		MenuDidEndTracking:                       1082,
		MenuDidHighlightItem:                     1083,
		MenuDidOpen:                              1084,
		MenuDidPopUp:                             1085,
		MenuDidRemoveItem:                        1086,
		MenuDidSendAction:                        1087,
		MenuDidSendActionToItem:                  1088,
		MenuDidUpdate:                            1089,
		MenuWillAddItem:                          1090,
		MenuWillBeginTracking:                    1091,
		MenuWillDisplayItem:                      1092,
		MenuWillEndTracking:                      1093,
		MenuWillHighlightItem:                    1094,
		MenuWillOpen:                             1095,
		MenuWillPopUp:                            1096,
		MenuWillRemoveItem:                       1097,
		MenuWillSendAction:                       1098,
		MenuWillSendActionToItem:                 1099,
		MenuWillUpdate:                           1100,
		WebViewDidCommitNavigation:               1101,
		WebViewDidFinishNavigation:               1102,
		WebViewDidReceiveServerRedirectForProvisionalNavigation: 1103,
		WebViewDidStartProvisionalNavigation:                    1104,
		WindowDidBecomeKey:                                      1105,
		WindowDidBecomeMain:                                     1106,
		WindowDidBeginSheet:                                     1107,
		WindowDidChangeAlpha:                                    1108,
		WindowDidChangeBackingLocation:                          1109,
		WindowDidChangeBackingProperties:                        1110,
		WindowDidChangeCollectionBehavior:                       1111,
		WindowDidChangeEffectiveAppearance:                      1112,
		WindowDidChangeOcclusionState:                           1113,
		WindowDidChangeOrderingMode:                             1114,
		WindowDidChangeScreen:                                   1115,
		WindowDidChangeScreenParameters:                         1116,
		WindowDidChangeScreenProfile:                            1117,
		WindowDidChangeScreenSpace:                              1118,
		WindowDidChangeScreenSpaceProperties:                    1119,
		WindowDidChangeSharingType:                              1120,
		WindowDidChangeSpace:                                    1121,
		WindowDidChangeSpaceOrderingMode:                        1122,
		WindowDidChangeTitle:                                    1123,
		WindowDidChangeToolbar:                                  1124,
		WindowDidDeminiaturize:                                  1125,
		WindowDidEndSheet:                                       1126,
		WindowDidEnterFullScreen:                                1127,
		WindowDidEnterVersionBrowser:                            1128,
		WindowDidExitFullScreen:                                 1129,
		WindowDidExitVersionBrowser:                             1130,
		WindowDidExpose:                                         1131,
		WindowDidFocus:                                          1132,
		WindowDidMiniaturize:                                    1133,
		WindowDidMove:                                           1134,
		WindowDidOrderOffScreen:                                 1135,
		WindowDidOrderOnScreen:                                  1136,
		WindowDidResignKey:                                      1137,
		WindowDidResignMain:                                     1138,
		WindowDidResize:                                         1139,
		WindowDidUpdate:                                         1140,
		WindowDidUpdateAlpha:                                    1141,
		WindowDidUpdateCollectionBehavior:                       1142,
		WindowDidUpdateCollectionProperties:                     1143,
		WindowDidUpdateShadow:                                   1144,
		WindowDidUpdateTitle:                                    1145,
		WindowDidUpdateToolbar:                                  1146,
		WindowDidZoom:                                           1147,
		WindowFileDraggingEntered:                               1148,
		WindowFileDraggingExited:                                1149,
		WindowFileDraggingPerformed:                             1150,
		WindowHide:                                              1151,
		WindowMaximize:                                          1152,
		WindowShouldClose:                                       1153,
		WindowShow:                                              1154,
		WindowUnMaximise:                                        1155,
		WindowWillBecomeKey:                                     1156,
		WindowWillBecomeMain:                                    1157,
		WindowWillBeginSheet:                                    1158,
		WindowWillChangeOrderingMode:                            1159,
		WindowWillClose:                                         1160,
		WindowWillDeminiaturize:                                 1161,
		WindowWillEnterFullScreen:                               1162,
		WindowWillEnterVersionBrowser:                           1163,
		WindowWillExitFullScreen:                                1164,
		WindowWillExitVersionBrowser:                            1165,
		WindowWillFocus:                                         1166,
		WindowWillMiniaturize:                                   1167,
		WindowWillMove:                                          1168,
		WindowWillOrderOffScreen:                                1169,
		WindowWillOrderOnScreen:                                 1170,
		WindowWillResignMain:                                    1171,
		WindowWillResize:                                        1172,
		WindowWillUnfocus:                                       1173,
		WindowWillUpdate:                                        1174,
		WindowWillUpdateAlpha:                                   1175,
		WindowWillUpdateCollectionBehavior:                      1176,
		WindowWillUpdateCollectionProperties:                    1177,
		WindowWillUpdateShadow:                                  1178,
		WindowWillUpdateTitle:                                   1179,
		WindowWillUpdateToolbar:                                 1180,
		WindowWillUpdateVisibility:                              1181,
		WindowWillUseStandardFrame:                              1182,
		WindowZoomIn:                                            1183,
		WindowZoomOut:                                           1184,
		WindowZoomReset:                                         1185,
	}
}

var Windows = newWindowsEvents()

type windowsEvents struct {
	APMPowerSettingChange      ApplicationEventType
	APMPowerStatusChange       ApplicationEventType
	APMResumeAutomatic         ApplicationEventType
	APMResumeSuspend           ApplicationEventType
	APMSuspend                 ApplicationEventType
	ApplicationStarted         ApplicationEventType
	SystemThemeChanged         ApplicationEventType
	WebViewNavigationCompleted WindowEventType
	WindowActive               WindowEventType
	WindowBackgroundErase      WindowEventType
	WindowClickActive          WindowEventType
	WindowClosing              WindowEventType
	WindowDidMove              WindowEventType
	WindowDidResize            WindowEventType
	WindowDPIChanged           WindowEventType
	WindowDragDrop             WindowEventType
	WindowDragEnter            WindowEventType
	WindowDragLeave            WindowEventType
	WindowDragOver             WindowEventType
	WindowEndMove              WindowEventType
	WindowEndResize            WindowEventType
	WindowFullscreen           WindowEventType
	WindowHide                 WindowEventType
	WindowInactive             WindowEventType
	WindowKeyDown              WindowEventType
	WindowKeyUp                WindowEventType
	WindowKillFocus            WindowEventType
	WindowMaximise             WindowEventType
	WindowMinimise             WindowEventType
	WindowNonClientHit         WindowEventType
	WindowNonClientMouseDown   WindowEventType
	WindowNonClientMouseLeave  WindowEventType
	WindowNonClientMouseMove   WindowEventType
	WindowNonClientMouseUp     WindowEventType
	WindowPaint                WindowEventType
	WindowRestore              WindowEventType
	WindowSetFocus             WindowEventType
	WindowShow                 WindowEventType
	WindowStartMove            WindowEventType
	WindowStartResize          WindowEventType
	WindowUnFullscreen         WindowEventType
	WindowUnMaximise           WindowEventType
	WindowUnMinimise           WindowEventType
	WindowZOrderChanged        WindowEventType
}

func newWindowsEvents() windowsEvents {
	return windowsEvents{
		APMPowerSettingChange:      1186,
		APMPowerStatusChange:       1187,
		APMResumeAutomatic:         1188,
		APMResumeSuspend:           1189,
		APMSuspend:                 1190,
		ApplicationStarted:         1191,
		SystemThemeChanged:         1192,
		WebViewNavigationCompleted: 1193,
		WindowActive:               1194,
		WindowBackgroundErase:      1195,
		WindowClickActive:          1196,
		WindowClosing:              1197,
		WindowDidMove:              1198,
		WindowDidResize:            1199,
		WindowDPIChanged:           1200,
		WindowDragDrop:             1201,
		WindowDragEnter:            1202,
		WindowDragLeave:            1203,
		WindowDragOver:             1204,
		WindowEndMove:              1205,
		WindowEndResize:            1206,
		WindowFullscreen:           1207,
		WindowHide:                 1208,
		WindowInactive:             1209,
		WindowKeyDown:              1210,
		WindowKeyUp:                1211,
		WindowKillFocus:            1212,
		WindowMaximise:             1213,
		WindowMinimise:             1214,
		WindowNonClientHit:         1215,
		WindowNonClientMouseDown:   1216,
		WindowNonClientMouseLeave:  1217,
		WindowNonClientMouseMove:   1218,
		WindowNonClientMouseUp:     1219,
		WindowPaint:                1220,
		WindowRestore:              1221,
		WindowSetFocus:             1222,
		WindowShow:                 1223,
		WindowStartMove:            1224,
		WindowStartResize:          1225,
		WindowUnFullscreen:         1226,
		WindowUnMaximise:           1227,
		WindowUnMinimise:           1228,
		WindowZOrderChanged:        1229,
	}
}

func JSEvent(event uint) string {
	return eventToJS[event]
}

var eventToJS = map[uint]string{
	1024: "common:ApplicationOpenedWithFile",
	1025: "common:ApplicationStarted",
	1026: "common:ThemeChanged",
	1027: "common:WindowClosing",
	1028: "common:WindowDidMove",
	1029: "common:WindowDidResize",
	1030: "common:WindowDPIChanged",
	1031: "common:WindowFilesDropped",
	1032: "common:WindowFocus",
	1033: "common:WindowFullscreen",
	1034: "common:WindowHide",
	1035: "common:WindowLostFocus",
	1036: "common:WindowMaximise",
	1037: "common:WindowMinimise",
	1038: "common:WindowRestore",
	1039: "common:WindowRuntimeReady",
	1040: "common:WindowShow",
	1041: "common:WindowUnFullscreen",
	1042: "common:WindowUnMaximise",
	1043: "common:WindowUnMinimise",
	1044: "common:WindowZoom",
	1045: "common:WindowZoomIn",
	1046: "common:WindowZoomOut",
	1047: "common:WindowZoomReset",
	1048: "linux:ApplicationStartup",
	1049: "linux:SystemThemeChanged",
	1050: "linux:WindowDeleteEvent",
	1051: "linux:WindowDidMove",
	1052: "linux:WindowDidResize",
	1053: "linux:WindowFocusIn",
	1054: "linux:WindowFocusOut",
	1055: "linux:WindowLoadChanged",
	1056: "mac:ApplicationDidBecomeActive",
	1057: "mac:ApplicationDidChangeBackingProperties",
	1058: "mac:ApplicationDidChangeEffectiveAppearance",
	1059: "mac:ApplicationDidChangeIcon",
	1060: "mac:ApplicationDidChangeOcclusionState",
	1061: "mac:ApplicationDidChangeScreenParameters",
	1062: "mac:ApplicationDidChangeStatusBarFrame",
	1063: "mac:ApplicationDidChangeStatusBarOrientation",
	1064: "mac:ApplicationDidChangeTheme!",
	1065: "mac:ApplicationDidFinishLaunching",
	1066: "mac:ApplicationDidHide",
	1067: "mac:ApplicationDidResignActiveNotification",
	1068: "mac:ApplicationDidUnhide",
	1069: "mac:ApplicationDidUpdate",
	1070: "mac:ApplicationShouldHandleReopen!",
	1071: "mac:ApplicationWillBecomeActive",
	1072: "mac:ApplicationWillFinishLaunching",
	1073: "mac:ApplicationWillHide",
	1074: "mac:ApplicationWillResignActive",
	1075: "mac:ApplicationWillTerminate",
	1076: "mac:ApplicationWillUnhide",
	1077: "mac:ApplicationWillUpdate",
	1078: "mac:MenuDidAddItem",
	1079: "mac:MenuDidBeginTracking",
	1080: "mac:MenuDidClose",
	1081: "mac:MenuDidDisplayItem",
	1082: "mac:MenuDidEndTracking",
	1083: "mac:MenuDidHighlightItem",
	1084: "mac:MenuDidOpen",
	1085: "mac:MenuDidPopUp",
	1086: "mac:MenuDidRemoveItem",
	1087: "mac:MenuDidSendAction",
	1088: "mac:MenuDidSendActionToItem",
	1089: "mac:MenuDidUpdate",
	1090: "mac:MenuWillAddItem",
	1091: "mac:MenuWillBeginTracking",
	1092: "mac:MenuWillDisplayItem",
	1093: "mac:MenuWillEndTracking",
	1094: "mac:MenuWillHighlightItem",
	1095: "mac:MenuWillOpen",
	1096: "mac:MenuWillPopUp",
	1097: "mac:MenuWillRemoveItem",
	1098: "mac:MenuWillSendAction",
	1099: "mac:MenuWillSendActionToItem",
	1100: "mac:MenuWillUpdate",
	1101: "mac:WebViewDidCommitNavigation",
	1102: "mac:WebViewDidFinishNavigation",
	1103: "mac:WebViewDidReceiveServerRedirectForProvisionalNavigation",
	1104: "mac:WebViewDidStartProvisionalNavigation",
	1105: "mac:WindowDidBecomeKey",
	1106: "mac:WindowDidBecomeMain",
	1107: "mac:WindowDidBeginSheet",
	1108: "mac:WindowDidChangeAlpha",
	1109: "mac:WindowDidChangeBackingLocation",
	1110: "mac:WindowDidChangeBackingProperties",
	1111: "mac:WindowDidChangeCollectionBehavior",
	1112: "mac:WindowDidChangeEffectiveAppearance",
	1113: "mac:WindowDidChangeOcclusionState",
	1114: "mac:WindowDidChangeOrderingMode",
	1115: "mac:WindowDidChangeScreen",
	1116: "mac:WindowDidChangeScreenParameters",
	1117: "mac:WindowDidChangeScreenProfile",
	1118: "mac:WindowDidChangeScreenSpace",
	1119: "mac:WindowDidChangeScreenSpaceProperties",
	1120: "mac:WindowDidChangeSharingType",
	1121: "mac:WindowDidChangeSpace",
	1122: "mac:WindowDidChangeSpaceOrderingMode",
	1123: "mac:WindowDidChangeTitle",
	1124: "mac:WindowDidChangeToolbar",
	1125: "mac:WindowDidDeminiaturize",
	1126: "mac:WindowDidEndSheet",
	1127: "mac:WindowDidEnterFullScreen",
	1128: "mac:WindowDidEnterVersionBrowser",
	1129: "mac:WindowDidExitFullScreen",
	1130: "mac:WindowDidExitVersionBrowser",
	1131: "mac:WindowDidExpose",
	1132: "mac:WindowDidFocus",
	1133: "mac:WindowDidMiniaturize",
	1134: "mac:WindowDidMove",
	1135: "mac:WindowDidOrderOffScreen",
	1136: "mac:WindowDidOrderOnScreen",
	1137: "mac:WindowDidResignKey",
	1138: "mac:WindowDidResignMain",
	1139: "mac:WindowDidResize",
	1140: "mac:WindowDidUpdate",
	1141: "mac:WindowDidUpdateAlpha",
	1142: "mac:WindowDidUpdateCollectionBehavior",
	1143: "mac:WindowDidUpdateCollectionProperties",
	1144: "mac:WindowDidUpdateShadow",
	1145: "mac:WindowDidUpdateTitle",
	1146: "mac:WindowDidUpdateToolbar",
	1147: "mac:WindowDidZoom!",
	1148: "mac:WindowFileDraggingEntered",
	1149: "mac:WindowFileDraggingExited",
	1150: "mac:WindowFileDraggingPerformed",
	1151: "mac:WindowHide",
	1152: "mac:WindowMaximize",
	1153: "mac:WindowShouldClose!",
	1154: "mac:WindowShow",
	1155: "mac:WindowUnMaximise",
	1156: "mac:WindowWillBecomeKey",
	1157: "mac:WindowWillBecomeMain",
	1158: "mac:WindowWillBeginSheet",
	1159: "mac:WindowWillChangeOrderingMode",
	1160: "mac:WindowWillClose",
	1161: "mac:WindowWillDeminiaturize",
	1162: "mac:WindowWillEnterFullScreen",
	1163: "mac:WindowWillEnterVersionBrowser",
	1164: "mac:WindowWillExitFullScreen",
	1165: "mac:WindowWillExitVersionBrowser",
	1166: "mac:WindowWillFocus",
	1167: "mac:WindowWillMiniaturize",
	1168: "mac:WindowWillMove",
	1169: "mac:WindowWillOrderOffScreen",
	1170: "mac:WindowWillOrderOnScreen",
	1171: "mac:WindowWillResignMain",
	1172: "mac:WindowWillResize",
	1173: "mac:WindowWillUnfocus",
	1174: "mac:WindowWillUpdate",
	1175: "mac:WindowWillUpdateAlpha",
	1176: "mac:WindowWillUpdateCollectionBehavior",
	1177: "mac:WindowWillUpdateCollectionProperties",
	1178: "mac:WindowWillUpdateShadow",
	1179: "mac:WindowWillUpdateTitle",
	1180: "mac:WindowWillUpdateToolbar",
	1181: "mac:WindowWillUpdateVisibility",
	1182: "mac:WindowWillUseStandardFrame",
	1183: "mac:WindowZoomIn!",
	1184: "mac:WindowZoomOut!",
	1185: "mac:WindowZoomReset!",
	1186: "windows:APMPowerSettingChange",
	1187: "windows:APMPowerStatusChange",
	1188: "windows:APMResumeAutomatic",
	1189: "windows:APMResumeSuspend",
	1190: "windows:APMSuspend",
	1191: "windows:ApplicationStarted",
	1192: "windows:SystemThemeChanged",
	1193: "windows:WebViewNavigationCompleted",
	1194: "windows:WindowActive",
	1195: "windows:WindowBackgroundErase",
	1196: "windows:WindowClickActive",
	1197: "windows:WindowClosing",
	1198: "windows:WindowDidMove",
	1199: "windows:WindowDidResize",
	1200: "windows:WindowDPIChanged",
	1201: "windows:WindowDragDrop",
	1202: "windows:WindowDragEnter",
	1203: "windows:WindowDragLeave",
	1204: "windows:WindowDragOver",
	1205: "windows:WindowEndMove",
	1206: "windows:WindowEndResize",
	1207: "windows:WindowFullscreen",
	1208: "windows:WindowHide",
	1209: "windows:WindowInactive",
	1210: "windows:WindowKeyDown",
	1211: "windows:WindowKeyUp",
	1212: "windows:WindowKillFocus",
	1213: "windows:WindowMaximise",
	1214: "windows:WindowMinimise",
	1215: "windows:WindowNonClientHit",
	1216: "windows:WindowNonClientMouseDown",
	1217: "windows:WindowNonClientMouseLeave",
	1218: "windows:WindowNonClientMouseMove",
	1219: "windows:WindowNonClientMouseUp",
	1220: "windows:WindowPaint",
	1221: "windows:WindowRestore",
	1222: "windows:WindowSetFocus",
	1223: "windows:WindowShow",
	1224: "windows:WindowStartMove",
	1225: "windows:WindowStartResize",
	1226: "windows:WindowUnFullscreen",
	1227: "windows:WindowUnMaximise",
	1228: "windows:WindowUnMinimise",
	1229: "windows:WindowZOrderChanged",
}
