package application

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ErrQuickLookNotSupported is returned by QuickLookManager methods on
// platforms without Quick Look.
var ErrQuickLookNotSupported = errors.New("quick look is not supported on this platform")

// Default thumbnail size in points when ThumbnailOptions leaves both
// dimensions at zero.
const quickLookDefaultThumbnailSize = 256

// ThumbnailOptions controls Thumbnail.
type ThumbnailOptions struct {
	// Width and Height are the maximum size in points. A zero dimension
	// takes the other one; both zero mean 256 x 256. The generated image
	// keeps the file's aspect ratio inside that box.
	Width  int
	Height int
	// Scale is the pixel density (1 for standard, 2 for Retina). Zero and
	// negative values mean 1.
	Scale float64
	// IconMode renders the thumbnail like a Finder icon: with the document
	// border and, for some types, a badge. Off, the content fills the image.
	IconMode bool
}

// withDefaults fills zero fields with their defaults.
func (o ThumbnailOptions) withDefaults() ThumbnailOptions {
	if o.Width <= 0 && o.Height <= 0 {
		o.Width, o.Height = quickLookDefaultThumbnailSize, quickLookDefaultThumbnailSize
	}
	if o.Width <= 0 {
		o.Width = o.Height
	}
	if o.Height <= 0 {
		o.Height = o.Width
	}
	if o.Scale <= 0 {
		o.Scale = 1
	}
	return o
}

// validateQuickLookPath checks that path is an absolute path to an existing
// file or directory.
func validateQuickLookPath(path string) error {
	if strings.TrimSpace(path) == "" {
		return errors.New("quick look: path is empty")
	}
	if !filepath.IsAbs(path) {
		return fmt.Errorf("quick look: path %q must be absolute", path)
	}
	if _, err := os.Stat(path); err != nil {
		return fmt.Errorf("quick look: %w", err)
	}
	return nil
}

func validateQuickLookPaths(paths []string) error {
	if len(paths) == 0 {
		return errors.New("quick look: no paths to preview")
	}
	for _, path := range paths {
		if err := validateQuickLookPath(path); err != nil {
			return err
		}
	}
	return nil
}

// QuickLookManager previews files and generates thumbnails with Quick Look.
//
// Platform support is documented on each method. Methods without support on
// the current platform are safe no-ops or return a documented error.
type QuickLookManager struct {
	app *App
}

func newQuickLookManager(app *App) *QuickLookManager {
	return &QuickLookManager{app: app}
}

// Preview opens the shared Quick Look panel on the given files. With more
// than one path the panel shows arrows to move between them. Calling
// Preview while the panel is open replaces its content. Every path must be
// absolute and exist.
//
// macOS: QLPreviewPanel. Other platforms return ErrQuickLookNotSupported.
func (q *QuickLookManager) Preview(paths []string) error {
	if err := validateQuickLookPaths(paths); err != nil {
		return err
	}
	return quickLookPreview(paths)
}

// ClosePreview closes the Quick Look panel if it is open.
//
// macOS only; a no-op elsewhere.
func (q *QuickLookManager) ClosePreview() {
	quickLookClosePreview()
}

// IsPreviewOpen reports whether the Quick Look panel is visible.
//
// macOS only; false elsewhere.
func (q *QuickLookManager) IsPreviewOpen() bool {
	return quickLookIsPreviewOpen()
}

// Thumbnail renders a thumbnail of the file at path and returns it as PNG.
// The image is generated by the system's Quick Look thumbnail providers, so
// documents, images, PDFs, movies and any type with a Quick Look plug-in are
// supported; other types get their file icon. Generation runs off the main
// thread and Thumbnail blocks the calling goroutine until it completes.
//
// macOS 10.15+: QLThumbnailGenerator. Earlier macOS and other platforms
// return ErrQuickLookNotSupported.
func (q *QuickLookManager) Thumbnail(path string, opts ThumbnailOptions) ([]byte, error) {
	if err := validateQuickLookPath(path); err != nil {
		return nil, err
	}
	return quickLookThumbnail(path, opts.withDefaults())
}
