package application

import (
	"bytes"
	"encoding/binary"
	"io"
	"net/http"
	"strconv"
	"sync"
	"time"
)

// The desktop transport. Two endpoints on the asset server the app already
// serves — nothing listens on a port, and nothing goes through
// evaluateJavaScript.
//
//	GET  /wails/stream/poll   held until there is something to deliver
//	POST /wails/stream/send   one frame from the frontend
//
// Control data travels in headers, never in the body or the query string.
// WebKitGTK 6.0 can deliver POST bodies as query params for custom URI schemes
// (transport_http.go carries a fallback for exactly that), and WebView2 caps
// body delivery around 2 MB. Headers are delivered intact on all three engines.
const (
	streamPath     = "/wails/stream/"
	streamPathPoll = streamPath + "poll"
	streamPathSend = streamPath + "send"

	streamHeaderSession = "x-wails-stream-session"
	streamHeaderConn    = "x-wails-stream-conn"
	streamHeaderKind    = "x-wails-stream-kind"
	streamHeaderName    = "x-wails-stream-name"

	// Large frames are split by the client, for the same WebView2 body limit
	// the runtime's own chunking works around.
	streamHeaderChunkID    = "x-wails-stream-chunk"
	streamHeaderChunkIndex = "x-wails-stream-chunk-index"
	streamHeaderChunkTotal = "x-wails-stream-chunk-total"

	streamMaxSendBytes  = 64 << 20
	streamMaxChunkTotal = 4096

	// Frame header on the wire: connID(4) + kind(1) + length(4).
	streamFrameHeaderBytes = 9
)

// streamMagic identifies the framing version. A page that has been served a
// stale cached runtime will fail the check loudly instead of misparsing.
var streamMagic = [4]byte{'W', 'S', '1', 0}

// serveStream routes the two stream endpoints. Registered in the asset server
// middleware chain next to the event payload endpoint.
func (a *App) serveStream(rw http.ResponseWriter, req *http.Request) {
	if a.streams == nil {
		http.NotFound(rw, req)
		return
	}

	switch req.URL.Path {
	case streamPathPoll:
		a.serveStreamPoll(rw, req)
	case streamPathSend:
		a.serveStreamSend(rw, req)
	default:
		http.NotFound(rw, req)
	}
}

// streamRequestWindow reads the window id the platform layer tags onto every
// webview request (see webViewAssetRequest.Header). Zero means the platform did
// not tag it, which skips the binding check the way eventPayloadStore.take
// does.
func streamRequestWindow(req *http.Request) uint {
	raw := req.Header.Get(webViewRequestHeaderWindowId)
	if raw == "" {
		return 0
	}
	parsed, err := strconv.ParseUint(raw, 10, strconv.IntSize)
	if err != nil {
		return 0
	}
	return uint(parsed)
}

// sessionFor resolves the session named by the request and enforces that it
// belongs to the requesting window. Returns nil after writing a response.
func (a *App) sessionFor(rw http.ResponseWriter, req *http.Request, create bool) *streamSession {
	id := req.Header.Get(streamHeaderSession)
	// Session ids are generated by the client, one per page load, exactly like
	// the runtime's clientId. They are not a capability: the binding below is
	// what stops one window reaching another's streams.
	if id == "" || len(id) > 64 {
		http.Error(rw, "missing session", http.StatusBadRequest)
		return nil
	}

	windowID := streamRequestWindow(req)

	var s *streamSession
	if create {
		s = a.streams.session(id, windowID)
	} else {
		s = a.streams.existingSession(id)
	}
	if s == nil {
		// Gone rather than NotFound: it tells the client to stop polling and
		// surface a close, instead of retrying forever.
		http.Error(rw, "session closed", http.StatusGone)
		return nil
	}
	if windowID != 0 && s.windowID != windowID {
		http.Error(rw, "session belongs to another window", http.StatusForbidden)
		return nil
	}
	return s
}

func (a *App) serveStreamPoll(rw http.ResponseWriter, req *http.Request) {
	if req.Method != http.MethodGet && req.Method != http.MethodHead {
		rw.Header().Set("Allow", "GET, HEAD")
		http.Error(rw, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	s := a.sessionFor(rw, req, true)
	if s == nil {
		return
	}

	frames, more, alive := s.awaitFrames(req.Context(), streamHoldTimeout, streamMaxResponseBytes)
	if !alive {
		a.streams.removeSession(s.id)
		http.Error(rw, "session closed", http.StatusGone)
		return
	}
	if len(frames) == 0 {
		rw.Header().Set("Cache-Control", "no-store")
		rw.WriteHeader(http.StatusNoContent)
		return
	}

	body := encodeStreamFrames(frames, more)
	rw.Header().Set("Content-Type", "application/octet-stream")
	rw.Header().Set("Cache-Control", "no-store")
	rw.Header().Set("Content-Length", strconv.Itoa(len(body)))
	_, _ = rw.Write(body)
}

// encodeStreamFrames lays out a poll response:
//
//	magic(4) | flags(1) | count(4) | count × ( connID(4) | kind(1) | len(4) | payload )
//
// Binary rather than JSON because frames are []byte: base64 inside a JSON
// envelope would cost 33% on every frame, and a megabyte of JSON also costs a
// parse on the UI thread.
func encodeStreamFrames(frames []outFrame, more bool) []byte {
	size := len(streamMagic) + 1 + 4
	for _, f := range frames {
		size += streamFrameHeaderBytes + len(f.data)
	}

	buf := bytes.NewBuffer(make([]byte, 0, size))
	buf.Write(streamMagic[:])
	var flags byte
	if more {
		flags |= 1
	}
	buf.WriteByte(flags)

	var scratch [4]byte
	binary.BigEndian.PutUint32(scratch[:], uint32(len(frames)))
	buf.Write(scratch[:])

	for _, f := range frames {
		binary.BigEndian.PutUint32(scratch[:], f.connID)
		buf.Write(scratch[:])
		buf.WriteByte(f.kind)
		binary.BigEndian.PutUint32(scratch[:], uint32(len(f.data)))
		buf.Write(scratch[:])
		buf.Write(f.data)
	}
	return buf.Bytes()
}

func (a *App) serveStreamSend(rw http.ResponseWriter, req *http.Request) {
	if req.Method != http.MethodPost {
		rw.Header().Set("Allow", "POST")
		http.Error(rw, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	s := a.sessionFor(rw, req, true)
	if s == nil {
		return
	}

	connID64, err := strconv.ParseUint(req.Header.Get(streamHeaderConn), 10, 32)
	if err != nil {
		http.Error(rw, "bad connection id", http.StatusBadRequest)
		return
	}
	connID := uint32(connID64)

	kind64, err := strconv.ParseUint(req.Header.Get(streamHeaderKind), 10, 8)
	if err != nil {
		http.Error(rw, "bad frame kind", http.StatusBadRequest)
		return
	}

	body, complete, err := readStreamBody(s, req)
	if err != nil {
		http.Error(rw, err.Error(), http.StatusBadRequest)
		return
	}
	if !complete {
		// A chunk landed; the frame is not whole yet.
		rw.WriteHeader(http.StatusNoContent)
		return
	}

	switch uint8(kind64) {
	case frameOpen:
		name := req.Header.Get(streamHeaderName)
		if name == "" {
			http.Error(rw, "missing stream name", http.StatusBadRequest)
			return
		}
		s.open(connID, name)

	case frameData:
		c := s.conn(connID)
		if c == nil {
			http.Error(rw, "unknown connection", http.StatusGone)
			return
		}
		// Queue before responding. The client does not issue its next send
		// until this response lands, so append-then-respond is what makes
		// frontend send order the order the handler observes.
		c.deliver(body)

	case frameClose:
		if c := s.conn(connID); c != nil {
			c.shutdown()
		}

	default:
		http.Error(rw, "unknown frame kind", http.StatusBadRequest)
		return
	}

	rw.WriteHeader(http.StatusNoContent)
}

// readStreamBody returns the frame body, reassembling it first if the client
// split it. complete is false when this request carried a non-final chunk.
func readStreamBody(s *streamSession, req *http.Request) (body []byte, complete bool, err error) {
	req.Body = http.MaxBytesReader(nil, req.Body, streamMaxSendBytes)

	chunkID := req.Header.Get(streamHeaderChunkID)
	if chunkID == "" {
		data, err := io.ReadAll(req.Body)
		if err != nil {
			return nil, false, errStreamBadBody
		}
		return data, true, nil
	}

	total, err := strconv.Atoi(req.Header.Get(streamHeaderChunkTotal))
	if err != nil || total <= 0 || total > streamMaxChunkTotal {
		return nil, false, errStreamBadChunk
	}
	index, err := strconv.Atoi(req.Header.Get(streamHeaderChunkIndex))
	if err != nil || index < 0 || index >= total {
		return nil, false, errStreamBadChunk
	}

	data, err := io.ReadAll(req.Body)
	if err != nil {
		return nil, false, errStreamBadBody
	}

	assembled, done := s.chunks().add(chunkID, index, total, data)
	if !done {
		return nil, false, nil
	}
	return assembled, true, nil
}

type streamError string

func (e streamError) Error() string { return string(e) }

const (
	errStreamBadBody  streamError = "unable to read frame body"
	errStreamBadChunk streamError = "invalid chunk headers"
)

// ---------------------------------------------------------------------------
// Chunk reassembly for oversized frontend frames
// ---------------------------------------------------------------------------

type streamChunkStore struct {
	mu     sync.Mutex
	items  map[string]*streamChunkSet
	bytes  int
	closed bool
}

type streamChunkSet struct {
	parts   map[int][]byte
	total   int
	size    int
	created time.Time
}

func (s *streamSession) chunks() *streamChunkStore {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.chunkStore == nil {
		s.chunkStore = &streamChunkStore{items: make(map[string]*streamChunkSet)}
	}
	return s.chunkStore
}

// add stores one chunk and returns the assembled frame once the last one lands.
func (c *streamChunkStore) add(id string, index, total int, data []byte) ([]byte, bool) {
	c.mu.Lock()
	defer c.mu.Unlock()

	// Reap anything a disappearing page left behind before taking more.
	now := time.Now()
	for k, v := range c.items {
		if now.Sub(v.created) > streamHoldTimeout {
			c.bytes -= v.size
			delete(c.items, k)
		}
	}

	set, ok := c.items[id]
	if !ok {
		set = &streamChunkSet{parts: make(map[int][]byte, total), total: total, created: now}
		c.items[id] = set
	}
	if set.total != total {
		delete(c.items, id)
		return nil, false
	}
	if _, dup := set.parts[index]; dup {
		return nil, false
	}
	if c.bytes+len(data) > streamMaxSendBytes {
		c.bytes -= set.size
		delete(c.items, id)
		return nil, false
	}

	set.parts[index] = data
	set.size += len(data)
	c.bytes += len(data)

	if len(set.parts) < total {
		return nil, false
	}

	assembled := make([]byte, 0, set.size)
	for i := 0; i < total; i++ {
		assembled = append(assembled, set.parts[i]...)
	}
	c.bytes -= set.size
	delete(c.items, id)
	return assembled, true
}
