// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as GreetService from "./greetservice.js";
export {
    GreetService
};

export {
    AliasGroup,
    AliasedPerson,
    EmptyStruct,
    GenericPerson,
    GenericPersonAlias,
    IndirectPersonAlias,
    Person,
    StrangelyAliasedPerson,
    SubPackageAlias
} from "./models.js";

export type {
    Alias,
    AliasStruct,
    EmptyAliasStruct,
    GenericMapAlias,
    GenericPtrAlias,
    OtherAliasStruct
} from "./models.js";
