// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as subpkg$0 from "./subpkg/models.js";

/**
 * A nice type Alias.
 */
export type Alias = number;

/**
 * A class whose fields have various aliased types.
 */
export class AliasGroup {
    "GPAs": GenericPtrAlias<string[]>;
    "GPAP": GenericPtrAlias<GenericPerson<number[]>>;
    "GMA": GenericMapAlias<string, number>;
    "GPA": GenericPersonAlias<boolean>;
    "IPA": IndirectPersonAlias;
    "SPA": SubPackageAlias;

    /** Creates a new AliasGroup instance. */
    constructor($$source: Partial<AliasGroup> = {}) {
        if (!("GPAs" in $$source)) {
            this["GPAs"] = null;
        }
        if (!("GPAP" in $$source)) {
            this["GPAP"] = null;
        }
        if (!("GMA" in $$source)) {
            this["GMA"] = {};
        }
        if (!("GPA" in $$source)) {
            this["GPA"] = (new GenericPersonAlias());
        }
        if (!("IPA" in $$source)) {
            this["IPA"] = (new IndirectPersonAlias());
        }
        if (!("SPA" in $$source)) {
            this["SPA"] = (new SubPackageAlias());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AliasGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): AliasGroup {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType7;
        const $$createField5_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("GPAs" in $$parsedSource) {
            $$parsedSource["GPAs"] = $$createField0_0($$parsedSource["GPAs"]);
        }
        if ("GPAP" in $$parsedSource) {
            $$parsedSource["GPAP"] = $$createField1_0($$parsedSource["GPAP"]);
        }
        if ("GMA" in $$parsedSource) {
            $$parsedSource["GMA"] = $$createField2_0($$parsedSource["GMA"]);
        }
        if ("GPA" in $$parsedSource) {
            $$parsedSource["GPA"] = $$createField3_0($$parsedSource["GPA"]);
        }
        if ("IPA" in $$parsedSource) {
            $$parsedSource["IPA"] = $$createField4_0($$parsedSource["IPA"]);
        }
        if ("SPA" in $$parsedSource) {
            $$parsedSource["SPA"] = $$createField5_0($$parsedSource["SPA"]);
        }
        return new AliasGroup($$parsedSource as Partial<AliasGroup>);
    }
}

/**
 * A struct alias.
 * This should be rendered as a typedef or interface in every mode.
 */
export interface AliasStruct {
    /**
     * A field with a comment.
     */
    "Foo": number[];

    /**
     * Definitely not Foo.
     */
    "Bar"?: string;
    "Baz"?: string;

    /**
     * A nested alias struct.
     */
    "Other": OtherAliasStruct;
}

/**
 * An empty struct alias.
 */
export interface EmptyAliasStruct {
}

/**
 * An empty struct.
 */
export class EmptyStruct {

    /** Creates a new EmptyStruct instance. */
    constructor($$source: Partial<EmptyStruct> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EmptyStruct instance from a string or object.
     */
    static createFrom($$source: any = {}): EmptyStruct {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EmptyStruct($$parsedSource as Partial<EmptyStruct>);
    }
}

/**
 * A generic alias that wraps a map.
 */
export type GenericMapAlias<T, U> = { [_ in string]?: U };

/**
 * A generic struct containing an alias.
 */
export class GenericPerson<T> {
    "Name"?: T;
    "AliasedField": Alias;

    /** Creates a new GenericPerson instance. */
    constructor($$source: Partial<GenericPerson<T>> = {}) {
        if (!("AliasedField" in $$source)) {
            this["AliasedField"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Given creation functions for each type parameter,
     * returns a creation function for a concrete instance
     * of the generic class GenericPerson.
     */
    static createFrom<T = any>($$createParamT: (source: any) => T): ($$source?: any) => GenericPerson<T> {
        const $$createField0_0 = $$createParamT;
        return ($$source: any = {}) => {
            let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
            if ("Name" in $$parsedSource) {
                $$parsedSource["Name"] = $$createField0_0($$parsedSource["Name"]);
            }
            return new GenericPerson<T>($$parsedSource as Partial<GenericPerson<T>>);
        };
    }
}

/**
 * A generic alias that wraps a generic struct.
 */
export const GenericPersonAlias = GenericPerson;

/**
 * A generic alias that wraps a generic struct.
 */
export type GenericPersonAlias<T> = GenericPerson<GenericPtrAlias<T>[]>;

/**
 * A generic alias that wraps a pointer type.
 */
export type GenericPtrAlias<T> = T | null;

/**
 * An alias that wraps a class through a non-typeparam alias.
 */
export const IndirectPersonAlias = GenericPersonAlias;

/**
 * An alias that wraps a class through a non-typeparam alias.
 */
export type IndirectPersonAlias = GenericPersonAlias<boolean>;

/**
 * Another struct alias.
 */
export interface OtherAliasStruct {
    "NoMoreIdeas": number[];
}

/**
 * A non-generic struct containing an alias.
 */
export class Person {
    /**
     * The Person's name.
     */
    "Name": string;

    /**
     * A random alias field.
     */
    "AliasedField": Alias;

    /** Creates a new Person instance. */
    constructor($$source: Partial<Person> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("AliasedField" in $$source)) {
            this["AliasedField"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Person instance from a string or object.
     */
    static createFrom($$source: any = {}): Person {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Person($$parsedSource as Partial<Person>);
    }
}

/**
 * A class alias.
 */
export const AliasedPerson = Person;

/**
 * A class alias.
 */
export type AliasedPerson = Person;

/**
 * Another class alias, but ordered after its aliased class.
 */
export const StrangelyAliasedPerson = Person;

/**
 * Another class alias, but ordered after its aliased class.
 */
export type StrangelyAliasedPerson = Person;

/**
 * An alias referencing another package that is not used elsewhere.
 */
export const SubPackageAlias = subpkg$0.SubStruct;

/**
 * An alias referencing another package that is not used elsewhere.
 */
export type SubPackageAlias = subpkg$0.SubStruct;

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = GenericPerson.createFrom($$createType2);
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = GenericPerson.createFrom($$createType6);
const $$createType8 = subpkg$0.SubStruct.createFrom;
