
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export * from "./github.com/wailsapp/wails/v3/internal/parser/testcases/enum_from_imported_package/services/index.ts";
export * from "./github.com/wailsapp/wails/v3/internal/parser/testcases/function_from_imported_package/services/index.ts";
export * from "./github.com/wailsapp/wails/v3/internal/parser/testcases/struct_literal_multiple_other/services/index.ts";
export * from "./github.com/wailsapp/wails/v3/internal/parser/testcases/variable_single_from_other_function/services/index.ts";
