// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Create as $Create} from "@wailsio/runtime";

export class Address {
    "Street": string;

    "State": string;

    "Country": string;

    /** Creates a new Address instance. */
    constructor($$source: Partial<Address> = {}) {
        if (!("Street" in $$source)) {
            this["Street"] = "";
        }
        if (!("State" in $$source)) {
            this["State"] = "";
        }
        if (!("Country" in $$source)) {
            this["Country"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Address instance from a string or object.
     * Generic types also need creation functions for each type parameter.
     */
    static createFrom($$source: any = {}): Address {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Address($$parsedSource as Partial<Address>);
    }
}
