// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GreetService is great
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Greet does XYZ
 */
export function Greet(name: string, title: $models.Title): $CancellablePromise<string> {
    return $Call.ByID(1411160069, name, title);
}

/**
 * NewPerson creates a new person
 */
export function NewPerson(name: string): $CancellablePromise<$models.Person | null> {
    return $Call.ByID(1661412647, name);
}
