// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export type TimeAlias = Date;

export type TimeAliasStruct = any;

export class TimeFieldStruct {
    "T1": Date;
    "T2": TimeAlias;
    "T3": TimeStruct;
    "T4": TimeAliasStruct;
    "Q": Date;
    "O"?: Date;
    "P": Date | null;
    "A": Date[];
    "S": Date[];
    "M": { [_ in string]?: Date };
    "I": {"T": Date};

    /** Creates a new TimeFieldStruct instance. */
    constructor($$source: Partial<TimeFieldStruct> = {}) {
        if (!("T1" in $$source)) {
            this["T1"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("T2" in $$source)) {
            this["T2"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("T3" in $$source)) {
            this["T3"] = null;
        }
        if (!("T4" in $$source)) {
            this["T4"] = null;
        }
        if (!("Q" in $$source)) {
            this["Q"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("P" in $$source)) {
            this["P"] = null;
        }
        if (!("A" in $$source)) {
            this["A"] = Array.from({ length: 3 }, () => new Date("0001-01-01T00:00:00.000Z"));
        }
        if (!("S" in $$source)) {
            this["S"] = [];
        }
        if (!("M" in $$source)) {
            this["M"] = {};
        }
        if (!("I" in $$source)) {
            this["I"] = {"T": new Date("0001-01-01T00:00:00.000Z")};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimeFieldStruct instance from a string or object.
     */
    static createFrom($$source: any = {}): TimeFieldStruct {
        const $$createField0_0 = $Create.DateFromTime;
        const $$createField1_0 = $Create.DateFromTime;
        const $$createField4_0 = $Create.DateFromTime;
        const $$createField5_0 = $Create.DateFromTime;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType2;
        const $$createField9_0 = $$createType3;
        const $$createField10_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("T1" in $$parsedSource) {
            $$parsedSource["T1"] = $$createField0_0($$parsedSource["T1"]);
        }
        if ("T2" in $$parsedSource) {
            $$parsedSource["T2"] = $$createField1_0($$parsedSource["T2"]);
        }
        if ("Q" in $$parsedSource) {
            $$parsedSource["Q"] = $$createField4_0($$parsedSource["Q"]);
        }
        if ("O" in $$parsedSource) {
            $$parsedSource["O"] = $$createField5_0($$parsedSource["O"]);
        }
        if ("P" in $$parsedSource) {
            $$parsedSource["P"] = $$createField6_0($$parsedSource["P"]);
        }
        if ("A" in $$parsedSource) {
            $$parsedSource["A"] = $$createField7_0($$parsedSource["A"]);
        }
        if ("S" in $$parsedSource) {
            $$parsedSource["S"] = $$createField8_0($$parsedSource["S"]);
        }
        if ("M" in $$parsedSource) {
            $$parsedSource["M"] = $$createField9_0($$parsedSource["M"]);
        }
        if ("I" in $$parsedSource) {
            $$parsedSource["I"] = $$createField10_0($$parsedSource["I"]);
        }
        return new TimeFieldStruct($$parsedSource as Partial<TimeFieldStruct>);
    }
}

export type TimeStruct = any;

// Private type creation functions
const $$createType0 = $Create.Nullable($Create.DateFromTime);
const $$createType1 = $Create.Array($Create.DateFromTime);
const $$createType2 = $Create.Array($Create.DateFromTime);
const $$createType3 = $Create.Map($Create.Any, $Create.DateFromTime);
const $$createType4 = $Create.Struct({
    "T": $Create.DateFromTime,
});
