// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DoVariousTimeThings(): $CancellablePromise<$models.TimeFieldStruct> {
    return $Call.ByID(2365938049).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetTime(): $CancellablePromise<Date> {
    return $Call.ByID(3727485718).then(($result: any) => {
        return $Create.DateFromTime($result);
    });
}

export function SetTime(t: Date): $CancellablePromise<void> {
    return $Call.ByID(718492490, t);
}

// Private type creation functions
const $$createType0 = $models.TimeFieldStruct.createFrom;
