// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Alpha sorts before Zeta, so the generator emits it first.
 */
export interface Alpha {
    "Name": string;
    "Box": Epsilon<string>;
}

export interface Epsilon<T> {
    "IntItems": number[] | null;
    "Zarray": Zeta<T>[] | null;
}

/**
 * Zeta is generic; []T and *T each need an element converter.
 */
export interface Zeta<T> {
    "Items": T[] | null;
    "Ref": Epsilon<T> | null;
}
