// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OtherService is a struct
 * that does things
 * @module
 */

import {Call as $Call, Create as $Create} from "@wailsio/runtime";

import {type Address} from "./models.ts";

/**
 * Yay does this and that
 */
export function Yay(): Promise<Address | null> {
    let $resultPromise = $Call.ByID(3249920254);
    return $resultPromise as any;
}
