// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * An exported but internal model.
 */
export interface InternalModel {
    "Field": string;
}

/**
 * An unexported model.
 */
export interface unexportedModel {
    "Field": string;
}
