// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as otherpackage$0 from "./otherpackage/models.js";

function InternalMethod($0: string): $CancellablePromise<void> {
    return $Call.ByID(3518775569, $0);
}

export function VisibleMethod($0: otherpackage$0.Dummy): $CancellablePromise<void> {
    return $Call.ByID(474018228, $0);
}

export async function CustomMethod(arg: string): Promise<void> {
    await InternalMethod("Hello " + arg + "!");
}
