//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"fmt"
	"strconv"
	"strings"
)

// InterfaceMinimumVersion maps an ICoreWebView2_N interface name to the
// minimum WebView2 SDK version that introduced it. Use SupportsInterface
// to compare against a runtime version.
var InterfaceMinimumVersion = map[string]string{
	"ICoreWebView2WindowFeatures": "0.9.622.11",
	"ICoreWebView2PrintCompletedHandler": "1.0.1518.46",
	"ICoreWebView2PrintSettings2": "1.0.1518.46",
	"ICoreWebView2PrintToPdfStreamCompletedHandler": "1.0.1518.46",
	"ICoreWebView2_16": "1.0.1518.46",
	"ICoreWebView2CustomSchemeRegistration": "1.0.1587.40",
	"ICoreWebView2EnvironmentOptions4": "1.0.1587.40",
	"ICoreWebView2ControllerOptions2": "1.0.1661.34",
	"ICoreWebView2Environment12": "1.0.1661.34",
	"ICoreWebView2EnvironmentOptions5": "1.0.1661.34",
	"ICoreWebView2Frame4": "1.0.1661.34",
	"ICoreWebView2GetNonDefaultPermissionSettingsCompletedHandler": "1.0.1661.34",
	"ICoreWebView2PermissionRequestedEventArgs3": "1.0.1661.34",
	"ICoreWebView2PermissionSetting": "1.0.1661.34",
	"ICoreWebView2PermissionSettingCollectionView": "1.0.1661.34",
	"ICoreWebView2Profile3": "1.0.1661.34",
	"ICoreWebView2Profile4": "1.0.1661.34",
	"ICoreWebView2SetPermissionStateCompletedHandler": "1.0.1661.34",
	"ICoreWebView2SharedBuffer": "1.0.1661.34",
	"ICoreWebView2_17": "1.0.1661.34",
	"ICoreWebView2Settings8": "1.0.1722.45",
	"ICoreWebView2File": "1.0.1774.30",
	"ICoreWebView2ObjectCollectionView": "1.0.1774.30",
	"ICoreWebView2WebMessageReceivedEventArgs2": "1.0.1774.30",
	"ICoreWebView2LaunchingExternalUriSchemeEventArgs": "1.0.1823.32",
	"ICoreWebView2LaunchingExternalUriSchemeEventHandler": "1.0.1823.32",
	"ICoreWebView2_18": "1.0.1823.32",
	"ICoreWebView2_19": "1.0.1823.32",
	"ICoreWebView2NavigationStartingEventArgs3": "1.0.1901.177",
	"ICoreWebView2NewWindowRequestedEventArgs3": "1.0.2151.40",
	"ICoreWebView2AcceleratorKeyPressedEventArgs2": "1.0.2210.55",
	"ICoreWebView2BrowserExtension": "1.0.2210.55",
	"ICoreWebView2BrowserExtensionEnableCompletedHandler": "1.0.2210.55",
	"ICoreWebView2BrowserExtensionList": "1.0.2210.55",
	"ICoreWebView2BrowserExtensionRemoveCompletedHandler": "1.0.2210.55",
	"ICoreWebView2Environment13": "1.0.2210.55",
	"ICoreWebView2EnvironmentOptions6": "1.0.2210.55",
	"ICoreWebView2Frame5": "1.0.2210.55",
	"ICoreWebView2FrameInfo2": "1.0.2210.55",
	"ICoreWebView2GetProcessExtendedInfosCompletedHandler": "1.0.2210.55",
	"ICoreWebView2ProcessExtendedInfo": "1.0.2210.55",
	"ICoreWebView2ProcessExtendedInfoCollection": "1.0.2210.55",
	"ICoreWebView2Profile7": "1.0.2210.55",
	"ICoreWebView2Profile8": "1.0.2210.55",
	"ICoreWebView2ProfileAddBrowserExtensionCompletedHandler": "1.0.2210.55",
	"ICoreWebView2ProfileDeletedEventHandler": "1.0.2210.55",
	"ICoreWebView2ProfileGetBrowserExtensionsCompletedHandler": "1.0.2210.55",
	"ICoreWebView2_20": "1.0.2210.55",
	"ICoreWebView2ExecuteScriptResult": "1.0.2277.86",
	"ICoreWebView2ExecuteScriptWithResultCompletedHandler": "1.0.2277.86",
	"ICoreWebView2ScriptException": "1.0.2277.86",
	"ICoreWebView2_21": "1.0.2277.86",
	"ICoreWebView2WebResourceRequestedEventArgs2": "1.0.2365.46",
	"ICoreWebView2_22": "1.0.2365.46",
	"ICoreWebView2CompositionController4": "1.0.2420.47",
	"ICoreWebView2NonClientRegionChangedEventArgs": "1.0.2420.47",
	"ICoreWebView2NonClientRegionChangedEventHandler": "1.0.2420.47",
	"ICoreWebView2ProcessFailedEventArgs3": "1.0.2420.47",
	"ICoreWebView2RegionRectCollectionView": "1.0.2420.47",
	"ICoreWebView2Settings9": "1.0.2420.47",
	"ICoreWebView2EnvironmentOptions7": "1.0.2478.35",
	"ICoreWebView2EnvironmentOptions8": "1.0.2535.41",
	"ICoreWebView2Environment14": "1.0.2651.64",
	"ICoreWebView2FileSystemHandle": "1.0.2651.64",
	"ICoreWebView2ObjectCollection": "1.0.2651.64",
	"ICoreWebView2_23": "1.0.2651.64",
	"ICoreWebView2Notification": "1.0.2739.15",
	"ICoreWebView2NotificationCloseRequestedEventHandler": "1.0.2739.15",
	"ICoreWebView2NotificationReceivedEventArgs": "1.0.2739.15",
	"ICoreWebView2NotificationReceivedEventHandler": "1.0.2739.15",
	"ICoreWebView2SaveAsUIShowingEventArgs": "1.0.2739.15",
	"ICoreWebView2SaveAsUIShowingEventHandler": "1.0.2739.15",
	"ICoreWebView2ShowSaveAsUICompletedHandler": "1.0.2739.15",
	"ICoreWebView2_24": "1.0.2739.15",
	"ICoreWebView2_25": "1.0.2739.15",
	"ICoreWebView2SaveFileSecurityCheckStartingEventArgs": "1.0.2849.39",
	"ICoreWebView2SaveFileSecurityCheckStartingEventHandler": "1.0.2849.39",
	"ICoreWebView2_26": "1.0.2849.39",
	"ICoreWebView2Frame6": "1.0.2903.40",
	"ICoreWebView2FrameScreenCaptureStartingEventHandler": "1.0.2903.40",
	"ICoreWebView2ScreenCaptureStartingEventArgs": "1.0.2903.40",
	"ICoreWebView2ScreenCaptureStartingEventHandler": "1.0.2903.40",
	"ICoreWebView2_27": "1.0.2903.40",
	"ICoreWebView2Frame7": "1.0.3240.44",
	"ICoreWebView2FrameChildFrameCreatedEventHandler": "1.0.3240.44",
	"ICoreWebView2ControllerOptions3": "1.0.3296.44",
	"ICoreWebView2ControllerOptions4": "1.0.3351.48",
	"ICoreWebView2Environment15": "1.0.3405.78",
	"ICoreWebView2Find": "1.0.3405.78",
	"ICoreWebView2FindActiveMatchIndexChangedEventHandler": "1.0.3405.78",
	"ICoreWebView2FindMatchCountChangedEventHandler": "1.0.3405.78",
	"ICoreWebView2FindOptions": "1.0.3405.78",
	"ICoreWebView2FindStartCompletedHandler": "1.0.3405.78",
	"ICoreWebView2_28": "1.0.3405.78",
	"ICoreWebView2CompositionController5": "1.0.3719.77",
	"ICoreWebView2CompositionControllerInterop3": "1.0.3719.77",
	"ICoreWebView2DragStartingEventArgs": "1.0.3719.77",
	"ICoreWebView2DragStartingEventHandler": "1.0.3719.77",
}

// SupportsInterface reports whether the given runtime version is at least
// the SDK version that introduced iface. Returns the required version when
// the answer is false, or an empty string otherwise. Returns an error if
// iface is unknown or runtimeVersion fails to parse.
func SupportsInterface(runtimeVersion, iface string) (bool, string, error) {
	required, ok := InterfaceMinimumVersion[iface]
	if !ok {
		return false, "", fmt.Errorf("unknown interface %q", iface)
	}
	c, err := compareVersions(runtimeVersion, required)
	if err != nil {
		return false, required, err
	}
	if c < 0 {
		return false, required, nil
	}
	return true, "", nil
}

// HasCapability is the high-level feature gate. Each Capability is wired
// to a specific interface; the runtime is checked against that interface's
// minimum version.
func HasCapability(runtimeVersion string, cap Capability) (bool, error) {
	supported, _, err := SupportsInterface(runtimeVersion, cap.Interface)
	return supported, err
}

// Capability identifies a Wails-relevant feature gate. The set is generated
// from the interface inventory; consumers may hand-add named subsets.
type Capability struct {
	Name        string
	Description string
	Interface   string
}

// AllCapabilities lists every known interface as a Capability.
var AllCapabilities = []Capability{
	{Name: "ICoreWebView2WindowFeatures", Description: "Requires interface ICoreWebView2WindowFeatures", Interface: "ICoreWebView2WindowFeatures"},
	{Name: "ICoreWebView2PrintCompletedHandler", Description: "Requires interface ICoreWebView2PrintCompletedHandler", Interface: "ICoreWebView2PrintCompletedHandler"},
	{Name: "ICoreWebView2PrintSettings2", Description: "Requires interface ICoreWebView2PrintSettings2", Interface: "ICoreWebView2PrintSettings2"},
	{Name: "ICoreWebView2PrintToPdfStreamCompletedHandler", Description: "Requires interface ICoreWebView2PrintToPdfStreamCompletedHandler", Interface: "ICoreWebView2PrintToPdfStreamCompletedHandler"},
	{Name: "ICoreWebView2_16", Description: "Requires interface ICoreWebView2_16", Interface: "ICoreWebView2_16"},
	{Name: "ICoreWebView2CustomSchemeRegistration", Description: "Requires interface ICoreWebView2CustomSchemeRegistration", Interface: "ICoreWebView2CustomSchemeRegistration"},
	{Name: "ICoreWebView2EnvironmentOptions4", Description: "Requires interface ICoreWebView2EnvironmentOptions4", Interface: "ICoreWebView2EnvironmentOptions4"},
	{Name: "ICoreWebView2ControllerOptions2", Description: "Requires interface ICoreWebView2ControllerOptions2", Interface: "ICoreWebView2ControllerOptions2"},
	{Name: "ICoreWebView2Environment12", Description: "Requires interface ICoreWebView2Environment12", Interface: "ICoreWebView2Environment12"},
	{Name: "ICoreWebView2EnvironmentOptions5", Description: "Requires interface ICoreWebView2EnvironmentOptions5", Interface: "ICoreWebView2EnvironmentOptions5"},
	{Name: "ICoreWebView2Frame4", Description: "Requires interface ICoreWebView2Frame4", Interface: "ICoreWebView2Frame4"},
	{Name: "ICoreWebView2GetNonDefaultPermissionSettingsCompletedHandler", Description: "Requires interface ICoreWebView2GetNonDefaultPermissionSettingsCompletedHandler", Interface: "ICoreWebView2GetNonDefaultPermissionSettingsCompletedHandler"},
	{Name: "ICoreWebView2PermissionRequestedEventArgs3", Description: "Requires interface ICoreWebView2PermissionRequestedEventArgs3", Interface: "ICoreWebView2PermissionRequestedEventArgs3"},
	{Name: "ICoreWebView2PermissionSetting", Description: "Requires interface ICoreWebView2PermissionSetting", Interface: "ICoreWebView2PermissionSetting"},
	{Name: "ICoreWebView2PermissionSettingCollectionView", Description: "Requires interface ICoreWebView2PermissionSettingCollectionView", Interface: "ICoreWebView2PermissionSettingCollectionView"},
	{Name: "ICoreWebView2Profile3", Description: "Requires interface ICoreWebView2Profile3", Interface: "ICoreWebView2Profile3"},
	{Name: "ICoreWebView2Profile4", Description: "Requires interface ICoreWebView2Profile4", Interface: "ICoreWebView2Profile4"},
	{Name: "ICoreWebView2SetPermissionStateCompletedHandler", Description: "Requires interface ICoreWebView2SetPermissionStateCompletedHandler", Interface: "ICoreWebView2SetPermissionStateCompletedHandler"},
	{Name: "ICoreWebView2SharedBuffer", Description: "Requires interface ICoreWebView2SharedBuffer", Interface: "ICoreWebView2SharedBuffer"},
	{Name: "ICoreWebView2_17", Description: "Requires interface ICoreWebView2_17", Interface: "ICoreWebView2_17"},
	{Name: "ICoreWebView2Settings8", Description: "Requires interface ICoreWebView2Settings8", Interface: "ICoreWebView2Settings8"},
	{Name: "ICoreWebView2File", Description: "Requires interface ICoreWebView2File", Interface: "ICoreWebView2File"},
	{Name: "ICoreWebView2ObjectCollectionView", Description: "Requires interface ICoreWebView2ObjectCollectionView", Interface: "ICoreWebView2ObjectCollectionView"},
	{Name: "ICoreWebView2WebMessageReceivedEventArgs2", Description: "Requires interface ICoreWebView2WebMessageReceivedEventArgs2", Interface: "ICoreWebView2WebMessageReceivedEventArgs2"},
	{Name: "ICoreWebView2LaunchingExternalUriSchemeEventArgs", Description: "Requires interface ICoreWebView2LaunchingExternalUriSchemeEventArgs", Interface: "ICoreWebView2LaunchingExternalUriSchemeEventArgs"},
	{Name: "ICoreWebView2LaunchingExternalUriSchemeEventHandler", Description: "Requires interface ICoreWebView2LaunchingExternalUriSchemeEventHandler", Interface: "ICoreWebView2LaunchingExternalUriSchemeEventHandler"},
	{Name: "ICoreWebView2_18", Description: "Requires interface ICoreWebView2_18", Interface: "ICoreWebView2_18"},
	{Name: "ICoreWebView2_19", Description: "Requires interface ICoreWebView2_19", Interface: "ICoreWebView2_19"},
	{Name: "ICoreWebView2NavigationStartingEventArgs3", Description: "Requires interface ICoreWebView2NavigationStartingEventArgs3", Interface: "ICoreWebView2NavigationStartingEventArgs3"},
	{Name: "ICoreWebView2NewWindowRequestedEventArgs3", Description: "Requires interface ICoreWebView2NewWindowRequestedEventArgs3", Interface: "ICoreWebView2NewWindowRequestedEventArgs3"},
	{Name: "ICoreWebView2AcceleratorKeyPressedEventArgs2", Description: "Requires interface ICoreWebView2AcceleratorKeyPressedEventArgs2", Interface: "ICoreWebView2AcceleratorKeyPressedEventArgs2"},
	{Name: "ICoreWebView2BrowserExtension", Description: "Requires interface ICoreWebView2BrowserExtension", Interface: "ICoreWebView2BrowserExtension"},
	{Name: "ICoreWebView2BrowserExtensionEnableCompletedHandler", Description: "Requires interface ICoreWebView2BrowserExtensionEnableCompletedHandler", Interface: "ICoreWebView2BrowserExtensionEnableCompletedHandler"},
	{Name: "ICoreWebView2BrowserExtensionList", Description: "Requires interface ICoreWebView2BrowserExtensionList", Interface: "ICoreWebView2BrowserExtensionList"},
	{Name: "ICoreWebView2BrowserExtensionRemoveCompletedHandler", Description: "Requires interface ICoreWebView2BrowserExtensionRemoveCompletedHandler", Interface: "ICoreWebView2BrowserExtensionRemoveCompletedHandler"},
	{Name: "ICoreWebView2Environment13", Description: "Requires interface ICoreWebView2Environment13", Interface: "ICoreWebView2Environment13"},
	{Name: "ICoreWebView2EnvironmentOptions6", Description: "Requires interface ICoreWebView2EnvironmentOptions6", Interface: "ICoreWebView2EnvironmentOptions6"},
	{Name: "ICoreWebView2Frame5", Description: "Requires interface ICoreWebView2Frame5", Interface: "ICoreWebView2Frame5"},
	{Name: "ICoreWebView2FrameInfo2", Description: "Requires interface ICoreWebView2FrameInfo2", Interface: "ICoreWebView2FrameInfo2"},
	{Name: "ICoreWebView2GetProcessExtendedInfosCompletedHandler", Description: "Requires interface ICoreWebView2GetProcessExtendedInfosCompletedHandler", Interface: "ICoreWebView2GetProcessExtendedInfosCompletedHandler"},
	{Name: "ICoreWebView2ProcessExtendedInfo", Description: "Requires interface ICoreWebView2ProcessExtendedInfo", Interface: "ICoreWebView2ProcessExtendedInfo"},
	{Name: "ICoreWebView2ProcessExtendedInfoCollection", Description: "Requires interface ICoreWebView2ProcessExtendedInfoCollection", Interface: "ICoreWebView2ProcessExtendedInfoCollection"},
	{Name: "ICoreWebView2Profile7", Description: "Requires interface ICoreWebView2Profile7", Interface: "ICoreWebView2Profile7"},
	{Name: "ICoreWebView2Profile8", Description: "Requires interface ICoreWebView2Profile8", Interface: "ICoreWebView2Profile8"},
	{Name: "ICoreWebView2ProfileAddBrowserExtensionCompletedHandler", Description: "Requires interface ICoreWebView2ProfileAddBrowserExtensionCompletedHandler", Interface: "ICoreWebView2ProfileAddBrowserExtensionCompletedHandler"},
	{Name: "ICoreWebView2ProfileDeletedEventHandler", Description: "Requires interface ICoreWebView2ProfileDeletedEventHandler", Interface: "ICoreWebView2ProfileDeletedEventHandler"},
	{Name: "ICoreWebView2ProfileGetBrowserExtensionsCompletedHandler", Description: "Requires interface ICoreWebView2ProfileGetBrowserExtensionsCompletedHandler", Interface: "ICoreWebView2ProfileGetBrowserExtensionsCompletedHandler"},
	{Name: "ICoreWebView2_20", Description: "Requires interface ICoreWebView2_20", Interface: "ICoreWebView2_20"},
	{Name: "ICoreWebView2ExecuteScriptResult", Description: "Requires interface ICoreWebView2ExecuteScriptResult", Interface: "ICoreWebView2ExecuteScriptResult"},
	{Name: "ICoreWebView2ExecuteScriptWithResultCompletedHandler", Description: "Requires interface ICoreWebView2ExecuteScriptWithResultCompletedHandler", Interface: "ICoreWebView2ExecuteScriptWithResultCompletedHandler"},
	{Name: "ICoreWebView2ScriptException", Description: "Requires interface ICoreWebView2ScriptException", Interface: "ICoreWebView2ScriptException"},
	{Name: "ICoreWebView2_21", Description: "Requires interface ICoreWebView2_21", Interface: "ICoreWebView2_21"},
	{Name: "ICoreWebView2WebResourceRequestedEventArgs2", Description: "Requires interface ICoreWebView2WebResourceRequestedEventArgs2", Interface: "ICoreWebView2WebResourceRequestedEventArgs2"},
	{Name: "ICoreWebView2_22", Description: "Requires interface ICoreWebView2_22", Interface: "ICoreWebView2_22"},
	{Name: "ICoreWebView2CompositionController4", Description: "Requires interface ICoreWebView2CompositionController4", Interface: "ICoreWebView2CompositionController4"},
	{Name: "ICoreWebView2NonClientRegionChangedEventArgs", Description: "Requires interface ICoreWebView2NonClientRegionChangedEventArgs", Interface: "ICoreWebView2NonClientRegionChangedEventArgs"},
	{Name: "ICoreWebView2NonClientRegionChangedEventHandler", Description: "Requires interface ICoreWebView2NonClientRegionChangedEventHandler", Interface: "ICoreWebView2NonClientRegionChangedEventHandler"},
	{Name: "ICoreWebView2ProcessFailedEventArgs3", Description: "Requires interface ICoreWebView2ProcessFailedEventArgs3", Interface: "ICoreWebView2ProcessFailedEventArgs3"},
	{Name: "ICoreWebView2RegionRectCollectionView", Description: "Requires interface ICoreWebView2RegionRectCollectionView", Interface: "ICoreWebView2RegionRectCollectionView"},
	{Name: "ICoreWebView2Settings9", Description: "Requires interface ICoreWebView2Settings9", Interface: "ICoreWebView2Settings9"},
	{Name: "ICoreWebView2EnvironmentOptions7", Description: "Requires interface ICoreWebView2EnvironmentOptions7", Interface: "ICoreWebView2EnvironmentOptions7"},
	{Name: "ICoreWebView2EnvironmentOptions8", Description: "Requires interface ICoreWebView2EnvironmentOptions8", Interface: "ICoreWebView2EnvironmentOptions8"},
	{Name: "ICoreWebView2Environment14", Description: "Requires interface ICoreWebView2Environment14", Interface: "ICoreWebView2Environment14"},
	{Name: "ICoreWebView2FileSystemHandle", Description: "Requires interface ICoreWebView2FileSystemHandle", Interface: "ICoreWebView2FileSystemHandle"},
	{Name: "ICoreWebView2ObjectCollection", Description: "Requires interface ICoreWebView2ObjectCollection", Interface: "ICoreWebView2ObjectCollection"},
	{Name: "ICoreWebView2_23", Description: "Requires interface ICoreWebView2_23", Interface: "ICoreWebView2_23"},
	{Name: "ICoreWebView2Notification", Description: "Requires interface ICoreWebView2Notification", Interface: "ICoreWebView2Notification"},
	{Name: "ICoreWebView2NotificationCloseRequestedEventHandler", Description: "Requires interface ICoreWebView2NotificationCloseRequestedEventHandler", Interface: "ICoreWebView2NotificationCloseRequestedEventHandler"},
	{Name: "ICoreWebView2NotificationReceivedEventArgs", Description: "Requires interface ICoreWebView2NotificationReceivedEventArgs", Interface: "ICoreWebView2NotificationReceivedEventArgs"},
	{Name: "ICoreWebView2NotificationReceivedEventHandler", Description: "Requires interface ICoreWebView2NotificationReceivedEventHandler", Interface: "ICoreWebView2NotificationReceivedEventHandler"},
	{Name: "ICoreWebView2SaveAsUIShowingEventArgs", Description: "Requires interface ICoreWebView2SaveAsUIShowingEventArgs", Interface: "ICoreWebView2SaveAsUIShowingEventArgs"},
	{Name: "ICoreWebView2SaveAsUIShowingEventHandler", Description: "Requires interface ICoreWebView2SaveAsUIShowingEventHandler", Interface: "ICoreWebView2SaveAsUIShowingEventHandler"},
	{Name: "ICoreWebView2ShowSaveAsUICompletedHandler", Description: "Requires interface ICoreWebView2ShowSaveAsUICompletedHandler", Interface: "ICoreWebView2ShowSaveAsUICompletedHandler"},
	{Name: "ICoreWebView2_24", Description: "Requires interface ICoreWebView2_24", Interface: "ICoreWebView2_24"},
	{Name: "ICoreWebView2_25", Description: "Requires interface ICoreWebView2_25", Interface: "ICoreWebView2_25"},
	{Name: "ICoreWebView2SaveFileSecurityCheckStartingEventArgs", Description: "Requires interface ICoreWebView2SaveFileSecurityCheckStartingEventArgs", Interface: "ICoreWebView2SaveFileSecurityCheckStartingEventArgs"},
	{Name: "ICoreWebView2SaveFileSecurityCheckStartingEventHandler", Description: "Requires interface ICoreWebView2SaveFileSecurityCheckStartingEventHandler", Interface: "ICoreWebView2SaveFileSecurityCheckStartingEventHandler"},
	{Name: "ICoreWebView2_26", Description: "Requires interface ICoreWebView2_26", Interface: "ICoreWebView2_26"},
	{Name: "ICoreWebView2Frame6", Description: "Requires interface ICoreWebView2Frame6", Interface: "ICoreWebView2Frame6"},
	{Name: "ICoreWebView2FrameScreenCaptureStartingEventHandler", Description: "Requires interface ICoreWebView2FrameScreenCaptureStartingEventHandler", Interface: "ICoreWebView2FrameScreenCaptureStartingEventHandler"},
	{Name: "ICoreWebView2ScreenCaptureStartingEventArgs", Description: "Requires interface ICoreWebView2ScreenCaptureStartingEventArgs", Interface: "ICoreWebView2ScreenCaptureStartingEventArgs"},
	{Name: "ICoreWebView2ScreenCaptureStartingEventHandler", Description: "Requires interface ICoreWebView2ScreenCaptureStartingEventHandler", Interface: "ICoreWebView2ScreenCaptureStartingEventHandler"},
	{Name: "ICoreWebView2_27", Description: "Requires interface ICoreWebView2_27", Interface: "ICoreWebView2_27"},
	{Name: "ICoreWebView2Frame7", Description: "Requires interface ICoreWebView2Frame7", Interface: "ICoreWebView2Frame7"},
	{Name: "ICoreWebView2FrameChildFrameCreatedEventHandler", Description: "Requires interface ICoreWebView2FrameChildFrameCreatedEventHandler", Interface: "ICoreWebView2FrameChildFrameCreatedEventHandler"},
	{Name: "ICoreWebView2ControllerOptions3", Description: "Requires interface ICoreWebView2ControllerOptions3", Interface: "ICoreWebView2ControllerOptions3"},
	{Name: "ICoreWebView2ControllerOptions4", Description: "Requires interface ICoreWebView2ControllerOptions4", Interface: "ICoreWebView2ControllerOptions4"},
	{Name: "ICoreWebView2Environment15", Description: "Requires interface ICoreWebView2Environment15", Interface: "ICoreWebView2Environment15"},
	{Name: "ICoreWebView2Find", Description: "Requires interface ICoreWebView2Find", Interface: "ICoreWebView2Find"},
	{Name: "ICoreWebView2FindActiveMatchIndexChangedEventHandler", Description: "Requires interface ICoreWebView2FindActiveMatchIndexChangedEventHandler", Interface: "ICoreWebView2FindActiveMatchIndexChangedEventHandler"},
	{Name: "ICoreWebView2FindMatchCountChangedEventHandler", Description: "Requires interface ICoreWebView2FindMatchCountChangedEventHandler", Interface: "ICoreWebView2FindMatchCountChangedEventHandler"},
	{Name: "ICoreWebView2FindOptions", Description: "Requires interface ICoreWebView2FindOptions", Interface: "ICoreWebView2FindOptions"},
	{Name: "ICoreWebView2FindStartCompletedHandler", Description: "Requires interface ICoreWebView2FindStartCompletedHandler", Interface: "ICoreWebView2FindStartCompletedHandler"},
	{Name: "ICoreWebView2_28", Description: "Requires interface ICoreWebView2_28", Interface: "ICoreWebView2_28"},
	{Name: "ICoreWebView2CompositionController5", Description: "Requires interface ICoreWebView2CompositionController5", Interface: "ICoreWebView2CompositionController5"},
	{Name: "ICoreWebView2CompositionControllerInterop3", Description: "Requires interface ICoreWebView2CompositionControllerInterop3", Interface: "ICoreWebView2CompositionControllerInterop3"},
	{Name: "ICoreWebView2DragStartingEventArgs", Description: "Requires interface ICoreWebView2DragStartingEventArgs", Interface: "ICoreWebView2DragStartingEventArgs"},
	{Name: "ICoreWebView2DragStartingEventHandler", Description: "Requires interface ICoreWebView2DragStartingEventHandler", Interface: "ICoreWebView2DragStartingEventHandler"},
}

func compareVersions(a, b string) (int, error) {
	pa, err := parseVersion(a)
	if err != nil {
		return 0, fmt.Errorf("runtime version %q: %w", a, err)
	}
	pb, err := parseVersion(b)
	if err != nil {
		return 0, fmt.Errorf("required version %q: %w", b, err)
	}
	for i := 0; i < 4; i++ {
		if pa[i] < pb[i] {
			return -1, nil
		}
		if pa[i] > pb[i] {
			return 1, nil
		}
	}
	return 0, nil
}

func parseVersion(s string) ([4]int, error) {
	var out [4]int
	// Drop a channel suffix ("1.0.515 prerelease" or "1.0.515-prerelease").
	if i := strings.IndexAny(s, " -"); i > 0 {
		s = s[:i]
	}
	parts := strings.Split(s, ".")
	if len(parts) > 4 {
		return out, fmt.Errorf("too many segments")
	}
	for i, p := range parts {
		n, err := strconv.Atoi(p)
		if err != nil {
			return out, err
		}
		out[i] = n
	}
	return out, nil
}
