//go:build windows

package webview2

type COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS uint32

const (
	COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_NONE           = 0x0
	COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_DOCUMENT       = 0x1
	COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_SHARED_WORKER  = 0x2
	COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_SERVICE_WORKER = 0x4
	COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_ALL            = 0xFFFFFFFF
)
