//go:build windows

package webview2

type COREWEBVIEW2_PROCESS_KIND uint32

const (
	COREWEBVIEW2_PROCESS_KIND_BROWSER        = 0
	COREWEBVIEW2_PROCESS_KIND_RENDERER       = 1
	COREWEBVIEW2_PROCESS_KIND_UTILITY        = 2
	COREWEBVIEW2_PROCESS_KIND_SANDBOX_HELPER = 3
	COREWEBVIEW2_PROCESS_KIND_GPU            = 4
	COREWEBVIEW2_PROCESS_KIND_PPAPI_PLUGIN   = 5
	COREWEBVIEW2_PROCESS_KIND_PPAPI_BROKER   = 6
)
