// Package webview2 contains the WebView2 COM bindings generated from
// Microsoft's WebView2 SDK IDL. Every file in this package except this
// one is machine-generated by `webview2gen` (see ../../scripts/cmd/webview2gen).
//
// Do NOT hand-edit generated files — they will be overwritten on the next
// run of the generator. To pick up a new SDK release:
//
//	cd webview2/scripts
//	go run ./cmd/webview2gen download --version <new-version>
//	go run ./cmd/webview2gen generate
//	go run ./cmd/webview2gen capabilities --source test.md
//	go run ./cmd/webview2gen verify   # CI will fail otherwise
//
// Capability-aware feature gating lives in capabilities.go; consumers
// should call SupportsInterface or HasCapability before invoking methods
// that are only present on newer WebView2 runtime versions.
package webview2

//go:generate go run ../../scripts/cmd/webview2gen full
