//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2Frame4_PostSharedBufferToScript(t *testing.T) {
	recReset()
	in0 := &ICoreWebView2SharedBuffer{}
	want := []wordExpect{}
	want = append(want, ptrw(unsafe.Pointer(in0)))
	want = append(want, xw(4))
	recCaptureUTF16(1 + len(want))
	want = append(want, anyw())
	obj := &ICoreWebView2Frame4{Vtbl: &ICoreWebView2Frame4Vtbl{}}
	obj.Vtbl.PostSharedBufferToScript = recProc(1 + len(want))
	err := obj.PostSharedBufferToScript(in0, COREWEBVIEW2_SHARED_BUFFER_ACCESS(4), "wv2-in-2")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got := recCapturedString(2); got != "wv2-in-2" {
		t.Errorf("string arg %d marshalled as %q, want wv2-in-2", 2, got)
	}
}

func TestICoreWebView2Frame4_QueryInterfaceHelper(t *testing.T) {
	recReset()
	root := &ICoreWebView2Frame{Vtbl: &ICoreWebView2FrameVtbl{}}
	root.Vtbl.QueryInterface = recProc(3)
	recCaptureGUID(1)
	recWritePtr(2, fakeTargetPtr())
	got, err := root.GetICoreWebView2Frame4()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if unsafe.Pointer(got) != fakeTargetPtr() {
		t.Errorf("returned pointer %p, want fake target", got)
	}
	if g := recCapturedGUID(1); g != "188782dc-92aa-4732-ab3c-fcc59f6f68b9" {
		t.Errorf("queried IID %s, want %s", g, "188782dc-92aa-4732-ab3c-fcc59f6f68b9")
	}
}
