//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2DownloadOperation_AddBytesReceivedChanged(t *testing.T) {
	recReset()
	in0 := &ICoreWebView2BytesReceivedChangedEventHandler{}
	want := []wordExpect{}
	want = append(want, ptrw(unsafe.Pointer(in0)))
	recWrite64(1+len(want), 0x101112131400)
	want = append(want, anyw())
	obj := &ICoreWebView2DownloadOperation{Vtbl: &ICoreWebView2DownloadOperationVtbl{}}
	obj.Vtbl.AddBytesReceivedChanged = recProc(1 + len(want))
	got0, err := obj.AddBytesReceivedChanged(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if tokenBits(got0) != 0x101112131400 {
		t.Errorf("token out = %x, want 0x101112131400", tokenBits(got0))
	}
}

func TestICoreWebView2DownloadOperation_RemoveBytesReceivedChanged(t *testing.T) {
	recReset()
	in0 := makeToken(0x0102030405060708)
	want := []wordExpect{}
	want = append(want, u64w(0x0102030405060708)...)
	obj := &ICoreWebView2DownloadOperation{Vtbl: &ICoreWebView2DownloadOperationVtbl{}}
	obj.Vtbl.RemoveBytesReceivedChanged = recProc(1 + len(want))
	err := obj.RemoveBytesReceivedChanged(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2DownloadOperation_AddEstimatedEndTimeChanged(t *testing.T) {
	recReset()
	in0 := &ICoreWebView2EstimatedEndTimeChangedEventHandler{}
	want := []wordExpect{}
	want = append(want, ptrw(unsafe.Pointer(in0)))
	recWrite64(1+len(want), 0x101112131400)
	want = append(want, anyw())
	obj := &ICoreWebView2DownloadOperation{Vtbl: &ICoreWebView2DownloadOperationVtbl{}}
	obj.Vtbl.AddEstimatedEndTimeChanged = recProc(1 + len(want))
	got0, err := obj.AddEstimatedEndTimeChanged(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if tokenBits(got0) != 0x101112131400 {
		t.Errorf("token out = %x, want 0x101112131400", tokenBits(got0))
	}
}

func TestICoreWebView2DownloadOperation_RemoveEstimatedEndTimeChanged(t *testing.T) {
	recReset()
	in0 := makeToken(0x0102030405060708)
	want := []wordExpect{}
	want = append(want, u64w(0x0102030405060708)...)
	obj := &ICoreWebView2DownloadOperation{Vtbl: &ICoreWebView2DownloadOperationVtbl{}}
	obj.Vtbl.RemoveEstimatedEndTimeChanged = recProc(1 + len(want))
	err := obj.RemoveEstimatedEndTimeChanged(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2DownloadOperation_AddStateChanged(t *testing.T) {
	recReset()
	in0 := &ICoreWebView2StateChangedEventHandler{}
	want := []wordExpect{}
	want = append(want, ptrw(unsafe.Pointer(in0)))
	recWrite64(1+len(want), 0x101112131400)
	want = append(want, anyw())
	obj := &ICoreWebView2DownloadOperation{Vtbl: &ICoreWebView2DownloadOperationVtbl{}}
	obj.Vtbl.AddStateChanged = recProc(1 + len(want))
	got0, err := obj.AddStateChanged(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if tokenBits(got0) != 0x101112131400 {
		t.Errorf("token out = %x, want 0x101112131400", tokenBits(got0))
	}
}

func TestICoreWebView2DownloadOperation_RemoveStateChanged(t *testing.T) {
	recReset()
	in0 := makeToken(0x0102030405060708)
	want := []wordExpect{}
	want = append(want, u64w(0x0102030405060708)...)
	obj := &ICoreWebView2DownloadOperation{Vtbl: &ICoreWebView2DownloadOperationVtbl{}}
	obj.Vtbl.RemoveStateChanged = recProc(1 + len(want))
	err := obj.RemoveStateChanged(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2DownloadOperation_GetUri(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2DownloadOperation{Vtbl: &ICoreWebView2DownloadOperationVtbl{}}
	obj.Vtbl.GetUri = recProc(1 + len(want))
	got0, err := obj.GetUri()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2DownloadOperation_GetContentDisposition(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2DownloadOperation{Vtbl: &ICoreWebView2DownloadOperationVtbl{}}
	obj.Vtbl.GetContentDisposition = recProc(1 + len(want))
	got0, err := obj.GetContentDisposition()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2DownloadOperation_GetMimeType(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2DownloadOperation{Vtbl: &ICoreWebView2DownloadOperationVtbl{}}
	obj.Vtbl.GetMimeType = recProc(1 + len(want))
	got0, err := obj.GetMimeType()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2DownloadOperation_GetTotalBytesToReceive(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite64(1+len(want), 0x55667788AA00)
	want = append(want, anyw())
	obj := &ICoreWebView2DownloadOperation{Vtbl: &ICoreWebView2DownloadOperationVtbl{}}
	obj.Vtbl.GetTotalBytesToReceive = recProc(1 + len(want))
	got0, err := obj.GetTotalBytesToReceive()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != int64(0x55667788AA00) {
		t.Errorf("64-bit out = %v", got0)
	}
}

func TestICoreWebView2DownloadOperation_GetBytesReceived(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite64(1+len(want), 0x55667788AA00)
	want = append(want, anyw())
	obj := &ICoreWebView2DownloadOperation{Vtbl: &ICoreWebView2DownloadOperationVtbl{}}
	obj.Vtbl.GetBytesReceived = recProc(1 + len(want))
	got0, err := obj.GetBytesReceived()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != int64(0x55667788AA00) {
		t.Errorf("64-bit out = %v", got0)
	}
}

func TestICoreWebView2DownloadOperation_GetEstimatedEndTime(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2DownloadOperation{Vtbl: &ICoreWebView2DownloadOperationVtbl{}}
	obj.Vtbl.GetEstimatedEndTime = recProc(1 + len(want))
	got0, err := obj.GetEstimatedEndTime()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2DownloadOperation_GetResultFilePath(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2DownloadOperation{Vtbl: &ICoreWebView2DownloadOperationVtbl{}}
	obj.Vtbl.GetResultFilePath = recProc(1 + len(want))
	got0, err := obj.GetResultFilePath()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2DownloadOperation_GetState(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 0x0AFE00)
	want = append(want, anyw())
	obj := &ICoreWebView2DownloadOperation{Vtbl: &ICoreWebView2DownloadOperationVtbl{}}
	obj.Vtbl.GetState = recProc(1 + len(want))
	got0, err := obj.GetState()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != COREWEBVIEW2_DOWNLOAD_STATE(0x0AFE00) {
		t.Errorf("scalar out = %v, want 0x0AFE00", got0)
	}
}

func TestICoreWebView2DownloadOperation_GetInterruptReason(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 0x0AFE00)
	want = append(want, anyw())
	obj := &ICoreWebView2DownloadOperation{Vtbl: &ICoreWebView2DownloadOperationVtbl{}}
	obj.Vtbl.GetInterruptReason = recProc(1 + len(want))
	got0, err := obj.GetInterruptReason()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON(0x0AFE00) {
		t.Errorf("scalar out = %v, want 0x0AFE00", got0)
	}
}

func TestICoreWebView2DownloadOperation_Cancel(t *testing.T) {
	recReset()
	want := []wordExpect{}
	obj := &ICoreWebView2DownloadOperation{Vtbl: &ICoreWebView2DownloadOperationVtbl{}}
	obj.Vtbl.Cancel = recProc(1 + len(want))
	err := obj.Cancel()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2DownloadOperation_Pause(t *testing.T) {
	recReset()
	want := []wordExpect{}
	obj := &ICoreWebView2DownloadOperation{Vtbl: &ICoreWebView2DownloadOperationVtbl{}}
	obj.Vtbl.Pause = recProc(1 + len(want))
	err := obj.Pause()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2DownloadOperation_Resume(t *testing.T) {
	recReset()
	want := []wordExpect{}
	obj := &ICoreWebView2DownloadOperation{Vtbl: &ICoreWebView2DownloadOperationVtbl{}}
	obj.Vtbl.Resume = recProc(1 + len(want))
	err := obj.Resume()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2DownloadOperation_GetCanResume(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2DownloadOperation{Vtbl: &ICoreWebView2DownloadOperationVtbl{}}
	obj.Vtbl.GetCanResume = recProc(1 + len(want))
	got0, err := obj.GetCanResume()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}
