// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as events_only$0 from "./generator/testcases/events_only/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as more$0 from "./generator/testcases/no_bindings_here/more/models.js";

declare module "/wails/runtime.js" {
    namespace Events {
        interface CustomEvents {
            "events_only:class": events_only$0.SomeClass;
            "events_only:map": { [_ in string]?: number[] };
            "events_only:nodata": void;
            "events_only:other": more$0.StringPtr[];
            "events_only:string": string;
            "interface": any;
            "overlap": {"Field": boolean[]} | null;
        }
    }
}
