// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GreetService is great
 * @module
 */

import {Call as $Call, Create as $Create} from "@wailsio/runtime";

import {type Person, type Title} from "./models.ts";

/**
 * Greet does XYZ
 */
export function Greet(name: string, title: Title): Promise<string> {
    let $resultPromise = $Call.ByName("main.GreetService.Greet", name, title);
    return $resultPromise as any;
}

/**
 * NewPerson creates a new person
 */
export function NewPerson(name: string): Promise<Person | null> {
    let $resultPromise = $Call.ByName("main.GreetService.NewPerson", name);
    return $resultPromise as any;
}
