// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


/** 
 * @function Hello
 * @returns {Promise<void>}
 **/
export function Hello() {
	return wails.CallByID(4249972365, ...Array.prototype.slice.call(arguments, 0));
}
