// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as Service from "./service.js";
export {
    Service
};

export {
    Maps
} from "./models.js";

export type {
    BasicCstrAlias,
    ComparableCstrAlias,
    EmbeddedCustomInterface,
    EmbeddedOriginalInterface,
    EmbeddedPointer,
    EmbeddedPointerPtr,
    EmbeddedValue,
    EmbeddedValuePtr,
    GoodTildeCstrAlias,
    InterfaceCstrAlias,
    MixedCstrAlias,
    NonBasicCstrAlias,
    PointableCstrAlias,
    PointerAlias,
    PointerTextMarshaler,
    StringAlias,
    StringType,
    ValueAlias,
    ValueTextMarshaler
} from "./models.js";
