// Turns the document into a Wails frontend: the files a `wails3 init -t
// vanilla-js` project has under frontend/, ready to drop in. The exported
// main.js mirrors runtime.ts so the wiring behaves the same as Run mode.

import {getDef} from './components';
import {type UIDocument, type UINode} from './model';
import {componentStyles} from './theme';

export interface ExportFile {
    path: string;
    content: string;
}

export function exportFrontend(doc: UIDocument): ExportFile[] {
    const root = renderPure(doc.root);
    root.dataset.theme = doc.theme;
    const title = escapeHTML(doc.name || 'My App');
    const services = [...new Set(
        Array.from(root.querySelectorAll<HTMLElement>('[data-call]')).map((b) => b.dataset.call!.split('.')[0]),
    )];

    const indexHTML = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="generator" content="Wails UI Builder"/>
    <link rel="stylesheet" href="/style.css"/>
    <title>${title}</title>
</head>
<body>
${indent(root.outerHTML)}
<script type="module" src="/src/main.js"></script>
</body>
</html>
`;

    const styleCSS = `/* Generated by Wails UI Builder — the window fills the webview. */
html, body { margin: 0; height: 100%; overflow: hidden; }
${componentStyles.trim()}
`;

    const readme = `# ${doc.name || 'My App'} — frontend

Exported from Wails UI Builder. These files replace the frontend of a project
created with \`wails3 init -t vanilla-js\`:

\`\`\`
frontend/index.html        ← index.html
frontend/public/style.css  ← public/style.css
frontend/src/main.js       ← src/main.js
\`\`\`

Copy them over, then run \`wails3 dev\`.

## Backend expectations
${services.length ? services.map((s) => `- Buttons call methods on \`${s}\`; register it with \`application.NewService(&${s}{})\`.`).join('\n') : '- No Go methods are called from this UI.'}
${collectBindings(root).map((c) => `- Something is bound to the \`${c}\` channel: emit it from Go with \`app.Event.Emit("${c}", data)\`${c === 'time' ? ' (the starter template already does this every second)' : ''}.`).join('\n')}

\`layout.uib.json\` is the design itself — open it in the builder to keep editing.
`;

    return [
        {path: 'index.html', content: indexHTML},
        {path: 'public/style.css', content: styleCSS},
        {path: 'src/main.js', content: MAIN_JS},
        {path: 'README.md', content: readme},
        {path: 'layout.uib.json', content: JSON.stringify(doc, null, 2) + '\n'},
    ];
}

function collectBindings(root: HTMLElement): string[] {
    const set = new Set<string>();
    for (const el of root.querySelectorAll<HTMLElement>('[data-bind]')) {
        set.add(el.dataset.bind!);
    }
    return [...set];
}

/** Render a node without any of the builder's data attributes or classes. */
function renderPure(node: UINode): HTMLElement {
    const def = getDef(node.type);
    const children = (node.children ?? []).map(renderPure);
    return def.render(node, children);
}

function escapeHTML(s: string): string {
    return s.replace(/[&<>"']/g, (c) => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'}[c] ?? c));
}

/** Light pretty-printing: one element per line, indented by depth. */
function indent(html: string): string {
    const out: string[] = [];
    let depth = 0;
    const tokens: string[] = [];
    let buf = '';
    for (const ch of html.replace(/>\s*</g, '><')) {
        if (ch === '<' && buf) {
            tokens.push(buf);
            buf = '';
        }
        buf += ch;
        if (ch === '>') {
            tokens.push(buf);
            buf = '';
        }
    }
    if (buf) {
        tokens.push(buf);
    }
    for (const token of tokens) {
        const isClose = token.startsWith('</');
        const isVoid = /^<(img|hr|br|input|meta|link)\b/i.test(token) || token.endsWith('/>');
        const isOpen = /^<[a-z]/i.test(token) && !isVoid;
        if (isClose) {
            depth = Math.max(0, depth - 1);
        }
        out.push('    '.repeat(depth) + token);
        if (isOpen) {
            depth += 1;
        }
    }
    return out.join('\n');
}

// The exported main.js. Keep in step with runtime.ts.
const MAIN_JS = `import {Call, Events, WML} from "@wailsio/runtime";

// Generated by Wails UI Builder.
//  - Buttons with data-call="Service.Method" call that Go method and publish
//    the result to the channel in data-result-to.
//  - Elements with data-bind="channel" display Go events with that name.
//  - data-wml-* attributes (events, window actions, URLs) are handled by WML.

const root = document.querySelector(".ub-root");

const bound = new Map();
for (const el of root.querySelectorAll("[data-bind]")) {
    const channel = el.dataset.bind;
    bound.set(channel, [...(bound.get(channel) ?? []), el]);
}

function publish(channel, data) {
    for (const el of bound.get(channel) ?? []) {
        display(el, data);
    }
}

function display(el, data) {
    const text = typeof data === "string" ? data : JSON.stringify(data);
    if (el.classList.contains("ub-progress")) {
        const pct = Math.max(0, Math.min(100, Number(data) || 0));
        el.querySelector(".ub-progress-track > i").style.width = pct + "%";
        el.querySelector("output").textContent = Math.round(pct) + "%";
        return;
    }
    if (el.dataset.bindMode === "append") {
        el.textContent = (el.textContent ? el.textContent + "\\n" : "") + text;
        el.scrollTop = el.scrollHeight;
        return;
    }
    el.textContent = text;
}

for (const channel of bound.keys()) {
    Events.On(channel, (ev) => publish(channel, ev.data));
}

// "GreetService.Greet" → "main.GreetService.Greet"
const qualify = (call) => (call.split(".").length >= 3 ? call : "main." + call);

// One argument per line; $field reads a control's value; numbers and booleans are typed.
function parseArgs(spec) {
    return spec.split("\\n").map((s) => s.trim()).filter(Boolean).map((arg) => {
        if (arg.startsWith("$")) {
            const control = root.querySelector('[name="' + CSS.escape(arg.slice(1)) + '"]');
            if (!control) return "";
            if (control.type === "checkbox") return control.checked;
            if (control.type === "number" || control.type === "range") return Number(control.value);
            return control.value;
        }
        if (arg === "true" || arg === "false") return arg === "true";
        if (arg !== "" && !Number.isNaN(Number(arg))) return Number(arg);
        return arg;
    });
}

for (const button of root.querySelectorAll("[data-call]")) {
    button.addEventListener("click", async () => {
        const name = qualify(button.dataset.call);
        const target = button.dataset.resultTo;
        button.dataset.busy = "true";
        try {
            const result = await Call.ByName(name, ...parseArgs(button.dataset.args ?? ""));
            if (target) publish(target, result);
        } catch (err) {
            console.error(name + " failed:", err);
            if (target) publish(target, "Error: " + (err?.message || "the call failed (is the Go backend running?)"));
        } finally {
            delete button.dataset.busy;
        }
    });
}

WML.Enable();
`;
