// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GreetService is great
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "/wails/runtime.js";

/**
 * Greet someone
 */
export function Greet($0: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByName("main.GreetService.Greet", $0) as any;
    return $resultPromise;
}
