// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as EmbedOther from "./embedother.ts";
import * as EmbedService from "./embedservice.ts";
import * as GreetService from "./greetservice.ts";
export {
    EmbedOther,
    EmbedService,
    GreetService
};
