// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * @returns {Promise<string>}
 */
export function OtherHiddenMethod() {
    let $resultPromise = $Call.ByID(1678140063);
    return /** @type {any} */($resultPromise);
}
