// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Call} from "/wails/runtime.js";

import {Person} from "./models";

export function Greet(person: Person): Promise<string> {
    return Call.ByID(2203441224, person);
}
