// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as uuid from "../github.com-google-uuid/models";

export interface Person {
    "UUID": uuid.UUID;
    "Name": string;
}
