// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export namespace main {
  
  export type PersonSource = Partial<{
    name: string;
    parent: Person;
    details: anon1;
  }>
  
  export class Person {
    name: string;
    parent: Person;
    details: anon1;
    
    static createFrom(source: string | PersonSource = {}) {
      return new Person(source);
    }

    constructor(source: string | PersonSource = {}) {
      if ('string' === typeof source) {
        source = JSON.parse(source);
      }

      this.name = source['name'];
      this.parent = Person.createFrom(source['parent']);
      this.details = anon1.createFrom(source['details']);
      
    }
  }
  
  export type anon1Source = Partial<{
    age: number;
    address: anon2;
  }>
  
  export class anon1 {
    age: number;
    address: anon2;
    
    static createFrom(source: string | anon1Source = {}) {
      return new anon1(source);
    }

    constructor(source: string | anon1Source = {}) {
      if ('string' === typeof source) {
        source = JSON.parse(source);
      }

      this.age = source['age'];
      this.address = anon2.createFrom(source['address']);
      
    }
  }
  
  export type anon2Source = Partial<{
    street: string;
  }>
  
  export class anon2 {
    street: string;
    
    static createFrom(source: string | anon2Source = {}) {
      return new anon2(source);
    }

    constructor(source: string | anon2Source = {}) {
      if ('string' === typeof source) {
        source = JSON.parse(source);
      }

      this.street = source['street'];
      
    }
  }
  
}
