# https://taskfile.dev

version: "3"

tasks:
  install-deps:
    internal: true
    sources:
      - package.json
    cmds:
      - npm install

  test:
    cmds:
      - npx vitest run

  update:
    cmds:
      - npx npm-check-updates -u

  build:debug:
    internal: true
    cmds:
      - npx esbuild@latest desktop/main.js --bundle --tree-shaking=true --sourcemap=inline --outfile=runtime_debug.js --define:DEBUG=true

  build:production:
    internal: true
    cmds:
      - npx esbuild@latest desktop/main.js --bundle --tree-shaking=true --minify --outfile=runtime.js --drop:console

  build:all:
    internal: true
    deps:
      - build:debug
      - build:production

    cmds:
      - cmd: echo "Build Complete."

  build:
    deps:
      - install-deps
    cmds:
      - task: build:all
