// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Create as $Create} from "/wails/runtime.js";

import * as other$0 from "./other/models.js";

import * as $internal from "./internal.js";

/**
 * HowDifferent is a curious kind of person
 * that lets other people decide how they are different.
 * @template How
 * @typedef {other$0.OtherPerson<{ [_: string]: How | null } | null>} HowDifferent
 */

/**
 * Impersonator gets their fields from other people.
 * @typedef {other$0.OtherPerson<number>} Impersonator
 */

/**
 * Person is not a number.
 * @typedef { {
 *     "Name": string,
 * } } Person
 */

/**
 * PrivatePerson gets their fields from hidden sources.
 * @typedef {$internal.personImpl} PrivatePerson
 */
