# https://taskfile.dev

version: "3"

shopt: [globstar]

tasks:
  clean:
    cmds:
      - rm -rf ./testdata/output/**/*.got.[jt]s ./testdata/output/**/*.got.log

  test:
    cmds:
      - go test -count=1 -v .
      - task: test:check

  test:analyse:
    cmds:
      - go test -count=1 -v -run ^TestAnalyser .

  test:constants:
    cmds:
      - go test -v -count=1 -run ^TestGenerateConstants .

  test:generate:
    cmds:
      - go test -v -count=1 -run ^TestGenerator .
      - task: test:check

  test:regenerate:
    cmds:
      - cmd: rm -rf ./testdata/output/*
      - cmd: go test -v -count=1 -run ^TestGenerator .
        ignore_error: true
      - task: test:generate

  test:check:
    dir: ./testdata
    deps:
      - install-deps
    cmds:
      - npx tsc
      - npx madge --circular output/

  install-deps:
    internal: true
    dir: ./testdata
    sources:
      - package.json
    cmds:
      - npm install

  update:
    dir: ./testdata
    cmds:
      - npx npm-check-updates -u
