// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function TestMethod2() {
    let $resultPromise = $Call.ByID(1859696033);
    return /** @type {any} */($resultPromise);
}
