// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OtherMethods has another method, but through a private embedded type.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call} from "/wails/runtime.js";

/**
 * LikeThisOtherOne does nothing as well, but is different.
 */
export function LikeThisOtherOne(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByName("github.com/wailsapp/wails/v3/internal/generator/testcases/no_bindings_here/other.OtherMethods.LikeThisOtherOne") as any;
    return $resultPromise;
}
