//go:build windows

package edge

type COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND uint32

const (
	COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY = iota
	COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_ALLOW
	COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY_CORS
)
