//go:build windows

package edge

type COREWEBVIEW2_MOUSE_EVENT_KIND uint32

const (
	COREWEBVIEW2_MOUSE_EVENT_KIND_HORIZONTAL_WHEEL             = 526
	COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_DOUBLE_CLICK     = 515
	COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_DOWN             = 513
	COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_UP               = 514
	COREWEBVIEW2_MOUSE_EVENT_KIND_LEAVE                        = 675
	COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_DOUBLE_CLICK   = 521
	COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_DOWN           = 519
	COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_UP             = 520
	COREWEBVIEW2_MOUSE_EVENT_KIND_MOVE                         = 512
	COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_DOUBLE_CLICK    = 518
	COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_DOWN            = 516
	COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_UP              = 517
	COREWEBVIEW2_MOUSE_EVENT_KIND_WHEEL                        = 522
	COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_DOUBLE_CLICK        = 525
	COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_DOWN                = 523
	COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_UP                  = 524
	COREWEBVIEW2_MOUSE_EVENT_KIND_NON_CLIENT_RIGHT_BUTTON_DOWN = 164
	COREWEBVIEW2_MOUSE_EVENT_KIND_NON_CLIENT_RIGHT_BUTTON_UP   = 165
)
