//go:build windows

package edge

type COREWEBVIEW2_KEY_EVENT_KIND uint32

const (
	COREWEBVIEW2_KEY_EVENT_KIND_KEY_DOWN        = 0
	COREWEBVIEW2_KEY_EVENT_KIND_KEY_UP          = 1
	COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_DOWN = 2
	COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_UP   = 3
)
