//go:build windows

package edge

type COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS uint32

const (
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_NONE          COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS = 0
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_LEFT_BUTTON   COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS = 1
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_RIGHT_BUTTON  COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS = 2
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_SHIFT         COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS = 4
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_CONTROL       COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS = 8
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_MIDDLE_BUTTON COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS = 16
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_X_BUTTON1     COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS = 32
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_X_BUTTON2     COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS = 64
)
