//go:build windows

package edge

type COREWEBVIEW2_MOVE_FOCUS_REASON uint32

const (
	COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC = 0
	COREWEBVIEW2_MOVE_FOCUS_REASON_NEXT         = 1
	COREWEBVIEW2_MOVE_FOCUS_REASON_PREVIOUS     = 2
)
