//go:build windows

package edge

type COREWEBVIEW2_WEB_RESOURCE_CONTEXT uint32

const (
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL                  = 0
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_DOCUMENT             = 1
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_STYLESHEET           = 2
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_IMAGE                = 3
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_MEDIA                = 4
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_FONT                 = 5
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_SCRIPT               = 6
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_XML_HTTP_REQUEST     = 7
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_FETCH                = 8
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_TEXT_TRACK           = 9
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_EVENT_SOURCE         = 10
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_WEBSOCKET            = 11
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_MANIFEST             = 12
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_SIGNED_EXCHANGE      = 13
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_PING                 = 14
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_CSP_VIOLATION_REPORT = 15
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_OTHER                = 16
)
