// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Create as $Create} from "@wailsio/runtime";

import * as services$0 from "./services/models.js";

/**
 * @typedef { {
 *     "Name": string,
 *     "Address": services$0.Address | null,
 * } } Person
 */
