package main

import (
	"fmt"
	"math"
	"strconv"
	"strings"
)

// RenderOptions controls the overall SVG output.
type RenderOptions struct {
	Width      float64
	SidePad    float64
	SponsorURL string
	// AvatarURIs maps sponsor login to a data URI. Missing entries get a
	// placeholder disc with the sponsor's initial.
	AvatarURIs map[string]string
}

type renderer struct {
	opts RenderOptions
	body strings.Builder
	y    float64
}

// num formats a coordinate compactly.
func num(v float64) string {
	return strconv.FormatFloat(math.Round(v*100)/100, 'f', -1, 64)
}

func esc(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;")
	return r.Replace(s)
}

func ellipsis(s string, max int) string {
	runes := []rune(s)
	if len(runes) <= max {
		return s
	}
	return string(runes[:max-1]) + "…"
}

// GroupByTier buckets sponsors into the configured tiers. Index i of the
// result corresponds to tiers[i].
func GroupByTier(sponsors []Sponsor) [][]Sponsor {
	groups := make([][]Sponsor, len(tiers))
	for _, s := range sponsors {
		for i, t := range tiers {
			if s.Monthly >= t.MinMonthly {
				groups[i] = append(groups[i], s)
				break
			}
		}
	}
	return groups
}

// Render produces the complete SVG document.
func Render(sponsors []Sponsor, opts RenderOptions) string {
	r := &renderer{opts: opts}
	groups := GroupByTier(sponsors)

	r.header()
	for i, group := range groups {
		if len(group) == 0 {
			continue
		}
		r.tierSection(tiers[i], group)
	}
	r.footer()

	height := r.y
	var out strings.Builder
	out.WriteString(fmt.Sprintf(`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 %s %s" width="%s" height="%s">`,
		num(opts.Width), num(height), num(opts.Width), num(height)))
	out.WriteString("\n<!-- Generated by wails-sponsorkit (tools/sponsorkit) -->\n")
	out.WriteString(defs)
	// Card background.
	out.WriteString(fmt.Sprintf(`<rect x="0.5" y="0.5" width="%s" height="%s" rx="16" fill="url(#bg)"/>`,
		num(opts.Width-1), num(height-1)))
	out.WriteString(fmt.Sprintf(`<rect x="0.5" y="0.5" width="%s" height="%s" rx="16" fill="url(#topGlow)"/>`,
		num(opts.Width-1), num(height-1)))
	out.WriteString(fmt.Sprintf(`<rect x="0.5" y="0.5" width="%s" height="%s" rx="16" fill="none" stroke="url(#border)"/>`,
		num(opts.Width-1), num(height-1)))
	out.WriteString(starField(opts.Width))
	out.WriteString(r.body.String())
	out.WriteString("</svg>\n")
	return out.String()
}

const defs = `<defs>
<linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
  <stop offset="0" stop-color="#131A2B"/>
  <stop offset="1" stop-color="#0B0F1A"/>
</linearGradient>
<radialGradient id="topGlow" cx="0.5" cy="0" r="0.9">
  <stop offset="0" stop-color="#DF0000" stop-opacity="0.14"/>
  <stop offset="0.5" stop-color="#DF0000" stop-opacity="0.03"/>
  <stop offset="1" stop-color="#DF0000" stop-opacity="0"/>
</radialGradient>
<linearGradient id="border" x1="0" y1="0" x2="0" y2="1">
  <stop offset="0" stop-color="#FF5C5C" stop-opacity="0.45"/>
  <stop offset="0.25" stop-color="#FFFFFF" stop-opacity="0.10"/>
  <stop offset="1" stop-color="#DF0000" stop-opacity="0.25"/>
</linearGradient>
<linearGradient id="accent" x1="0" y1="0" x2="1" y2="0">
  <stop offset="0" stop-color="#FF3D3D"/>
  <stop offset="1" stop-color="#DF0000"/>
</linearGradient>
<linearGradient id="ringPartner" x1="0" y1="0" x2="1" y2="1">
  <stop offset="0" stop-color="#FF3D3D"/>
  <stop offset="0.35" stop-color="#FFAA3D"/>
  <stop offset="0.7" stop-color="#FF3DA1"/>
  <stop offset="1" stop-color="#FF3D3D"/>
</linearGradient>
<linearGradient id="ringChampion" x1="0" y1="0" x2="1" y2="1">
  <stop offset="0" stop-color="#FF8A5C"/>
  <stop offset="0.5" stop-color="#FF3D3D"/>
  <stop offset="1" stop-color="#FFB25C"/>
</linearGradient>
<linearGradient id="ringGold" x1="0" y1="0" x2="1" y2="1">
  <stop offset="0" stop-color="#FFE9A3"/>
  <stop offset="0.5" stop-color="#D4A017"/>
  <stop offset="1" stop-color="#FFD34D"/>
</linearGradient>
<linearGradient id="ringSilver" x1="0" y1="0" x2="1" y2="1">
  <stop offset="0" stop-color="#F2F4F8"/>
  <stop offset="0.5" stop-color="#9BA3B4"/>
  <stop offset="1" stop-color="#DDE2EC"/>
</linearGradient>
<linearGradient id="ringBronze" x1="0" y1="0" x2="1" y2="1">
  <stop offset="0" stop-color="#F0C29B"/>
  <stop offset="0.5" stop-color="#A05A2C"/>
  <stop offset="1" stop-color="#DDA070"/>
</linearGradient>
<filter id="soften" x="-60%" y="-60%" width="220%" height="220%">
  <feGaussianBlur stdDeviation="5"/>
</filter>
<clipPath id="circle" clipPathUnits="objectBoundingBox">
  <circle cx="0.5" cy="0.5" r="0.5"/>
</clipPath>
<linearGradient id="glare" x1="0" y1="0" x2="1" y2="0" gradientTransform="rotate(18 0.5 0.5)">
  <stop offset="0" stop-color="#FFFFFF" stop-opacity="0"/>
  <stop offset="0.5" stop-color="#FFFFFF" stop-opacity="1"/>
  <stop offset="1" stop-color="#FFFFFF" stop-opacity="0"/>
</linearGradient>
</defs>
<style>
text {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
  fill: #E8ECF4;
}
.title { font-size: 26px; font-weight: 700; letter-spacing: 0.5px; }
.subtitle { font-size: 12.5px; fill: #8B95A9; }
.tier { font-size: 13px; font-weight: 600; letter-spacing: 3px; }
.name { font-weight: 500; }
.cta { font-size: 14.5px; font-weight: 600; fill: #FFFFFF; }
.link { cursor: pointer; }
/* Hover "power-up" for Gold+ sponsors. Only fires when the SVG is loaded
   as a document (object/inline embeds or direct view); in img embeds the
   hover layers simply stay hidden. */
.cell { transform-box: fill-box; transform-origin: center; transition: transform 0.2s ease; }
.sp:hover .cell { transform: translateY(-4px); }
.sp image { transition: filter 0.3s ease; }
.sp:hover image { filter: saturate(1.35) brightness(1.08); }
.bloom, .fast { opacity: 0; transition: opacity 0.3s ease; }
.sp:hover .bloom { opacity: 0.85; }
.sp:hover .fast { opacity: 0.9; }
.glare { opacity: 0; transform: translateX(calc(-1 * var(--d))); transition: transform 0.65s ease, opacity 0.2s ease; }
.sp:hover .glare { opacity: 0.55; transform: translateX(var(--d)); }
.pulse { opacity: 0; transform-box: fill-box; transform-origin: center; }
.sp:hover .pulse { animation: pulseOut 1.5s ease-out infinite; }
@keyframes pulseOut { 0% { transform: scale(1); opacity: 0.5; } 100% { transform: scale(1.35); opacity: 0; } }
.uline { transform: scaleX(0); transform-box: fill-box; transform-origin: center; transition: transform 0.3s ease; }
.sp:hover .uline { transform: scaleX(1); }
.name { transition: fill 0.2s ease; }
.sp:hover .name { fill: #FFFFFF; }
@media (prefers-reduced-motion: reduce) {
  .cell, .sp image, .glare, .uline { transition: none; }
  .sp:hover .pulse { animation: none; }
}
</style>
`

// starField sprinkles a few softly twinkling dots near the top of the card.
func starField(width float64) string {
	// Deterministic hand-placed positions so output is stable run to run.
	stars := []struct{ x, y, r, dur, begin float64 }{
		{0.08, 46, 1.4, 4.2, 0}, {0.16, 108, 1.0, 3.4, 1.1}, {0.23, 30, 1.2, 5.0, 0.4},
		{0.31, 92, 0.9, 3.8, 2.0}, {0.44, 24, 1.1, 4.6, 0.9}, {0.56, 88, 1.3, 3.6, 1.6},
		{0.68, 34, 1.0, 4.4, 0.2}, {0.77, 104, 1.2, 3.9, 2.4}, {0.86, 52, 1.4, 4.8, 1.3},
		{0.93, 118, 0.9, 3.5, 0.7},
	}
	var b strings.Builder
	b.WriteString(`<g fill="#FFFFFF">`)
	for _, s := range stars {
		b.WriteString(fmt.Sprintf(`<circle cx="%s" cy="%s" r="%s" opacity="0.25">`,
			num(s.x*width), num(s.y), num(s.r)))
		b.WriteString(fmt.Sprintf(`<animate attributeName="opacity" values="0.08;0.5;0.08" dur="%ss" begin="%ss" repeatCount="indefinite"/>`,
			num(s.dur), num(s.begin)))
		b.WriteString(`</circle>`)
	}
	b.WriteString(`</g>`)
	return b.String()
}

func (r *renderer) header() {
	cx := r.opts.Width / 2
	r.y = 58
	// Heart mark above the title, with a double-thump heartbeat.
	r.body.WriteString(fmt.Sprintf(`<g transform="translate(%s %s)"><g><path d="M0 4.8 C -1.6 1.2 -6.5 0.2 -6.5 -3.4 C -6.5 -5.8 -4.7 -7 -3.1 -7 C -1.9 -7 -0.7 -6.3 0 -4.9 C 0.7 -6.3 1.9 -7 3.1 -7 C 4.7 -7 6.5 -5.8 6.5 -3.4 C 6.5 0.2 1.6 1.2 0 4.8 Z" fill="url(#accent)"/><animateTransform attributeName="transform" type="scale" values="1.15;1.35;1.15;1.3;1.15;1.15" keyTimes="0;0.08;0.16;0.24;0.34;1" dur="2.2s" repeatCount="indefinite"/></g></g>`,
		num(cx), num(r.y-10)))
	r.y += 26
	r.body.WriteString(fmt.Sprintf(`<text x="%s" y="%s" text-anchor="middle" class="title">Wails Sponsors</text>`, num(cx), num(r.y)))
	r.y += 24
	r.body.WriteString(fmt.Sprintf(`<text x="%s" y="%s" text-anchor="middle" class="subtitle">Thank you to everyone who supports the project</text>`, num(cx), num(r.y)))
	r.y += 30
}

func (r *renderer) tierHeader(t TierStyle) {
	cx := r.opts.Width / 2
	r.y += 34
	title := strings.ToUpper(t.Title)
	// Approximate label width for the flanking rules.
	labelHalf := float64(len(title))*9.2/2 + 22
	lineLen := 120.0
	r.body.WriteString(fmt.Sprintf(`<text x="%s" y="%s" text-anchor="middle" class="tier" fill="%s">%s</text>`,
		num(cx), num(r.y), t.Accent, esc(title)))
	yLine := r.y - 4.5
	r.body.WriteString(fmt.Sprintf(`<linearGradient id="rule%s" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="%s" stop-opacity="0"/><stop offset="1" stop-color="%s" stop-opacity="0.55"/></linearGradient>`,
		sanitizeID(t.Title), t.Accent, t.Accent))
	id := sanitizeID(t.Title)
	r.body.WriteString(fmt.Sprintf(`<rect x="%s" y="%s" width="%s" height="1" fill="url(#rule%s)"/>`,
		num(cx-labelHalf-lineLen), num(yLine), num(lineLen), id))
	r.body.WriteString(fmt.Sprintf(`<rect x="%s" y="%s" width="%s" height="1" fill="url(#rule%s)" transform="rotate(180 %s %s)"/>`,
		num(cx+labelHalf), num(yLine), num(lineLen), id, num(cx+labelHalf+lineLen/2), num(yLine+0.5)))
	r.y += 14
}

func sanitizeID(s string) string {
	return strings.Map(func(c rune) rune {
		if c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' {
			return c
		}
		return -1
	}, s)
}

func (r *renderer) tierSection(t TierStyle, group []Sponsor) {
	r.tierHeader(t)

	innerW := r.opts.Width - 2*r.opts.SidePad
	perRow := int(innerW / t.Box)
	if perRow < 1 {
		perRow = 1
	}

	ringPad := t.RingWidth + 3.5
	cellTop := 6.0
	nameH := 0.0
	if t.ShowName {
		nameH = t.NameSize + 14
	}
	cellH := cellTop + t.Avatar + 2*ringPad + nameH

	for start := 0; start < len(group); start += perRow {
		end := start + perRow
		if end > len(group) {
			end = len(group)
		}
		row := group[start:end]
		n := float64(len(row))
		startX := (r.opts.Width-n*t.Box)/2 + t.Box/2
		cy := r.y + cellTop + ringPad + t.Avatar/2
		for i, s := range row {
			cx := startX + float64(i)*t.Box
			r.sponsor(s, t, cx, cy)
		}
		r.y += cellH
		if end < len(group) {
			r.y += t.RowGap
		}
	}
	r.y += 10
}

func (r *renderer) sponsor(s Sponsor, t TierStyle, cx, cy float64) {
	rad := t.Avatar / 2
	ringR := rad + 2 + t.RingWidth/2
	hover := t.Ring == "animated"

	if hover {
		r.body.WriteString(fmt.Sprintf(`<a href="%s" target="_blank" class="link sp" style="--d:%spx">`, esc(s.URL), num(rad*1.5)))
	} else {
		r.body.WriteString(fmt.Sprintf(`<a href="%s" target="_blank" class="link">`, esc(s.URL)))
	}
	r.body.WriteString(fmt.Sprintf(`<title>%s (@%s)</title>`, esc(s.DisplayName()), esc(s.Login)))
	if hover {
		r.body.WriteString(`<g class="cell">`)
	}

	// Halo behind the ring for the top tiers, breathing gently.
	if t.Glow {
		r.body.WriteString(fmt.Sprintf(`<circle cx="%s" cy="%s" r="%s" fill="none" stroke="url(#%s)" stroke-width="%s" opacity="0.55" filter="url(#soften)"><animate attributeName="opacity" values="0.35;0.8;0.35" dur="3.6s" repeatCount="indefinite"/></circle>`,
			num(cx), num(cy), num(ringR), t.RingGradient, num(t.RingWidth+4)))
	}

	// The ring itself.
	switch t.Ring {
	case "animated":
		r.body.WriteString(fmt.Sprintf(`<g><circle cx="%s" cy="%s" r="%s" fill="none" stroke="url(#%s)" stroke-width="%s"/><animateTransform attributeName="transform" type="rotate" from="0 %s %s" to="360 %s %s" dur="9s" repeatCount="indefinite"/></g>`,
			num(cx), num(cy), num(ringR), t.RingGradient, num(t.RingWidth),
			num(cx), num(cy), num(cx), num(cy)))
		// A bright arc sweeping around the ring, faster and opposite the
		// gradient rotation so the two never look locked together.
		circ := 2 * math.Pi * ringR
		r.body.WriteString(fmt.Sprintf(`<g><circle cx="%s" cy="%s" r="%s" fill="none" stroke="#FFFFFF" stroke-opacity="0.65" stroke-width="%s" stroke-linecap="round" stroke-dasharray="%s %s"/><animateTransform attributeName="transform" type="rotate" from="360 %s %s" to="0 %s %s" dur="5s" repeatCount="indefinite"/></g>`,
			num(cx), num(cy), num(ringR), num(t.RingWidth*0.6), num(circ*0.14), num(circ*0.86),
			num(cx), num(cy), num(cx), num(cy)))
		// Orbiting sparkles for the flagship tiers.
		if t.Glow {
			r.sparkle(cx, cy, ringR+3, 2.4, 7, false)
			if t.ExtraSparkle {
				r.sparkle(cx, cy, ringR+6, 1.7, 11, true)
			}
		}
		// Hover-only layers: a wider glow bloom and a second, much faster
		// light sweep that "spins up" while the pointer is over the sponsor.
		r.body.WriteString(fmt.Sprintf(`<circle class="bloom" cx="%s" cy="%s" r="%s" fill="none" stroke="url(#%s)" stroke-width="%s" filter="url(#soften)"/>`,
			num(cx), num(cy), num(ringR+2), t.RingGradient, num(t.RingWidth+7)))
		r.body.WriteString(fmt.Sprintf(`<g><circle class="fast" cx="%s" cy="%s" r="%s" fill="none" stroke="#FFFFFF" stroke-width="%s" stroke-linecap="round" stroke-dasharray="%s %s"/><animateTransform attributeName="transform" type="rotate" from="0 %s %s" to="360 %s %s" dur="1.4s" repeatCount="indefinite"/></g>`,
			num(cx), num(cy), num(ringR), num(t.RingWidth*0.7), num(circ*0.08), num(circ*0.92),
			num(cx), num(cy), num(cx), num(cy)))
	case "static":
		r.body.WriteString(fmt.Sprintf(`<circle cx="%s" cy="%s" r="%s" fill="none" stroke="url(#%s)" stroke-width="%s"/>`,
			num(cx), num(cy), num(ringR), t.RingGradient, num(t.RingWidth)))
	case "subtle":
		r.body.WriteString(fmt.Sprintf(`<circle cx="%s" cy="%s" r="%s" fill="none" stroke="#FFFFFF" stroke-opacity="0.16" stroke-width="%s"/>`,
			num(cx), num(cy), num(ringR), num(t.RingWidth)))
	}

	// Avatar (or placeholder disc with the sponsor's initial).
	if uri, ok := r.opts.AvatarURIs[s.Login]; ok {
		r.body.WriteString(fmt.Sprintf(`<image x="%s" y="%s" width="%s" height="%s" href="%s" clip-path="url(#circle)" preserveAspectRatio="xMidYMid slice"/>`,
			num(cx-rad), num(cy-rad), num(t.Avatar), num(t.Avatar), uri))
	} else {
		initial := "?"
		if name := s.DisplayName(); name != "" {
			initial = strings.ToUpper(string([]rune(name)[0]))
		}
		r.body.WriteString(fmt.Sprintf(`<circle cx="%s" cy="%s" r="%s" fill="#1D2536"/>`, num(cx), num(cy), num(rad)))
		r.body.WriteString(fmt.Sprintf(`<text x="%s" y="%s" text-anchor="middle" font-size="%s" fill="#8B95A9">%s</text>`,
			num(cx), num(cy+rad*0.32), num(rad*0.9), esc(initial)))
	}
	// Hairline between avatar and ring for definition.
	r.body.WriteString(fmt.Sprintf(`<circle cx="%s" cy="%s" r="%s" fill="none" stroke="#000000" stroke-opacity="0.35"/>`,
		num(cx), num(cy), num(rad)))

	if hover {
		// Glass-glare stripe that sweeps across the avatar on hover, plus a
		// pulse ring that emanates while hovered.
		clipID := "gc" + sanitizeID(s.Login)
		glareW := rad * 0.8
		r.body.WriteString(fmt.Sprintf(`<clipPath id="%s"><circle cx="%s" cy="%s" r="%s"/></clipPath>`,
			clipID, num(cx), num(cy), num(rad)))
		r.body.WriteString(fmt.Sprintf(`<g clip-path="url(#%s)"><rect class="glare" x="%s" y="%s" width="%s" height="%s" fill="url(#glare)"/></g>`,
			clipID, num(cx-glareW/2), num(cy-rad), num(glareW), num(t.Avatar)))
		r.body.WriteString(fmt.Sprintf(`<circle class="pulse" cx="%s" cy="%s" r="%s" fill="none" stroke="url(#%s)" stroke-width="2"/>`,
			num(cx), num(cy), num(ringR+1), t.RingGradient))
	}

	y := cy + rad + t.RingWidth
	if t.ShowName {
		y += t.NameSize + 10
		name := ellipsis(s.DisplayName(), t.MaxName)
		r.body.WriteString(fmt.Sprintf(`<text x="%s" y="%s" text-anchor="middle" class="name" font-size="%s">%s</text>`,
			num(cx), num(y), num(t.NameSize), esc(name)))
		if hover {
			// Gradient underline that draws itself under the name on hover.
			ulW := float64(len([]rune(name))) * t.NameSize * 0.52
			r.body.WriteString(fmt.Sprintf(`<rect class="uline" x="%s" y="%s" width="%s" height="2.5" rx="1.25" fill="url(#accent)"/>`,
				num(cx-ulW/2), num(y+5), num(ulW)))
		}
	}
	if hover {
		r.body.WriteString(`</g>`)
	}
	r.body.WriteString(`</a>`)
}

// sparkle draws a small twinkling dot orbiting (cx, cy) at radius orbit.
func (r *renderer) sparkle(cx, cy, orbit, size, dur float64, reverse bool) {
	from, to := "0", "360"
	if reverse {
		from, to = "360", "0"
	}
	r.body.WriteString(fmt.Sprintf(`<g><circle cx="%s" cy="%s" r="%s" fill="#FFFFFF"><animate attributeName="opacity" values="0.15;1;0.15" dur="2.3s" repeatCount="indefinite"/></circle><animateTransform attributeName="transform" type="rotate" from="%s %s %s" to="%s %s %s" dur="%ss" repeatCount="indefinite"/></g>`,
		num(cx+orbit), num(cy), num(size),
		from, num(cx), num(cy), to, num(cx), num(cy), num(dur)))
}

func (r *renderer) footer() {
	cx := r.opts.Width / 2
	r.y += 36
	btnW, btnH := 210.0, 42.0
	r.body.WriteString(fmt.Sprintf(`<a href="%s" target="_blank" class="link">`, esc(r.opts.SponsorURL)))
	// Soft breathing glow behind the button.
	r.body.WriteString(fmt.Sprintf(`<rect x="%s" y="%s" width="%s" height="%s" rx="21" fill="url(#accent)" filter="url(#soften)" opacity="0.5"><animate attributeName="opacity" values="0.3;0.75;0.3" dur="3s" repeatCount="indefinite"/></rect>`,
		num(cx-btnW/2), num(r.y), num(btnW), num(btnH)))
	r.body.WriteString(fmt.Sprintf(`<rect x="%s" y="%s" width="%s" height="%s" rx="21" fill="url(#accent)"/>`,
		num(cx-btnW/2), num(r.y), num(btnW), num(btnH)))
	r.body.WriteString(fmt.Sprintf(`<rect x="%s" y="%s" width="%s" height="%s" rx="21" fill="none" stroke="#FFFFFF" stroke-opacity="0.25"/>`,
		num(cx-btnW/2), num(r.y), num(btnW), num(btnH)))
	// Small heart inside the button.
	r.body.WriteString(fmt.Sprintf(`<g transform="translate(%s %s) scale(0.85)"><path d="M0 4.8 C -1.6 1.2 -6.5 0.2 -6.5 -3.4 C -6.5 -5.8 -4.7 -7 -3.1 -7 C -1.9 -7 -0.7 -6.3 0 -4.9 C 0.7 -6.3 1.9 -7 3.1 -7 C 4.7 -7 6.5 -5.8 6.5 -3.4 C 6.5 0.2 1.6 1.2 0 4.8 Z" fill="#FFFFFF"/></g>`,
		num(cx-72), num(r.y+btnH/2)))
	r.body.WriteString(fmt.Sprintf(`<text x="%s" y="%s" text-anchor="middle" class="cta">Become a Sponsor</text>`,
		num(cx+10), num(r.y+btnH/2+5)))
	r.body.WriteString(`</a>`)
	r.y += btnH + 34
}
