package main

import (
	"fmt"
	"math"
	"strings"
)

// ContributorRenderOptions controls the contributors SVG output.
type ContributorRenderOptions struct {
	Width   float64
	SidePad float64
	// ContributeURL is the CTA target.
	ContributeURL string
	// AvatarURIs maps login to a data URI. Missing entries get a
	// placeholder squircle with the contributor's initial.
	AvatarURIs map[string]string
}

// GroupByBand buckets contributors into the configured bands. Index i of
// the result corresponds to bands[i].
func GroupByBand(cs []Contributor) [][]Contributor {
	groups := make([][]Contributor, len(bands))
	for _, c := range cs {
		for i, b := range bands {
			if c.Credit() >= b.MinCredit {
				groups[i] = append(groups[i], c)
				break
			}
		}
	}
	return groups
}

// squirclePoints samples the superellipse |x/r|^4 + |y/r|^4 = 1 centred on
// (cx, cy). 64 samples keep the largest squircles smooth while staying
// compact in the output.
func squirclePoints(cx, cy, r float64) [][2]float64 {
	const n = 64
	pts := make([][2]float64, n)
	for i := 0; i < n; i++ {
		t := 2 * math.Pi * float64(i) / n
		c, s := math.Cos(t), math.Sin(t)
		x := math.Copysign(math.Sqrt(math.Abs(c)), c)
		y := math.Copysign(math.Sqrt(math.Abs(s)), s)
		pts[i] = [2]float64{cx + r*x, cy + r*y}
	}
	return pts
}

func squirclePathD(cx, cy, r float64) string {
	pts := squirclePoints(cx, cy, r)
	var b strings.Builder
	b.WriteString("M")
	for i, p := range pts {
		if i > 0 {
			b.WriteString("L")
		}
		b.WriteString(num(p[0]))
		b.WriteString(" ")
		b.WriteString(num(p[1]))
	}
	b.WriteString("Z")
	return b.String()
}

// squirclePerimeter returns the sampled perimeter length of a squircle
// with half-size r, used to size travelling dash arcs.
func squirclePerimeter(r float64) float64 {
	pts := squirclePoints(0, 0, r)
	total := 0.0
	for i := range pts {
		next := pts[(i+1)%len(pts)]
		total += math.Hypot(next[0]-pts[i][0], next[1]-pts[i][1])
	}
	return total
}

// contributorDefs holds the extra defs and styles the contributors card
// needs on top of the shared sponsor defs: a unit squircle clip and the
// hover credit chip.
const contributorDefs = `<defs>
<clipPath id="squircle" clipPathUnits="objectBoundingBox">
  <path d="__UNIT_SQUIRCLE__"/>
</clipPath>
</defs>
<style>
.chip { opacity: 0; transform: translateY(6px); transform-box: fill-box; transform-origin: center; transition: transform 0.25s ease, opacity 0.25s ease; pointer-events: none; }
.sp:hover .chip { opacity: 1; transform: translateY(0); }
.chiptext { font-size: 11px; font-weight: 600; fill: #FFFFFF; }
@media (prefers-reduced-motion: reduce) {
  .chip { transition: none; }
}
</style>
`

// RenderContributors produces the complete contributors SVG document.
func RenderContributors(cs []Contributor, opts ContributorRenderOptions) string {
	r := &renderer{opts: RenderOptions{
		Width:      opts.Width,
		SidePad:    opts.SidePad,
		AvatarURIs: opts.AvatarURIs,
	}}
	groups := GroupByBand(cs)

	totalCommits := 0
	for _, c := range cs {
		totalCommits += c.Commits
	}
	r.contributorHeader(len(cs), totalCommits)
	for i, group := range groups {
		if len(group) == 0 {
			continue
		}
		r.bandSection(i, group)
	}
	r.contributorFooter(opts.ContributeURL)

	height := r.y
	var out strings.Builder
	out.WriteString(fmt.Sprintf(`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 %s %s" width="%s" height="%s">`,
		num(opts.Width), num(height), num(opts.Width), num(height)))
	out.WriteString("\n<!-- Generated by wails-sponsorkit (tools/sponsorkit) -->\n")
	out.WriteString(defs)
	out.WriteString(strings.Replace(contributorDefs, "__UNIT_SQUIRCLE__", squirclePathD(0.5, 0.5, 0.5), 1))
	// One origin-centred squircle path per band size, referenced with <use>
	// so hundreds of contributors do not each carry their own path data.
	out.WriteString("<defs>")
	for i, b := range bands {
		out.WriteString(fmt.Sprintf(`<path id="sqa%d" d="%s"/>`, i, squirclePathD(0, 0, b.Avatar/2)))
		out.WriteString(fmt.Sprintf(`<path id="sqr%d" d="%s"/>`, i, squirclePathD(0, 0, b.Avatar/2+2+b.RingWidth/2)))
	}
	out.WriteString("</defs>")
	out.WriteString(fmt.Sprintf(`<rect x="0.5" y="0.5" width="%s" height="%s" rx="16" fill="url(#bg)"/>`,
		num(opts.Width-1), num(height-1)))
	out.WriteString(fmt.Sprintf(`<rect x="0.5" y="0.5" width="%s" height="%s" rx="16" fill="url(#topGlow)"/>`,
		num(opts.Width-1), num(height-1)))
	out.WriteString(fmt.Sprintf(`<rect x="0.5" y="0.5" width="%s" height="%s" rx="16" fill="none" stroke="url(#border)"/>`,
		num(opts.Width-1), num(height-1)))
	out.WriteString(starField(opts.Width))
	out.WriteString(r.body.String())
	out.WriteString("</svg>\n")
	return out.String()
}

// contributorHeader draws the title and a stats line.
func (r *renderer) contributorHeader(contributors, commits int) {
	cx := r.opts.Width / 2
	r.y = 62
	r.body.WriteString(fmt.Sprintf(`<text x="%s" y="%s" text-anchor="middle" class="title">Wails Contributors</text>`, num(cx), num(r.y)))
	r.y += 24
	r.body.WriteString(fmt.Sprintf(`<text x="%s" y="%s" text-anchor="middle" class="subtitle">%s contributors · %s commits — thank you!</text>`,
		num(cx), num(r.y), comma(contributors), comma(commits)))
	r.y += 34
}

// bandSection lays out one band's rows, centred like sponsor tiers but
// without a heading: sizes alone carry the hierarchy.
func (r *renderer) bandSection(bi int, group []Contributor) {
	b := bands[bi]
	innerW := r.opts.Width - 2*r.opts.SidePad
	perRow := int(innerW / b.Box)
	if perRow < 1 {
		perRow = 1
	}

	ringPad := b.RingWidth + 3
	cellTop := 4.0
	nameH := 0.0
	if b.ShowName {
		nameH = b.NameSize + 14
	}
	cellH := cellTop + b.Avatar + 2*ringPad + nameH

	for start := 0; start < len(group); start += perRow {
		end := start + perRow
		if end > len(group) {
			end = len(group)
		}
		row := group[start:end]
		n := float64(len(row))
		startX := (r.opts.Width-n*b.Box)/2 + b.Box/2
		cy := r.y + cellTop + ringPad + b.Avatar/2
		for i, c := range row {
			cx := startX + float64(i)*b.Box
			r.contributor(c, bi, cx, cy)
		}
		r.y += cellH
		if end < len(group) {
			r.y += b.RowGap
		}
	}
	r.y += 14
}

func (r *renderer) contributor(c Contributor, bi int, cx, cy float64) {
	b := bands[bi]
	half := b.Avatar / 2
	ringHalf := half + 2 + b.RingWidth/2
	perim := squirclePerimeter(ringHalf)

	if b.Hover {
		r.body.WriteString(fmt.Sprintf(`<a href="%s" target="_blank" rel="noopener noreferrer" class="link sp" style="--d:%spx">`, esc(c.URL), num(half*1.5)))
	} else {
		r.body.WriteString(fmt.Sprintf(`<a href="%s" target="_blank" rel="noopener noreferrer" class="link">`, esc(c.URL)))
	}
	r.body.WriteString(fmt.Sprintf(`<title>@%s · %s</title>`, esc(c.Login), esc(creditLabel(c))))
	if b.Hover {
		r.body.WriteString(`<g class="cell">`)
	}

	ring := fmt.Sprintf(`<use href="#sqr%d" x="%s" y="%s" fill="none"`, bi, num(cx), num(cy))
	switch b.Ring {
	case "animated":
		// Breathing halo behind the ring.
		r.body.WriteString(fmt.Sprintf(`%s stroke="url(#%s)" stroke-width="%s" opacity="0.5" filter="url(#soften)"><animate attributeName="opacity" values="0.3;0.75;0.3" dur="3.6s" repeatCount="indefinite"/></use>`,
			ring, b.RingGradient, num(b.RingWidth+4)))
		// Gradient squircle ring with a bright arc travelling around it.
		// Rotating a squircle would visibly spin the shape, so the arc
		// marches along the path via stroke-dashoffset instead.
		r.body.WriteString(fmt.Sprintf(`%s stroke="url(#%s)" stroke-width="%s"/>`,
			ring, b.RingGradient, num(b.RingWidth)))
		r.body.WriteString(fmt.Sprintf(`%s stroke="#FFFFFF" stroke-opacity="0.65" stroke-width="%s" stroke-linecap="round" stroke-dasharray="%s %s"><animate attributeName="stroke-dashoffset" from="0" to="%s" dur="6s" repeatCount="indefinite"/></use>`,
			ring, num(b.RingWidth*0.6), num(perim*0.12), num(perim*0.88), num(-perim)))
		// Hover-only bloom and fast counter-marching sweep.
		r.body.WriteString(fmt.Sprintf(`%s class="bloom" stroke="url(#%s)" stroke-width="%s" filter="url(#soften)"/>`,
			ring, b.RingGradient, num(b.RingWidth+7)))
		r.body.WriteString(fmt.Sprintf(`%s class="fast" stroke="#FFFFFF" stroke-width="%s" stroke-linecap="round" stroke-dasharray="%s %s"><animate attributeName="stroke-dashoffset" from="0" to="%s" dur="1.4s" repeatCount="indefinite"/></use>`,
			ring, num(b.RingWidth*0.7), num(perim*0.07), num(perim*0.93), num(perim)))
	case "static":
		r.body.WriteString(fmt.Sprintf(`%s stroke="url(#%s)" stroke-width="%s"/>`,
			ring, b.RingGradient, num(b.RingWidth)))
		if b.Hover {
			r.body.WriteString(fmt.Sprintf(`%s class="bloom" stroke="url(#%s)" stroke-width="%s" filter="url(#soften)"/>`,
				ring, b.RingGradient, num(b.RingWidth+5)))
		}
	case "subtle":
		r.body.WriteString(fmt.Sprintf(`%s stroke="#FFFFFF" stroke-opacity="0.16" stroke-width="%s"/>`,
			ring, num(b.RingWidth)))
	}

	// Avatar (or placeholder squircle with the contributor's initial).
	if uri, ok := r.opts.AvatarURIs[c.Login]; ok {
		r.body.WriteString(fmt.Sprintf(`<image x="%s" y="%s" width="%s" height="%s" href="%s" clip-path="url(#squircle)" preserveAspectRatio="xMidYMid slice"/>`,
			num(cx-half), num(cy-half), num(b.Avatar), num(b.Avatar), uri))
	} else {
		initial := strings.ToUpper(string([]rune(c.Login)[0]))
		r.body.WriteString(fmt.Sprintf(`<use href="#sqa%d" x="%s" y="%s" fill="#1D2536"/>`, bi, num(cx), num(cy)))
		r.body.WriteString(fmt.Sprintf(`<text x="%s" y="%s" text-anchor="middle" font-size="%s" fill="#8B95A9">%s</text>`,
			num(cx), num(cy+half*0.32), num(half*0.9), esc(initial)))
	}
	// Hairline between avatar and ring for definition.
	r.body.WriteString(fmt.Sprintf(`<use href="#sqa%d" x="%s" y="%s" fill="none" stroke="#000000" stroke-opacity="0.35"/>`,
		bi, num(cx), num(cy)))

	if b.Hover {
		// Glass-glare sweep across the avatar on hover.
		clipID := fmt.Sprintf("qc%d", r.clipSeq)
		r.clipSeq++
		glareW := half * 0.8
		r.body.WriteString(fmt.Sprintf(`<clipPath id="%s"><use href="#sqa%d" x="%s" y="%s"/></clipPath>`,
			clipID, bi, num(cx), num(cy)))
		r.body.WriteString(fmt.Sprintf(`<g clip-path="url(#%s)"><rect class="glare" x="%s" y="%s" width="%s" height="%s" fill="url(#glare)"/></g>`,
			clipID, num(cx-glareW/2), num(cy-half), num(glareW), num(b.Avatar)))
		// A little credit chip that pops up above the squircle on hover.
		label := creditLabel(c)
		chipW := float64(len(label))*6.4 + 18
		chipY := cy - ringHalf - 26
		r.body.WriteString(`<g class="chip">`)
		r.body.WriteString(fmt.Sprintf(`<rect x="%s" y="%s" width="%s" height="20" rx="10" fill="#1D2536" stroke="url(#%s)" stroke-width="1.25"/>`,
			num(cx-chipW/2), num(chipY), num(chipW), b.RingGradient))
		r.body.WriteString(fmt.Sprintf(`<text x="%s" y="%s" text-anchor="middle" class="chiptext">%s</text>`,
			num(cx), num(chipY+14), esc(label)))
		r.body.WriteString(`</g>`)
	}

	if b.ShowName {
		y := cy + half + b.RingWidth + b.NameSize + 10
		name := ellipsis(c.Login, b.MaxName)
		r.body.WriteString(fmt.Sprintf(`<text x="%s" y="%s" text-anchor="middle" class="name" font-size="%s">%s</text>`,
			num(cx), num(y), num(b.NameSize), esc(name)))
		if b.Hover {
			ulW := float64(len([]rune(name))) * b.NameSize * 0.52
			r.body.WriteString(fmt.Sprintf(`<rect class="uline" x="%s" y="%s" width="%s" height="2.5" rx="1.25" fill="url(#accent)"/>`,
				num(cx-ulW/2), num(y+5), num(ulW)))
		}
	}
	if b.Hover {
		r.body.WriteString(`</g>`)
	}
	r.body.WriteString(`</a>`)
}

// creditLabel describes what a contributor is being credited for.
func creditLabel(c Contributor) string {
	primary, unit, unitOne := c.Commits, "commits", "commit"
	if creditMetric == "prs" && (c.PRs > 0 || c.Commits == 0) {
		primary, unit, unitOne = c.PRs, "merged PRs", "merged PR"
	}
	if c.Mentions > primary {
		primary, unit, unitOne = c.Mentions, "changelog credits", "changelog credit"
	}
	if primary == 1 {
		unit = unitOne
	}
	return comma(primary) + " " + unit
}

// comma formats n with thousands separators.
func comma(n int) string {
	s := fmt.Sprintf("%d", n)
	if len(s) <= 3 {
		return s
	}
	var b strings.Builder
	lead := len(s) % 3
	if lead > 0 {
		b.WriteString(s[:lead])
	}
	for i := lead; i < len(s); i += 3 {
		if b.Len() > 0 {
			b.WriteString(",")
		}
		b.WriteString(s[i : i+3])
	}
	return b.String()
}

func (r *renderer) contributorFooter(url string) {
	cx := r.opts.Width / 2
	r.y += 34
	btnW, btnH := 236.0, 42.0
	r.body.WriteString(fmt.Sprintf(`<a href="%s" target="_blank" rel="noopener noreferrer" class="link">`, esc(url)))
	r.body.WriteString(fmt.Sprintf(`<rect x="%s" y="%s" width="%s" height="%s" rx="21" fill="url(#accent)" filter="url(#soften)" opacity="0.5"><animate attributeName="opacity" values="0.3;0.75;0.3" dur="3s" repeatCount="indefinite"/></rect>`,
		num(cx-btnW/2), num(r.y), num(btnW), num(btnH)))
	r.body.WriteString(fmt.Sprintf(`<rect x="%s" y="%s" width="%s" height="%s" rx="21" fill="url(#accent)"/>`,
		num(cx-btnW/2), num(r.y), num(btnW), num(btnH)))
	r.body.WriteString(fmt.Sprintf(`<rect x="%s" y="%s" width="%s" height="%s" rx="21" fill="none" stroke="#FFFFFF" stroke-opacity="0.25"/>`,
		num(cx-btnW/2), num(r.y), num(btnW), num(btnH)))
	// A tiny git branch glyph: trunk, branch curve and nodes.
	bx, by := cx-92, r.y+btnH/2
	r.body.WriteString(fmt.Sprintf(`<g transform="translate(%s %s)" stroke="#FFFFFF" stroke-width="1.8" fill="none"><path d="M-3 -6 V6 M-3 -2 C-3 2 5 0 5 4"/><circle cx="-3" cy="-6" r="2.4" fill="#FFFFFF" stroke="none"/><circle cx="-3" cy="6" r="2.4" fill="#FFFFFF" stroke="none"/><circle cx="5" cy="4" r="2.4" fill="#FFFFFF" stroke="none"/></g>`,
		num(bx), num(by)))
	r.body.WriteString(fmt.Sprintf(`<text x="%s" y="%s" text-anchor="middle" class="cta">Become a Contributor</text>`,
		num(cx+8), num(r.y+btnH/2+5)))
	r.body.WriteString(`</a>`)
	r.y += btnH + 34
}
