// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GreetService is great
 * @module
 */

import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * Comment 1.
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Method1() {
    let $resultPromise = $Call.ByID(841558284);
    return /** @type {any} */($resultPromise);
}

/**
 * Comment 2.
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Method2() {
    let $resultPromise = $Call.ByID(891891141);
    return /** @type {any} */($resultPromise);
}

/**
 * Comment 3a.
 * Comment 3b.
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Method3() {
    let $resultPromise = $Call.ByID(875113522);
    return /** @type {any} */($resultPromise);
}

/**
 * Comment 4.
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Method4() {
    let $resultPromise = $Call.ByID(791225427);
    return /** @type {any} */($resultPromise);
}

/**
 * Comment 5.
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Method5() {
    let $resultPromise = $Call.ByID(774447808);
    return /** @type {any} */($resultPromise);
}
