//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"fmt"
	"strconv"
	"strings"
)

// InterfaceSupport describes when an ICoreWebView2* interface became
// available.
type InterfaceSupport struct {
	// SDKVersion is the stable WebView2 SDK release that introduced the
	// interface. Empty means the interface predates the SDK release-notes
	// archive and has been available in every runtime this package supports.
	SDKVersion string

	// MinRuntimeVersion is the minimum WebView2 Runtime (browser) version
	// required, in the four-part form reported by
	// GetAvailableCoreWebView2BrowserVersionString (e.g. "121.0.2277.83").
	// Empty means no minimum is known; the interface is assumed available.
	MinRuntimeVersion string
}

// InterfaceSupportTable maps every interface generated in this package
// (plus interop interfaces named in the SDK release notes) to its support
// data. Completeness over the generated inventory is enforced at
// generation time.
var InterfaceSupportTable = map[string]InterfaceSupport{
	"ICoreWebView2": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2AcceleratorKeyPressedEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2AcceleratorKeyPressedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2BasicAuthenticationRequestedEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2BasicAuthenticationRequestedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2BasicAuthenticationResponse": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2BrowserProcessExitedEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2BrowserProcessExitedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2BytesReceivedChangedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2CallDevToolsProtocolMethodCompletedHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2CapturePreviewCompletedHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Certificate": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ClearBrowsingDataCompletedHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ClearServerCertificateErrorActionsCompletedHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ClientCertificate": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ClientCertificateCollection": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ClientCertificateRequestedEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ClientCertificateRequestedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2CompositionController": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2CompositionController2": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2CompositionController3": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ContainsFullScreenElementChangedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ContentLoadingEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ContentLoadingEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ContextMenuItem": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ContextMenuItemCollection": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ContextMenuRequestedEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ContextMenuRequestedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ContextMenuTarget": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Controller": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Controller2": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Controller3": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Controller4": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ControllerOptions": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Cookie": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2CookieList": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2CookieManager": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2CreateCoreWebView2CompositionControllerCompletedHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2CreateCoreWebView2ControllerCompletedHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2CursorChangedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2CustomItemSelectedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2DOMContentLoadedEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2DOMContentLoadedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Deferral": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2DevToolsProtocolEventReceivedEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2DevToolsProtocolEventReceivedEventArgs2": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2DevToolsProtocolEventReceivedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2DevToolsProtocolEventReceiver": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2DocumentTitleChangedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2DownloadOperation": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2DownloadStartingEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2DownloadStartingEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Environment": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Environment10": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Environment11": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Environment2": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Environment3": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Environment4": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Environment5": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Environment6": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Environment7": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Environment8": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Environment9": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2EnvironmentOptions": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2EnvironmentOptions2": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2EnvironmentOptions3": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2EstimatedEndTimeChangedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ExecuteScriptCompletedHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2FaviconChangedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2FocusChangedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Frame": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Frame2": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Frame3": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2FrameContentLoadingEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2FrameCreatedEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2FrameCreatedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2FrameDOMContentLoadedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2FrameDestroyedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2FrameInfo": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2FrameInfoCollection": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2FrameInfoCollectionIterator": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2FrameNameChangedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2FrameNavigationCompletedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2FrameNavigationStartingEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2FramePermissionRequestedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2FrameWebMessageReceivedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2GetCookiesCompletedHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2GetFaviconCompletedHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2HistoryChangedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2HttpHeadersCollectionIterator": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2HttpRequestHeaders": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2HttpResponseHeaders": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2IsDefaultDownloadDialogOpenChangedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2IsDocumentPlayingAudioChangedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2IsMutedChangedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2MoveFocusRequestedEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2MoveFocusRequestedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2NavigationCompletedEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2NavigationCompletedEventArgs2": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2NavigationCompletedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2NavigationStartingEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2NavigationStartingEventArgs2": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2NavigationStartingEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2NewBrowserVersionAvailableEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2NewWindowRequestedEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2NewWindowRequestedEventArgs2": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2NewWindowRequestedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2PermissionRequestedEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2PermissionRequestedEventArgs2": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2PermissionRequestedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2PointerInfo": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2PrintSettings": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2PrintToPdfCompletedHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ProcessFailedEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ProcessFailedEventArgs2": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ProcessFailedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ProcessInfo": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ProcessInfoCollection": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ProcessInfosChangedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Profile": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Profile2": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Profile5": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Profile6": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2RasterizationScaleChangedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ScriptDialogOpeningEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ScriptDialogOpeningEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ServerCertificateErrorDetectedEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ServerCertificateErrorDetectedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Settings": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Settings2": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Settings3": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Settings4": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Settings5": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Settings6": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2Settings7": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2SourceChangedEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2SourceChangedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2StateChangedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2StatusBarTextChangedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2StringCollection": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2TrySuspendCompletedHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2WebMessageReceivedEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2WebMessageReceivedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2WebResourceRequest": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2WebResourceRequestedEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2WebResourceRequestedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2WebResourceResponse": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2WebResourceResponseReceivedEventArgs": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2WebResourceResponseReceivedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2WebResourceResponseView": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2WebResourceResponseViewGetContentCompletedHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2WindowCloseRequestedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2ZoomFactorChangedEventHandler": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2_10": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2_11": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2_12": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2_13": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2_14": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2_15": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2_2": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2_3": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2_4": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2_5": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2_6": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2_7": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2_8": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2_9": {SDKVersion: "", MinRuntimeVersion: ""},
	"ICoreWebView2WindowFeatures": {SDKVersion: "0.9.622.11", MinRuntimeVersion: "86.0.579.0"},
	"ICoreWebView2PrintCompletedHandler": {SDKVersion: "1.0.1518.46", MinRuntimeVersion: "109.0.1518.46"},
	"ICoreWebView2PrintSettings2": {SDKVersion: "1.0.1518.46", MinRuntimeVersion: "109.0.1518.46"},
	"ICoreWebView2PrintToPdfStreamCompletedHandler": {SDKVersion: "1.0.1518.46", MinRuntimeVersion: "109.0.1518.46"},
	"ICoreWebView2_16": {SDKVersion: "1.0.1518.46", MinRuntimeVersion: "109.0.1518.46"},
	"ICoreWebView2CustomSchemeRegistration": {SDKVersion: "1.0.1587.40", MinRuntimeVersion: "110.0.1587.40"},
	"ICoreWebView2EnvironmentOptions4": {SDKVersion: "1.0.1587.40", MinRuntimeVersion: "110.0.1587.40"},
	"ICoreWebView2ControllerOptions2": {SDKVersion: "1.0.1661.34", MinRuntimeVersion: "111.0.1661.34"},
	"ICoreWebView2Environment12": {SDKVersion: "1.0.1661.34", MinRuntimeVersion: "111.0.1661.34"},
	"ICoreWebView2EnvironmentOptions5": {SDKVersion: "1.0.1661.34", MinRuntimeVersion: "111.0.1661.34"},
	"ICoreWebView2Frame4": {SDKVersion: "1.0.1661.34", MinRuntimeVersion: "111.0.1661.34"},
	"ICoreWebView2GetNonDefaultPermissionSettingsCompletedHandler": {SDKVersion: "1.0.1661.34", MinRuntimeVersion: "111.0.1661.34"},
	"ICoreWebView2PermissionRequestedEventArgs3": {SDKVersion: "1.0.1661.34", MinRuntimeVersion: "111.0.1661.34"},
	"ICoreWebView2PermissionSetting": {SDKVersion: "1.0.1661.34", MinRuntimeVersion: "111.0.1661.34"},
	"ICoreWebView2PermissionSettingCollectionView": {SDKVersion: "1.0.1661.34", MinRuntimeVersion: "111.0.1661.34"},
	"ICoreWebView2Profile3": {SDKVersion: "1.0.1661.34", MinRuntimeVersion: "111.0.1661.34"},
	"ICoreWebView2Profile4": {SDKVersion: "1.0.1661.34", MinRuntimeVersion: "111.0.1661.34"},
	"ICoreWebView2SetPermissionStateCompletedHandler": {SDKVersion: "1.0.1661.34", MinRuntimeVersion: "111.0.1661.34"},
	"ICoreWebView2SharedBuffer": {SDKVersion: "1.0.1661.34", MinRuntimeVersion: "111.0.1661.34"},
	"ICoreWebView2_17": {SDKVersion: "1.0.1661.34", MinRuntimeVersion: "111.0.1661.34"},
	"ICoreWebView2Settings8": {SDKVersion: "1.0.1722.45", MinRuntimeVersion: "112.0.1722.45"},
	"ICoreWebView2File": {SDKVersion: "1.0.1774.30", MinRuntimeVersion: "113.0.1774.30"},
	"ICoreWebView2ObjectCollectionView": {SDKVersion: "1.0.1774.30", MinRuntimeVersion: "113.0.1774.30"},
	"ICoreWebView2WebMessageReceivedEventArgs2": {SDKVersion: "1.0.1774.30", MinRuntimeVersion: "113.0.1774.30"},
	"ICoreWebView2LaunchingExternalUriSchemeEventArgs": {SDKVersion: "1.0.1823.32", MinRuntimeVersion: "114.0.1823.32"},
	"ICoreWebView2LaunchingExternalUriSchemeEventHandler": {SDKVersion: "1.0.1823.32", MinRuntimeVersion: "114.0.1823.32"},
	"ICoreWebView2_18": {SDKVersion: "1.0.1823.32", MinRuntimeVersion: "114.0.1823.32"},
	"ICoreWebView2_19": {SDKVersion: "1.0.1823.32", MinRuntimeVersion: "114.0.1823.32"},
	"ICoreWebView2NavigationStartingEventArgs3": {SDKVersion: "1.0.1901.177", MinRuntimeVersion: "115.0.1901.177"},
	"ICoreWebView2NewWindowRequestedEventArgs3": {SDKVersion: "1.0.2151.40", MinRuntimeVersion: "119.0.2151.40"},
	"ICoreWebView2AcceleratorKeyPressedEventArgs2": {SDKVersion: "1.0.2210.55", MinRuntimeVersion: "120.0.2210.55"},
	"ICoreWebView2BrowserExtension": {SDKVersion: "1.0.2210.55", MinRuntimeVersion: "120.0.2210.55"},
	"ICoreWebView2BrowserExtensionEnableCompletedHandler": {SDKVersion: "1.0.2210.55", MinRuntimeVersion: "120.0.2210.55"},
	"ICoreWebView2BrowserExtensionList": {SDKVersion: "1.0.2210.55", MinRuntimeVersion: "120.0.2210.55"},
	"ICoreWebView2BrowserExtensionRemoveCompletedHandler": {SDKVersion: "1.0.2210.55", MinRuntimeVersion: "120.0.2210.55"},
	"ICoreWebView2Environment13": {SDKVersion: "1.0.2210.55", MinRuntimeVersion: "120.0.2210.55"},
	"ICoreWebView2EnvironmentOptions6": {SDKVersion: "1.0.2210.55", MinRuntimeVersion: "120.0.2210.55"},
	"ICoreWebView2Frame5": {SDKVersion: "1.0.2210.55", MinRuntimeVersion: "120.0.2210.55"},
	"ICoreWebView2FrameInfo2": {SDKVersion: "1.0.2210.55", MinRuntimeVersion: "120.0.2210.55"},
	"ICoreWebView2GetProcessExtendedInfosCompletedHandler": {SDKVersion: "1.0.2210.55", MinRuntimeVersion: "120.0.2210.55"},
	"ICoreWebView2ProcessExtendedInfo": {SDKVersion: "1.0.2210.55", MinRuntimeVersion: "120.0.2210.55"},
	"ICoreWebView2ProcessExtendedInfoCollection": {SDKVersion: "1.0.2210.55", MinRuntimeVersion: "120.0.2210.55"},
	"ICoreWebView2Profile7": {SDKVersion: "1.0.2210.55", MinRuntimeVersion: "120.0.2210.55"},
	"ICoreWebView2Profile8": {SDKVersion: "1.0.2210.55", MinRuntimeVersion: "120.0.2210.55"},
	"ICoreWebView2ProfileAddBrowserExtensionCompletedHandler": {SDKVersion: "1.0.2210.55", MinRuntimeVersion: "120.0.2210.55"},
	"ICoreWebView2ProfileDeletedEventHandler": {SDKVersion: "1.0.2210.55", MinRuntimeVersion: "120.0.2210.55"},
	"ICoreWebView2ProfileGetBrowserExtensionsCompletedHandler": {SDKVersion: "1.0.2210.55", MinRuntimeVersion: "120.0.2210.55"},
	"ICoreWebView2_20": {SDKVersion: "1.0.2210.55", MinRuntimeVersion: "120.0.2210.55"},
	"ICoreWebView2ExecuteScriptResult": {SDKVersion: "1.0.2277.86", MinRuntimeVersion: "121.0.2277.86"},
	"ICoreWebView2ExecuteScriptWithResultCompletedHandler": {SDKVersion: "1.0.2277.86", MinRuntimeVersion: "121.0.2277.86"},
	"ICoreWebView2ScriptException": {SDKVersion: "1.0.2277.86", MinRuntimeVersion: "121.0.2277.86"},
	"ICoreWebView2_21": {SDKVersion: "1.0.2277.86", MinRuntimeVersion: "121.0.2277.86"},
	"ICoreWebView2WebResourceRequestedEventArgs2": {SDKVersion: "1.0.2365.46", MinRuntimeVersion: "122.0.2365.46"},
	"ICoreWebView2_22": {SDKVersion: "1.0.2365.46", MinRuntimeVersion: "122.0.2365.46"},
	"ICoreWebView2CompositionController4": {SDKVersion: "1.0.2420.47", MinRuntimeVersion: "123.0.2420.47"},
	"ICoreWebView2NonClientRegionChangedEventArgs": {SDKVersion: "1.0.2420.47", MinRuntimeVersion: "123.0.2420.47"},
	"ICoreWebView2NonClientRegionChangedEventHandler": {SDKVersion: "1.0.2420.47", MinRuntimeVersion: "123.0.2420.47"},
	"ICoreWebView2ProcessFailedEventArgs3": {SDKVersion: "1.0.2420.47", MinRuntimeVersion: "123.0.2420.47"},
	"ICoreWebView2RegionRectCollectionView": {SDKVersion: "1.0.2420.47", MinRuntimeVersion: "123.0.2420.47"},
	"ICoreWebView2Settings9": {SDKVersion: "1.0.2420.47", MinRuntimeVersion: "123.0.2420.47"},
	"ICoreWebView2EnvironmentOptions7": {SDKVersion: "1.0.2478.35", MinRuntimeVersion: "124.0.2478.35"},
	"ICoreWebView2EnvironmentOptions8": {SDKVersion: "1.0.2535.41", MinRuntimeVersion: "125.0.2535.41"},
	"ICoreWebView2Environment14": {SDKVersion: "1.0.2651.64", MinRuntimeVersion: "127.0.2651.64"},
	"ICoreWebView2FileSystemHandle": {SDKVersion: "1.0.2651.64", MinRuntimeVersion: "127.0.2651.64"},
	"ICoreWebView2ObjectCollection": {SDKVersion: "1.0.2651.64", MinRuntimeVersion: "127.0.2651.64"},
	"ICoreWebView2_23": {SDKVersion: "1.0.2651.64", MinRuntimeVersion: "127.0.2651.64"},
	"ICoreWebView2Notification": {SDKVersion: "1.0.2739.15", MinRuntimeVersion: "128.0.2739.15"},
	"ICoreWebView2NotificationCloseRequestedEventHandler": {SDKVersion: "1.0.2739.15", MinRuntimeVersion: "128.0.2739.15"},
	"ICoreWebView2NotificationReceivedEventArgs": {SDKVersion: "1.0.2739.15", MinRuntimeVersion: "128.0.2739.15"},
	"ICoreWebView2NotificationReceivedEventHandler": {SDKVersion: "1.0.2739.15", MinRuntimeVersion: "128.0.2739.15"},
	"ICoreWebView2SaveAsUIShowingEventArgs": {SDKVersion: "1.0.2739.15", MinRuntimeVersion: "128.0.2739.15"},
	"ICoreWebView2SaveAsUIShowingEventHandler": {SDKVersion: "1.0.2739.15", MinRuntimeVersion: "128.0.2739.15"},
	"ICoreWebView2ShowSaveAsUICompletedHandler": {SDKVersion: "1.0.2739.15", MinRuntimeVersion: "128.0.2739.15"},
	"ICoreWebView2_24": {SDKVersion: "1.0.2739.15", MinRuntimeVersion: "128.0.2739.15"},
	"ICoreWebView2_25": {SDKVersion: "1.0.2739.15", MinRuntimeVersion: "128.0.2739.15"},
	"ICoreWebView2SaveFileSecurityCheckStartingEventArgs": {SDKVersion: "1.0.2849.39", MinRuntimeVersion: "130.0.2849.39"},
	"ICoreWebView2SaveFileSecurityCheckStartingEventHandler": {SDKVersion: "1.0.2849.39", MinRuntimeVersion: "130.0.2849.39"},
	"ICoreWebView2_26": {SDKVersion: "1.0.2849.39", MinRuntimeVersion: "130.0.2849.39"},
	"ICoreWebView2Frame6": {SDKVersion: "1.0.2903.40", MinRuntimeVersion: "131.0.2903.40"},
	"ICoreWebView2FrameScreenCaptureStartingEventHandler": {SDKVersion: "1.0.2903.40", MinRuntimeVersion: "131.0.2903.40"},
	"ICoreWebView2ScreenCaptureStartingEventArgs": {SDKVersion: "1.0.2903.40", MinRuntimeVersion: "131.0.2903.40"},
	"ICoreWebView2ScreenCaptureStartingEventHandler": {SDKVersion: "1.0.2903.40", MinRuntimeVersion: "131.0.2903.40"},
	"ICoreWebView2_27": {SDKVersion: "1.0.2903.40", MinRuntimeVersion: "131.0.2903.40"},
	"ICoreWebView2Frame7": {SDKVersion: "1.0.3240.44", MinRuntimeVersion: "136.0.3240.44"},
	"ICoreWebView2FrameChildFrameCreatedEventHandler": {SDKVersion: "1.0.3240.44", MinRuntimeVersion: "136.0.3240.44"},
	"ICoreWebView2ControllerOptions3": {SDKVersion: "1.0.3296.44", MinRuntimeVersion: "137.0.3296.44"},
	"ICoreWebView2ControllerOptions4": {SDKVersion: "1.0.3351.48", MinRuntimeVersion: "138.0.3351.48"},
	"ICoreWebView2Environment15": {SDKVersion: "1.0.3405.78", MinRuntimeVersion: "139.0.3405.78"},
	"ICoreWebView2Find": {SDKVersion: "1.0.3405.78", MinRuntimeVersion: "139.0.3405.78"},
	"ICoreWebView2FindActiveMatchIndexChangedEventHandler": {SDKVersion: "1.0.3405.78", MinRuntimeVersion: "139.0.3405.78"},
	"ICoreWebView2FindMatchCountChangedEventHandler": {SDKVersion: "1.0.3405.78", MinRuntimeVersion: "139.0.3405.78"},
	"ICoreWebView2FindOptions": {SDKVersion: "1.0.3405.78", MinRuntimeVersion: "139.0.3405.78"},
	"ICoreWebView2FindStartCompletedHandler": {SDKVersion: "1.0.3405.78", MinRuntimeVersion: "139.0.3405.78"},
	"ICoreWebView2_28": {SDKVersion: "1.0.3405.78", MinRuntimeVersion: "139.0.3405.78"},
	"ICoreWebView2CompositionController5": {SDKVersion: "1.0.3719.77", MinRuntimeVersion: "144.0.3719.77"},
	"ICoreWebView2CompositionControllerInterop3": {SDKVersion: "1.0.3719.77", MinRuntimeVersion: "144.0.3719.77"},
	"ICoreWebView2DragStartingEventArgs": {SDKVersion: "1.0.3719.77", MinRuntimeVersion: "144.0.3719.77"},
	"ICoreWebView2DragStartingEventHandler": {SDKVersion: "1.0.3719.77", MinRuntimeVersion: "144.0.3719.77"},
}

// SupportsInterface reports whether the installed WebView2 Runtime supports
// iface. runtimeVersion is the browser version reported by
// GetAvailableCoreWebView2BrowserVersionString (e.g. "121.0.2277.83");
// channel suffixes like " beta" are ignored. When the answer is false, the
// second return value carries the minimum runtime version required. An
// unknown interface name or an unparseable version is an error.
func SupportsInterface(runtimeVersion, iface string) (bool, string, error) {
	entry, ok := InterfaceSupportTable[iface]
	if !ok {
		return false, "", fmt.Errorf("unknown interface %q", iface)
	}
	if entry.MinRuntimeVersion == "" {
		return true, "", nil
	}
	c, err := compareVersions(runtimeVersion, entry.MinRuntimeVersion)
	if err != nil {
		return false, entry.MinRuntimeVersion, err
	}
	if c < 0 {
		return false, entry.MinRuntimeVersion, nil
	}
	return true, "", nil
}

func compareVersions(a, b string) (int, error) {
	pa, err := parseVersion(a)
	if err != nil {
		return 0, fmt.Errorf("runtime version %q: %w", a, err)
	}
	pb, err := parseVersion(b)
	if err != nil {
		return 0, fmt.Errorf("required version %q: %w", b, err)
	}
	for i := 0; i < 4; i++ {
		if pa[i] < pb[i] {
			return -1, nil
		}
		if pa[i] > pb[i] {
			return 1, nil
		}
	}
	return 0, nil
}

func parseVersion(s string) ([4]int, error) {
	var out [4]int
	// Drop a channel suffix ("1.0.515 prerelease" or "1.0.515-prerelease").
	if i := strings.IndexAny(s, " -"); i > 0 {
		s = s[:i]
	}
	parts := strings.Split(s, ".")
	if len(parts) > 4 {
		return out, fmt.Errorf("too many segments")
	}
	for i, p := range parts {
		n, err := strconv.Atoi(p)
		if err != nil {
			return out, err
		}
		out[i] = n
	}
	return out, nil
}
