//go:build windows

package webview2

type COREWEBVIEW2_CLIENT_CERTIFICATE_KIND uint32

const (
	COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_SMART_CARD = 0
	COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_PIN        = 1
	COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_OTHER      = 2
)
