//go:build windows

package webview2

type COREWEBVIEW2_TRACKING_PREVENTION_LEVEL uint32

const (
	COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_NONE     = 0
	COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_BASIC    = 1
	COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_BALANCED = 2
	COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_STRICT   = 3
)
