//go:build windows

package webview2

type COREWEBVIEW2_NAVIGATION_KIND uint32

const (
	COREWEBVIEW2_NAVIGATION_KIND_RELOAD          = 0
	COREWEBVIEW2_NAVIGATION_KIND_BACK_OR_FORWARD = 1
	COREWEBVIEW2_NAVIGATION_KIND_NEW_DOCUMENT    = 2
)
