//go:build windows

package webview2

type COREWEBVIEW2_PRINT_COLOR_MODE uint32

const (
	COREWEBVIEW2_PRINT_COLOR_MODE_DEFAULT   = 0
	COREWEBVIEW2_PRINT_COLOR_MODE_COLOR     = 1
	COREWEBVIEW2_PRINT_COLOR_MODE_GRAYSCALE = 2
)
