//go:build windows

package webview2

type COREWEBVIEW2_BROWSER_PROCESS_EXIT_KIND uint32

const (
	COREWEBVIEW2_BROWSER_PROCESS_EXIT_KIND_NORMAL = 0
	COREWEBVIEW2_BROWSER_PROCESS_EXIT_KIND_FAILED = 1
)
