//go:build windows

package webview2

type COREWEBVIEW2_SCRIPT_DIALOG_KIND uint32

const (
	COREWEBVIEW2_SCRIPT_DIALOG_KIND_ALERT        = 0
	COREWEBVIEW2_SCRIPT_DIALOG_KIND_CONFIRM      = 1
	COREWEBVIEW2_SCRIPT_DIALOG_KIND_PROMPT       = 2
	COREWEBVIEW2_SCRIPT_DIALOG_KIND_BEFOREUNLOAD = 3
)
