//go:build windows

package webview2

type COREWEBVIEW2_RELEASE_CHANNELS uint32

const (
	COREWEBVIEW2_RELEASE_CHANNELS_NONE   = 0x0
	COREWEBVIEW2_RELEASE_CHANNELS_STABLE = 0x1
	COREWEBVIEW2_RELEASE_CHANNELS_BETA   = 0x2
	COREWEBVIEW2_RELEASE_CHANNELS_DEV    = 0x4
	COREWEBVIEW2_RELEASE_CHANNELS_CANARY = 0x8
)
