//go:build windows

package webview2

type COREWEBVIEW2_PERMISSION_STATE uint32

const (
	COREWEBVIEW2_PERMISSION_STATE_DEFAULT = 0
	COREWEBVIEW2_PERMISSION_STATE_ALLOW   = 1
	COREWEBVIEW2_PERMISSION_STATE_DENY    = 2
)
