//go:build windows

package webview2

type COREWEBVIEW2_FILE_SYSTEM_HANDLE_KIND uint32

const (
	COREWEBVIEW2_FILE_SYSTEM_HANDLE_KIND_FILE      = 0
	COREWEBVIEW2_FILE_SYSTEM_HANDLE_KIND_DIRECTORY = 1
)
