//go:build windows

package webview2

type COREWEBVIEW2_PREFERRED_COLOR_SCHEME uint32

const (
	COREWEBVIEW2_PREFERRED_COLOR_SCHEME_AUTO  = 0
	COREWEBVIEW2_PREFERRED_COLOR_SCHEME_LIGHT = 1
	COREWEBVIEW2_PREFERRED_COLOR_SCHEME_DARK  = 2
)
