//go:build windows

package webview2

type COREWEBVIEW2_PRINT_DUPLEX uint32

const (
	COREWEBVIEW2_PRINT_DUPLEX_DEFAULT              = 0
	COREWEBVIEW2_PRINT_DUPLEX_ONE_SIDED            = 1
	COREWEBVIEW2_PRINT_DUPLEX_TWO_SIDED_LONG_EDGE  = 2
	COREWEBVIEW2_PRINT_DUPLEX_TWO_SIDED_SHORT_EDGE = 3
)
