//go:build windows

package webview2

type COREWEBVIEW2_WEB_ERROR_STATUS uint32

const (
	COREWEBVIEW2_WEB_ERROR_STATUS_UNKNOWN                                   = 0
	COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_COMMON_NAME_IS_INCORRECT      = 1
	COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_EXPIRED                       = 2
	COREWEBVIEW2_WEB_ERROR_STATUS_CLIENT_CERTIFICATE_CONTAINS_ERRORS        = 3
	COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_REVOKED                       = 4
	COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_IS_INVALID                    = 5
	COREWEBVIEW2_WEB_ERROR_STATUS_SERVER_UNREACHABLE                        = 6
	COREWEBVIEW2_WEB_ERROR_STATUS_TIMEOUT                                   = 7
	COREWEBVIEW2_WEB_ERROR_STATUS_ERROR_HTTP_INVALID_SERVER_RESPONSE        = 8
	COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_ABORTED                        = 9
	COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_RESET                          = 10
	COREWEBVIEW2_WEB_ERROR_STATUS_DISCONNECTED                              = 11
	COREWEBVIEW2_WEB_ERROR_STATUS_CANNOT_CONNECT                            = 12
	COREWEBVIEW2_WEB_ERROR_STATUS_HOST_NAME_NOT_RESOLVED                    = 13
	COREWEBVIEW2_WEB_ERROR_STATUS_OPERATION_CANCELED                        = 14
	COREWEBVIEW2_WEB_ERROR_STATUS_REDIRECT_FAILED                           = 15
	COREWEBVIEW2_WEB_ERROR_STATUS_UNEXPECTED_ERROR                          = 16
	COREWEBVIEW2_WEB_ERROR_STATUS_VALID_AUTHENTICATION_CREDENTIALS_REQUIRED = 17
	COREWEBVIEW2_WEB_ERROR_STATUS_VALID_PROXY_AUTHENTICATION_REQUIRED       = 18
)
