//go:build windows

package webview2

type COREWEBVIEW2_PERMISSION_KIND uint32

const (
	COREWEBVIEW2_PERMISSION_KIND_UNKNOWN_PERMISSION             = 0
	COREWEBVIEW2_PERMISSION_KIND_MICROPHONE                     = 1
	COREWEBVIEW2_PERMISSION_KIND_CAMERA                         = 2
	COREWEBVIEW2_PERMISSION_KIND_GEOLOCATION                    = 3
	COREWEBVIEW2_PERMISSION_KIND_NOTIFICATIONS                  = 4
	COREWEBVIEW2_PERMISSION_KIND_OTHER_SENSORS                  = 5
	COREWEBVIEW2_PERMISSION_KIND_CLIPBOARD_READ                 = 6
	COREWEBVIEW2_PERMISSION_KIND_MULTIPLE_AUTOMATIC_DOWNLOADS   = 7
	COREWEBVIEW2_PERMISSION_KIND_FILE_READ_WRITE                = 8
	COREWEBVIEW2_PERMISSION_KIND_AUTOPLAY                       = 9
	COREWEBVIEW2_PERMISSION_KIND_LOCAL_FONTS                    = 10
	COREWEBVIEW2_PERMISSION_KIND_MIDI_SYSTEM_EXCLUSIVE_MESSAGES = 11
	COREWEBVIEW2_PERMISSION_KIND_WINDOW_MANAGEMENT              = 12
)
