//go:build windows

package webview2

type COREWEBVIEW2_COOKIE_SAME_SITE_KIND uint32

const (
	COREWEBVIEW2_COOKIE_SAME_SITE_KIND_NONE   = 0
	COREWEBVIEW2_COOKIE_SAME_SITE_KIND_LAX    = 1
	COREWEBVIEW2_COOKIE_SAME_SITE_KIND_STRICT = 2
)
