//go:build windows

package webview2

type COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND uint32

const (
	COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_PAGE          = 0
	COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_IMAGE         = 1
	COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_SELECTED_TEXT = 2
	COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_AUDIO         = 3
	COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_VIDEO         = 4
)
