//go:build windows

package webview2

type COREWEBVIEW2_TEXT_DIRECTION_KIND uint32

const (
	COREWEBVIEW2_TEXT_DIRECTION_KIND_DEFAULT       = 0
	COREWEBVIEW2_TEXT_DIRECTION_KIND_LEFT_TO_RIGHT = 1
	COREWEBVIEW2_TEXT_DIRECTION_KIND_RIGHT_TO_LEFT = 2
)
