//go:build windows

package webview2

type COREWEBVIEW2_PRINT_COLLATION uint32

const (
	COREWEBVIEW2_PRINT_COLLATION_DEFAULT    = 0
	COREWEBVIEW2_PRINT_COLLATION_COLLATED   = 1
	COREWEBVIEW2_PRINT_COLLATION_UNCOLLATED = 2
)
