//go:build windows

package webview2

type COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND uint32

const (
	COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY      = 0
	COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_ALLOW     = 1
	COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY_CORS = 2
)
