//go:build windows

package webview2

type COREWEBVIEW2_PROCESS_FAILED_KIND uint32

const (
	COREWEBVIEW2_PROCESS_FAILED_KIND_BROWSER_PROCESS_EXITED        = 0
	COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_EXITED         = 1
	COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_UNRESPONSIVE   = 2
	COREWEBVIEW2_PROCESS_FAILED_KIND_FRAME_RENDER_PROCESS_EXITED   = 3
	COREWEBVIEW2_PROCESS_FAILED_KIND_UTILITY_PROCESS_EXITED        = 4
	COREWEBVIEW2_PROCESS_FAILED_KIND_SANDBOX_HELPER_PROCESS_EXITED = 5
	COREWEBVIEW2_PROCESS_FAILED_KIND_GPU_PROCESS_EXITED            = 6
	COREWEBVIEW2_PROCESS_FAILED_KIND_PPAPI_PLUGIN_PROCESS_EXITED   = 7
	COREWEBVIEW2_PROCESS_FAILED_KIND_PPAPI_BROKER_PROCESS_EXITED   = 8
	COREWEBVIEW2_PROCESS_FAILED_KIND_UNKNOWN_PROCESS_EXITED        = 9
)
