//go:build windows

package webview2

type COREWEBVIEW2_DOWNLOAD_STATE uint32

const (
	COREWEBVIEW2_DOWNLOAD_STATE_IN_PROGRESS = 0
	COREWEBVIEW2_DOWNLOAD_STATE_INTERRUPTED = 1
	COREWEBVIEW2_DOWNLOAD_STATE_COMPLETED   = 2
)
