//go:build windows

package webview2

type COREWEBVIEW2_FRAME_KIND uint32

const (
	COREWEBVIEW2_FRAME_KIND_UNKNOWN    = 0
	COREWEBVIEW2_FRAME_KIND_MAIN_FRAME = 1
	COREWEBVIEW2_FRAME_KIND_IFRAME     = 2
	COREWEBVIEW2_FRAME_KIND_EMBED      = 3
	COREWEBVIEW2_FRAME_KIND_OBJECT     = 4
)
