//go:build windows

package webview2

type COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON uint32

const (
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NONE                           = 0
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_FAILED                    = 1
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_ACCESS_DENIED             = 2
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_NO_SPACE                  = 3
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_NAME_TOO_LONG             = 4
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_TOO_LARGE                 = 5
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_MALICIOUS                 = 6
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_TRANSIENT_ERROR           = 7
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_BLOCKED_BY_POLICY         = 8
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_SECURITY_CHECK_FAILED     = 9
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_TOO_SHORT                 = 10
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_HASH_MISMATCH             = 11
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_FAILED                 = 12
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_TIMEOUT                = 13
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_DISCONNECTED           = 14
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_SERVER_DOWN            = 15
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_INVALID_REQUEST        = 16
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_FAILED                  = 17
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_NO_RANGE                = 18
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_BAD_CONTENT             = 19
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_UNAUTHORIZED            = 20
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_CERTIFICATE_PROBLEM     = 21
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_FORBIDDEN               = 22
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_UNEXPECTED_RESPONSE     = 23
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_CONTENT_LENGTH_MISMATCH = 24
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_CROSS_ORIGIN_REDIRECT   = 25
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_USER_CANCELED                  = 26
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_USER_SHUTDOWN                  = 27
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_USER_PAUSED                    = 28
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_DOWNLOAD_PROCESS_CRASHED       = 29
)
