//go:build windows

package webview2

type COREWEBVIEW2_BROWSING_DATA_KINDS uint32

const (
	COREWEBVIEW2_BROWSING_DATA_KINDS_FILE_SYSTEMS      = 0x1
	COREWEBVIEW2_BROWSING_DATA_KINDS_INDEXED_DB        = 0x2
	COREWEBVIEW2_BROWSING_DATA_KINDS_LOCAL_STORAGE     = 0x4
	COREWEBVIEW2_BROWSING_DATA_KINDS_WEB_SQL           = 0x8
	COREWEBVIEW2_BROWSING_DATA_KINDS_CACHE_STORAGE     = 0x10
	COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_DOM_STORAGE   = 0x20
	COREWEBVIEW2_BROWSING_DATA_KINDS_COOKIES           = 0x40
	COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_SITE          = 0x80
	COREWEBVIEW2_BROWSING_DATA_KINDS_DISK_CACHE        = 0x100
	COREWEBVIEW2_BROWSING_DATA_KINDS_DOWNLOAD_HISTORY  = 0x200
	COREWEBVIEW2_BROWSING_DATA_KINDS_GENERAL_AUTOFILL  = 0x400
	COREWEBVIEW2_BROWSING_DATA_KINDS_PASSWORD_AUTOSAVE = 0x800
	COREWEBVIEW2_BROWSING_DATA_KINDS_BROWSING_HISTORY  = 0x1000
	COREWEBVIEW2_BROWSING_DATA_KINDS_SETTINGS          = 0x2000
	COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_PROFILE       = 0x4000
	COREWEBVIEW2_BROWSING_DATA_KINDS_SERVICE_WORKERS   = 0x8000
)
