//go:build windows

package webview2

type COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT uint32

const (
	COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_PNG  = 0
	COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_JPEG = 1
)
