//go:build windows

package webview2

type COREWEBVIEW2_POINTER_EVENT_KIND uint32

const (
	COREWEBVIEW2_POINTER_EVENT_KIND_ACTIVATE = 587
	COREWEBVIEW2_POINTER_EVENT_KIND_DOWN     = 582
	COREWEBVIEW2_POINTER_EVENT_KIND_ENTER    = 585
	COREWEBVIEW2_POINTER_EVENT_KIND_LEAVE    = 586
	COREWEBVIEW2_POINTER_EVENT_KIND_UP       = 583
	COREWEBVIEW2_POINTER_EVENT_KIND_UPDATE   = 581
)
