// Package webview2 contains the WebView2 COM bindings generated from
// Microsoft's WebView2 SDK IDL. Every file in this package is
// machine-generated by `webview2gen` (see ../../scripts/cmd/webview2gen)
// except this one and comtest_support_test.go (the hand-written harness
// behind the generated *_gen_test.go suite).
//
// Do NOT hand-edit generated files — they will be overwritten on the next
// run of the generator and CI verifies they match a fresh regeneration.
// To pick up a new SDK release:
//
//	cd webview2/scripts
//	go run ./cmd/webview2gen download --version <new-version>
//	go run ./cmd/webview2gen changelog --from <old-version>
//	go run ./cmd/webview2gen generate
//	go run ./cmd/webview2gen capabilities --source test.md
//	go run ./cmd/webview2gen verify   # CI will fail otherwise
//
// Capability-aware feature gating lives in capabilities.go; consumers
// should call SupportsInterface before invoking methods that are only
// present on newer WebView2 runtime versions, passing the browser version
// reported by GetAvailableCoreWebView2BrowserVersionString.
package webview2

// The generator lives in its own module and expects to run from inside
// webview2/scripts (where the IDL cache sits), hence go run -C.
//go:generate go run -C ../../scripts ./cmd/webview2gen full --source test.md
