//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2Environment3_CreateCoreWebView2CompositionController(t *testing.T) {
	recReset()
	in1 := &ICoreWebView2CreateCoreWebView2CompositionControllerCompletedHandler{}
	want := []wordExpect{}
	want = append(want, xw(0xBEE0))
	want = append(want, ptrw(unsafe.Pointer(in1)))
	obj := &ICoreWebView2Environment3{Vtbl: &ICoreWebView2Environment3Vtbl{}}
	obj.Vtbl.CreateCoreWebView2CompositionController = recProc(1 + len(want))
	err := obj.CreateCoreWebView2CompositionController(HWND(0xBEE0), in1)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Environment3_CreateCoreWebView2PointerInfo(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWritePtr(1+len(want), fakeTargetPtr())
	want = append(want, anyw())
	obj := &ICoreWebView2Environment3{Vtbl: &ICoreWebView2Environment3Vtbl{}}
	obj.Vtbl.CreateCoreWebView2PointerInfo = recProc(1 + len(want))
	got0, err := obj.CreateCoreWebView2PointerInfo()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if unsafe.Pointer(got0) != fakeTargetPtr() {
		t.Errorf("pointer out = %v", got0)
	}
}

func TestICoreWebView2Environment3_QueryInterfaceHelper(t *testing.T) {
	recReset()
	root := &ICoreWebView2Environment{Vtbl: &ICoreWebView2EnvironmentVtbl{}}
	root.Vtbl.QueryInterface = recProc(3)
	recCaptureGUID(1)
	recWritePtr(2, fakeTargetPtr())
	got, err := root.GetICoreWebView2Environment3()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if unsafe.Pointer(got) != fakeTargetPtr() {
		t.Errorf("returned pointer %p, want fake target", got)
	}
	if g := recCapturedGUID(1); g != "80a22ae3-be7c-4ce2-afe1-5a50056cdeeb" {
		t.Errorf("queried IID %s, want %s", g, "80a22ae3-be7c-4ce2-afe1-5a50056cdeeb")
	}
}
