//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"math"
	"testing"
	"unsafe"
)

func TestICoreWebView2ClientCertificate_GetSubject(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2ClientCertificate{Vtbl: &ICoreWebView2ClientCertificateVtbl{}}
	obj.Vtbl.GetSubject = recProc(1 + len(want))
	got0, err := obj.GetSubject()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2ClientCertificate_GetIssuer(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2ClientCertificate{Vtbl: &ICoreWebView2ClientCertificateVtbl{}}
	obj.Vtbl.GetIssuer = recProc(1 + len(want))
	got0, err := obj.GetIssuer()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2ClientCertificate_GetValidFrom(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite64(1+len(want), math.Float64bits(3.25))
	want = append(want, anyw())
	obj := &ICoreWebView2ClientCertificate{Vtbl: &ICoreWebView2ClientCertificateVtbl{}}
	obj.Vtbl.GetValidFrom = recProc(1 + len(want))
	got0, err := obj.GetValidFrom()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != 3.25 {
		t.Errorf("float64 out = %v, want 3.25", got0)
	}
}

func TestICoreWebView2ClientCertificate_GetValidTo(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite64(1+len(want), math.Float64bits(3.25))
	want = append(want, anyw())
	obj := &ICoreWebView2ClientCertificate{Vtbl: &ICoreWebView2ClientCertificateVtbl{}}
	obj.Vtbl.GetValidTo = recProc(1 + len(want))
	got0, err := obj.GetValidTo()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != 3.25 {
		t.Errorf("float64 out = %v, want 3.25", got0)
	}
}

func TestICoreWebView2ClientCertificate_GetDerEncodedSerialNumber(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2ClientCertificate{Vtbl: &ICoreWebView2ClientCertificateVtbl{}}
	obj.Vtbl.GetDerEncodedSerialNumber = recProc(1 + len(want))
	got0, err := obj.GetDerEncodedSerialNumber()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2ClientCertificate_GetDisplayName(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2ClientCertificate{Vtbl: &ICoreWebView2ClientCertificateVtbl{}}
	obj.Vtbl.GetDisplayName = recProc(1 + len(want))
	got0, err := obj.GetDisplayName()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2ClientCertificate_ToPemEncoding(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2ClientCertificate{Vtbl: &ICoreWebView2ClientCertificateVtbl{}}
	obj.Vtbl.ToPemEncoding = recProc(1 + len(want))
	got0, err := obj.ToPemEncoding()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2ClientCertificate_GetPemEncodedIssuerCertificateChain(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWritePtr(1+len(want), fakeTargetPtr())
	want = append(want, anyw())
	obj := &ICoreWebView2ClientCertificate{Vtbl: &ICoreWebView2ClientCertificateVtbl{}}
	obj.Vtbl.GetPemEncodedIssuerCertificateChain = recProc(1 + len(want))
	got0, err := obj.GetPemEncodedIssuerCertificateChain()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if unsafe.Pointer(got0) != fakeTargetPtr() {
		t.Errorf("pointer out = %v", got0)
	}
}

func TestICoreWebView2ClientCertificate_GetKind(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 0x0AFE00)
	want = append(want, anyw())
	obj := &ICoreWebView2ClientCertificate{Vtbl: &ICoreWebView2ClientCertificateVtbl{}}
	obj.Vtbl.GetKind = recProc(1 + len(want))
	got0, err := obj.GetKind()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != COREWEBVIEW2_CLIENT_CERTIFICATE_KIND(0x0AFE00) {
		t.Errorf("scalar out = %v, want 0x0AFE00", got0)
	}
}
