//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2ContextMenuItemCollection_GetCount(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 0x0AFE00)
	want = append(want, anyw())
	obj := &ICoreWebView2ContextMenuItemCollection{Vtbl: &ICoreWebView2ContextMenuItemCollectionVtbl{}}
	obj.Vtbl.GetCount = recProc(1 + len(want))
	got0, err := obj.GetCount()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != uint32(0x0AFE00) {
		t.Errorf("scalar out = %v, want 0x0AFE00", got0)
	}
}

func TestICoreWebView2ContextMenuItemCollection_GetValueAtIndex(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(40))
	recWritePtr(1+len(want), fakeTargetPtr())
	want = append(want, anyw())
	obj := &ICoreWebView2ContextMenuItemCollection{Vtbl: &ICoreWebView2ContextMenuItemCollectionVtbl{}}
	obj.Vtbl.GetValueAtIndex = recProc(1 + len(want))
	got0, err := obj.GetValueAtIndex(uint32(40))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if unsafe.Pointer(got0) != fakeTargetPtr() {
		t.Errorf("pointer out = %v", got0)
	}
}

func TestICoreWebView2ContextMenuItemCollection_RemoveValueAtIndex(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(40))
	obj := &ICoreWebView2ContextMenuItemCollection{Vtbl: &ICoreWebView2ContextMenuItemCollectionVtbl{}}
	obj.Vtbl.RemoveValueAtIndex = recProc(1 + len(want))
	err := obj.RemoveValueAtIndex(uint32(40))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2ContextMenuItemCollection_InsertValueAtIndex(t *testing.T) {
	recReset()
	in1 := &ICoreWebView2ContextMenuItem{}
	want := []wordExpect{}
	want = append(want, xw(40))
	want = append(want, ptrw(unsafe.Pointer(in1)))
	obj := &ICoreWebView2ContextMenuItemCollection{Vtbl: &ICoreWebView2ContextMenuItemCollectionVtbl{}}
	obj.Vtbl.InsertValueAtIndex = recProc(1 + len(want))
	err := obj.InsertValueAtIndex(uint32(40), in1)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}
