//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"math"
	"testing"
	"unsafe"
)

func TestICoreWebView2Cookie_GetName(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2Cookie{Vtbl: &ICoreWebView2CookieVtbl{}}
	obj.Vtbl.GetName = recProc(1 + len(want))
	got0, err := obj.GetName()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2Cookie_GetValue(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2Cookie{Vtbl: &ICoreWebView2CookieVtbl{}}
	obj.Vtbl.GetValue = recProc(1 + len(want))
	got0, err := obj.GetValue()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2Cookie_PutValue(t *testing.T) {
	recReset()
	want := []wordExpect{}
	capIdx0 := 1 + len(want)
	recCaptureUTF16(capIdx0)
	want = append(want, anyw())
	obj := &ICoreWebView2Cookie{Vtbl: &ICoreWebView2CookieVtbl{}}
	obj.Vtbl.PutValue = recProc(1 + len(want))
	err := obj.PutValue("wv2-in-0")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got := recCapturedString(capIdx0); got != "wv2-in-0" {
		t.Errorf("string arg %d marshalled as %q, want wv2-in-0", 0, got)
	}
}

func TestICoreWebView2Cookie_GetDomain(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2Cookie{Vtbl: &ICoreWebView2CookieVtbl{}}
	obj.Vtbl.GetDomain = recProc(1 + len(want))
	got0, err := obj.GetDomain()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2Cookie_GetPath(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2Cookie{Vtbl: &ICoreWebView2CookieVtbl{}}
	obj.Vtbl.GetPath = recProc(1 + len(want))
	got0, err := obj.GetPath()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2Cookie_GetExpires(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite64(1+len(want), math.Float64bits(3.25))
	want = append(want, anyw())
	obj := &ICoreWebView2Cookie{Vtbl: &ICoreWebView2CookieVtbl{}}
	obj.Vtbl.GetExpires = recProc(1 + len(want))
	got0, err := obj.GetExpires()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != 3.25 {
		t.Errorf("float64 out = %v, want 3.25", got0)
	}
}

func TestICoreWebView2Cookie_PutExpires(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, f64w(1.5)...)
	obj := &ICoreWebView2Cookie{Vtbl: &ICoreWebView2CookieVtbl{}}
	obj.Vtbl.PutExpires = recProc(1 + len(want))
	err := obj.PutExpires(1.5)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Cookie_GetIsHttpOnly(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2Cookie{Vtbl: &ICoreWebView2CookieVtbl{}}
	obj.Vtbl.GetIsHttpOnly = recProc(1 + len(want))
	got0, err := obj.GetIsHttpOnly()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2Cookie_PutIsHttpOnly(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2Cookie{Vtbl: &ICoreWebView2CookieVtbl{}}
	obj.Vtbl.PutIsHttpOnly = recProc(1 + len(want))
	err := obj.PutIsHttpOnly(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Cookie_GetSameSite(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 0x0AFE00)
	want = append(want, anyw())
	obj := &ICoreWebView2Cookie{Vtbl: &ICoreWebView2CookieVtbl{}}
	obj.Vtbl.GetSameSite = recProc(1 + len(want))
	got0, err := obj.GetSameSite()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != COREWEBVIEW2_COOKIE_SAME_SITE_KIND(0x0AFE00) {
		t.Errorf("scalar out = %v, want 0x0AFE00", got0)
	}
}

func TestICoreWebView2Cookie_PutSameSite(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(3))
	obj := &ICoreWebView2Cookie{Vtbl: &ICoreWebView2CookieVtbl{}}
	obj.Vtbl.PutSameSite = recProc(1 + len(want))
	err := obj.PutSameSite(COREWEBVIEW2_COOKIE_SAME_SITE_KIND(3))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Cookie_GetIsSecure(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2Cookie{Vtbl: &ICoreWebView2CookieVtbl{}}
	obj.Vtbl.GetIsSecure = recProc(1 + len(want))
	got0, err := obj.GetIsSecure()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2Cookie_PutIsSecure(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2Cookie{Vtbl: &ICoreWebView2CookieVtbl{}}
	obj.Vtbl.PutIsSecure = recProc(1 + len(want))
	err := obj.PutIsSecure(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Cookie_GetIsSession(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2Cookie{Vtbl: &ICoreWebView2CookieVtbl{}}
	obj.Vtbl.GetIsSession = recProc(1 + len(want))
	got0, err := obj.GetIsSession()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}
