//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2WebMessageReceivedEventArgs2_GetAdditionalObjects(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWritePtr(1+len(want), fakeTargetPtr())
	want = append(want, anyw())
	obj := &ICoreWebView2WebMessageReceivedEventArgs2{Vtbl: &ICoreWebView2WebMessageReceivedEventArgs2Vtbl{}}
	obj.Vtbl.GetAdditionalObjects = recProc(1 + len(want))
	got0, err := obj.GetAdditionalObjects()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if unsafe.Pointer(got0) != fakeTargetPtr() {
		t.Errorf("pointer out = %v", got0)
	}
}

func TestICoreWebView2WebMessageReceivedEventArgs2_QueryInterfaceHelper(t *testing.T) {
	recReset()
	root := &ICoreWebView2WebMessageReceivedEventArgs{Vtbl: &ICoreWebView2WebMessageReceivedEventArgsVtbl{}}
	root.Vtbl.QueryInterface = recProc(3)
	recCaptureGUID(1)
	recWritePtr(2, fakeTargetPtr())
	got, err := root.GetICoreWebView2WebMessageReceivedEventArgs2()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if unsafe.Pointer(got) != fakeTargetPtr() {
		t.Errorf("returned pointer %p, want fake target", got)
	}
	if g := recCapturedGUID(1); g != "06fc7ab7-c90c-4297-9389-33ca01cf6d5e" {
		t.Errorf("queried IID %s, want %s", g, "06fc7ab7-c90c-4297-9389-33ca01cf6d5e")
	}
}
