//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2ContentLoadingEventArgs_GetIsErrorPage(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2ContentLoadingEventArgs{Vtbl: &ICoreWebView2ContentLoadingEventArgsVtbl{}}
	obj.Vtbl.GetIsErrorPage = recProc(1 + len(want))
	got0, err := obj.GetIsErrorPage()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2ContentLoadingEventArgs_GetNavigationId(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite64(1+len(want), 0x55667788AA00)
	want = append(want, anyw())
	obj := &ICoreWebView2ContentLoadingEventArgs{Vtbl: &ICoreWebView2ContentLoadingEventArgsVtbl{}}
	obj.Vtbl.GetNavigationId = recProc(1 + len(want))
	got0, err := obj.GetNavigationId()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != uint64(0x55667788AA00) {
		t.Errorf("64-bit out = %v", got0)
	}
}
