//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2WebResourceResponseReceivedEventArgs_GetRequest(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWritePtr(1+len(want), fakeTargetPtr())
	want = append(want, anyw())
	obj := &ICoreWebView2WebResourceResponseReceivedEventArgs{Vtbl: &ICoreWebView2WebResourceResponseReceivedEventArgsVtbl{}}
	obj.Vtbl.GetRequest = recProc(1 + len(want))
	got0, err := obj.GetRequest()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if unsafe.Pointer(got0) != fakeTargetPtr() {
		t.Errorf("pointer out = %v", got0)
	}
}

func TestICoreWebView2WebResourceResponseReceivedEventArgs_GetResponse(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWritePtr(1+len(want), fakeTargetPtr())
	want = append(want, anyw())
	obj := &ICoreWebView2WebResourceResponseReceivedEventArgs{Vtbl: &ICoreWebView2WebResourceResponseReceivedEventArgsVtbl{}}
	obj.Vtbl.GetResponse = recProc(1 + len(want))
	got0, err := obj.GetResponse()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if unsafe.Pointer(got0) != fakeTargetPtr() {
		t.Errorf("pointer out = %v", got0)
	}
}
