//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2_20_GetFrameId(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 0x0AFE00)
	want = append(want, anyw())
	obj := &ICoreWebView2_20{Vtbl: &ICoreWebView2_20Vtbl{}}
	obj.Vtbl.GetFrameId = recProc(1 + len(want))
	got0, err := obj.GetFrameId()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != uint32(0x0AFE00) {
		t.Errorf("scalar out = %v, want 0x0AFE00", got0)
	}
}

func TestICoreWebView2_20_QueryInterfaceHelper(t *testing.T) {
	recReset()
	root := &ICoreWebView2{Vtbl: &ICoreWebView2Vtbl{}}
	root.Vtbl.QueryInterface = recProc(3)
	recCaptureGUID(1)
	recWritePtr(2, fakeTargetPtr())
	got, err := root.GetICoreWebView2_20()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if unsafe.Pointer(got) != fakeTargetPtr() {
		t.Errorf("returned pointer %p, want fake target", got)
	}
	if g := recCapturedGUID(1); g != "b4bc1926-7305-11ee-b962-0242ac120002" {
		t.Errorf("queried IID %s, want %s", g, "b4bc1926-7305-11ee-b962-0242ac120002")
	}
}
