//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2CustomSchemeRegistration_GetSchemeName(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2CustomSchemeRegistration{Vtbl: &ICoreWebView2CustomSchemeRegistrationVtbl{}}
	obj.Vtbl.GetSchemeName = recProc(1 + len(want))
	got0, err := obj.GetSchemeName()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2CustomSchemeRegistration_GetTreatAsSecure(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2CustomSchemeRegistration{Vtbl: &ICoreWebView2CustomSchemeRegistrationVtbl{}}
	obj.Vtbl.GetTreatAsSecure = recProc(1 + len(want))
	got0, err := obj.GetTreatAsSecure()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2CustomSchemeRegistration_PutTreatAsSecure(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2CustomSchemeRegistration{Vtbl: &ICoreWebView2CustomSchemeRegistrationVtbl{}}
	obj.Vtbl.PutTreatAsSecure = recProc(1 + len(want))
	err := obj.PutTreatAsSecure(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2CustomSchemeRegistration_GetAllowedOrigins(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 2)
	want = append(want, anyw())
	recWriteUTF16Array(1+len(want), []string{"wv2-arr-0", "wv2-arr-1"})
	want = append(want, anyw())
	obj := &ICoreWebView2CustomSchemeRegistration{Vtbl: &ICoreWebView2CustomSchemeRegistrationVtbl{}}
	obj.Vtbl.GetAllowedOrigins = recProc(1 + len(want))
	got0, got1, err := obj.GetAllowedOrigins()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != uint32(2) {
		t.Errorf("count out = %v, want 2", got0)
	}
	if len(got1) != 2 || got1[0] != "wv2-arr-0" || got1[1] != "wv2-arr-1" {
		t.Errorf("string array out = %q", got1)
	}
}

func TestICoreWebView2CustomSchemeRegistration_SetAllowedOrigins(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(40))
	want = append(want, xw(0))
	obj := &ICoreWebView2CustomSchemeRegistration{Vtbl: &ICoreWebView2CustomSchemeRegistrationVtbl{}}
	obj.Vtbl.SetAllowedOrigins = recProc(1 + len(want))
	err := obj.SetAllowedOrigins(uint32(40), nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2CustomSchemeRegistration_GetHasAuthorityComponent(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2CustomSchemeRegistration{Vtbl: &ICoreWebView2CustomSchemeRegistrationVtbl{}}
	obj.Vtbl.GetHasAuthorityComponent = recProc(1 + len(want))
	got0, err := obj.GetHasAuthorityComponent()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2CustomSchemeRegistration_PutHasAuthorityComponent(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2CustomSchemeRegistration{Vtbl: &ICoreWebView2CustomSchemeRegistrationVtbl{}}
	obj.Vtbl.PutHasAuthorityComponent = recProc(1 + len(want))
	err := obj.PutHasAuthorityComponent(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}
