//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

type stubICoreWebView2ShowSaveAsUICompletedHandlerImpl struct {
	got_errorCode uintptr
	got_result COREWEBVIEW2_SAVE_AS_UI_RESULT
	called bool
}

func (s *stubICoreWebView2ShowSaveAsUICompletedHandlerImpl) QueryInterface(refiid, object uintptr) uintptr { return 0 }
func (s *stubICoreWebView2ShowSaveAsUICompletedHandlerImpl) AddRef() uint32  { return 1 }
func (s *stubICoreWebView2ShowSaveAsUICompletedHandlerImpl) Release() uint32 { return 1 }
func (s *stubICoreWebView2ShowSaveAsUICompletedHandlerImpl) ShowSaveAsUICompleted(errorCode uintptr, result COREWEBVIEW2_SAVE_AS_UI_RESULT) uintptr {
	s.got_errorCode = errorCode
	s.got_result = result
	s.called = true
	return 0x42
}

func TestICoreWebView2ShowSaveAsUICompletedHandler_InvokeDispatch(t *testing.T) {
	stub := &stubICoreWebView2ShowSaveAsUICompletedHandlerImpl{}
	h := NewICoreWebView2ShowSaveAsUICompletedHandler(stub)
	hr, _, _ := h.Vtbl.Invoke.Call(
		uintptr(unsafe.Pointer(h)),
		uintptr(50),
		uintptr(4),
	)
	if hr != 0x42 {
		t.Errorf("Invoke returned %#x, want 0x42 (impl return value)", hr)
	}
	if !stub.called {
		t.Fatal("impl was not called")
	}
	if stub.got_errorCode != uintptr(50) {
		t.Errorf("numeric arg = %v, want 50", stub.got_errorCode)
	}
	if stub.got_result != COREWEBVIEW2_SAVE_AS_UI_RESULT(4) {
		t.Errorf("enum arg = %v, want 4", stub.got_result)
	}
}
