//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2Settings4_GetIsPasswordAutosaveEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2Settings4{Vtbl: &ICoreWebView2Settings4Vtbl{}}
	obj.Vtbl.GetIsPasswordAutosaveEnabled = recProc(1 + len(want))
	got0, err := obj.GetIsPasswordAutosaveEnabled()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2Settings4_PutIsPasswordAutosaveEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2Settings4{Vtbl: &ICoreWebView2Settings4Vtbl{}}
	obj.Vtbl.PutIsPasswordAutosaveEnabled = recProc(1 + len(want))
	err := obj.PutIsPasswordAutosaveEnabled(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Settings4_GetIsGeneralAutofillEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2Settings4{Vtbl: &ICoreWebView2Settings4Vtbl{}}
	obj.Vtbl.GetIsGeneralAutofillEnabled = recProc(1 + len(want))
	got0, err := obj.GetIsGeneralAutofillEnabled()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2Settings4_PutIsGeneralAutofillEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2Settings4{Vtbl: &ICoreWebView2Settings4Vtbl{}}
	obj.Vtbl.PutIsGeneralAutofillEnabled = recProc(1 + len(want))
	err := obj.PutIsGeneralAutofillEnabled(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Settings4_QueryInterfaceHelper(t *testing.T) {
	recReset()
	root := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	root.Vtbl.QueryInterface = recProc(3)
	recCaptureGUID(1)
	recWritePtr(2, fakeTargetPtr())
	got, err := root.GetICoreWebView2Settings4()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if unsafe.Pointer(got) != fakeTargetPtr() {
		t.Errorf("returned pointer %p, want fake target", got)
	}
	if g := recCapturedGUID(1); g != "cb56846c-4168-4d53-b04f-03b6d6796ff2" {
		t.Errorf("queried IID %s, want %s", g, "cb56846c-4168-4d53-b04f-03b6d6796ff2")
	}
}
