//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2FindOptions_GetFindTerm(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2FindOptions{Vtbl: &ICoreWebView2FindOptionsVtbl{}}
	obj.Vtbl.GetFindTerm = recProc(1 + len(want))
	got0, err := obj.GetFindTerm()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2FindOptions_PutFindTerm(t *testing.T) {
	recReset()
	want := []wordExpect{}
	capIdx0 := 1 + len(want)
	recCaptureUTF16(capIdx0)
	want = append(want, anyw())
	obj := &ICoreWebView2FindOptions{Vtbl: &ICoreWebView2FindOptionsVtbl{}}
	obj.Vtbl.PutFindTerm = recProc(1 + len(want))
	err := obj.PutFindTerm("wv2-in-0")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got := recCapturedString(capIdx0); got != "wv2-in-0" {
		t.Errorf("string arg %d marshalled as %q, want wv2-in-0", 0, got)
	}
}

func TestICoreWebView2FindOptions_GetIsCaseSensitive(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2FindOptions{Vtbl: &ICoreWebView2FindOptionsVtbl{}}
	obj.Vtbl.GetIsCaseSensitive = recProc(1 + len(want))
	got0, err := obj.GetIsCaseSensitive()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2FindOptions_PutIsCaseSensitive(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2FindOptions{Vtbl: &ICoreWebView2FindOptionsVtbl{}}
	obj.Vtbl.PutIsCaseSensitive = recProc(1 + len(want))
	err := obj.PutIsCaseSensitive(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2FindOptions_GetShouldHighlightAllMatches(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2FindOptions{Vtbl: &ICoreWebView2FindOptionsVtbl{}}
	obj.Vtbl.GetShouldHighlightAllMatches = recProc(1 + len(want))
	got0, err := obj.GetShouldHighlightAllMatches()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2FindOptions_PutShouldHighlightAllMatches(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2FindOptions{Vtbl: &ICoreWebView2FindOptionsVtbl{}}
	obj.Vtbl.PutShouldHighlightAllMatches = recProc(1 + len(want))
	err := obj.PutShouldHighlightAllMatches(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2FindOptions_GetShouldMatchWord(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2FindOptions{Vtbl: &ICoreWebView2FindOptionsVtbl{}}
	obj.Vtbl.GetShouldMatchWord = recProc(1 + len(want))
	got0, err := obj.GetShouldMatchWord()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2FindOptions_PutShouldMatchWord(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2FindOptions{Vtbl: &ICoreWebView2FindOptionsVtbl{}}
	obj.Vtbl.PutShouldMatchWord = recProc(1 + len(want))
	err := obj.PutShouldMatchWord(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2FindOptions_GetSuppressDefaultFindDialog(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2FindOptions{Vtbl: &ICoreWebView2FindOptionsVtbl{}}
	obj.Vtbl.GetSuppressDefaultFindDialog = recProc(1 + len(want))
	got0, err := obj.GetSuppressDefaultFindDialog()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2FindOptions_PutSuppressDefaultFindDialog(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2FindOptions{Vtbl: &ICoreWebView2FindOptionsVtbl{}}
	obj.Vtbl.PutSuppressDefaultFindDialog = recProc(1 + len(want))
	err := obj.PutSuppressDefaultFindDialog(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}
