//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2DevToolsProtocolEventReceiver_AddDevToolsProtocolEventReceived(t *testing.T) {
	recReset()
	in0 := &ICoreWebView2DevToolsProtocolEventReceivedEventHandler{}
	want := []wordExpect{}
	want = append(want, ptrw(unsafe.Pointer(in0)))
	recWrite64(1+len(want), 0x101112131400)
	want = append(want, anyw())
	obj := &ICoreWebView2DevToolsProtocolEventReceiver{Vtbl: &ICoreWebView2DevToolsProtocolEventReceiverVtbl{}}
	obj.Vtbl.AddDevToolsProtocolEventReceived = recProc(1 + len(want))
	got0, err := obj.AddDevToolsProtocolEventReceived(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if tokenBits(got0) != 0x101112131400 {
		t.Errorf("token out = %x, want 0x101112131400", tokenBits(got0))
	}
}

func TestICoreWebView2DevToolsProtocolEventReceiver_RemoveDevToolsProtocolEventReceived(t *testing.T) {
	recReset()
	in0 := makeToken(0x0102030405060708)
	want := []wordExpect{}
	want = append(want, u64w(0x0102030405060708)...)
	obj := &ICoreWebView2DevToolsProtocolEventReceiver{Vtbl: &ICoreWebView2DevToolsProtocolEventReceiverVtbl{}}
	obj.Vtbl.RemoveDevToolsProtocolEventReceived = recProc(1 + len(want))
	err := obj.RemoveDevToolsProtocolEventReceived(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}
