//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2_2_AddWebResourceResponseReceived(t *testing.T) {
	recReset()
	in0 := &ICoreWebView2WebResourceResponseReceivedEventHandler{}
	want := []wordExpect{}
	want = append(want, ptrw(unsafe.Pointer(in0)))
	recWrite64(1+len(want), 0x101112131400)
	want = append(want, anyw())
	obj := &ICoreWebView2_2{Vtbl: &ICoreWebView2_2Vtbl{}}
	obj.Vtbl.AddWebResourceResponseReceived = recProc(1 + len(want))
	got0, err := obj.AddWebResourceResponseReceived(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if tokenBits(got0) != 0x101112131400 {
		t.Errorf("token out = %x, want 0x101112131400", tokenBits(got0))
	}
}

func TestICoreWebView2_2_RemoveWebResourceResponseReceived(t *testing.T) {
	recReset()
	in0 := makeToken(0x0102030405060708)
	want := []wordExpect{}
	want = append(want, u64w(0x0102030405060708)...)
	obj := &ICoreWebView2_2{Vtbl: &ICoreWebView2_2Vtbl{}}
	obj.Vtbl.RemoveWebResourceResponseReceived = recProc(1 + len(want))
	err := obj.RemoveWebResourceResponseReceived(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2_2_NavigateWithWebResourceRequest(t *testing.T) {
	recReset()
	in0 := &ICoreWebView2WebResourceRequest{}
	want := []wordExpect{}
	want = append(want, ptrw(unsafe.Pointer(in0)))
	obj := &ICoreWebView2_2{Vtbl: &ICoreWebView2_2Vtbl{}}
	obj.Vtbl.NavigateWithWebResourceRequest = recProc(1 + len(want))
	err := obj.NavigateWithWebResourceRequest(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2_2_AddDOMContentLoaded(t *testing.T) {
	recReset()
	in0 := &ICoreWebView2DOMContentLoadedEventHandler{}
	want := []wordExpect{}
	want = append(want, ptrw(unsafe.Pointer(in0)))
	recWrite64(1+len(want), 0x101112131400)
	want = append(want, anyw())
	obj := &ICoreWebView2_2{Vtbl: &ICoreWebView2_2Vtbl{}}
	obj.Vtbl.AddDOMContentLoaded = recProc(1 + len(want))
	got0, err := obj.AddDOMContentLoaded(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if tokenBits(got0) != 0x101112131400 {
		t.Errorf("token out = %x, want 0x101112131400", tokenBits(got0))
	}
}

func TestICoreWebView2_2_RemoveDOMContentLoaded(t *testing.T) {
	recReset()
	in0 := makeToken(0x0102030405060708)
	want := []wordExpect{}
	want = append(want, u64w(0x0102030405060708)...)
	obj := &ICoreWebView2_2{Vtbl: &ICoreWebView2_2Vtbl{}}
	obj.Vtbl.RemoveDOMContentLoaded = recProc(1 + len(want))
	err := obj.RemoveDOMContentLoaded(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2_2_GetCookieManager(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWritePtr(1+len(want), fakeTargetPtr())
	want = append(want, anyw())
	obj := &ICoreWebView2_2{Vtbl: &ICoreWebView2_2Vtbl{}}
	obj.Vtbl.GetCookieManager = recProc(1 + len(want))
	got0, err := obj.GetCookieManager()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if unsafe.Pointer(got0) != fakeTargetPtr() {
		t.Errorf("pointer out = %v", got0)
	}
}

func TestICoreWebView2_2_GetEnvironment(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWritePtr(1+len(want), fakeTargetPtr())
	want = append(want, anyw())
	obj := &ICoreWebView2_2{Vtbl: &ICoreWebView2_2Vtbl{}}
	obj.Vtbl.GetEnvironment = recProc(1 + len(want))
	got0, err := obj.GetEnvironment()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if unsafe.Pointer(got0) != fakeTargetPtr() {
		t.Errorf("pointer out = %v", got0)
	}
}

func TestICoreWebView2_2_QueryInterfaceHelper(t *testing.T) {
	recReset()
	root := &ICoreWebView2{Vtbl: &ICoreWebView2Vtbl{}}
	root.Vtbl.QueryInterface = recProc(3)
	recCaptureGUID(1)
	recWritePtr(2, fakeTargetPtr())
	got, err := root.GetICoreWebView2_2()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if unsafe.Pointer(got) != fakeTargetPtr() {
		t.Errorf("returned pointer %p, want fake target", got)
	}
	if g := recCapturedGUID(1); g != "9e8f0cf8-e670-4b5e-b2bc-73e061e3184c" {
		t.Errorf("queried IID %s, want %s", g, "9e8f0cf8-e670-4b5e-b2bc-73e061e3184c")
	}
}
