//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2Settings8_GetIsReputationCheckingRequired(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2Settings8{Vtbl: &ICoreWebView2Settings8Vtbl{}}
	obj.Vtbl.GetIsReputationCheckingRequired = recProc(1 + len(want))
	got0, err := obj.GetIsReputationCheckingRequired()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2Settings8_PutIsReputationCheckingRequired(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2Settings8{Vtbl: &ICoreWebView2Settings8Vtbl{}}
	obj.Vtbl.PutIsReputationCheckingRequired = recProc(1 + len(want))
	err := obj.PutIsReputationCheckingRequired(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Settings8_QueryInterfaceHelper(t *testing.T) {
	recReset()
	root := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	root.Vtbl.QueryInterface = recProc(3)
	recCaptureGUID(1)
	recWritePtr(2, fakeTargetPtr())
	got, err := root.GetICoreWebView2Settings8()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if unsafe.Pointer(got) != fakeTargetPtr() {
		t.Errorf("returned pointer %p, want fake target", got)
	}
	if g := recCapturedGUID(1); g != "9e6b0e8f-86ad-4e81-8147-a9b5edb68650" {
		t.Errorf("queried IID %s, want %s", g, "9e6b0e8f-86ad-4e81-8147-a9b5edb68650")
	}
}
