//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

type stubICoreWebView2CapturePreviewCompletedHandlerImpl struct {
	got_errorCode uintptr
	called bool
}

func (s *stubICoreWebView2CapturePreviewCompletedHandlerImpl) QueryInterface(refiid, object uintptr) uintptr { return 0 }
func (s *stubICoreWebView2CapturePreviewCompletedHandlerImpl) AddRef() uint32  { return 1 }
func (s *stubICoreWebView2CapturePreviewCompletedHandlerImpl) Release() uint32 { return 1 }
func (s *stubICoreWebView2CapturePreviewCompletedHandlerImpl) CapturePreviewCompleted(errorCode uintptr) uintptr {
	s.got_errorCode = errorCode
	s.called = true
	return 0x42
}

func TestICoreWebView2CapturePreviewCompletedHandler_InvokeDispatch(t *testing.T) {
	stub := &stubICoreWebView2CapturePreviewCompletedHandlerImpl{}
	h := NewICoreWebView2CapturePreviewCompletedHandler(stub)
	hr, _, _ := h.Vtbl.Invoke.Call(
		uintptr(unsafe.Pointer(h)),
		uintptr(50),
	)
	if hr != 0x42 {
		t.Errorf("Invoke returned %#x, want 0x42 (impl return value)", hr)
	}
	if !stub.called {
		t.Fatal("impl was not called")
	}
	if stub.got_errorCode != uintptr(50) {
		t.Errorf("numeric arg = %v, want 50", stub.got_errorCode)
	}
}
