//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2PermissionSetting_GetPermissionKind(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 0x0AFE00)
	want = append(want, anyw())
	obj := &ICoreWebView2PermissionSetting{Vtbl: &ICoreWebView2PermissionSettingVtbl{}}
	obj.Vtbl.GetPermissionKind = recProc(1 + len(want))
	got0, err := obj.GetPermissionKind()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != COREWEBVIEW2_PERMISSION_KIND(0x0AFE00) {
		t.Errorf("scalar out = %v, want 0x0AFE00", got0)
	}
}

func TestICoreWebView2PermissionSetting_GetPermissionOrigin(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2PermissionSetting{Vtbl: &ICoreWebView2PermissionSettingVtbl{}}
	obj.Vtbl.GetPermissionOrigin = recProc(1 + len(want))
	got0, err := obj.GetPermissionOrigin()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2PermissionSetting_GetPermissionState(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 0x0AFE00)
	want = append(want, anyw())
	obj := &ICoreWebView2PermissionSetting{Vtbl: &ICoreWebView2PermissionSettingVtbl{}}
	obj.Vtbl.GetPermissionState = recProc(1 + len(want))
	got0, err := obj.GetPermissionState()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != COREWEBVIEW2_PERMISSION_STATE(0x0AFE00) {
		t.Errorf("scalar out = %v, want 0x0AFE00", got0)
	}
}
