//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2Environment13_GetProcessExtendedInfos(t *testing.T) {
	recReset()
	in0 := &ICoreWebView2GetProcessExtendedInfosCompletedHandler{}
	want := []wordExpect{}
	want = append(want, ptrw(unsafe.Pointer(in0)))
	obj := &ICoreWebView2Environment13{Vtbl: &ICoreWebView2Environment13Vtbl{}}
	obj.Vtbl.GetProcessExtendedInfos = recProc(1 + len(want))
	err := obj.GetProcessExtendedInfos(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Environment13_QueryInterfaceHelper(t *testing.T) {
	recReset()
	root := &ICoreWebView2Environment{Vtbl: &ICoreWebView2EnvironmentVtbl{}}
	root.Vtbl.QueryInterface = recProc(3)
	recCaptureGUID(1)
	recWritePtr(2, fakeTargetPtr())
	got, err := root.GetICoreWebView2Environment13()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if unsafe.Pointer(got) != fakeTargetPtr() {
		t.Errorf("returned pointer %p, want fake target", got)
	}
	if g := recCapturedGUID(1); g != "af641f58-72b2-11ee-b962-0242ac120002" {
		t.Errorf("queried IID %s, want %s", g, "af641f58-72b2-11ee-b962-0242ac120002")
	}
}
