//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"math"
	"testing"
	"unsafe"
)

func TestICoreWebView2Controller3_GetRasterizationScale(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite64(1+len(want), math.Float64bits(3.25))
	want = append(want, anyw())
	obj := &ICoreWebView2Controller3{Vtbl: &ICoreWebView2Controller3Vtbl{}}
	obj.Vtbl.GetRasterizationScale = recProc(1 + len(want))
	got0, err := obj.GetRasterizationScale()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != 3.25 {
		t.Errorf("float64 out = %v, want 3.25", got0)
	}
}

func TestICoreWebView2Controller3_PutRasterizationScale(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, f64w(1.5)...)
	obj := &ICoreWebView2Controller3{Vtbl: &ICoreWebView2Controller3Vtbl{}}
	obj.Vtbl.PutRasterizationScale = recProc(1 + len(want))
	err := obj.PutRasterizationScale(1.5)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Controller3_GetShouldDetectMonitorScaleChanges(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2Controller3{Vtbl: &ICoreWebView2Controller3Vtbl{}}
	obj.Vtbl.GetShouldDetectMonitorScaleChanges = recProc(1 + len(want))
	got0, err := obj.GetShouldDetectMonitorScaleChanges()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2Controller3_PutShouldDetectMonitorScaleChanges(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2Controller3{Vtbl: &ICoreWebView2Controller3Vtbl{}}
	obj.Vtbl.PutShouldDetectMonitorScaleChanges = recProc(1 + len(want))
	err := obj.PutShouldDetectMonitorScaleChanges(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Controller3_AddRasterizationScaleChanged(t *testing.T) {
	recReset()
	in0 := &ICoreWebView2RasterizationScaleChangedEventHandler{}
	want := []wordExpect{}
	want = append(want, ptrw(unsafe.Pointer(in0)))
	recWrite64(1+len(want), 0x101112131400)
	want = append(want, anyw())
	obj := &ICoreWebView2Controller3{Vtbl: &ICoreWebView2Controller3Vtbl{}}
	obj.Vtbl.AddRasterizationScaleChanged = recProc(1 + len(want))
	got0, err := obj.AddRasterizationScaleChanged(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if tokenBits(got0) != 0x101112131400 {
		t.Errorf("token out = %x, want 0x101112131400", tokenBits(got0))
	}
}

func TestICoreWebView2Controller3_RemoveRasterizationScaleChanged(t *testing.T) {
	recReset()
	in0 := makeToken(0x0102030405060708)
	want := []wordExpect{}
	want = append(want, u64w(0x0102030405060708)...)
	obj := &ICoreWebView2Controller3{Vtbl: &ICoreWebView2Controller3Vtbl{}}
	obj.Vtbl.RemoveRasterizationScaleChanged = recProc(1 + len(want))
	err := obj.RemoveRasterizationScaleChanged(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Controller3_GetBoundsMode(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 0x0AFE00)
	want = append(want, anyw())
	obj := &ICoreWebView2Controller3{Vtbl: &ICoreWebView2Controller3Vtbl{}}
	obj.Vtbl.GetBoundsMode = recProc(1 + len(want))
	got0, err := obj.GetBoundsMode()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != COREWEBVIEW2_BOUNDS_MODE(0x0AFE00) {
		t.Errorf("scalar out = %v, want 0x0AFE00", got0)
	}
}

func TestICoreWebView2Controller3_PutBoundsMode(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(3))
	obj := &ICoreWebView2Controller3{Vtbl: &ICoreWebView2Controller3Vtbl{}}
	obj.Vtbl.PutBoundsMode = recProc(1 + len(want))
	err := obj.PutBoundsMode(COREWEBVIEW2_BOUNDS_MODE(3))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Controller3_QueryInterfaceHelper(t *testing.T) {
	recReset()
	root := &ICoreWebView2Controller{Vtbl: &ICoreWebView2ControllerVtbl{}}
	root.Vtbl.QueryInterface = recProc(3)
	recCaptureGUID(1)
	recWritePtr(2, fakeTargetPtr())
	got, err := root.GetICoreWebView2Controller3()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if unsafe.Pointer(got) != fakeTargetPtr() {
		t.Errorf("returned pointer %p, want fake target", got)
	}
	if g := recCapturedGUID(1); g != "f9614724-5d2b-41dc-aef7-73d62b51543b" {
		t.Errorf("queried IID %s, want %s", g, "f9614724-5d2b-41dc-aef7-73d62b51543b")
	}
}
