//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2NavigationStartingEventArgs2_GetAdditionalAllowedFrameAncestors(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2NavigationStartingEventArgs2{Vtbl: &ICoreWebView2NavigationStartingEventArgs2Vtbl{}}
	obj.Vtbl.GetAdditionalAllowedFrameAncestors = recProc(1 + len(want))
	got0, err := obj.GetAdditionalAllowedFrameAncestors()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2NavigationStartingEventArgs2_PutAdditionalAllowedFrameAncestors(t *testing.T) {
	recReset()
	want := []wordExpect{}
	capIdx0 := 1 + len(want)
	recCaptureUTF16(capIdx0)
	want = append(want, anyw())
	obj := &ICoreWebView2NavigationStartingEventArgs2{Vtbl: &ICoreWebView2NavigationStartingEventArgs2Vtbl{}}
	obj.Vtbl.PutAdditionalAllowedFrameAncestors = recProc(1 + len(want))
	err := obj.PutAdditionalAllowedFrameAncestors("wv2-in-0")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got := recCapturedString(capIdx0); got != "wv2-in-0" {
		t.Errorf("string arg %d marshalled as %q, want wv2-in-0", 0, got)
	}
}

func TestICoreWebView2NavigationStartingEventArgs2_QueryInterfaceHelper(t *testing.T) {
	recReset()
	root := &ICoreWebView2NavigationStartingEventArgs{Vtbl: &ICoreWebView2NavigationStartingEventArgsVtbl{}}
	root.Vtbl.QueryInterface = recProc(3)
	recCaptureGUID(1)
	recWritePtr(2, fakeTargetPtr())
	got, err := root.GetICoreWebView2NavigationStartingEventArgs2()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if unsafe.Pointer(got) != fakeTargetPtr() {
		t.Errorf("returned pointer %p, want fake target", got)
	}
	if g := recCapturedGUID(1); g != "9086be93-91aa-472d-a7e0-579f2ba006ad" {
		t.Errorf("queried IID %s, want %s", g, "9086be93-91aa-472d-a7e0-579f2ba006ad")
	}
}
