//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

type stubICoreWebView2LaunchingExternalUriSchemeEventHandlerImpl struct {
	got_sender *ICoreWebView2
	got_args *ICoreWebView2LaunchingExternalUriSchemeEventArgs
	called bool
}

func (s *stubICoreWebView2LaunchingExternalUriSchemeEventHandlerImpl) QueryInterface(refiid, object uintptr) uintptr { return 0 }
func (s *stubICoreWebView2LaunchingExternalUriSchemeEventHandlerImpl) AddRef() uint32  { return 1 }
func (s *stubICoreWebView2LaunchingExternalUriSchemeEventHandlerImpl) Release() uint32 { return 1 }
func (s *stubICoreWebView2LaunchingExternalUriSchemeEventHandlerImpl) LaunchingExternalUriScheme(sender *ICoreWebView2, args *ICoreWebView2LaunchingExternalUriSchemeEventArgs) uintptr {
	s.got_sender = sender
	s.got_args = args
	s.called = true
	return 0x42
}

func TestICoreWebView2LaunchingExternalUriSchemeEventHandler_InvokeDispatch(t *testing.T) {
	stub := &stubICoreWebView2LaunchingExternalUriSchemeEventHandlerImpl{}
	h := NewICoreWebView2LaunchingExternalUriSchemeEventHandler(stub)
	a0 := &ICoreWebView2{}
	a1 := &ICoreWebView2LaunchingExternalUriSchemeEventArgs{}
	hr, _, _ := h.Vtbl.Invoke.Call(
		uintptr(unsafe.Pointer(h)),
		uintptr(unsafe.Pointer(a0)),
		uintptr(unsafe.Pointer(a1)),
	)
	if hr != 0x42 {
		t.Errorf("Invoke returned %#x, want 0x42 (impl return value)", hr)
	}
	if !stub.called {
		t.Fatal("impl was not called")
	}
	if stub.got_sender != a0 {
		t.Errorf("pointer arg %v, want %v", stub.got_sender, a0)
	}
	if stub.got_args != a1 {
		t.Errorf("pointer arg %v, want %v", stub.got_args, a1)
	}
}
