//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2ControllerOptions2_GetScriptLocale(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2ControllerOptions2{Vtbl: &ICoreWebView2ControllerOptions2Vtbl{}}
	obj.Vtbl.GetScriptLocale = recProc(1 + len(want))
	got0, err := obj.GetScriptLocale()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2ControllerOptions2_PutScriptLocale(t *testing.T) {
	recReset()
	want := []wordExpect{}
	capIdx0 := 1 + len(want)
	recCaptureUTF16(capIdx0)
	want = append(want, anyw())
	obj := &ICoreWebView2ControllerOptions2{Vtbl: &ICoreWebView2ControllerOptions2Vtbl{}}
	obj.Vtbl.PutScriptLocale = recProc(1 + len(want))
	err := obj.PutScriptLocale("wv2-in-0")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got := recCapturedString(capIdx0); got != "wv2-in-0" {
		t.Errorf("string arg %d marshalled as %q, want wv2-in-0", 0, got)
	}
}

func TestICoreWebView2ControllerOptions2_QueryInterfaceHelper(t *testing.T) {
	recReset()
	root := &ICoreWebView2ControllerOptions{Vtbl: &ICoreWebView2ControllerOptionsVtbl{}}
	root.Vtbl.QueryInterface = recProc(3)
	recCaptureGUID(1)
	recWritePtr(2, fakeTargetPtr())
	got, err := root.GetICoreWebView2ControllerOptions2()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if unsafe.Pointer(got) != fakeTargetPtr() {
		t.Errorf("returned pointer %p, want fake target", got)
	}
	if g := recCapturedGUID(1); g != "06c991d8-9e7e-11ed-a8fc-0242ac120002" {
		t.Errorf("queried IID %s, want %s", g, "06c991d8-9e7e-11ed-a8fc-0242ac120002")
	}
}
