//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2Environment2_CreateWebResourceRequest(t *testing.T) {
	recReset()
	in2 := &IStream{}
	want := []wordExpect{}
	capIdx0 := 1 + len(want)
	recCaptureUTF16(capIdx0)
	want = append(want, anyw())
	capIdx1 := 1 + len(want)
	recCaptureUTF16(capIdx1)
	want = append(want, anyw())
	want = append(want, ptrw(unsafe.Pointer(in2)))
	capIdx3 := 1 + len(want)
	recCaptureUTF16(capIdx3)
	want = append(want, anyw())
	recWritePtr(1+len(want), fakeTargetPtr())
	want = append(want, anyw())
	obj := &ICoreWebView2Environment2{Vtbl: &ICoreWebView2Environment2Vtbl{}}
	obj.Vtbl.CreateWebResourceRequest = recProc(1 + len(want))
	got0, err := obj.CreateWebResourceRequest("wv2-in-0", "wv2-in-1", in2, "wv2-in-3")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got := recCapturedString(capIdx0); got != "wv2-in-0" {
		t.Errorf("string arg %d marshalled as %q, want wv2-in-0", 0, got)
	}
	if got := recCapturedString(capIdx1); got != "wv2-in-1" {
		t.Errorf("string arg %d marshalled as %q, want wv2-in-1", 1, got)
	}
	if got := recCapturedString(capIdx3); got != "wv2-in-3" {
		t.Errorf("string arg %d marshalled as %q, want wv2-in-3", 3, got)
	}
	if unsafe.Pointer(got0) != fakeTargetPtr() {
		t.Errorf("pointer out = %v", got0)
	}
}

func TestICoreWebView2Environment2_QueryInterfaceHelper(t *testing.T) {
	recReset()
	root := &ICoreWebView2Environment{Vtbl: &ICoreWebView2EnvironmentVtbl{}}
	root.Vtbl.QueryInterface = recProc(3)
	recCaptureGUID(1)
	recWritePtr(2, fakeTargetPtr())
	got, err := root.GetICoreWebView2Environment2()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if unsafe.Pointer(got) != fakeTargetPtr() {
		t.Errorf("returned pointer %p, want fake target", got)
	}
	if g := recCapturedGUID(1); g != "41f3632b-5ef4-404f-ad82-2d606c5a9a21" {
		t.Errorf("queried IID %s, want %s", g, "41f3632b-5ef4-404f-ad82-2d606c5a9a21")
	}
}
