//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2_8_AddIsMutedChanged(t *testing.T) {
	recReset()
	in0 := &ICoreWebView2IsMutedChangedEventHandler{}
	want := []wordExpect{}
	want = append(want, ptrw(unsafe.Pointer(in0)))
	recWrite64(1+len(want), 0x101112131400)
	want = append(want, anyw())
	obj := &ICoreWebView2_8{Vtbl: &ICoreWebView2_8Vtbl{}}
	obj.Vtbl.AddIsMutedChanged = recProc(1 + len(want))
	got0, err := obj.AddIsMutedChanged(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if tokenBits(got0) != 0x101112131400 {
		t.Errorf("token out = %x, want 0x101112131400", tokenBits(got0))
	}
}

func TestICoreWebView2_8_RemoveIsMutedChanged(t *testing.T) {
	recReset()
	in0 := makeToken(0x0102030405060708)
	want := []wordExpect{}
	want = append(want, u64w(0x0102030405060708)...)
	obj := &ICoreWebView2_8{Vtbl: &ICoreWebView2_8Vtbl{}}
	obj.Vtbl.RemoveIsMutedChanged = recProc(1 + len(want))
	err := obj.RemoveIsMutedChanged(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2_8_GetIsMuted(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2_8{Vtbl: &ICoreWebView2_8Vtbl{}}
	obj.Vtbl.GetIsMuted = recProc(1 + len(want))
	got0, err := obj.GetIsMuted()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2_8_PutIsMuted(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2_8{Vtbl: &ICoreWebView2_8Vtbl{}}
	obj.Vtbl.PutIsMuted = recProc(1 + len(want))
	err := obj.PutIsMuted(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2_8_AddIsDocumentPlayingAudioChanged(t *testing.T) {
	recReset()
	in0 := &ICoreWebView2IsDocumentPlayingAudioChangedEventHandler{}
	want := []wordExpect{}
	want = append(want, ptrw(unsafe.Pointer(in0)))
	recWrite64(1+len(want), 0x101112131400)
	want = append(want, anyw())
	obj := &ICoreWebView2_8{Vtbl: &ICoreWebView2_8Vtbl{}}
	obj.Vtbl.AddIsDocumentPlayingAudioChanged = recProc(1 + len(want))
	got0, err := obj.AddIsDocumentPlayingAudioChanged(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if tokenBits(got0) != 0x101112131400 {
		t.Errorf("token out = %x, want 0x101112131400", tokenBits(got0))
	}
}

func TestICoreWebView2_8_RemoveIsDocumentPlayingAudioChanged(t *testing.T) {
	recReset()
	in0 := makeToken(0x0102030405060708)
	want := []wordExpect{}
	want = append(want, u64w(0x0102030405060708)...)
	obj := &ICoreWebView2_8{Vtbl: &ICoreWebView2_8Vtbl{}}
	obj.Vtbl.RemoveIsDocumentPlayingAudioChanged = recProc(1 + len(want))
	err := obj.RemoveIsDocumentPlayingAudioChanged(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2_8_GetIsDocumentPlayingAudio(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2_8{Vtbl: &ICoreWebView2_8Vtbl{}}
	obj.Vtbl.GetIsDocumentPlayingAudio = recProc(1 + len(want))
	got0, err := obj.GetIsDocumentPlayingAudio()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2_8_QueryInterfaceHelper(t *testing.T) {
	recReset()
	root := &ICoreWebView2{Vtbl: &ICoreWebView2Vtbl{}}
	root.Vtbl.QueryInterface = recProc(3)
	recCaptureGUID(1)
	recWritePtr(2, fakeTargetPtr())
	got, err := root.GetICoreWebView2_8()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if unsafe.Pointer(got) != fakeTargetPtr() {
		t.Errorf("returned pointer %p, want fake target", got)
	}
	if g := recCapturedGUID(1); g != "e9632730-6e1e-43ab-b7b8-7b2c9e62e094" {
		t.Errorf("queried IID %s, want %s", g, "e9632730-6e1e-43ab-b7b8-7b2c9e62e094")
	}
}
