//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2FrameCreatedEventArgs_GetFrame(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWritePtr(1+len(want), fakeTargetPtr())
	want = append(want, anyw())
	obj := &ICoreWebView2FrameCreatedEventArgs{Vtbl: &ICoreWebView2FrameCreatedEventArgsVtbl{}}
	obj.Vtbl.GetFrame = recProc(1 + len(want))
	got0, err := obj.GetFrame()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if unsafe.Pointer(got0) != fakeTargetPtr() {
		t.Errorf("pointer out = %v", got0)
	}
}
