//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2EnvironmentOptions6_GetAreBrowserExtensionsEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2EnvironmentOptions6{Vtbl: &ICoreWebView2EnvironmentOptions6Vtbl{}}
	obj.Vtbl.GetAreBrowserExtensionsEnabled = recProc(1 + len(want))
	got0, err := obj.GetAreBrowserExtensionsEnabled()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2EnvironmentOptions6_PutAreBrowserExtensionsEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2EnvironmentOptions6{Vtbl: &ICoreWebView2EnvironmentOptions6Vtbl{}}
	obj.Vtbl.PutAreBrowserExtensionsEnabled = recProc(1 + len(want))
	err := obj.PutAreBrowserExtensionsEnabled(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}
