//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2FrameInfo2_GetParentFrameInfo(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWritePtr(1+len(want), fakeTargetPtr())
	want = append(want, anyw())
	obj := &ICoreWebView2FrameInfo2{Vtbl: &ICoreWebView2FrameInfo2Vtbl{}}
	obj.Vtbl.GetParentFrameInfo = recProc(1 + len(want))
	got0, err := obj.GetParentFrameInfo()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if unsafe.Pointer(got0) != fakeTargetPtr() {
		t.Errorf("pointer out = %v", got0)
	}
}

func TestICoreWebView2FrameInfo2_GetFrameId(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 0x0AFE00)
	want = append(want, anyw())
	obj := &ICoreWebView2FrameInfo2{Vtbl: &ICoreWebView2FrameInfo2Vtbl{}}
	obj.Vtbl.GetFrameId = recProc(1 + len(want))
	got0, err := obj.GetFrameId()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != uint32(0x0AFE00) {
		t.Errorf("scalar out = %v, want 0x0AFE00", got0)
	}
}

func TestICoreWebView2FrameInfo2_GetFrameKind(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 0x0AFE00)
	want = append(want, anyw())
	obj := &ICoreWebView2FrameInfo2{Vtbl: &ICoreWebView2FrameInfo2Vtbl{}}
	obj.Vtbl.GetFrameKind = recProc(1 + len(want))
	got0, err := obj.GetFrameKind()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != COREWEBVIEW2_FRAME_KIND(0x0AFE00) {
		t.Errorf("scalar out = %v, want 0x0AFE00", got0)
	}
}

func TestICoreWebView2FrameInfo2_QueryInterfaceHelper(t *testing.T) {
	recReset()
	root := &ICoreWebView2FrameInfo{Vtbl: &ICoreWebView2FrameInfoVtbl{}}
	root.Vtbl.QueryInterface = recProc(3)
	recCaptureGUID(1)
	recWritePtr(2, fakeTargetPtr())
	got, err := root.GetICoreWebView2FrameInfo2()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if unsafe.Pointer(got) != fakeTargetPtr() {
		t.Errorf("returned pointer %p, want fake target", got)
	}
	if g := recCapturedGUID(1); g != "56f85cfa-72c4-11ee-b962-0242ac120002" {
		t.Errorf("queried IID %s, want %s", g, "56f85cfa-72c4-11ee-b962-0242ac120002")
	}
}
