//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2WebResourceResponseView_GetHeaders(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWritePtr(1+len(want), fakeTargetPtr())
	want = append(want, anyw())
	obj := &ICoreWebView2WebResourceResponseView{Vtbl: &ICoreWebView2WebResourceResponseViewVtbl{}}
	obj.Vtbl.GetHeaders = recProc(1 + len(want))
	got0, err := obj.GetHeaders()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if unsafe.Pointer(got0) != fakeTargetPtr() {
		t.Errorf("pointer out = %v", got0)
	}
}

func TestICoreWebView2WebResourceResponseView_GetStatusCode(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 0x0AFE00)
	want = append(want, anyw())
	obj := &ICoreWebView2WebResourceResponseView{Vtbl: &ICoreWebView2WebResourceResponseViewVtbl{}}
	obj.Vtbl.GetStatusCode = recProc(1 + len(want))
	got0, err := obj.GetStatusCode()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != int(0x0AFE00) {
		t.Errorf("scalar out = %v, want 0x0AFE00", got0)
	}
}

func TestICoreWebView2WebResourceResponseView_GetReasonPhrase(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2WebResourceResponseView{Vtbl: &ICoreWebView2WebResourceResponseViewVtbl{}}
	obj.Vtbl.GetReasonPhrase = recProc(1 + len(want))
	got0, err := obj.GetReasonPhrase()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2WebResourceResponseView_GetContent(t *testing.T) {
	recReset()
	in0 := &ICoreWebView2WebResourceResponseViewGetContentCompletedHandler{}
	want := []wordExpect{}
	want = append(want, ptrw(unsafe.Pointer(in0)))
	obj := &ICoreWebView2WebResourceResponseView{Vtbl: &ICoreWebView2WebResourceResponseViewVtbl{}}
	obj.Vtbl.GetContent = recProc(1 + len(want))
	err := obj.GetContent(in0)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}
