//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

type stubICoreWebView2PrintToPdfStreamCompletedHandlerImpl struct {
	got_errorCode uintptr
	got_result *IStream
	called bool
}

func (s *stubICoreWebView2PrintToPdfStreamCompletedHandlerImpl) QueryInterface(refiid, object uintptr) uintptr { return 0 }
func (s *stubICoreWebView2PrintToPdfStreamCompletedHandlerImpl) AddRef() uint32  { return 1 }
func (s *stubICoreWebView2PrintToPdfStreamCompletedHandlerImpl) Release() uint32 { return 1 }
func (s *stubICoreWebView2PrintToPdfStreamCompletedHandlerImpl) PrintToPdfStreamCompleted(errorCode uintptr, result *IStream) uintptr {
	s.got_errorCode = errorCode
	s.got_result = result
	s.called = true
	return 0x42
}

func TestICoreWebView2PrintToPdfStreamCompletedHandler_InvokeDispatch(t *testing.T) {
	stub := &stubICoreWebView2PrintToPdfStreamCompletedHandlerImpl{}
	h := NewICoreWebView2PrintToPdfStreamCompletedHandler(stub)
	a1 := &IStream{}
	hr, _, _ := h.Vtbl.Invoke.Call(
		uintptr(unsafe.Pointer(h)),
		uintptr(50),
		uintptr(unsafe.Pointer(a1)),
	)
	if hr != 0x42 {
		t.Errorf("Invoke returned %#x, want 0x42 (impl return value)", hr)
	}
	if !stub.called {
		t.Fatal("impl was not called")
	}
	if stub.got_errorCode != uintptr(50) {
		t.Errorf("numeric arg = %v, want 50", stub.got_errorCode)
	}
	if stub.got_result != a1 {
		t.Errorf("pointer arg %v, want %v", stub.got_result, a1)
	}
}
