//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2Settings_GetIsScriptEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	obj.Vtbl.GetIsScriptEnabled = recProc(1 + len(want))
	got0, err := obj.GetIsScriptEnabled()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2Settings_PutIsScriptEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	obj.Vtbl.PutIsScriptEnabled = recProc(1 + len(want))
	err := obj.PutIsScriptEnabled(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Settings_GetIsWebMessageEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	obj.Vtbl.GetIsWebMessageEnabled = recProc(1 + len(want))
	got0, err := obj.GetIsWebMessageEnabled()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2Settings_PutIsWebMessageEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	obj.Vtbl.PutIsWebMessageEnabled = recProc(1 + len(want))
	err := obj.PutIsWebMessageEnabled(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Settings_GetAreDefaultScriptDialogsEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	obj.Vtbl.GetAreDefaultScriptDialogsEnabled = recProc(1 + len(want))
	got0, err := obj.GetAreDefaultScriptDialogsEnabled()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2Settings_PutAreDefaultScriptDialogsEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	obj.Vtbl.PutAreDefaultScriptDialogsEnabled = recProc(1 + len(want))
	err := obj.PutAreDefaultScriptDialogsEnabled(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Settings_GetIsStatusBarEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	obj.Vtbl.GetIsStatusBarEnabled = recProc(1 + len(want))
	got0, err := obj.GetIsStatusBarEnabled()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2Settings_PutIsStatusBarEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	obj.Vtbl.PutIsStatusBarEnabled = recProc(1 + len(want))
	err := obj.PutIsStatusBarEnabled(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Settings_GetAreDevToolsEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	obj.Vtbl.GetAreDevToolsEnabled = recProc(1 + len(want))
	got0, err := obj.GetAreDevToolsEnabled()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2Settings_PutAreDevToolsEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	obj.Vtbl.PutAreDevToolsEnabled = recProc(1 + len(want))
	err := obj.PutAreDevToolsEnabled(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Settings_GetAreDefaultContextMenusEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	obj.Vtbl.GetAreDefaultContextMenusEnabled = recProc(1 + len(want))
	got0, err := obj.GetAreDefaultContextMenusEnabled()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2Settings_PutAreDefaultContextMenusEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	obj.Vtbl.PutAreDefaultContextMenusEnabled = recProc(1 + len(want))
	err := obj.PutAreDefaultContextMenusEnabled(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Settings_GetAreHostObjectsAllowed(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	obj.Vtbl.GetAreHostObjectsAllowed = recProc(1 + len(want))
	got0, err := obj.GetAreHostObjectsAllowed()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2Settings_PutAreHostObjectsAllowed(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	obj.Vtbl.PutAreHostObjectsAllowed = recProc(1 + len(want))
	err := obj.PutAreHostObjectsAllowed(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Settings_GetIsZoomControlEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	obj.Vtbl.GetIsZoomControlEnabled = recProc(1 + len(want))
	got0, err := obj.GetIsZoomControlEnabled()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2Settings_PutIsZoomControlEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	obj.Vtbl.PutIsZoomControlEnabled = recProc(1 + len(want))
	err := obj.PutIsZoomControlEnabled(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2Settings_GetIsBuiltInErrorPageEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 1)
	want = append(want, anyw())
	obj := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	obj.Vtbl.GetIsBuiltInErrorPageEnabled = recProc(1 + len(want))
	got0, err := obj.GetIsBuiltInErrorPageEnabled()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != true {
		t.Errorf("bool out = %v, want true", got0)
	}
}

func TestICoreWebView2Settings_PutIsBuiltInErrorPageEnabled(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(1))
	obj := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	obj.Vtbl.PutIsBuiltInErrorPageEnabled = recProc(1 + len(want))
	err := obj.PutIsBuiltInErrorPageEnabled(true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}
