//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

type stubICoreWebView2CreateCoreWebView2CompositionControllerCompletedHandlerImpl struct {
	got_errorCode uintptr
	got_result *ICoreWebView2CompositionController
	called bool
}

func (s *stubICoreWebView2CreateCoreWebView2CompositionControllerCompletedHandlerImpl) QueryInterface(refiid, object uintptr) uintptr { return 0 }
func (s *stubICoreWebView2CreateCoreWebView2CompositionControllerCompletedHandlerImpl) AddRef() uint32  { return 1 }
func (s *stubICoreWebView2CreateCoreWebView2CompositionControllerCompletedHandlerImpl) Release() uint32 { return 1 }
func (s *stubICoreWebView2CreateCoreWebView2CompositionControllerCompletedHandlerImpl) CreateCoreWebView2CompositionControllerCompleted(errorCode uintptr, result *ICoreWebView2CompositionController) uintptr {
	s.got_errorCode = errorCode
	s.got_result = result
	s.called = true
	return 0x42
}

func TestICoreWebView2CreateCoreWebView2CompositionControllerCompletedHandler_InvokeDispatch(t *testing.T) {
	stub := &stubICoreWebView2CreateCoreWebView2CompositionControllerCompletedHandlerImpl{}
	h := NewICoreWebView2CreateCoreWebView2CompositionControllerCompletedHandler(stub)
	a1 := &ICoreWebView2CompositionController{}
	hr, _, _ := h.Vtbl.Invoke.Call(
		uintptr(unsafe.Pointer(h)),
		uintptr(50),
		uintptr(unsafe.Pointer(a1)),
	)
	if hr != 0x42 {
		t.Errorf("Invoke returned %#x, want 0x42 (impl return value)", hr)
	}
	if !stub.called {
		t.Fatal("impl was not called")
	}
	if stub.got_errorCode != uintptr(50) {
		t.Errorf("numeric arg = %v, want 50", stub.got_errorCode)
	}
	if stub.got_result != a1 {
		t.Errorf("pointer arg %v, want %v", stub.got_result, a1)
	}
}
