//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2BasicAuthenticationResponse_GetUserName(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2BasicAuthenticationResponse{Vtbl: &ICoreWebView2BasicAuthenticationResponseVtbl{}}
	obj.Vtbl.GetUserName = recProc(1 + len(want))
	got0, err := obj.GetUserName()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2BasicAuthenticationResponse_PutUserName(t *testing.T) {
	recReset()
	want := []wordExpect{}
	capIdx0 := 1 + len(want)
	recCaptureUTF16(capIdx0)
	want = append(want, anyw())
	obj := &ICoreWebView2BasicAuthenticationResponse{Vtbl: &ICoreWebView2BasicAuthenticationResponseVtbl{}}
	obj.Vtbl.PutUserName = recProc(1 + len(want))
	err := obj.PutUserName("wv2-in-0")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got := recCapturedString(capIdx0); got != "wv2-in-0" {
		t.Errorf("string arg %d marshalled as %q, want wv2-in-0", 0, got)
	}
}

func TestICoreWebView2BasicAuthenticationResponse_GetPassword(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2BasicAuthenticationResponse{Vtbl: &ICoreWebView2BasicAuthenticationResponseVtbl{}}
	obj.Vtbl.GetPassword = recProc(1 + len(want))
	got0, err := obj.GetPassword()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2BasicAuthenticationResponse_PutPassword(t *testing.T) {
	recReset()
	want := []wordExpect{}
	capIdx0 := 1 + len(want)
	recCaptureUTF16(capIdx0)
	want = append(want, anyw())
	obj := &ICoreWebView2BasicAuthenticationResponse{Vtbl: &ICoreWebView2BasicAuthenticationResponseVtbl{}}
	obj.Vtbl.PutPassword = recProc(1 + len(want))
	err := obj.PutPassword("wv2-in-0")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got := recCapturedString(capIdx0); got != "wv2-in-0" {
		t.Errorf("string arg %d marshalled as %q, want wv2-in-0", 0, got)
	}
}
