//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2Settings2_GetUserAgent(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2Settings2{Vtbl: &ICoreWebView2Settings2Vtbl{}}
	obj.Vtbl.GetUserAgent = recProc(1 + len(want))
	got0, err := obj.GetUserAgent()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2Settings2_PutUserAgent(t *testing.T) {
	recReset()
	want := []wordExpect{}
	capIdx0 := 1 + len(want)
	recCaptureUTF16(capIdx0)
	want = append(want, anyw())
	obj := &ICoreWebView2Settings2{Vtbl: &ICoreWebView2Settings2Vtbl{}}
	obj.Vtbl.PutUserAgent = recProc(1 + len(want))
	err := obj.PutUserAgent("wv2-in-0")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got := recCapturedString(capIdx0); got != "wv2-in-0" {
		t.Errorf("string arg %d marshalled as %q, want wv2-in-0", 0, got)
	}
}

func TestICoreWebView2Settings2_QueryInterfaceHelper(t *testing.T) {
	recReset()
	root := &ICoreWebView2Settings{Vtbl: &ICoreWebView2SettingsVtbl{}}
	root.Vtbl.QueryInterface = recProc(3)
	recCaptureGUID(1)
	recWritePtr(2, fakeTargetPtr())
	got, err := root.GetICoreWebView2Settings2()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if unsafe.Pointer(got) != fakeTargetPtr() {
		t.Errorf("returned pointer %p, want fake target", got)
	}
	if g := recCapturedGUID(1); g != "ee9a0f68-f46c-4e32-ac23-ef8cac224d2a" {
		t.Errorf("queried IID %s, want %s", g, "ee9a0f68-f46c-4e32-ac23-ef8cac224d2a")
	}
}
