//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2NewWindowRequestedEventArgs2_GetName(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWriteUTF16(1+len(want), "wv2-out-0")
	want = append(want, anyw())
	obj := &ICoreWebView2NewWindowRequestedEventArgs2{Vtbl: &ICoreWebView2NewWindowRequestedEventArgs2Vtbl{}}
	obj.Vtbl.GetName = recProc(1 + len(want))
	got0, err := obj.GetName()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != "wv2-out-0" {
		t.Errorf("string out = %q, want wv2-out-0", got0)
	}
}

func TestICoreWebView2NewWindowRequestedEventArgs2_QueryInterfaceHelper(t *testing.T) {
	recReset()
	root := &ICoreWebView2NewWindowRequestedEventArgs{Vtbl: &ICoreWebView2NewWindowRequestedEventArgsVtbl{}}
	root.Vtbl.QueryInterface = recProc(3)
	recCaptureGUID(1)
	recWritePtr(2, fakeTargetPtr())
	got, err := root.GetICoreWebView2NewWindowRequestedEventArgs2()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if unsafe.Pointer(got) != fakeTargetPtr() {
		t.Errorf("returned pointer %p, want fake target", got)
	}
	if g := recCapturedGUID(1); g != "bbc7baed-74c6-4c92-b63a-7f5aeae03de3" {
		t.Errorf("queried IID %s, want %s", g, "bbc7baed-74c6-4c92-b63a-7f5aeae03de3")
	}
}
