//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2Deferral_Complete(t *testing.T) {
	recReset()
	want := []wordExpect{}
	obj := &ICoreWebView2Deferral{Vtbl: &ICoreWebView2DeferralVtbl{}}
	obj.Vtbl.Complete = recProc(1 + len(want))
	err := obj.Complete()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}
