//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

type stubICoreWebView2NewBrowserVersionAvailableEventHandlerImpl struct {
	got_sender *ICoreWebView2Environment
	got_args *IUnknown
	called bool
}

func (s *stubICoreWebView2NewBrowserVersionAvailableEventHandlerImpl) QueryInterface(refiid, object uintptr) uintptr { return 0 }
func (s *stubICoreWebView2NewBrowserVersionAvailableEventHandlerImpl) AddRef() uint32  { return 1 }
func (s *stubICoreWebView2NewBrowserVersionAvailableEventHandlerImpl) Release() uint32 { return 1 }
func (s *stubICoreWebView2NewBrowserVersionAvailableEventHandlerImpl) NewBrowserVersionAvailable(sender *ICoreWebView2Environment, args *IUnknown) uintptr {
	s.got_sender = sender
	s.got_args = args
	s.called = true
	return 0x42
}

func TestICoreWebView2NewBrowserVersionAvailableEventHandler_InvokeDispatch(t *testing.T) {
	stub := &stubICoreWebView2NewBrowserVersionAvailableEventHandlerImpl{}
	h := NewICoreWebView2NewBrowserVersionAvailableEventHandler(stub)
	a0 := &ICoreWebView2Environment{}
	a1 := &IUnknown{}
	hr, _, _ := h.Vtbl.Invoke.Call(
		uintptr(unsafe.Pointer(h)),
		uintptr(unsafe.Pointer(a0)),
		uintptr(unsafe.Pointer(a1)),
	)
	if hr != 0x42 {
		t.Errorf("Invoke returned %#x, want 0x42 (impl return value)", hr)
	}
	if !stub.called {
		t.Fatal("impl was not called")
	}
	if stub.got_sender != a0 {
		t.Errorf("pointer arg %v, want %v", stub.got_sender, a0)
	}
	if stub.got_args != a1 {
		t.Errorf("pointer arg %v, want %v", stub.got_args, a1)
	}
}
