//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2EnvironmentOptions8_GetScrollBarStyle(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 0x0AFE00)
	want = append(want, anyw())
	obj := &ICoreWebView2EnvironmentOptions8{Vtbl: &ICoreWebView2EnvironmentOptions8Vtbl{}}
	obj.Vtbl.GetScrollBarStyle = recProc(1 + len(want))
	got0, err := obj.GetScrollBarStyle()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != COREWEBVIEW2_SCROLLBAR_STYLE(0x0AFE00) {
		t.Errorf("scalar out = %v, want 0x0AFE00", got0)
	}
}

func TestICoreWebView2EnvironmentOptions8_PutScrollBarStyle(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(3))
	obj := &ICoreWebView2EnvironmentOptions8{Vtbl: &ICoreWebView2EnvironmentOptions8Vtbl{}}
	obj.Vtbl.PutScrollBarStyle = recProc(1 + len(want))
	err := obj.PutScrollBarStyle(COREWEBVIEW2_SCROLLBAR_STYLE(3))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}
