//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2RegionRectCollectionView_GetCount(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 0x0AFE00)
	want = append(want, anyw())
	obj := &ICoreWebView2RegionRectCollectionView{Vtbl: &ICoreWebView2RegionRectCollectionViewVtbl{}}
	obj.Vtbl.GetCount = recProc(1 + len(want))
	got0, err := obj.GetCount()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != uint32(0x0AFE00) {
		t.Errorf("scalar out = %v, want 0x0AFE00", got0)
	}
}

func TestICoreWebView2RegionRectCollectionView_GetValueAtIndex(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(40))
	want = append(want, anyw())
	obj := &ICoreWebView2RegionRectCollectionView{Vtbl: &ICoreWebView2RegionRectCollectionViewVtbl{}}
	obj.Vtbl.GetValueAtIndex = recProc(1 + len(want))
	got0, err := obj.GetValueAtIndex(uint32(40))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != (RECT{}) {
		t.Errorf("struct out = %+v, want zero value", got0)
	}
}
