//go:build windows

// Code generated by webview2gen. DO NOT EDIT.

package webview2

import (
	"testing"
	"unsafe"
)

func TestICoreWebView2_19_GetMemoryUsageTargetLevel(t *testing.T) {
	recReset()
	want := []wordExpect{}
	recWrite32(1+len(want), 0x0AFE00)
	want = append(want, anyw())
	obj := &ICoreWebView2_19{Vtbl: &ICoreWebView2_19Vtbl{}}
	obj.Vtbl.GetMemoryUsageTargetLevel = recProc(1 + len(want))
	got0, err := obj.GetMemoryUsageTargetLevel()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
	if got0 != COREWEBVIEW2_MEMORY_USAGE_TARGET_LEVEL(0x0AFE00) {
		t.Errorf("scalar out = %v, want 0x0AFE00", got0)
	}
}

func TestICoreWebView2_19_PutMemoryUsageTargetLevel(t *testing.T) {
	recReset()
	want := []wordExpect{}
	want = append(want, xw(3))
	obj := &ICoreWebView2_19{Vtbl: &ICoreWebView2_19Vtbl{}}
	obj.Vtbl.PutMemoryUsageTargetLevel = recProc(1 + len(want))
	err := obj.PutMemoryUsageTargetLevel(COREWEBVIEW2_MEMORY_USAGE_TARGET_LEVEL(3))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expectCall(t, unsafe.Pointer(obj), want)
}

func TestICoreWebView2_19_QueryInterfaceHelper(t *testing.T) {
	recReset()
	root := &ICoreWebView2{Vtbl: &ICoreWebView2Vtbl{}}
	root.Vtbl.QueryInterface = recProc(3)
	recCaptureGUID(1)
	recWritePtr(2, fakeTargetPtr())
	got, err := root.GetICoreWebView2_19()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if unsafe.Pointer(got) != fakeTargetPtr() {
		t.Errorf("returned pointer %p, want fake target", got)
	}
	if g := recCapturedGUID(1); g != "6921f954-79b0-437f-a997-c85811897c68" {
		t.Errorf("queried IID %s, want %s", g, "6921f954-79b0-437f-a997-c85811897c68")
	}
}
