// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export class Aliases {
    /**
     * Creates a new Aliases instance.
     * @param {Partial<Aliases>} [source = {}] - The source object to create the Aliases.
     */
    constructor(source = {}) {
        if (!("Name" in source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Numbers" in source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["Numbers"] = [];
        }
        if (!("Settings" in source)) {
            /**
             * @member
             * @type {{ [_: string]: string }}
             */
            this["Settings"] = {};
        }
        if (!("Person" in source)) {
            /**
             * @member
             * @type {Human}
             */
            this["Person"] = (new Human());
        }

        Object.assign(this, source);
    }

    /**
     * Creates a new Aliases instance from a string or object.
     * @param {string|object} source - The source data to create a Aliases instance from.
     * @returns {Aliases} A new Aliases instance.
     */
    static createFrom(source) {
        let parsedSource = typeof source === 'string' ? JSON.parse(source) : source;
        return new Aliases(parsedSource);
    }
};

/**
 * Human is a copy of Person
 * it is only visible without GODEBUG=gotypesalias=1
 */
export class Human {
    /**
     * Creates a new Human instance.
     * @param {Partial<Human>} [source = {}] - The source object to create the Human.
     */
    constructor(source = {}) {
        if (!("name" in source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, source);
    }

    /**
     * Creates a new Human instance from a string or object.
     * @param {string|object} source - The source data to create a Human instance from.
     * @returns {Human} A new Human instance.
     */
    static createFrom(source) {
        let parsedSource = typeof source === 'string' ? JSON.parse(source) : source;
        return new Human(parsedSource);
    }
};
