// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EmbedOther is even trickier.
 * @module
 */

import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * LikeThisOtherOne does nothing as well, but is different.
 */
export function LikeThisOtherOne(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3566862802);
    return $resultPromise as any;
}
