# https://taskfile.dev

version: '3'

tasks:

  setup:
    summary: Setup the project
    preconditions:
      - sh: python{{exeExt}} --version
        msg: "Looks like Python isn't installed. Python is required to build the documentation: https://www.python.org/downloads/"
    cmds:
      - python -m pip install -r requirements.txt --user

  setup:insiders:
    summary: Setup the project (insiders)
    preconditions:
      - sh: python{{exeExt}} --version
        msg: "Looks like Python isn't installed. Python is required to build the documentation: https://www.python.org/downloads/"
    cmds:
      - python -m pip install -r requirements.insiders.txt --user

  upgrade:insiders:
    summary: Upgrade the project (insiders)
    preconditions:
      - sh: python{{exeExt}} --version
        msg: "Looks like Python isn't installed. Python is required to build the documentation: https://www.python.org/downloads/"
    cmds:
      - python -m pip install -r requirements.insiders.txt --upgrade --user

  build:
    summary: Builds the documentation
    preconditions:
      - sh: mkdocs --version
        msg: "Looks like mkdocs isn't installed. Run `wails3 task setup` or `task setup` in the documentation directory to install it."
    cmds:
      - mkdocs build

  serve:
    summary: Builds the documentation and serves it locally
    preconditions:
      - sh: mkdocs --version
        msg: "Looks like mkdocs isn't installed. Run `wails3 task setup` or `task setup` in the documentation directory to install it."
    cmds:
      - mkdocs serve

  serve:insiders:
    summary: Builds the documentation and serves it locally
    preconditions:
      - sh: mkdocs --version
        msg: "Looks like mkdocs isn't installed. Run `wails3 task setup` or `task setup` in the documentation directory to install it."
    cmds:
      - mkdocs serve --config-file mkdocs.insiders.yml
