# https://taskfile.dev

version: '3'

vars:
  # Change this to switch package managers: bun, npm, pnpm, yarn
  PKG_MANAGER: bun

tasks:

  setup:
    summary: Setup the project
    preconditions:
      - sh: '{{.PKG_MANAGER}} --version'
        msg: "Looks like {{.PKG_MANAGER}} isn't installed."
    cmds:
      - '{{.PKG_MANAGER}} install'

  dev:
    summary: Run the dev server
    preconditions:
      - sh: '{{.PKG_MANAGER}} --version'
        msg: "Looks like {{.PKG_MANAGER}} isn't installed."
    cmds:
      - '{{.PKG_MANAGER}} run dev'

  build:
    summary: Build the docs
    preconditions:
      - sh: '{{.PKG_MANAGER}} --version'
        msg: "Looks like {{.PKG_MANAGER}} isn't installed."
    cmds:
      - '{{.PKG_MANAGER}} run build'

