// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GreetService is great
 * @module
 */

import {Call as $Call, Create as $Create} from "/wails/runtime.js";

import * as $models from "./models.js";

/**
 * Get someone
 * @param {number} aliasValue
 * @returns {Promise<$models.Person<string>> & { cancel(): void }}
 */
export function Get(aliasValue) {
    let $resultPromise = $Call.ByName("main.GreetService.Get", aliasValue);
    return /** @type {any} */($resultPromise);
}

/**
 * Get someone quite different
 * @returns {Promise<$models.Person<boolean>> & { cancel(): void }}
 */
export function GetButDifferent() {
    let $resultPromise = $Call.ByName("main.GreetService.GetButDifferent");
    return /** @type {any} */($resultPromise);
}
