
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export * as Service1 from "./Service1.ts";
export * as Service2 from "./Service2.ts";
export * as Service3 from "./Service3.ts";
export * as Service4 from "./Service4.ts";
export * as Service5 from "./Service5.ts";
export * as Service6 from "./Service6.ts";

