// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Create as $Create} from "/wails/runtime.js";

import * as services$0 from "./services/models.js";

/**
 * Person is a person!
 * They have a name and an address
 * @typedef {Object} Person
 * @property {string} Name
 * @property {services$0.Address | null} Address
 */
