// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DoVariousTimeThings(): $CancellablePromise<$models.TimeFieldStruct> {
    return $Call.ByID(2365938049);
}

export function GetTime(): $CancellablePromise<string> {
    return $Call.ByID(3727485718);
}

export function SetTime(t: string): $CancellablePromise<void> {
    return $Call.ByID(718492490, t);
}
