// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SomeMethods exports some methods.
 * @module
 */

import {Call as $Call, Create as $Create} from "/wails/runtime.js";

import * as $models from "./models.ts";

/**
 * LikeThisOne is an example method that does nothing.
 */
export function LikeThisOne(): Promise<[$models.Person, $models.Impersonator, $models.HowDifferent<boolean>, $models.PrivatePerson]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2124352079) as any;
    return $resultPromise;
}

/**
 * LikeThisOtherOne does nothing as well, but is different.
 */
export function LikeThisOtherOne(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4281222271) as any;
    return $resultPromise;
}
