name: Build + Test

on:
  push:
    branches: [ release/*, master ]
  workflow_dispatch:

jobs:
  test:
    name: Run Go Tests
    if: github.repository == 'wailsapp/wails'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        go-version: [ 1.18, 1.19 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update -y && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev build-essential pkg-config

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: go test -v ./...

  test_templates:
    name: Test Templates
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        template: [ svelte, svelte-ts, vue, vue-ts, react, react-ts, preact, preact-ts, lit, lit-ts, vanilla, vanilla-ts, plain ]
        go-version: [ 1.18, 1.19 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build Wails CLI
        run: |
          cd ./v2/cmd/wails
          go install
          wails -help

      - name: Install linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update -y && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev build-essential pkg-config

      - name: Generate template '${{ matrix.template }}'
        run: |
          mkdir -p ./test-${{ matrix.template }}
          cd ./test-${{ matrix.template }}
          wails init -n ${{ matrix.template }} -t ${{ matrix.template }} -ci
          cd ${{ matrix.template }}
          wails build -v 2
