name: Sync upstream branch and deploy mirror | 同步上游分支并部署镜像

on:
  schedule:
    - cron: "0 8,20 * * *"
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Automatic deployment | 自动部署
    runs-on: ubuntu-latest
    if: github.repository == 'misitebao/wails'

    steps:
      - name: Checkout | 切换到部署分支
        uses: actions/checkout@v2
        with:
          ref: "master"
          submodules: true
          fetch-depth: 0

      - name: Setup Git | 设置Git
        run: |
          git config --local user.email "i@misitebao.com"
          git config --local user.name "misitebao"

      - name: Add remote upstream repository and sync | 添加远程上游仓库并同步
        run: |
          git remote add upstream https://github.com/wailsapp/wails
          git pull -v --progress --no-rebase "upstream" master

      - name: Push | 推送
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Build Site | 构建网站
        run: |
          cd website &&
          npm install && npm run build

      - name: Deploy to Server | 部署到服务器
        uses: hengkx/ssh-deploy@v1.0.1
        with:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USERNAME: ${{ secrets.DEPLOY_HOST_USER }}
          PASSWORD: ${{ secrets.DEPLOY_HOST_PASSWORD }}
          SOURCE: "website/build"
          TARGET: "/www/wwwroot/wails.top"
