name: PR Checks
on:
  pull_request:

jobs:
  check_branch_name:
    runs-on: ubuntu-latest
    name: Check branch name
    steps:
      - name: Get branch names
        run: if ! [[ "$(echo ${GITHUB_HEAD_REF} | cut -d "/" -f1)" =~ (feature|hotfix|bugfix|release|chore) ]]; then
          echo "Branch name must start with feature/, hotfix/, bugfix/, release/, or chore/"
          exit 1
          fi

  test:
    name: Run Go Tests
    runs-on: ${{ matrix.os }}
    needs: check_branch_name
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        go-version: [ 1.18, 1.19 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update -y && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev build-essential pkg-config

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: go test -v ./...
