name: Push Checks

on:
  push:
    branches: [master]

jobs:
  push_files_to_crowdin:
    name: Push files to Crowdin
    if: github.repository == 'wailsapp/wails'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Verify Changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            website/**/*.mdx
            website/**/*.md
            website/**/*.json

      - name: Set node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Push files
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        run: |
          cd website
          corepack enable
          pnpm install
          pnpm run crowdin push -b master
