name: Test JS

on:
  push:
    branches: [ release/*, master ]
  workflow_dispatch:

jobs:
  test:
    name: Run JS Tests
    if: github.repository == 'wailsapp/wails'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: v2/internal/frontend/runtime

      - name: Run tests
        run: npm test
        working-directory: v2/internal/frontend/runtime
