// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GreetService is great
 * @module
 */

import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * Greet someone
 */
export function Greet(name: string): Promise<string> {
    let $resultPromise = $Call.ByName("main.GreetService.Greet", name);
    return $resultPromise as any;
}
