// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    HowDifferent,
    Impersonator,
    Person,
    PrivatePerson
} from "./internal.js";
