// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "/wails/runtime.js";

export class Dummy {

    /** Creates a new Dummy instance. */
    constructor($$source: Partial<Dummy> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Dummy instance from a string or object.
     */
    static createFrom($$source: any = {}): Dummy {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Dummy($$parsedSource as Partial<Dummy>);
    }
}
